// dv_part_13.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: XFA_C4_DEP2, XFA_C5_DEP3, FORALL_GPU_DV, MIX_ARRAY_DV_IF, QUEENS_DV, GAUSSJ_PERM_DV, FORINIT_HISTORY_DV, MATMULT_DV, MM_DV, TRANSPOSE_DV, SP_DV, INVERSE_DV, BADFFT_DV
#include "dv_harness.h"


#if defined(TEST_XFA_C4_DEP2) || defined(TEST_XFA_C5_DEP3)
extern "C" sisal_array_t func_MAIN(int32_t n);
#endif

#ifdef TEST_FORALL_GPU_DV
extern "C" sisal_array_t func_MAIN_GPU(int32_t n);
#endif

#ifdef TEST_MIX_ARRAY_DV_IF
struct FUNC_MAIN_results { sisal_array_t r0, r1; };
extern "C" struct FUNC_MAIN_results func_MAIN(bool flag);
#endif

#ifdef TEST_QUEENS_DV
extern "C" sisal_array_t func_MAIN(int32_t level);
#endif

#ifdef TEST_GAUSSJ_PERM_DV
extern "C" sisal_array_t func_GAUSSJ_PERM(int32_t n, sisal_array_t A, sisal_array_t B);
#endif

#ifdef TEST_FORINIT_HISTORY_DV
extern "C" sisal_array_t func_MAIN(int32_t n);
extern "C" int32_t func_LAST_VAL(int32_t n);
#endif

#ifdef TEST_MATMULT_DV
extern "C" sisal_array_t func_MULTIPLY(int32_t x, int32_t y, int32_t z,
                                        sisal_array_t A, sisal_array_t B);
#endif

#ifdef TEST_MM_DV
extern "C" float func_MAIN(int32_t rowsize);
#endif

#ifdef TEST_TRANSPOSE_DV
extern "C" sisal_array_t func_TRANSPOSE(int32_t n, int32_t m, sisal_array_t A);
#endif

#ifdef TEST_SP_DV
struct FUNC_MAIN_results { int32_t res_0; sisal_array_t res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t n, sisal_array_t A,
                                              sisal_array_t AJ,
                                              sisal_array_t x0,
                                              sisal_array_t g);
#endif

#ifdef TEST_INVERSE_DV
extern "C" sisal_array_t func_FIND_INVERSE(sisal_array_t A, int32_t n);
#endif

#ifdef TEST_BADFFT_DV
extern "C" bool func_MAIN(int32_t m);
#endif
#ifdef TEST_XFA_C4_DEP2
static void test_xfa_c4_dep2(void) {
    printf("\n=== Group: xfa_c4_dep2 (dependent cross `i in 1,n cross j in i,n`, Fortran-DO; vs C reference) ===\n");
    const int n = 6;
    // reference C implementation: triangular nest, row-major flat order
    int32_t ref[64]; int cnt = 0;
    for (int i = 1; i <= n; i++)
        for (int j = i; j <= n; j++) ref[cnt++] = i * j;
    sisal_array_t r = func_MAIN(n);
    check("flat rank-1, size = n*(n+1)/2",
          r.rank == 1 && (int)r.size == cnt && (int)r.dims[0] == cnt);
    bool ok = true;
    for (int k = 0; ok && k < cnt; k++) ok = (((int32_t*)r.data)[k] == ref[k]);
    check("i*j elements match C reference", ok);
    if (r.data) free(r.data);
}
#endif
#ifdef TEST_XFA_C5_DEP3
static void test_xfa_c5_dep3(void) {
    printf("\n=== Group: xfa_c5_dep3 (3-deep dependent cross, Fortran-DO; vs C reference) ===\n");
    const int n = 5;
    // reference C implementation: tetrahedral nest, row-major flat order
    int32_t ref[128]; int cnt = 0;
    for (int i = 1; i <= n; i++)
        for (int j = i; j <= n; j++)
            for (int k = j; k <= n; k++) ref[cnt++] = i + j + k;
    sisal_array_t r = func_MAIN(n);
    check("flat rank-1, size = C(n+2,3)",
          r.rank == 1 && (int)r.size == cnt && (int)r.dims[0] == cnt);
    bool ok = true;
    for (int k = 0; ok && k < cnt; k++) ok = (((int32_t*)r.data)[k] == ref[k]);
    check("i+j+k elements match C reference", ok);
    if (r.data) free(r.data);
}
#endif
#ifdef TEST_FORALL_GPU_DV
static void test_forall_gpu(void) {
    printf("\n=== Group: forall_gpu (negate gather Main_GPU; vs C reference) ===\n");
    const int n = 7;
    // reference C implementation
    float ref[n];
    for (int i = 0; i < n; i++) ref[i] = -(float)(i + 1);
    sisal_array_t r = func_MAIN_GPU(n);
    check("rank 1, size n", r.rank == 1 && (int)r.size == n);
    bool ok = true;
    for (int i = 0; ok && i < n; i++) ok = (((float*)r.data)[i] == ref[i]);
    check("-X elements match C reference", ok);
    if (r.data) free(r.data);
}
#endif
#ifdef TEST_MIX_ARRAY_DV_IF
static void test_mix_array_dv_if(void) {
    printf("\n=== Group: test_mix_array_dv_if (IF returning monolithic array + array_dv) ===\n");
    // both IF arms return (array[integer], array_dv[integer]) literals
    FUNC_MAIN_results a = func_MAIN(true);
    check("then-arm: array [1,2] and dv [10,20]",
          (int)a.r0.size == 2 && ((int32_t*)a.r0.data)[0] == 1
          && ((int32_t*)a.r0.data)[1] == 2
          && (int)a.r1.size == 2 && ((int32_t*)a.r1.data)[0] == 10
          && ((int32_t*)a.r1.data)[1] == 20);
    FUNC_MAIN_results b = func_MAIN(false);
    check("else-arm: array [0] and dv [0]",
          (int)b.r0.size == 1 && ((int32_t*)b.r0.data)[0] == 0
          && (int)b.r1.size == 1 && ((int32_t*)b.r1.data)[0] == 0);
    if (a.r0.data) free(a.r0.data);
    if (a.r1.data) free(a.r1.data);
    if (b.r0.data) free(b.r0.data);
    if (b.r1.data) free(b.r1.data);
}
#endif
#ifdef TEST_QUEENS_DV
// reference C: enumerate N-queens depth-first, columns left to right,
// candidate rows ascending -- the same order the Sisal recursion visits,
// so solutions compare element-for-element.
static int q_nref = 0;
static int q_refsol[1024][8];
static void q_enum(int n, int col, int *rows) {
    if (col == n) {
        for (int c = 0; c < n; c++) q_refsol[q_nref][c] = rows[c];
        q_nref++;
        return;
    }
    for (int r = 1; r <= n; r++) {
        bool ok = true;
        for (int c = 0; c < col && ok; c++)
            ok = (rows[c] != r && rows[c] + (c+1) != r + (col+1)
                  && rows[c] - (c+1) != r - (col+1));
        if (ok) { rows[col] = r; q_enum(n, col+1, rows); }
    }
}
static void test_8queens_dv(void) {
    printf("\n=== Group: 8queens_dv (rank-2 solution slab, COMPRESS + catenate; vs C reference) ===\n");
    for (int n = 4; n <= 8; n++) {
        q_nref = 0; int rows[8];
        q_enum(n, 0, rows);
        sisal_array_t s = func_MAIN(n);
        bool ok = (s.rank == 2 && (int)s.dims[0] == q_nref && (int)s.dims[1] == n
                   && (int)s.size == q_nref * n);
        for (int k = 0; ok && k < q_nref; k++)
            for (int c = 0; ok && c < n; c++)
                ok = (((int32_t*)s.data)[k*n + c] == q_refsol[k][c]);
        char label[64];
        snprintf(label, sizeof label, "n=%d: %d solutions match C reference", n, q_nref);
        check(label, ok);
        if (s.data) free(s.data);
    }
}
#endif
#ifdef TEST_GAUSSJ_PERM_DV
static void test_gaussj_perm_dv(void) {
    printf("\n=== Group: gaussj_perm_dv (Gauss-Jordan, permutation-free pivoting, float; vs C reference) ===\n");
    // Also the regression test for the for-initial FinalVal ZERO-TRIP bug:
    // find_pivot(N,N,..) never enters its while loop and must return the
    // INIT seed (the MERGE carry), not a zeroed bodycap.
    const int N = 4;
    double Ad[N][N] = {{2,1,-1,3},{-3,-1,2,-11},{-2,1,2,-3},{1,2,3,4}};
    double bd[N]    = {13, -34, -4, 20};
    // reference C: Gaussian elimination, partial pivoting, back-substitution
    double M[N][N+1];
    for (int i=0;i<N;i++){ for(int j=0;j<N;j++) M[i][j]=Ad[i][j]; M[i][N]=bd[i]; }
    for (int k=0;k<N;k++){
        int p=k; for(int i=k+1;i<N;i++) if (fabs(M[i][k])>fabs(M[p][k])) p=i;
        for(int j=0;j<=N;j++){ double t=M[k][j]; M[k][j]=M[p][j]; M[p][j]=t; }
        for(int i=0;i<N;i++) if(i!=k){ double f=M[i][k]/M[k][k];
            for(int j=k;j<=N;j++) M[i][j]-=f*M[k][j]; }
    }
    double ref[N]; for(int i=0;i<N;i++) ref[i]=M[i][N]/M[i][i];
    // inputs are array_dv[real] = FLOAT (tid 8)
    sisal_array_t A = sisal_array_alloc_empty(2, 8, N*N);
    A.dims[0]=N; A.dims[1]=N; A.lower_bound[0]=1; A.lower_bound[1]=1;
    for(int i=0;i<N;i++) for(int j=0;j<N;j++) ((float*)A.data)[i*N+j]=(float)Ad[i][j];
    sisal_array_t B = sisal_array_alloc_empty(1, 8, N);
    for(int i=0;i<N;i++) ((float*)B.data)[i]=(float)bd[i];
    sisal_array_t x = func_GAUSSJ_PERM(N, A, B);
    bool ok = (x.rank == 1 && (int)x.size == N);
    for (int i = 0; ok && i < N; i++)
        ok = fabs(((float*)x.data)[i] - ref[i]) < 1e-4;   // float arithmetic
    check("4x4 solve matches C reference (1e-4)", ok);
    free(A.data); free(B.data); if (x.data) free(x.data);
}
#endif
#ifdef TEST_FORINIT_HISTORY_DV
static void test_forinit_history_dv(void) {
    printf("\n=== Group: forinit_history_dv (1.2 history: seed = body_0 of the gather; vs C reference) ===\n");
    // reference C mirrors the SISAL 1.2 history model: the initial clause is
    // body_0, so the sequence is seed, then each body iteration's value.
    {
        const int n = 13;
        int32_t ref[16]; int cnt = 0;
        int i = 10;
        ref[cnt++] = i;                    // body_0: the seed
        while (i < n) { i = i + 1; ref[cnt++] = i; }
        sisal_array_t r = func_MAIN(n);
        bool ok = ((int)r.size == cnt);
        for (int k = 0; ok && k < cnt; k++) ok = (((int32_t*)r.data)[k] == ref[k]);
        check("n=13: gather = [10,11,12,13] (seed included)", ok);
        if (r.data) free(r.data);
    }
    {
        sisal_array_t r = func_MAIN(10);   // guard false on entry: zero body trips
        bool ok = ((int)r.size == 1 && ((int32_t*)r.data)[0] == 10);
        check("n=10 zero-trip: gather = [seed]", ok);
        if (r.data) free(r.data);
    }
    {
        // value-of zero-trip pin (was gaussj_perm's find_pivot(N,N) case
        // before its if-guard rewrite): reference C mirrors the history
        // model -- the seed, then a doubling per body iteration.
        int32_t ref0 = 42;                 // n=0: body never runs -> seed
        int32_t ref3;
        { int i = 42, k = 1; while (k <= 3) { k++; i *= 2; } ref3 = i; }
        check("value-of zero-trip = seed (42)", func_LAST_VAL(0) == ref0);
        check("value-of n=3 = last body value", func_LAST_VAL(3) == ref3);
    }
}
#endif
#ifdef TEST_MATMULT_DV
static void test_matmult_dv(void) {
    printf("\n=== Group: matmult_dv (rank-2 dv matmul across a call boundary; vs C reference) ===\n");
    const int X=2, Y=3, Z=2;
    double Av[X*Y] = {1,2,3, 4,5,6};
    double Bv[Y*Z] = {7,8, 9,10, 11,12};
    // reference C implementation
    double ref[X*Z];
    for (int i=0;i<X;i++) for (int j=0;j<Z;j++) {
        double s=0; for (int k=0;k<Y;k++) s += Av[i*Y+k]*Bv[k*Z+j];
        ref[i*Z+j]=s;
    }
    sisal_array_t A = sisal_array_alloc_empty(2, 4, X*Y);
    A.dims[0]=X; A.dims[1]=Y;
    for (int i=0;i<X*Y;i++) ((double*)A.data)[i]=Av[i];
    sisal_array_t B = sisal_array_alloc_empty(2, 4, Y*Z);
    B.dims[0]=Y; B.dims[1]=Z;
    for (int i=0;i<Y*Z;i++) ((double*)B.data)[i]=Bv[i];
    sisal_array_t r = func_MULTIPLY(X, Y, Z, A, B);
    bool ok = ((int)r.size == X*Z);
    for (int i=0;ok&&i<X*Z;i++) ok = fabs(((double*)r.data)[i]-ref[i])<1e-12;
    check("2x3 * 3x2 matches C reference", ok);
    free(A.data); free(B.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_MM_DV
static void test_mm_dv(void) {
    printf("\n=== Group: mm_dv (dv matmul of constant matrices; vs C reference) ===\n");
    const int n = 5;
    // reference C: every entry of the product is sum of n 1.1*1.1 terms (float)
    float acc = 0; for (int i=0;i<n;i++) acc += 1.1f*1.1f;
    check("rmc[1,1] matches C reference", fabsf(func_MAIN(n) - acc) < 1e-5f);
}
#endif
#ifdef TEST_TRANSPOSE_DV
static void test_transpose_dv(void) {
    printf("\n=== Group: transpose_dv (rank-2 dv transpose by permuted read; vs C reference) ===\n");
    const int N=2, M=3;
    double Av[N*M] = {1,2,3, 4,5,6};
    // reference C implementation
    double ref[M*N];
    for (int i=0;i<M;i++) for (int j=0;j<N;j++) ref[i*N+j] = Av[j*M+i];
    sisal_array_t A = sisal_array_alloc_empty(2, 4, N*M);
    A.dims[0]=N; A.dims[1]=M;
    for (int i=0;i<N*M;i++) ((double*)A.data)[i]=Av[i];
    sisal_array_t r = func_TRANSPOSE(N, M, A);
    bool ok = (r.rank==2 && (int)r.dims[0]==M && (int)r.dims[1]==N);
    for (int i=0;ok&&i<M*N;i++) ok = (((double*)r.data)[i]==ref[i]);
    check("2x3 -> 3x2, elements a[i,j]=b[j,i]", ok);
    free(A.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_SP_DV
static void test_sp_dv(void) {
    printf("\n=== Group: sp_dv (sparse matvec, 10 repeat-until iterations; vs C reference) ===\n");
    const int n = 5;
    float Av[4*n]; int32_t AJv[4*n]; float x0v[n], gv[n];
    for (int k=0;k<4;k++) for (int i=0;i<n;i++) {
        Av[k*n+i]  = 0.1f*(k+1) + 0.01f*i;
        AJv[k*n+i] = (i + k) % n + 1;          // 1-based column index
    }
    for (int i=0;i<n;i++) { x0v[i]=1.0f+i; gv[i]=0.5f*i; }
    // reference C: 10 iterations of x = g + sum_k A[k,i]*x[AJ[k,i]]
    float x[n], xn[n]; for (int i=0;i<n;i++) x[i]=x0v[i];
    for (int it=0;it<10;it++) {
        for (int i=0;i<n;i++) {
            float ax=0; for (int k=0;k<4;k++) ax += Av[k*n+i]*x[AJv[k*n+i]-1];
            xn[i]=gv[i]+ax;
        }
        for (int i=0;i<n;i++) x[i]=xn[i];
    }
    sisal_array_t A = sisal_array_alloc_empty(2, 8, 4*n);
    A.dims[0]=4; A.dims[1]=n;
    for (int i=0;i<4*n;i++) ((float*)A.data)[i]=Av[i];
    sisal_array_t AJ = sisal_array_alloc_empty(2, 6, 4*n);
    AJ.dims[0]=4; AJ.dims[1]=n;
    for (int i=0;i<4*n;i++) ((int32_t*)AJ.data)[i]=AJv[i];
    sisal_array_t x0 = sisal_array_alloc_empty(1, 8, n);
    for (int i=0;i<n;i++) ((float*)x0.data)[i]=x0v[i];
    sisal_array_t g = sisal_array_alloc_empty(1, 8, n);
    for (int i=0;i<n;i++) ((float*)g.data)[i]=gv[i];
    FUNC_MAIN_results r = func_MAIN(n, A, AJ, x0, g);
    bool ok = (r.res_0 == 10 && (int)r.res_1.size == n);
    for (int i=0;ok&&i<n;i++)
        ok = fabsf(((float*)r.res_1.data)[i]-x[i]) < 1e-3f * fabsf(x[i]);
    check("ncount=10 and final x matches C reference (rel 1e-3, float)", ok);
    free(A.data); free(AJ.data); free(x0.data); free(g.data);
    if (r.res_1.data) free(r.res_1.data);
}
#endif
#ifdef TEST_INVERSE_DV
static void test_inverse_dv(void) {
    printf("\n=== Group: inverse_dv (Gauss-Jordan matrix inverse, full pivoting, rank-2 dv; vs C reference) ===\n");
    const int N = 4;
    double Ad[N][N] = {{4,2,1,3},{2,5,2,1},{1,2,6,2},{3,1,2,7}};
    // reference C: Gauss-Jordan inverse with partial pivoting, in double
    double M[N][2*N];
    for (int i=0;i<N;i++) { for (int j=0;j<N;j++) M[i][j]=Ad[i][j];
        for (int j=0;j<N;j++) M[i][N+j] = (i==j) ? 1.0 : 0.0; }
    for (int k=0;k<N;k++) {
        int p=k; for (int i=k+1;i<N;i++) if (fabs(M[i][k])>fabs(M[p][k])) p=i;
        for (int j=0;j<2*N;j++) { double t=M[k][j]; M[k][j]=M[p][j]; M[p][j]=t; }
        double d = M[k][k];
        for (int j=0;j<2*N;j++) M[k][j] /= d;
        for (int i=0;i<N;i++) if (i!=k) {
            double f=M[i][k];
            for (int j=0;j<2*N;j++) M[i][j] -= f*M[k][j];
        }
    }
    sisal_array_t A = sisal_array_alloc_empty(2, 8, N*N);
    A.dims[0]=N; A.dims[1]=N; A.lower_bound[0]=1; A.lower_bound[1]=1;
    for (int i=0;i<N;i++) for (int j=0;j<N;j++) ((float*)A.data)[i*N+j]=(float)Ad[i][j];
    sisal_array_t r = func_FIND_INVERSE(A, N);
    bool ok = (r.rank == 2 && (int)r.size == N*N);
    for (int i=0;i<N && ok;i++) for (int j=0;j<N && ok;j++)
        ok = fabs(((float*)r.data)[i*N+j] - M[i][N+j]) < 1e-4;
    check("4x4 inverse matches C reference (1e-4, float)", ok);
    free(A.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_BADFFT_DV
static void test_badfft_dv(void) {
    printf("\n=== Group: badfft_dv (Cooley-Tukey FFT over array_dv[complex record]; analytic reference) ===\n");
    // The .sis main is self-checking against the ANALYTIC reference: for the
    // signal sin(j*pi/8) of length n = 2^m, |F| at bins n/16 and n - n/16 is
    // exactly n/2.  Verified against OSC 13.0.3 (original badfft.sis -> T).
    for (int m = 4; m <= 7; m++) {
        char label[64];
        snprintf(label, sizeof label, "m=%d (n=%d): FFT peaks = n/2", m, 1 << m);
        check(label, func_MAIN(m));
    }
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_XFA_C4_DEP2
  test_xfa_c4_dep2 ();
#endif
#ifdef TEST_XFA_C5_DEP3
  test_xfa_c5_dep3 ();
#endif
#ifdef TEST_FORALL_GPU_DV
  test_forall_gpu ();
#endif
#ifdef TEST_MIX_ARRAY_DV_IF
  test_mix_array_dv_if ();
#endif
#ifdef TEST_QUEENS_DV
  test_8queens_dv ();
#endif
#ifdef TEST_GAUSSJ_PERM_DV
  test_gaussj_perm_dv ();
#endif
#ifdef TEST_FORINIT_HISTORY_DV
  test_forinit_history_dv ();
#endif
#ifdef TEST_MATMULT_DV
  test_matmult_dv ();
#endif
#ifdef TEST_MM_DV
  test_mm_dv ();
#endif
#ifdef TEST_TRANSPOSE_DV
  test_transpose_dv ();
#endif
#ifdef TEST_SP_DV
  test_sp_dv ();
#endif
#ifdef TEST_INVERSE_DV
  test_inverse_dv ();
#endif
#ifdef TEST_BADFFT_DV
  test_badfft_dv ();
#endif
#if !defined(TEST_XFA_C4_DEP2) \
    && !defined(TEST_XFA_C5_DEP3) \
    && !defined(TEST_FORALL_GPU_DV) \
    && !defined(TEST_MIX_ARRAY_DV_IF) \
    && !defined(TEST_QUEENS_DV) \
    && !defined(TEST_GAUSSJ_PERM_DV) \
    && !defined(TEST_FORINIT_HISTORY_DV) \
    && !defined(TEST_MATMULT_DV) \
    && !defined(TEST_MM_DV) \
    && !defined(TEST_TRANSPOSE_DV) \
    && !defined(TEST_SP_DV) \
    && !defined(TEST_INVERSE_DV) \
    && !defined(TEST_BADFFT_DV)
  g_no_macro = true;
#endif
}
