// dv_part_04.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: LOOP3_DV, LOOP7_DV, LOOP12_DV, LOOP24_DV, LOOP9_DV, LOOP10_DV, LOOP21_DV, LOOP2_DV, LOOP2S_DV, MR2_INIT, LOOP16_DV, LOOP13_DV, LOOP5_DV
#include "dv_harness.h"

#ifdef TEST_LOOP3_DV
extern "C" double func_MAIN (int32_t REP, int32_t N, sisal_array_t X,
                             sisal_array_t Z); // inner product
#endif
#ifdef TEST_LOOP7_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, double R, double T,
                                    sisal_array_t U, sisal_array_t Y,
                                    sisal_array_t Z); // equation of state
#endif
#ifdef TEST_LOOP12_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N,
                                    sisal_array_t YIN); // first difference
#endif
#ifdef TEST_LOOP24_DV
extern "C" int32_t func_MAIN (int32_t REP, int32_t N,
                              sisal_array_t X); // location of first minimum
#endif
#ifdef TEST_LOOP9_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, double CO, double DM22, double DM23,
           double DM24, double DM25, double DM26, double DM27, double DM28,
           sisal_array_t PXIN); // integrate predictors
#endif
#ifdef TEST_LOOP10_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t CX,
           sisal_array_t PXIN); // difference predictors
#endif
#ifdef TEST_LOOP21_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t CX,
                                    sisal_array_t PXIN,
                                    sisal_array_t VY); // matrix*matrix product
#endif
#ifdef TEST_LOOP2_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t V,
                                    sisal_array_t XIN); // ICCG excerpt
#endif
#ifdef TEST_LOOP2S_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t V,
           sisal_array_t XIN); // ICCG excerpt (s-form)
#endif
#ifdef TEST_MR2_INIT
struct MR2_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct MR2_results
func_MAIN (int32_t N); // for-initial returning TWO array_dv carries
#endif
#ifdef TEST_LOOP16_DV
struct LOOP16_results
{
  int32_t res_0;
  int32_t res_1;
};
extern "C" struct LOOP16_results
func_MAIN (int32_t REP, int32_t N, double R, double S, double T,
           sisal_array_t D, sisal_array_t PLAN,
           sisal_array_t ZONE); // Monte Carlo search (v1,v2)
#endif
#ifdef TEST_LOOP13_DV
struct LOOP13_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct LOOP13_results
func_MAIN (int32_t REP, int32_t N, sisal_array_t E, sisal_array_t F,
           sisal_array_t B, sisal_array_t C, sisal_array_t HIN,
           sisal_array_t PIN, sisal_array_t Y,
           sisal_array_t Z); // 2-D PIC -> (H,P)
#endif
#ifdef TEST_LOOP5_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t XIN, sisal_array_t Y,
           sisal_array_t Z); // tridiagonal: for-initial `array of X` gather
#endif
#ifdef TEST_LOOP3_DV
// Inner product: sum_{i=1..n} X[i]*Z[i]
static void
test_loop3_dv (void)
{
  printf ("\n=== Group: loop3_dv (inner product, vs C reference) ===\n");
  const int n = 5;
  double X[5], Z[5];
  double exp = 0.0;
  for (int i = 0; i < n; i++)
    {
      X[i] = i + 1;
      Z[i] = i + 1;
      exp += X[i] * Z[i];
    }
  sisal_array_t Xa = make_double_arr (X, n), Za = make_double_arr (Z, n);
  double r = func_MAIN (1, n, Xa, Za);
  check ("loop3_dv inner product == 55", fabs (r - exp) < 1e-9);
  if (Xa.data)
    free (Xa.data);
  if (Za.data)
    free (Za.data);
}
#endif
#ifdef TEST_LOOP7_DV
// Equation of state: out[k] = U[k] + R*(Z[k]+R*Y[k])
//   + T*(U[k+3]+R*(U[k+2]+R*U[k+1]) + T*(U[k+6]+R*(U[k+5]+R*U[k+4])))  (U
//   needs n+6)
static void
test_loop7_dv (void)
{
  printf ("\n=== Group: loop7_dv (equation of state, vs C reference) ===\n");
  const int n = 6;
  double R = 0.5, T = 0.25;
  double U[12];
  for (int i = 0; i < n + 6; i++)
    U[i] = 0.1 * (i + 1);
  double Y[6], Z[6];
  for (int i = 0; i < n; i++)
    {
      Y[i] = i + 1;
      Z[i] = 2 * (i + 1);
    }
  double exp[6];
  for (int k = 0; k < n; k++)
    exp[k] = U[k] + R * (Z[k] + R * Y[k])
             + T
                   * (U[k + 3] + R * (U[k + 2] + R * U[k + 1])
                      + T * (U[k + 6] + R * (U[k + 5] + R * U[k + 4])));
  sisal_array_t Ua = make_double_arr (U, n + 6), Ya = make_double_arr (Y, n),
                Za = make_double_arr (Z, n);
  sisal_array_t r = func_MAIN (1, n, R, T, Ua, Ya, Za);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && (fabs (ad (r, k) - exp[k]) < 1e-9);
  check ("loop7_dv eos matches C reference (n=6)", ok);
  if (Ua.data)
    free (Ua.data);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP12_DV
// First difference: out[i] = Y[i+1] - Y[i]  (Y needs n+1)
static void
test_loop12_dv (void)
{
  printf ("\n=== Group: loop12_dv (first difference, vs C reference) ===\n");
  const int n = 6;
  double Y[7];
  for (int i = 0; i < n + 1; i++)
    Y[i] = (double)(i * i);
  double exp[6];
  for (int i = 0; i < n; i++)
    exp[i] = Y[i + 1] - Y[i];
  sisal_array_t Ya = make_double_arr (Y, n + 1);
  sisal_array_t r = func_MAIN (1, n, Ya);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int i = 0; ok && i < n; i++)
    ok = ok && (fabs (ad (r, i) - exp[i]) < 1e-9);
  check ("loop12_dv first-difference matches C reference (2i+1)", ok);
  if (Ya.data)
    free (Ya.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP24_DV
// Location (1-based) of first minimum: loc=1; for k=2..n if X[k]<X[loc] loc=k
static void
test_loop24_dv (void)
{
  printf (
      "\n=== Group: loop24_dv (first-minimum location, vs C reference) ===\n");
  const int n = 7;
  double X[7]
      = { 5.0, 3.0, 8.0, 1.0, 1.0, 9.0, 2.0 }; // first min (1.0) at 1-based 4
  int loc = 1;
  for (int k = 2; k <= n; k++)
    if (X[k - 1] < X[loc - 1])
      loc = k;
  sisal_array_t Xa = make_double_arr (X, n);
  int32_t r = func_MAIN (1, n, Xa);
  check ("loop24_dv first-min location == 4", r == loc && r == 4);
  if (Xa.data)
    free (Xa.data);
}
#endif

#ifdef TEST_LOOP9_DV
// Integrate predictors: out[i] = PX[3,i] + CO*(PX[5,i]+PX[6,i]) + DM22*PX[7,i]
//   + DM23*PX[8,i] + ... + DM28*PX[13,i].  PX is 13 rows x n cols (row-major).
static void
test_loop9_dv (void)
{
  printf (
      "\n=== Group: loop9_dv (integrate predictors, vs C reference) ===\n");
  const int n = 4, R = 13;
  double CO = 0.5, DM[7] = { 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7 }; // DM22..DM28
  double PX[13 * 4];
  for (int r = 1; r <= R; r++)
    for (int c = 1; c <= n; c++)
      PX[(r - 1) * n + (c - 1)] = (double)(r * 100 + c);
#define PXV(r, i) PX[((r) - 1) * n + ((i) - 1)]
  double exp[4];
  for (int i = 1; i <= n; i++)
    exp[i - 1] = PXV (3, i) + CO * (PXV (5, i) + PXV (6, i))
                 + DM[0] * PXV (7, i) + DM[1] * PXV (8, i) + DM[2] * PXV (9, i)
                 + DM[3] * PXV (10, i) + DM[4] * PXV (11, i)
                 + DM[5] * PXV (12, i) + DM[6] * PXV (13, i);
#undef PXV
  sisal_array_t PXa = make_double_2d (PX, R, n);
  sisal_array_t r = func_MAIN (1, n, CO, DM[0], DM[1], DM[2], DM[3], DM[4],
                               DM[5], DM[6], PXa);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int i = 0; ok && i < n; i++)
    ok = ok && (fabs (ad (r, i) - exp[i]) < 1e-6);
  check ("loop9_dv integrate-predictors matches C reference (n=4)", ok);
  if (PXa.data)
    free (PXa.data);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_LOOP10_DV
static void
test_loop10_dv (void)
{
  printf (
      "\n=== Group: loop10_dv (difference predictors, vs C reference) ===\n");
  const int R = 14, n = 2;
  double CX[28], PX[28];
  for (int r = 1; r <= R; r++)
    {
      for (int c = 1; c <= n; c++)
        {
          CX[(r - 1) * n + c - 1] = 100 + r;
          PX[(r - 1) * n + c - 1] = r;
        }
    }
  double ref[10 * n];
  for (int c = 0; c < n; c++)
    {
      double px = CX[(5 - 1) * n + c];
      ref[0 * n + c] = px;
      for (int k = 6; k <= 14; k++)
        {
          px = px - PX[((k - 1) - 1) * n + c];
          ref[(k - 5) * n + c] = px;
        }
    }
  sisal_array_t CXa = make_double_2d (CX, R, n);
  sisal_array_t PXa = make_double_2d (PX, R, n);
  sisal_array_t r = func_MAIN (1, n, CXa, PXa);
  bool ok = ((int)r.dims[0] == 10) && ((int)r.dims[1] == n);
  for (int k = 0; ok && k < 10 * n; k++)
    {
      ok = ok && (fabs (ad (r, k) - ref[k]) < 1e-9);
    }
  check ("loop10_dv difference-predictors matches C reference", ok);
  if (CXa.data)
    free (CXa.data);
  if (PXa.data)
    free (PXa.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP21_DV
// Matrix*matrix: out[i,j] = PX[i,j] + sum_{k=1..25} VY[i,k]*CX[j,k], i=1..25,
// j=1..n.
//   CX is n x 25, VY is 25 x 25, PX is 25 x n; output is 25 x n (row-major).
static void
test_loop21_dv (void)
{
  printf (
      "\n=== Group: loop21_dv (matrix*matrix product, vs C reference) ===\n");
  const int n = 3, M = 25;
  double CX[3 * 25], VY[25 * 25], PX[25 * 3];
  for (int j = 1; j <= n; j++)
    for (int k = 1; k <= M; k++)
      CX[(j - 1) * M + (k - 1)] = 0.01 * (j + k);
  for (int i = 1; i <= M; i++)
    for (int k = 1; k <= M; k++)
      VY[(i - 1) * M + (k - 1)] = 0.01 * ((i * k) % 7);
  for (int i = 1; i <= M; i++)
    for (int j = 1; j <= n; j++)
      PX[(i - 1) * n + (j - 1)] = 0.1 * (i + j);
  double exp[25 * 3];
  for (int i = 1; i <= M; i++)
    for (int j = 1; j <= n; j++)
      {
        double s = 0.0;
        for (int k = 1; k <= M; k++)
          s += VY[(i - 1) * M + (k - 1)] * CX[(j - 1) * M + (k - 1)];
        exp[(i - 1) * n + (j - 1)] = PX[(i - 1) * n + (j - 1)] + s;
      }
  sisal_array_t CXa = make_double_2d (CX, n, M),
                PXa = make_double_2d (PX, M, n),
                VYa = make_double_2d (VY, M, M);
  sisal_array_t r = func_MAIN (1, n, CXa, PXa, VYa);
  bool ok = (r.rank == 2) && ((int)r.dims[0] == M) && ((int)r.dims[1] == n);
  for (int t = 0; ok && t < M * n; t++)
    ok = ok && (fabs (ad (r, t) - exp[t]) < 1e-6);
  check ("loop21_dv matrix*matrix matches C reference (25x3)", ok);
  if (CXa.data)
    free (CXa.data);
  if (PXa.data)
    free (PXa.data);
  if (VYa.data)
    free (VYa.data);
  if (r.data)
    free (r.data);
}
#endif

#if defined(TEST_LOOP2_DV) || defined(TEST_LOOP2S_DV)
// ICCG excerpt (loop2 / loop2s -- identical kernels, only formatting differs):
// outer halving sweep (IL = n, n/2, ...) driving an inner tridiagonal-style
// update Xt[i] = Xt[k] - V[k]*Xt[k-1] + V[k+1]*Xt[k+1] (Sisal 1-based).
// In-place on X matches the Sisal `old Xt` semantics: each inner step writes
// one element and later steps read it back, which is exactly the running
// carry.  (This is the full kernel whose inner-only form is loop2_inner.)
static void
ref_loop2 (int n, const double *V, const double *Xin, int sz, double *X)
{
  for (int j = 0; j < sz; j++)
    X[j] = Xin[j];
  int IL = n, IPNTP = 0;
  while (IL > 1)
    {
      int IPNT = IPNTP;
      IPNTP = IPNTP + IL;
      IL = IL / 2;
      int k = IPNT + 2, i = IPNTP;
      while (k <= IPNTP)
        {
          int ok = k;
          k = ok + 2;
          i = i + 1;
          X[i - 1] = X[ok - 1] - V[ok - 1] * X[ok - 2] + V[ok] * X[ok];
        }
    }
}
#endif
#ifdef TEST_LOOP2_DV
static void
test_loop2_dv (void)
{
  printf ("\n=== Group: loop2_dv (ICCG excerpt, vs C reference) ===\n");
  const int n = 8, sz = 24;
  double V[24], Xin[24];
  for (int j = 0; j < sz; j++)
    {
      V[j] = 0.1 * (j + 1);
      Xin[j] = (double)(j + 1);
    }
  double exp[24];
  ref_loop2 (n, V, Xin, sz, exp);
  sisal_array_t Va = make_double_arr (V, sz), Xa = make_double_arr (Xin, sz);
  sisal_array_t r = func_MAIN (1, n, Va, Xa);
  bool ok = (r.rank == 1) && ((int)r.size == sz);
  for (int j = 0; ok && j < sz; j++)
    ok = ok && (fabs (ad (r, j) - exp[j]) < 1e-9);
  check ("loop2_dv ICCG matches C reference (n=8)", ok);
  check ("loop2_dv did update X (X[11] != Xin[11])",
         fabs (ad (r, 11) - Xin[11]) > 1e-12);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP2S_DV
// loop2s = loop2 with different source formatting only; same ref_loop2.
static void
test_loop2s_dv (void)
{
  printf ("\n=== Group: loop2s_dv (ICCG excerpt, vs C reference) ===\n");
  const int n = 8, sz = 24;
  double V[24], Xin[24];
  for (int j = 0; j < sz; j++)
    {
      V[j] = 0.1 * (j + 1);
      Xin[j] = (double)(j + 1);
    }
  double exp[24];
  ref_loop2 (n, V, Xin, sz, exp);
  sisal_array_t Va = make_double_arr (V, sz), Xa = make_double_arr (Xin, sz);
  sisal_array_t r = func_MAIN (1, n, Va, Xa);
  bool ok = (r.rank == 1) && ((int)r.size == sz);
  for (int j = 0; ok && j < sz; j++)
    ok = ok && (fabs (ad (r, j) - exp[j]) < 1e-9);
  check ("loop2s_dv ICCG matches C reference (n=8)", ok);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_MR2_INIT
// Minimal two-array for-initial return: H = all 10, P = all 20 (n x n). Guards
// the multi-return tuple wiring -- the per-clause (node,port) resolution fix.
// Without it both slots collapse to one carry.
static void
test_mr2_init (void)
{
  printf ("\n=== Group: mr2_init (for-initial returns two array_dv carries) "
          "===\n");
  // The 10s and 20s are constants in the .sis, so they ARE the specification;
  // what this group exists to check is that the two return slots stay distinct
  // and neither is cross-wired to the other.  Swept over n, since the carries
  // are rank-2 built by a cross forall and a size-dependent mis-wire would
  // otherwise hide at the single n = 3 it used to run.
  bool ok = true;
  for (int n : { 1, 2, 3, 5 })
    {
      struct MR2_results r = func_MAIN (n);
      const int sz = n * n;
      ok = ok && (r.res_0.rank == 2) && ((int)r.res_0.dims[0] == n)
           && ((int)r.res_0.dims[1] == n) && ((int)r.res_0.size == sz)
           && (r.res_1.rank == 2) && ((int)r.res_1.dims[0] == n)
           && ((int)r.res_1.dims[1] == n) && ((int)r.res_1.size == sz);
      for (int t = 0; ok && t < sz; t++)
        ok = (ai (r.res_0, t) == 10) && (ai (r.res_1, t) == 20);
      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data && r.res_1.data != r.res_0.data) free (r.res_1.data);
    }
  check ("both rank-2 carries return distinctly (H all 10, P all 20) for "
         "n = 1, 2, 3, 5",
         ok);
}
#endif
#ifdef TEST_LOOP16_DV
// Monte Carlo search (loop16): Y = least j4 of cells whose classifier C1==0;
// then (v1,v2) = Y==BIG ? (1,0) : ((Y-3)/(2n)+1, Y).  Sisal `exp(a,b)` is
// power -> pow.
static void
ref_loop16 (int n, double R, double S, double T, const double *D,
            const double *PLAN, const int *ZONE, int *v1, int *v2)
{
  int Z1 = ZONE[0];
  long BIG = 2L * n * Z1 + 2, Y = BIG;
  for (int j = 1; j <= n; j++)
    for (int i = 1; i <= Z1; i++)
      {
        int m = n * (i - 1) + j - 1;
        int j4 = 2 * m + 3;
        int j5 = ZONE[j4 - 1];
        int C1;
        if (j5 < n / 3)
          C1 = (PLAN[j5 - 1] < T)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == T) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 < 2 * n / 3)
          C1 = (PLAN[j5 - 1] < S)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == S) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 < n)
          C1 = (PLAN[j5 - 1] < R)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == R) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 == n)
          C1 = 0;
        else
          {
            double test
                = D[j5 - 1]
                  - (D[j5 - 2] * pow (T - D[j5 - 3], 2)
                     + pow (S - D[j5 - 4], 2) + pow (R - D[j5 - 5], 2));
            C1 = (test < 0.0) ? ZONE[j4 - 2] : -ZONE[j4 - 2];
          }
        long cand = (C1 == 0) ? j4 : BIG;
        if (cand < Y)
          Y = cand;
      }
  if (Y == BIG)
    {
      *v1 = 1;
      *v2 = 0;
    }
  else
    {
      *v1 = (int)((Y - 3) / (2 * n) + 1);
      *v2 = (int)Y;
    }
}
static void
test_loop16_dv (void)
{
  printf ("\n=== Group: loop16_dv (Monte Carlo search, vs C reference) ===\n");
  const int n = 3;
  double R = 0.3, S = 0.5, T = 0.7;
  double D[8] = { 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8 };
  double PLAN[3] = { 0.0, 0.0, 0.0 };
  int32_t ZONE[13] = { 2, 7, 5, 9, 3, 11, 3, 13, 3, 15, 3, 17, 3 };
  int ev1, ev2;
  ref_loop16 (n, R, S, T, D, PLAN, ZONE, &ev1, &ev2);
  sisal_array_t Da = make_double_arr (D, 8), Pa = make_double_arr (PLAN, 3),
                Za = make_int_arr (ZONE, 13);
  struct LOOP16_results r = func_MAIN (1, n, R, S, T, Da, Pa, Za);
  check ("loop16_dv v1 matches C reference", r.res_0 == ev1);
  check ("loop16_dv v2 matches C reference", r.res_1 == ev2);
  if (Da.data)
    free (Da.data);
  if (Pa.data)
    free (Pa.data);
  if (Za.data)
    free (Za.data);
}
#endif
#ifdef TEST_LOOP13_DV
// 2-D PIC (loop13): per particle i, compute grid cell from P, push P, bump H
// histogram. MOD2N(i,j): i<0 ? i-(i/j)*j+j/2+|j/2| : i-(i/j)*j+j/2-|j/2|.  All
// indices Sisal 1-based. P is 4 x n; H/B/C are G x G; E/F/Y/Z 1-based length
// >= 96.  In-place on P and H matches the Sisal `old P`/`old H` carries (each
// particle writes its own P column; H accumulates). (This kernel is the
// regression guard for the 2-D element-update X[r,c: v] fix.)
static int
l13_mod2n (int i, int j)
{
  int r = i - (i / j) * j + j / 2;
  return (i < 0) ? r + abs (j / 2) : r - abs (j / 2);
}
static void
ref_loop13 (int n, const int32_t *E, const int32_t *F, const double *B,
            const double *C, int G, double *H, double *P, const double *Y,
            const double *Z)
{
  for (int i = 1; i <= n; i++)
    {
#define PV(r, c) P[((r) - 1) * n + ((c) - 1)]
      int i1 = 1 + l13_mod2n ((int)trunc (PV (1, i)), 64);
      int j1 = 1 + l13_mod2n ((int)trunc (PV (2, i)), 64);
      double Bij = B[(i1 - 1) * G + (j1 - 1)],
             Cij = C[(i1 - 1) * G + (j1 - 1)];
      double o1 = PV (1, i), o2 = PV (2, i), o3 = PV (3, i), o4 = PV (4, i);
      PV (4, i) = o4 + Cij;
      PV (3, i) = o3 + Bij;
      PV (2, i) = o2 + o4 + Cij;
      PV (1, i) = o1 + o3 + Bij;
      int i2 = l13_mod2n ((int)trunc (PV (1, i)), 64);
      int j2 = l13_mod2n ((int)trunc (PV (2, i)), 64);
      int i3 = i2 + E[(i2 + 32) - 1];
      int j3 = j2 + F[(j2 + 32) - 1];
      PV (1, i) = PV (1, i) + Y[(i2 + 32) - 1];
      PV (2, i) = PV (2, i) + Z[(j2 + 32) - 1];
      H[(i3 - 1) * G + (j3 - 1)] += 1.0;
#undef PV
    }
}
static void
test_loop13_dv (void)
{
  printf ("\n=== Group: loop13_dv (2-D PIC, vs C reference) ===\n");
  const int n = 2, G = 64;
  static int32_t E[96], F[96];
  static double B[64 * 64], C[64 * 64], Hin[64 * 64], Y[96], Z[96];
  for (int k = 0; k < 96; k++)
    {
      E[k] = 1;
      F[k] = 1;
      Y[k] = 0.5;
      Z[k] = 0.25;
    }
  for (int k = 0; k < G * G; k++)
    {
      B[k] = 0.0;
      C[k] = 0.0;
      Hin[k] = 0.0;
    }
  double Pin[4 * 2] = { 5, 3, 7, 9, 0, 0, 0, 0 };
  static double Hexp[64 * 64];
  for (int k = 0; k < G * G; k++)
    Hexp[k] = Hin[k];
  double Pexp[4 * 2];
  for (int k = 0; k < 8; k++)
    Pexp[k] = Pin[k];
  ref_loop13 (n, E, F, B, C, G, Hexp, Pexp, Y, Z);
  sisal_array_t Ea = make_int_arr (E, 96), Fa = make_int_arr (F, 96);
  sisal_array_t Ba = make_double_2d (B, G, G), Ca = make_double_2d (C, G, G);
  sisal_array_t Ha = make_double_2d (Hin, G, G),
                Pa = make_double_2d (Pin, 4, n);
  sisal_array_t Ya = make_double_arr (Y, 96), Za = make_double_arr (Z, 96);
  struct LOOP13_results r = func_MAIN (1, n, Ea, Fa, Ba, Ca, Ha, Pa, Ya, Za);
  bool hok = (r.res_0.rank == 2) && ((int)r.res_0.dims[0] == G)
             && ((int)r.res_0.dims[1] == G);
  for (int k = 0; hok && k < G * G; k++)
    hok = hok && (fabs (ad (r.res_0, k) - Hexp[k]) < 1e-9);
  bool pok = (r.res_1.rank == 2) && ((int)r.res_1.dims[0] == 4)
             && ((int)r.res_1.dims[1] == n);
  for (int k = 0; pok && k < 4 * n; k++)
    pok = pok && (fabs (ad (r.res_1, k) - Pexp[k]) < 1e-9);
  check ("loop13_dv H histogram matches C reference", hok);
  check ("loop13_dv P particles match C reference", pok);
  check ("loop13_dv H got the two particle hits (6,8)&(4,10)",
         ad (r.res_0, (6 - 1) * G + (8 - 1)) == 1.0
             && ad (r.res_0, (4 - 1) * G + (10 - 1)) == 1.0);
  if (Ea.data)
    free (Ea.data);
  if (Fa.data)
    free (Fa.data);
  if (Ba.data)
    free (Ba.data);
  if (Ca.data)
    free (Ca.data);
  if (Ha.data)
    free (Ha.data);
  if (Pa.data)
    free (Pa.data);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
}
#endif
#ifdef TEST_LOOP5_DV
// Livermore loop 5: tridiagonal elimination (sequential recurrence) lowered as
// a `for initial ... returns array_dv(n) of X`.  X[1]=Xin[1];
// X[i]=Z[i]*(Y[i]-X[i-1]) for i=2..n.  The declared extent is a SIZE
// DESCRIPTOR: slot 0 is the seed (body_0, here X[1]) and the loop fills the
// rest, so the gather is the whole X[1..n] -- n elements, not the n-1 body
// values.  That is what makes this form agree with `value of`, the bare
// `array_dv of`, `stream of`, every reduction, and OSC 13.0.3.
static void
test_loop5_dv (void)
{
  printf ("\n=== Group: loop5_dv (tridiagonal for-initial gather, vs C "
          "reference) ===\n");
  const int n = 6;
  double Xin[6] = { 2, 0, 0, 0, 0, 0 };         // only Xin[1] used
  double Y[6] = { 0, 5, 10, 15, 20, 25 };       // 1-based Y[2..6]
  double Z[6] = { 0, 0.5, 0.5, 0.5, 0.5, 0.5 }; // 1-based Z[2..6]
  double X[7];
  X[1] = Xin[0];
  for (int i = 2; i <= n; i++)
    X[i] = Z[i - 1] * (Y[i - 1] - X[i - 1]); // ref recurrence
  sisal_array_t Xa = make_double_arr (Xin, 6), Ya = make_double_arr (Y, 6),
                Za = make_double_arr (Z, 6);
  sisal_array_t r = func_MAIN (1, n, Xa, Ya, Za);
  bool ok = (r.rank == 1) && ((int)r.size == n) && ((int)r.dims[0] == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && near_d (ad (r, k), X[k + 1]);
  check ("loop5_dv gather [X1..Xn] incl. the seed matches C reference", ok);
  if (Xa.data)
    free (Xa.data);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.data)
    free (r.data);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_LOOP3_DV
  test_loop3_dv ();
#endif
#ifdef TEST_LOOP7_DV
  test_loop7_dv ();
#endif
#ifdef TEST_LOOP12_DV
  test_loop12_dv ();
#endif
#ifdef TEST_LOOP24_DV
  test_loop24_dv ();
#endif
#ifdef TEST_LOOP9_DV
  test_loop9_dv ();
#endif
#ifdef TEST_LOOP10_DV
  test_loop10_dv ();
#endif
#ifdef TEST_LOOP21_DV
  test_loop21_dv ();
#endif
#ifdef TEST_LOOP2_DV
  test_loop2_dv ();
#endif
#ifdef TEST_LOOP2S_DV
  test_loop2s_dv ();
#endif
#ifdef TEST_MR2_INIT
  test_mr2_init ();
#endif
#ifdef TEST_LOOP16_DV
  test_loop16_dv ();
#endif
#ifdef TEST_LOOP13_DV
  test_loop13_dv ();
#endif
#ifdef TEST_LOOP5_DV
  test_loop5_dv ();
#endif
#if !defined(TEST_LOOP3_DV) \
    && !defined(TEST_LOOP7_DV) \
    && !defined(TEST_LOOP12_DV) \
    && !defined(TEST_LOOP24_DV) \
    && !defined(TEST_LOOP9_DV) \
    && !defined(TEST_LOOP10_DV) \
    && !defined(TEST_LOOP21_DV) \
    && !defined(TEST_LOOP2_DV) \
    && !defined(TEST_LOOP2S_DV) \
    && !defined(TEST_MR2_INIT) \
    && !defined(TEST_LOOP16_DV) \
    && !defined(TEST_LOOP13_DV) \
    && !defined(TEST_LOOP5_DV)
  g_no_macro = true;
#endif
}
