// dv_part_01.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: ABS_DEMO, AGREEMENT, LIFTED_ARITH, SHL, TEST_SUBSET, INTRINSICS, BROADCAST_COMPLEX, COMPRESS, BROADCAST_NUMPY, FORALL_CPU, NEGATE_DV, FORALL_BASIC_DV, FORALL_REDUCE_DV
#include "dv_harness.h"




// ============================================================
// External declarations — one block per generated .cpp file.
// Only the block matching the active TEST_XXX guard is linked.
// ============================================================

#ifdef TEST_ABS_DEMO
extern "C" sisal_array_t func_DV_ABS_DEMO (sisal_array_t V);
#endif

#ifdef TEST_AGREEMENT
extern "C" sisal_array_t func_MAIN (sisal_array_t A,
                                    sisal_array_t B); // dv_agreement
#endif

#ifdef TEST_LIFTED_ARITH
extern "C" sisal_array_t func_MAIN (sisal_array_t A,
                                    sisal_array_t B); // dv_lifted_arith
#endif

#ifdef TEST_SHL
extern "C" sisal_array_t func_DV_SHL_SCALAR (sisal_array_t V, int32_t N);
#endif

#ifdef TEST_TEST_SUBSET
extern "C" sisal_array_t func_DV_ABS_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_NEGATE_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_SQRT_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_SIN_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_COS_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_ADD_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_MUL_SCALAR (sisal_array_t V, float S);
extern "C" sisal_array_t func_DV_ADD_SCALAR (sisal_array_t V, float S);
extern "C" sisal_array_t func_DV_GT_SCALAR (sisal_array_t V, float S);
extern "C" float func_DV_SUM_REAL (sisal_array_t V);
#endif

#ifdef TEST_INTRINSICS
extern "C" sisal_array_t func_DV_ABS_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_SQRT_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_SIN_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_COS_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_LOG_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_FLOOR_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_TRUNC_REAL (sisal_array_t V);
extern "C" sisal_array_t func_DV_ABS_DOUBLE (sisal_array_t V);
extern "C" sisal_array_t func_DV_SQRT_DOUBLE (sisal_array_t V);
extern "C" sisal_array_t func_DV_ADD_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_SUB_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_MUL_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_DIV_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_SCALAR_ADD_DV (float S, sisal_array_t V);
extern "C" sisal_array_t func_DV_GT_SCALAR (sisal_array_t V, float S);
extern "C" sisal_array_t func_DV_EQ_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_NE_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_AND_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_OR_DV (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_DV_SHL_SCALAR (sisal_array_t V, int32_t N);
extern "C" sisal_array_t func_DV_SHR_SCALAR (sisal_array_t V, int32_t N);
extern "C" float func_DV_SUM_REAL (sisal_array_t V);
extern "C" float func_DV_PRODUCT_REAL (sisal_array_t V);
extern "C" float func_DV_LEAST_REAL (sisal_array_t V);
extern "C" float func_DV_GREATEST_REAL (sisal_array_t V);
extern "C" int32_t func_DV_SUM_INT (sisal_array_t V);
extern "C" int32_t func_DV_PRODUCT_INT (sisal_array_t V);
extern "C" int32_t func_DV_LEAST_INT (sisal_array_t V);
extern "C" int32_t func_DV_GREATEST_INT (sisal_array_t V);
#endif

#ifdef TEST_BROADCAST_COMPLEX
extern "C" sisal_array_t func_BROADCAST_VEC_MAT (sisal_array_t V,
                                                 sisal_array_t M);
extern "C" sisal_array_t func_BROADCAST_UNIT (sisal_array_t A,
                                              sisal_array_t B);
extern "C" sisal_array_t func_BROADCAST_SCALAR (double S, sisal_array_t M);
#endif

#ifdef TEST_COMPRESS
extern "C" sisal_array_t func_COMPRESS_MONOLITHIC (sisal_array_t MASK,
                                                   sisal_array_t A);
extern "C" sisal_array_t func_COMPRESS_DV_INPUT (int32_t N);
extern "C" int32_t func_COMPRESS_CHAIN (sisal_array_t MASK, sisal_array_t A);
#endif

#ifdef TEST_BROADCAST_NUMPY
extern "C" sisal_array_t func_MAIN (sisal_array_t A,
                                    sisal_array_t B); // dv_broadcast_numpy
#endif

#ifdef TEST_FORALL_CPU
extern "C" sisal_array_t func_MAIN_CPU (int32_t N);
#endif

#ifdef TEST_NEGATE_DV
extern "C" sisal_array_t func_NEGATE (sisal_array_t A);
#endif

#ifdef TEST_FORALL_BASIC_DV
extern "C" sisal_array_t func_FORALL_BASIC (int32_t N);
#endif

#ifdef TEST_FORALL_REDUCE_DV
extern "C" int32_t func_SUM_TO_N (int32_t N);
extern "C" int32_t func_PRODUCT_TO_N (int32_t N);
extern "C" int32_t func_MIN_TO_N (int32_t N);
extern "C" int32_t func_MAX_TO_N (int32_t N);
#endif

// ============================================================
// GROUP A — dv_abs_demo
// ============================================================

#ifdef TEST_ABS_DEMO
static void
test_abs_demo (void)
{
  printf ("\n=== Group A: dv_abs_demo ===\n");
  float inp[] = { -1.5f, 2.5f, -3.5f };
  float exp[] = { 1.5f, 2.5f, 3.5f };
  sisal_array_t v = make_float_arr (inp, 3);
  sisal_array_t r = func_DV_ABS_DEMO (v);
  check ("abs_demo[0]", near_f (af (r, 0), exp[0]));
  check ("abs_demo[1]", near_f (af (r, 1), exp[1]));
  check ("abs_demo[2]", near_f (af (r, 2), exp[2]));
  free (v.data);
  free (r.data);
}
#endif

// ============================================================
// GROUP B — dv_agreement  (func_MAIN: int32 + int32 → int32)
// ============================================================

#ifdef TEST_AGREEMENT
static void
test_agreement (void)
{
  printf ("\n=== Group B: dv_agreement ===\n");
  int32_t a[] = { 1, 2, 3 };
  int32_t b[] = { 10, 20, 30 };
  int32_t ex[] = { 11, 22, 33 };
  sisal_array_t va = make_int_arr (a, 3);
  sisal_array_t vb = make_int_arr (b, 3);
  sisal_array_t r = func_MAIN (va, vb);
  check ("agreement[0]", ai (r, 0) == ex[0]);
  check ("agreement[1]", ai (r, 1) == ex[1]);
  check ("agreement[2]", ai (r, 2) == ex[2]);
  free (va.data);
  free (vb.data);
  free (r.data);
}
#endif

// ============================================================
// GROUP C — dv_lifted_arith  (func_MAIN: double A*B+A)
// ============================================================

#ifdef TEST_LIFTED_ARITH
static void
test_lifted_arith (void)
{
  printf ("\n=== Group C: dv_lifted_arith ===\n");
  double a[] = { 1.0, 2.0, 3.0 };
  double b[] = { 10.0, 20.0, 30.0 };
  // A*B+A = [1*10+1, 2*20+2, 3*30+3] = [11, 42, 93]
  double ex[] = { 11.0, 42.0, 93.0 };
  sisal_array_t va = make_double_arr (a, 3);
  sisal_array_t vb = make_double_arr (b, 3);
  sisal_array_t r = func_MAIN (va, vb);
  check ("lifted_arith[0]", near_d (ad (r, 0), ex[0]));
  check ("lifted_arith[1]", near_d (ad (r, 1), ex[1]));
  check ("lifted_arith[2]", near_d (ad (r, 2), ex[2]));
  free (va.data);
  free (vb.data);
  free (r.data);
}
#endif

// ============================================================
// GROUP D — dv_shl  (int32 << N)
// ============================================================

#ifdef TEST_SHL
static void
test_shl (void)
{
  printf ("\n=== Group D: dv_shl ===\n");
  int32_t v[] = { 1, 2, 4 };
  int32_t ex[] = { 4, 8, 16 };
  sisal_array_t vv = make_int_arr (v, 3);
  sisal_array_t r = func_DV_SHL_SCALAR (vv, 2);
  check ("shl[0]", ai (r, 0) == ex[0]);
  check ("shl[1]", ai (r, 1) == ex[1]);
  check ("shl[2]", ai (r, 2) == ex[2]);
  free (vv.data);
  free (r.data);
}
#endif

// ============================================================
// GROUP E — dv_test_subset
// ============================================================

#ifdef TEST_TEST_SUBSET
static void
test_test_subset (void)
{
  printf ("\n=== Group E: dv_test_subset ===\n");

  // abs([-1,2,-3]) → [1,2,3]
  {
    float inp[] = { -1.f, 2.f, -3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_ABS_REAL (v);
    check ("ts_abs[0]", near_f (af (r, 0), 1.f));
    check ("ts_abs[1]", near_f (af (r, 1), 2.f));
    check ("ts_abs[2]", near_f (af (r, 2), 3.f));
    free (v.data);
    free (r.data);
  }

  // negate([1,-2,3]) → [-1,2,-3]
  {
    float inp[] = { 1.f, -2.f, 3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_NEGATE_REAL (v);
    check ("ts_negate[0]", near_f (af (r, 0), -1.f));
    check ("ts_negate[1]", near_f (af (r, 1), 2.f));
    check ("ts_negate[2]", near_f (af (r, 2), -3.f));
    free (v.data);
    free (r.data);
  }

  // sqrt([1,4,9]) → [1,2,3]
  {
    float inp[] = { 1.f, 4.f, 9.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_SQRT_REAL (v);
    check ("ts_sqrt[0]", near_f (af (r, 0), 1.f));
    check ("ts_sqrt[1]", near_f (af (r, 1), 2.f));
    check ("ts_sqrt[2]", near_f (af (r, 2), 3.f));
    free (v.data);
    free (r.data);
  }

  // sin([0]) → [0]
  {
    float inp[] = { 0.f };
    sisal_array_t v = make_float_arr (inp, 1);
    sisal_array_t r = func_DV_SIN_REAL (v);
    check ("ts_sin[0]", near_f (af (r, 0), 0.f));
    free (v.data);
    free (r.data);
  }

  // cos([0]) → [1]
  {
    float inp[] = { 0.f };
    sisal_array_t v = make_float_arr (inp, 1);
    sisal_array_t r = func_DV_COS_REAL (v);
    check ("ts_cos[0]", near_f (af (r, 0), 1.f));
    free (v.data);
    free (r.data);
  }

  // add_dv([1,2],[3,4]) → [4,6]
  {
    float a[] = { 1.f, 2.f };
    float b[] = { 3.f, 4.f };
    sisal_array_t va = make_float_arr (a, 2);
    sisal_array_t vb = make_float_arr (b, 2);
    sisal_array_t r = func_DV_ADD_DV (va, vb);
    check ("ts_add_dv[0]", near_f (af (r, 0), 4.f));
    check ("ts_add_dv[1]", near_f (af (r, 1), 6.f));
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // mul_scalar([2,3,4], 10) → [20,30,40]
  {
    float inp[] = { 2.f, 3.f, 4.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_MUL_SCALAR (v, 10.f);
    check ("ts_mul_scalar[0]", near_f (af (r, 0), 20.f));
    check ("ts_mul_scalar[1]", near_f (af (r, 1), 30.f));
    check ("ts_mul_scalar[2]", near_f (af (r, 2), 40.f));
    free (v.data);
    free (r.data);
  }

  // add_scalar([1,2,3], 10) → [11,12,13]
  {
    float inp[] = { 1.f, 2.f, 3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_ADD_SCALAR (v, 10.f);
    check ("ts_add_scalar[0]", near_f (af (r, 0), 11.f));
    check ("ts_add_scalar[1]", near_f (af (r, 1), 12.f));
    check ("ts_add_scalar[2]", near_f (af (r, 2), 13.f));
    free (v.data);
    free (r.data);
  }

  // gt_scalar([1,5,3], 2) → [false,true,true]
  {
    float inp[] = { 1.f, 5.f, 3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_GT_SCALAR (v, 2.f);
    check ("ts_gt_scalar[0]", ab (r, 0) == false);
    check ("ts_gt_scalar[1]", ab (r, 1) == true);
    check ("ts_gt_scalar[2]", ab (r, 2) == true);
    free (v.data);
    free (r.data);
  }

  // sum_real([1,2,3,4]) → 10
  {
    float inp[] = { 1.f, 2.f, 3.f, 4.f };
    sisal_array_t v = make_float_arr (inp, 4);
    float s = func_DV_SUM_REAL (v);
    check ("ts_sum_real", near_f (s, 10.f));
    free (v.data);
  }
}
#endif

// ============================================================
// GROUP F — dv_intrinsics (representative subset)
// ============================================================

#ifdef TEST_INTRINSICS
static void
test_intrinsics (void)
{
  printf ("\n=== Group F: dv_intrinsics ===\n");

  // dv_abs_real([-1,2,-3]) → [1,2,3]
  {
    float inp[] = { -1.f, 2.f, -3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_ABS_REAL (v);
    check ("intr_abs_real[0]", near_f (af (r, 0), 1.f));
    check ("intr_abs_real[1]", near_f (af (r, 1), 2.f));
    check ("intr_abs_real[2]", near_f (af (r, 2), 3.f));
    free (v.data);
    free (r.data);
  }

  // dv_sqrt_real([1,4,9]) → [1,2,3]
  {
    float inp[] = { 1.f, 4.f, 9.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_SQRT_REAL (v);
    check ("intr_sqrt_real[0]", near_f (af (r, 0), 1.f));
    check ("intr_sqrt_real[1]", near_f (af (r, 1), 2.f));
    check ("intr_sqrt_real[2]", near_f (af (r, 2), 3.f));
    free (v.data);
    free (r.data);
  }

  // dv_sin_real([0]) → [0]
  {
    float inp[] = { 0.f };
    sisal_array_t v = make_float_arr (inp, 1);
    sisal_array_t r = func_DV_SIN_REAL (v);
    check ("intr_sin_real[0]", near_f (af (r, 0), 0.f));
    free (v.data);
    free (r.data);
  }

  // dv_cos_real([0]) → [1]
  {
    float inp[] = { 0.f };
    sisal_array_t v = make_float_arr (inp, 1);
    sisal_array_t r = func_DV_COS_REAL (v);
    check ("intr_cos_real[0]", near_f (af (r, 0), 1.f));
    free (v.data);
    free (r.data);
  }

  // dv_log_real([1]) → [0]  (ln 1 = 0)
  {
    float inp[] = { 1.f };
    sisal_array_t v = make_float_arr (inp, 1);
    sisal_array_t r = func_DV_LOG_REAL (v);
    check ("intr_log_real[0]", near_f (af (r, 0), 0.f));
    free (v.data);
    free (r.data);
  }

  // dv_floor_real([1.7, 2.3, -0.5]) → int32[1, 2, -1]
  {
    float inp[] = { 1.7f, 2.3f, -0.5f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_FLOOR_REAL (v);
    check ("intr_floor_real[0]", ai (r, 0) == 1);
    check ("intr_floor_real[1]", ai (r, 1) == 2);
    check ("intr_floor_real[2]", ai (r, 2) == -1);
    free (v.data);
    free (r.data);
  }

  // dv_trunc_real([1.7, 2.3, -0.5]) → int32[1, 2, 0]
  {
    float inp[] = { 1.7f, 2.3f, -0.5f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_TRUNC_REAL (v);
    check ("intr_trunc_real[0]", ai (r, 0) == 1);
    check ("intr_trunc_real[1]", ai (r, 1) == 2);
    check ("intr_trunc_real[2]", ai (r, 2) == 0);
    free (v.data);
    free (r.data);
  }

  // dv_abs_double([-1.0, 2.0]) → [1.0, 2.0]
  {
    double inp[] = { -1.0, 2.0 };
    sisal_array_t v = make_double_arr (inp, 2);
    sisal_array_t r = func_DV_ABS_DOUBLE (v);
    check ("intr_abs_double[0]", near_d (ad (r, 0), 1.0));
    check ("intr_abs_double[1]", near_d (ad (r, 1), 2.0));
    free (v.data);
    free (r.data);
  }

  // dv_sqrt_double([4.0, 9.0]) → [2.0, 3.0]
  {
    double inp[] = { 4.0, 9.0 };
    sisal_array_t v = make_double_arr (inp, 2);
    sisal_array_t r = func_DV_SQRT_DOUBLE (v);
    check ("intr_sqrt_double[0]", near_d (ad (r, 0), 2.0));
    check ("intr_sqrt_double[1]", near_d (ad (r, 1), 3.0));
    free (v.data);
    free (r.data);
  }

  // dv_add_dv([1,2,3],[4,5,6]) → [5,7,9]
  {
    float a[] = { 1.f, 2.f, 3.f }, b[] = { 4.f, 5.f, 6.f };
    sisal_array_t va = make_float_arr (a, 3), vb = make_float_arr (b, 3);
    sisal_array_t r = func_DV_ADD_DV (va, vb);
    check ("intr_add_dv[0]", near_f (af (r, 0), 5.f));
    check ("intr_add_dv[1]", near_f (af (r, 1), 7.f));
    check ("intr_add_dv[2]", near_f (af (r, 2), 9.f));
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_sub_dv([4,5,6],[1,2,3]) → [3,3,3]
  {
    float a[] = { 4.f, 5.f, 6.f }, b[] = { 1.f, 2.f, 3.f };
    sisal_array_t va = make_float_arr (a, 3), vb = make_float_arr (b, 3);
    sisal_array_t r = func_DV_SUB_DV (va, vb);
    check ("intr_sub_dv[0]", near_f (af (r, 0), 3.f));
    check ("intr_sub_dv[1]", near_f (af (r, 1), 3.f));
    check ("intr_sub_dv[2]", near_f (af (r, 2), 3.f));
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_mul_dv([2,3,4],[5,6,7]) → [10,18,28]
  {
    float a[] = { 2.f, 3.f, 4.f }, b[] = { 5.f, 6.f, 7.f };
    sisal_array_t va = make_float_arr (a, 3), vb = make_float_arr (b, 3);
    sisal_array_t r = func_DV_MUL_DV (va, vb);
    check ("intr_mul_dv[0]", near_f (af (r, 0), 10.f));
    check ("intr_mul_dv[1]", near_f (af (r, 1), 18.f));
    check ("intr_mul_dv[2]", near_f (af (r, 2), 28.f));
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_div_dv([10,20,30],[2,4,5]) → [5,5,6]
  {
    float a[] = { 10.f, 20.f, 30.f }, b[] = { 2.f, 4.f, 5.f };
    sisal_array_t va = make_float_arr (a, 3), vb = make_float_arr (b, 3);
    sisal_array_t r = func_DV_DIV_DV (va, vb);
    check ("intr_div_dv[0]", near_f (af (r, 0), 5.f));
    check ("intr_div_dv[1]", near_f (af (r, 1), 5.f));
    check ("intr_div_dv[2]", near_f (af (r, 2), 6.f));
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // scalar_add_dv(10, [1,2,3]) → [11,12,13]
  {
    float inp[] = { 1.f, 2.f, 3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_SCALAR_ADD_DV (10.f, v);
    check ("intr_scalar_add_dv[0]", near_f (af (r, 0), 11.f));
    check ("intr_scalar_add_dv[1]", near_f (af (r, 1), 12.f));
    check ("intr_scalar_add_dv[2]", near_f (af (r, 2), 13.f));
    free (v.data);
    free (r.data);
  }

  // dv_gt_scalar([1,5,3], 2) → [F,T,T]
  {
    float inp[] = { 1.f, 5.f, 3.f };
    sisal_array_t v = make_float_arr (inp, 3);
    sisal_array_t r = func_DV_GT_SCALAR (v, 2.f);
    check ("intr_gt_scalar[0]", ab (r, 0) == false);
    check ("intr_gt_scalar[1]", ab (r, 1) == true);
    check ("intr_gt_scalar[2]", ab (r, 2) == true);
    free (v.data);
    free (r.data);
  }

  // dv_eq_dv([1,2,3],[1,9,3]) → [T,F,T]
  {
    float a[] = { 1.f, 2.f, 3.f }, b[] = { 1.f, 9.f, 3.f };
    sisal_array_t va = make_float_arr (a, 3), vb = make_float_arr (b, 3);
    sisal_array_t r = func_DV_EQ_DV (va, vb);
    check ("intr_eq_dv[0]", ab (r, 0) == true);
    check ("intr_eq_dv[1]", ab (r, 1) == false);
    check ("intr_eq_dv[2]", ab (r, 2) == true);
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_ne_dv([1,2,3],[1,9,3]) → [F,T,F]
  {
    float a[] = { 1.f, 2.f, 3.f }, b[] = { 1.f, 9.f, 3.f };
    sisal_array_t va = make_float_arr (a, 3), vb = make_float_arr (b, 3);
    sisal_array_t r = func_DV_NE_DV (va, vb);
    check ("intr_ne_dv[0]", ab (r, 0) == false);
    check ("intr_ne_dv[1]", ab (r, 1) == true);
    check ("intr_ne_dv[2]", ab (r, 2) == false);
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_and_dv([T,T,F],[T,F,F]) → [T,F,F]
  {
    bool a[] = { true, true, false }, b[] = { true, false, false };
    sisal_array_t va = make_bool_arr (a, 3), vb = make_bool_arr (b, 3);
    sisal_array_t r = func_DV_AND_DV (va, vb);
    check ("intr_and_dv[0]", ab (r, 0) == true);
    check ("intr_and_dv[1]", ab (r, 1) == false);
    check ("intr_and_dv[2]", ab (r, 2) == false);
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_or_dv([T,F,F],[F,F,T]) → [T,F,T]
  {
    bool a[] = { true, false, false }, b[] = { false, false, true };
    sisal_array_t va = make_bool_arr (a, 3), vb = make_bool_arr (b, 3);
    sisal_array_t r = func_DV_OR_DV (va, vb);
    check ("intr_or_dv[0]", ab (r, 0) == true);
    check ("intr_or_dv[1]", ab (r, 1) == false);
    check ("intr_or_dv[2]", ab (r, 2) == true);
    free (va.data);
    free (vb.data);
    free (r.data);
  }

  // dv_shl_scalar([1,2,4], 2) → [4,8,16]
  {
    int32_t inp[] = { 1, 2, 4 };
    sisal_array_t v = make_int_arr (inp, 3);
    sisal_array_t r = func_DV_SHL_SCALAR (v, 2);
    check ("intr_shl_scalar[0]", ai (r, 0) == 4);
    check ("intr_shl_scalar[1]", ai (r, 1) == 8);
    check ("intr_shl_scalar[2]", ai (r, 2) == 16);
    free (v.data);
    free (r.data);
  }

  // dv_shr_scalar([8,4,16], 2) → [2,1,4]
  {
    int32_t inp[] = { 8, 4, 16 };
    sisal_array_t v = make_int_arr (inp, 3);
    sisal_array_t r = func_DV_SHR_SCALAR (v, 2);
    check ("intr_shr_scalar[0]", ai (r, 0) == 2);
    check ("intr_shr_scalar[1]", ai (r, 1) == 1);
    check ("intr_shr_scalar[2]", ai (r, 2) == 4);
    free (v.data);
    free (r.data);
  }

  // dv_sum_real([1,2,3,4]) → 10
  {
    float inp[] = { 1.f, 2.f, 3.f, 4.f };
    sisal_array_t v = make_float_arr (inp, 4);
    float s = func_DV_SUM_REAL (v);
    check ("intr_sum_real", near_f (s, 10.f));
    free (v.data);
  }

  // dv_product_real([1,2,3,4]) → 24
  // NOTE: sisal_array_reduce_float_product is a stub returning 1.0f — EXPECTED
  // FAIL
  {
    float inp[] = { 1.f, 2.f, 3.f, 4.f };
    sisal_array_t v = make_float_arr (inp, 4);
    float s = func_DV_PRODUCT_REAL (v);
    printf ("  INFO  intr_product_real = %g (expected 24; runtime stub "
            "returns 1 — known issue)\n",
            s);
    check ("intr_product_real", near_f (s, 24.f));
    free (v.data);
  }

  // dv_least_real([3,1,4,1,5]) → 1
  // NOTE: sisal_array_reduce_least is a stub returning 0.0f — EXPECTED FAIL
  {
    float inp[] = { 3.f, 1.f, 4.f, 1.f, 5.f };
    sisal_array_t v = make_float_arr (inp, 5);
    float s = func_DV_LEAST_REAL (v);
    printf ("  INFO  intr_least_real = %g (expected 1; runtime stub returns 0 "
            "— known issue)\n",
            s);
    check ("intr_least_real", near_f (s, 1.f));
    free (v.data);
  }

  // dv_greatest_real([3,1,4,1,5]) → 5
  // NOTE: sisal_array_reduce_greatest is a stub returning 0.0f — EXPECTED FAIL
  {
    float inp[] = { 3.f, 1.f, 4.f, 1.f, 5.f };
    sisal_array_t v = make_float_arr (inp, 5);
    float s = func_DV_GREATEST_REAL (v);
    printf ("  INFO  intr_greatest_real = %g (expected 5; runtime stub "
            "returns 0 — known issue)\n",
            s);
    check ("intr_greatest_real", near_f (s, 5.f));
    free (v.data);
  }

  // dv_sum_int([1,2,3,4]) → 10
  // NOTE: reduce_int_sum calls reduce_sum (float*) on int32 data — result is
  // implementation-defined
  {
    int32_t inp[] = { 1, 2, 3, 4 };
    sisal_array_t v = make_int_arr (inp, 4);
    int32_t s = func_DV_SUM_INT (v);
    printf ("  INFO  intr_sum_int = %d (expected 10; runtime interprets int "
            "bits as float — may differ)\n",
            s);
    check ("intr_sum_int", s == 10);
    free (v.data);
  }

  // dv_product_int([1,2,3,4]) → 24  (reduce_int_product is properly
  // implemented)
  {
    int32_t inp[] = { 1, 2, 3, 4 };
    sisal_array_t v = make_int_arr (inp, 4);
    int32_t s = func_DV_PRODUCT_INT (v);
    check ("intr_product_int", s == 24);
    free (v.data);
  }

  // dv_least_int([3,1,4]) → 1
  // NOTE: reduce_int_least is a stub returning 0 — EXPECTED FAIL
  {
    int32_t inp[] = { 3, 1, 4 };
    sisal_array_t v = make_int_arr (inp, 3);
    int32_t s = func_DV_LEAST_INT (v);
    printf ("  INFO  intr_least_int = %d (expected 1; runtime stub returns 0 "
            "— known issue)\n",
            s);
    check ("intr_least_int", s == 1);
    free (v.data);
  }

  // dv_greatest_int([3,1,4]) → 4
  // NOTE: reduce_int_greatest is a stub returning 0 — EXPECTED FAIL
  {
    int32_t inp[] = { 3, 1, 4 };
    sisal_array_t v = make_int_arr (inp, 3);
    int32_t s = func_DV_GREATEST_INT (v);
    printf ("  INFO  intr_greatest_int = %d (expected 4; runtime stub returns "
            "0 — known issue)\n",
            s);
    check ("intr_greatest_int", s == 4);
    free (v.data);
  }
}
#endif

// ============================================================
// GROUP G — dv_broadcast_complex  (2D double broadcasting)
//
// Known compiler bug: the broadcast functions produce wrong shape metadata
// (rank/dims) and in the vec_mat case also wrong element count.  The tests
// below assert the *actual* observed behaviour so they function as a
// regression baseline.  Correct expected values are noted in comments.
// ============================================================

#ifdef TEST_BROADCAST_COMPLEX
static void
test_broadcast_complex (void)
{
  printf ("\n=== Group G: dv_broadcast_complex ===\n");

  // broadcast_vec_mat: V=[1,2,3] (1D) + M=[[10,20,30],[40,50,60]] (shape
  // [2,3]) numpy: result shape [2,3], values [11,22,33, 41,52,63].
  {
    double v_data[] = { 1.0, 2.0, 3.0 };
    double m_data[] = { 10.0, 20.0, 30.0, 40.0, 50.0, 60.0 };
    sisal_array_t V = make_double_arr (v_data, 3);
    sisal_array_t M = make_double_2d (m_data, 2, 3);
    sisal_array_t r = func_BROADCAST_VEC_MAT (V, M);
    check ("bcast_vec_mat shape [2,3]",
           r.rank == 2 && r.dims[0] == 2 && r.dims[1] == 3 && r.size == 6);
    double ex[] = { 11, 22, 33, 41, 52, 63 };
    bool ok = (r.size == 6);
    for (int i = 0; i < 6 && ok; i++)
      ok &= near_d (ad (r, i), ex[i]);
    check ("bcast_vec_mat values 11 22 33 41 52 63", ok);
    free (V.data);
    free (M.data);
    free (r.data);
  }

  // broadcast_unit: A=[[1],[2]] (shape [2,1]) + B=[[10,20,30]] (shape [1,3])
  // numpy: result shape [2,3], values [11,21,31, 12,22,32].
  {
    double a_data[] = { 1.0, 2.0 };
    double b_data[] = { 10.0, 20.0, 30.0 };
    sisal_array_t A = make_double_2d (a_data, 2, 1);
    sisal_array_t B = make_double_2d (b_data, 1, 3);
    sisal_array_t r = func_BROADCAST_UNIT (A, B);
    check ("bcast_unit shape [2,3]",
           r.rank == 2 && r.dims[0] == 2 && r.dims[1] == 3 && r.size == 6);
    double ex[] = { 11, 21, 31, 12, 22, 32 };
    bool ok = (r.size == 6);
    for (int i = 0; i < 6 && ok; i++)
      ok &= near_d (ad (r, i), ex[i]);
    check ("bcast_unit values 11 21 31 12 22 32", ok);
    free (A.data);
    free (B.data);
    free (r.data);
  }

  // broadcast_scalar: S=100.0 + M=[[1..9]] (shape [3,3]) -> values [101..109].
  // VALUES are correct; the result SHAPE is still rank-1 [9] -- a separate bug
  // in the scalar+array path (the conform fix only covers array+array rank
  // mismatch).
  {
    double m_data[] = { 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0 };
    sisal_array_t M = make_double_2d (m_data, 3, 3);
    sisal_array_t r = func_BROADCAST_SCALAR (100.0, M);
    // scalar broadcast keeps M's shape: the flat elementwise result is
    // reshaped back to M's runtime rank/dims (DV_NUM_RANK -> DV_DIMENSION ->
    // RESHAPE).
    check ("bcast_scalar shape [3,3]",
           r.rank == 2 && r.dims[0] == 3 && r.dims[1] == 3 && r.size == 9);
    bool ok = (r.size == 9);
    for (int i = 0; i < 9 && ok; i++)
      ok &= near_d (ad (r, i), m_data[i] + 100.0);
    check ("bcast_scalar values 101..109", ok);
    free (M.data);
    free (r.data);
  }
}
#endif

// ============================================================
// GROUP H — dv_compress_test
// ============================================================

#ifdef TEST_COMPRESS
static void
test_compress (void)
{
  printf ("\n=== Group H: dv_compress_test ===\n");

  // compress_monolithic: mask=[T,F,T,F,T], a=[10,20,30,40,50] → [10,30,50]
  // NOTE: sisal_array_compress uses float* cast to copy elements regardless of
  // type_id. For int32 inputs, this means a 4-byte copy as if the bits were
  // float. The result array has type_id=6 (int32) but was written via float*,
  // so values should still be bit-identical to the original int32 values if
  // sizeof(float)==sizeof(int32_t).
  {
    bool mask[] = { true, false, true, false, true };
    int32_t a[] = { 10, 20, 30, 40, 50 };
    sisal_array_t vm = make_bool_arr (mask, 5);
    sisal_array_t va = make_int_arr (a, 5);
    sisal_array_t r = func_COMPRESS_MONOLITHIC (vm, va);
    check ("compress_mono_size", r.size == 3);
    // The runtime copies via float* (4 bytes each), same width as int32_t,
    // so the bit pattern is preserved.
    check ("compress_mono[0]", ai (r, 0) == 10);
    check ("compress_mono[1]", ai (r, 1) == 30);
    check ("compress_mono[2]", ai (r, 2) == 50);
    free (vm.data);
    free (va.data);
    free (r.data);
  }

  // compress_dv_input(6): even numbers from 1..6 = [2,4,6]
  {
    sisal_array_t r = func_COMPRESS_DV_INPUT (6);
    check ("compress_dv_size", r.size == 3);
    // The values array was int32, copied via float* — bit-identical
    check ("compress_dv[0]", ai (r, 0) == 2);
    check ("compress_dv[1]", ai (r, 1) == 4);
    check ("compress_dv[2]", ai (r, 2) == 6);
    free (r.data);
  }

  // compress_chain: mask=[T,F,T], a=[10,20,30] → size=2
  {
    bool mask[] = { true, false, true };
    int32_t a[] = { 10, 20, 30 };
    sisal_array_t vm = make_bool_arr (mask, 3);
    sisal_array_t va = make_int_arr (a, 3);
    int32_t s = func_COMPRESS_CHAIN (vm, va);
    check ("compress_chain", s == 2);
    free (vm.data);
    free (va.data);
  }
}
#endif

// ============================================================
// GROUP I — dv_broadcast_numpy (APL rank-mismatch: expected error)
// ============================================================

#ifdef TEST_BROADCAST_NUMPY
static void
test_broadcast_numpy (void)
{
  printf ("\n=== Group I: dv_broadcast_numpy (trailing-axis broadcast, vs C "
          "reference) ===\n");
  // Implemented semantics for 2D [2,3] + 1D [3]: broadcast B across rows,
  //   out[i,j] = A[i,j] + B[j].  (numpy-style, despite the source's stale
  //   note.)
  const int R = 2, C = 3;
  double a_data[] = { 1.0, 2.0, 3.0, 4.0, 5.0, 6.0 };
  double b_data[] = { 10.0, 20.0, 30.0 };
  double exp[6];
  for (int i = 0; i < R; i++)
    for (int j = 0; j < C; j++)
      exp[i * C + j] = a_data[i * C + j] + b_data[j];
  sisal_array_t A = make_double_2d (a_data, R, C);
  sisal_array_t B = make_double_arr (b_data, C); // 1D, rank=1
  sisal_array_t r = func_MAIN (A, B);
  bool ok = (r.rank == 2) && ((int)r.dims[0] == R) && ((int)r.dims[1] == C);
  for (int t = 0; ok && t < R * C; t++)
    ok = ok && (fabs (ad (r, t) - exp[t]) < 1e-9);
  check ("broadcast_numpy [2,3]+[3] == A[i,j]+B[j] (vs C reference)", ok);
  free (A.data);
  free (B.data);
  if (r.data)
    free (r.data);
}
#endif

// ============================================================
// GROUP J — forall_cpu  (for i in 1..N → array_dv of -real(i))
// ============================================================

#ifdef TEST_FORALL_CPU
static void
test_forall_cpu (void)
{
  printf ("\n=== Group J: forall_cpu ===\n");
  // func_MAIN_CPU(4): X = real(i) for i in 1..4, return -X
  // Expected: [-1.0, -2.0, -3.0, -4.0]
  sisal_array_t r = func_MAIN_CPU (4);
  float exp[] = { -1.0f, -2.0f, -3.0f, -4.0f };
  check ("forall_cpu_size", (int32_t)r.size == 4);
  for (int i = 0; i < 4; i++)
    {
      char name[32];
      snprintf (name, sizeof (name), "forall_cpu[%d]", i);
      check (name, near_f (af (r, i), exp[i]));
    }
  if (r.data)
    free (r.data);
}
#endif

// ============================================================
// GROUP K — negate_dv  (let N := size(A) in for I in 1..N: -A[I])
// ============================================================

#ifdef TEST_NEGATE_DV
static void
test_negate_dv (void)
{
  printf ("\n=== Group K: negate_dv ===\n");
  // func_NEGATE([3, 1, 4, 1, 5]) → [-3, -1, -4, -1, -5]
  int32_t inp[] = { 3, 1, 4, 1, 5 };
  int32_t exp[] = { -3, -1, -4, -1, -5 };
  sisal_array_t A = make_int_arr (inp, 5); // lower_bound = 1
  sisal_array_t r = func_NEGATE (A);
  check ("negate_dv_size", (int32_t)r.size == 5);
  for (int i = 0; i < 5; i++)
    {
      char name[32];
      snprintf (name, sizeof (name), "negate_dv[%d]", i);
      check (name, ai (r, i) == exp[i]);
    }
  free (A.data);
  if (r.data)
    free (r.data);
}
#endif

// ============================================================
// GROUP L — dv_forall_basic  (for i in 1..N → array_dv of i)
// ============================================================

#ifdef TEST_FORALL_BASIC_DV
static void
test_forall_basic_dv (void)
{
  printf ("\n=== Group L: dv_forall_basic ===\n");
  // func_FORALL_BASIC(5) → [1, 2, 3, 4, 5]
  sisal_array_t r = func_FORALL_BASIC (5);
  int32_t exp[] = { 1, 2, 3, 4, 5 };
  check ("forall_basic_dv_size", (int32_t)r.size == 5);
  for (int i = 0; i < 5; i++)
    {
      char name[32];
      snprintf (name, sizeof (name), "forall_basic_dv[%d]", i);
      check (name, ai (r, i) == exp[i]);
    }
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_FORALL_REDUCE_DV
static void
test_forall_reduce_dv (void)
{
  printf ("\n=== Group M: dv_forall_reduce ===\n");
  // sum_to_n(5)  = 1+2+3+4+5 = 15
  check ("sum_to_n_5", func_SUM_TO_N (5) == 15);
  check ("sum_to_n_0", func_SUM_TO_N (0) == 0);
  // product_to_n(5) = 120
  check ("product_to_n_5", func_PRODUCT_TO_N (5) == 120);
  check ("product_to_n_1", func_PRODUCT_TO_N (1) == 1);
  // min_to_n(5) = 1, max_to_n(5) = 5
  check ("min_to_n_5", func_MIN_TO_N (5) == 1);
  check ("max_to_n_5", func_MAX_TO_N (5) == 5);
  check ("max_to_n_1", func_MAX_TO_N (1) == 1);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{

#ifdef TEST_ABS_DEMO
  test_abs_demo ();
#endif
#ifdef TEST_AGREEMENT
  test_agreement ();
#endif
#ifdef TEST_LIFTED_ARITH
  test_lifted_arith ();
#endif
#ifdef TEST_SHL
  test_shl ();
#endif
#ifdef TEST_TEST_SUBSET
  test_test_subset ();
#endif
#ifdef TEST_INTRINSICS
  test_intrinsics ();
#endif
#ifdef TEST_BROADCAST_COMPLEX
  test_broadcast_complex ();
#endif
#ifdef TEST_COMPRESS
  test_compress ();
#endif
#ifdef TEST_BROADCAST_NUMPY
  test_broadcast_numpy ();
#endif
#ifdef TEST_FORALL_CPU
  test_forall_cpu ();
#endif
#ifdef TEST_NEGATE_DV
  test_negate_dv ();
#endif
#ifdef TEST_FORALL_BASIC_DV
  test_forall_basic_dv ();
#endif
#ifdef TEST_FORALL_REDUCE_DV
  test_forall_reduce_dv ();
#endif
#if !defined(TEST_ABS_DEMO) \
    && !defined(TEST_AGREEMENT) \
    && !defined(TEST_LIFTED_ARITH) \
    && !defined(TEST_SHL) \
    && !defined(TEST_TEST_SUBSET) \
    && !defined(TEST_INTRINSICS) \
    && !defined(TEST_BROADCAST_COMPLEX) \
    && !defined(TEST_COMPRESS) \
    && !defined(TEST_BROADCAST_NUMPY) \
    && !defined(TEST_FORALL_CPU) \
    && !defined(TEST_NEGATE_DV) \
    && !defined(TEST_FORALL_BASIC_DV) \
    && !defined(TEST_FORALL_REDUCE_DV)
  g_no_macro = true;
#endif
}
