// dv_part_16.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: XFA_B1_DECLDEF, XFA_C3_3AXIS, SLICE_STORE, MR_TWO_ARRAY, AA, SUB_2D, SUB_3D, SLICE_DOTDOT, TEST_MULTI_ARRAY_IF, FORALL_DV_AT, FORALL_DV_CROSS, FORALL_DV_DOT, FORALL_DV_DOT3
#include "dv_harness.h"

#ifdef TEST_SUB_2D
extern "C" int32_t func_MAIN (int32_t N); // build A[i,j]=i*10+j, read A[2,3]
#endif
#ifdef TEST_SUB_3D
extern "C" int32_t func_MAIN (int32_t N); // build A[i,j,k], read A[2,3,1]
#endif
#ifdef TEST_SLICE_DOTDOT
extern "C" sisal_array_t
func_MAIN (int32_t N); // A[2, ..] row slice (rank-reduce)
#endif
#ifdef TEST_TEST_MULTI_ARRAY_IF
struct MULTI_ARRAY_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct MULTI_ARRAY_results
func_MAIN (int32_t N); // two array outputs, if-in-body
#endif
#ifdef TEST_XFA_B1_DECLDEF
extern "C" sisal_array_t func_MAIN (int32_t N,
                                    int32_t M); // cross i*j via body decldef
#endif
#ifdef TEST_XFA_C3_3AXIS
extern "C" sisal_array_t func_MAIN (int32_t A, int32_t B,
                                    int32_t C); // rank-3 cross i*j*k
#endif
#ifdef TEST_SLICE_STORE
extern "C" sisal_array_t
func_MAIN (int32_t N); // A[2, .. : Z] write-side slice
#endif
#ifdef TEST_MR_TWO_ARRAY
extern "C" sisal_array_t
func_MAIN (int32_t N, sisal_array_t A); // multi-array destructure -> P
#endif
#ifdef TEST_AA
extern "C" sisal_array_t func_DVFILL (int32_t LO, int32_t HI,
                                      int32_t V); // array_dv fill
#endif

// Scatter-axis generators over array params (element var renamed off the array
// name to avoid the case-insensitive self-shadow; see forall_rebuild_note.md).
#ifdef TEST_FORALL_DV_AT
extern "C" sisal_array_t func_MAIN (sisal_array_t A); // for x in A at i -> x+i
#endif
#ifdef TEST_FORALL_DV_CROSS
extern "C" sisal_array_t func_MAIN (sisal_array_t A,
                                    sisal_array_t B); // x cross y -> x*y
#endif
#ifdef TEST_FORALL_DV_DOT
extern "C" sisal_array_t func_MAIN (sisal_array_t A,
                                    sisal_array_t B); // x dot y -> x+y
#endif
#ifdef TEST_FORALL_DV_DOT3
extern "C" sisal_array_t func_MAIN (sisal_array_t A, sisal_array_t B,
                                    sisal_array_t C); // x dot y dot z -> x+y+z
#endif

#ifdef TEST_XFA_B1_DECLDEF
static void
test_xfa_b1_decldef (void)
{
  printf ("\n=== Group: xfa_b1_decldef (cross i*j via body decldef) ===\n");
  sisal_array_t r = func_MAIN (2, 3);
  int32_t exp[] = { 1, 2, 3, 2, 4, 6 };
  bool ok = (r.rank == 2) && ((int)r.dims[0] == 2) && ((int)r.dims[1] == 3);
  for (int k = 0; ok && k < 6; k++)
    ok = ok && (ai (r, k) == exp[k]);
  check ("xfa_b1_decldef(2,3) == [1,2,3,2,4,6] 2x3", ok);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_XFA_C3_3AXIS
static void
test_xfa_c3_3axis (void)
{
  printf ("\n=== Group: xfa_c3_3axis (rank-3 cross i*j*k) ===\n");
  sisal_array_t r = func_MAIN (2, 2, 2);
  int32_t exp[] = { 1, 2, 2, 4, 2, 4, 4, 8 };
  bool ok = (r.rank == 3) && ((int)r.dims[0] == 2) && ((int)r.dims[1] == 2)
            && ((int)r.dims[2] == 2);
  for (int k = 0; ok && k < 8; k++)
    ok = ok && (ai (r, k) == exp[k]);
  check ("xfa_c3_3axis(2,2,2) == [1,2,2,4,2,4,4,8] 2x2x2", ok);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_SLICE_STORE
static void
test_slice_store (void)
{
  printf ("\n=== Group: slice_store (A[2, .. : Z] write-side slice) ===\n");
  sisal_array_t r = func_MAIN (3); // row 2 replaced by zeros
  int32_t exp[] = { 11, 12, 13, 0, 0, 0, 31, 32, 33 };
  bool ok = (r.rank == 2) && ((int)r.dims[0] == 3) && ((int)r.dims[1] == 3);
  for (int k = 0; ok && k < 9; k++)
    ok = ok && (ai (r, k) == exp[k]);
  check ("slice_store(3) == [11,12,13,0,0,0,31,32,33]", ok);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_MR_TWO_ARRAY
static void
test_mr_two_array (void)
{
  printf ("\n=== Group: mr_two_array (two array results, first taken) ===\n");
  // Two(n,A) = (A[i]+1, A[i]*2); Main binds both and returns P, the FIRST.
  // The reference computes both so a swap of the two result slots is visible
  // as P coming back as A[i]*2.
  const std::vector<double> a = { 1.0, 2.0, 3.0, -1.5 };
  sisal_array_t A = ewref::mkd (a);
  sisal_array_t r = func_MAIN ((int)a.size (), A);
  bool ok = (r.rank == 1) && ((size_t)r.size == a.size ());
  bool would_be_q = ok;
  for (size_t k = 0; k < a.size () && ok; k++)
    ok = near_d (ad (r, (int)k), a[k] + 1.0);
  for (size_t k = 0; k < a.size () && would_be_q; k++)
    would_be_q = near_d (ad (r, (int)k), a[k] * 2.0);
  check ("P == A[i] + 1.0 (the first of the two results)", ok);
  check ("...and it is not Q == A[i] * 2.0, so the slots are not swapped",
         !would_be_q);
  free (A.data);
  if (r.data && r.data != A.data) free (r.data);
}
#endif

#ifdef TEST_AA
static void
test_aa (void)
{
  printf ("\n=== Group: aa (array_dv fill) ===\n");
  sisal_array_t r = func_DVFILL (1, 5, 7); // [7,7,7,7,7]
  check ("dvfill rank-1", r.rank == 1 && (int)r.size == 5);
  bool ok = true;
  for (int k = 0; k < 5; k++)
    ok = ok && (ai (r, k) == 7);
  check ("dvfill(1,5,7) == [7]*5", ok);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_SUB_2D
static void
test_sub_2d (void)
{
  printf ("\n=== Group: sub_2d (rank-2 element subscript) ===\n");
  // A[i,j] = i*10 + j; the program reads A[2,3], so N must be >= 3
  const int32_t want = 2 * 10 + 3;
  bool ok = true;
  for (int n : { 3, 5, 8 }) ok = ok && (func_MAIN (n) == want);
  check ("A[2,3] == 2*10+3, independent of N >= 3", ok);
}
#endif

#ifdef TEST_SUB_3D
static void
test_sub_3d (void)
{
  printf ("\n=== Group: sub_3d (rank-3 element subscript) ===\n");
  // A[i,j,k] = i*100 + j*10 + k; the program reads A[2,3,1]
  const int32_t want = 2 * 100 + 3 * 10 + 1;
  bool ok = true;
  for (int n : { 3, 4, 5 }) ok = ok && (func_MAIN (n) == want);
  check ("A[2,3,1] == 2*100+3*10+1, independent of N >= 3", ok);
}
#endif

#ifdef TEST_SLICE_DOTDOT
static void
test_slice_dotdot (void)
{
  printf ("\n=== Group: slice_dotdot (row slice A[2, ..]) ===\n");
  // A[i,j] = i*10 + j; A[2, ..] is row 2, so element j is 2*10 + j
  bool ok = true;
  for (int n : { 3, 5 })
    {
      sisal_array_t r = func_MAIN (n);
      ok = ok && (r.rank == 1) && ((int)r.size == n);
      for (int j = 1; ok && j <= n; j++) ok = (ai (r, j - 1) == 2 * 10 + j);
      // NOT freed: a row slice is a descriptor pointing INTO its parent's
      // buffer at an offset, so the pointer is not a malloc block start and
      // free() traps on it.
    }
  check ("A[2, ..] == row 2 of A[i,j] = i*10+j, for N = 3 and 5", ok);
}
#endif

#ifdef TEST_TEST_MULTI_ARRAY_IF
// for i in 1,N returns array of (even? i*1.5 : i*0.5)  AND  array of i*i
static void
test_test_multi_array_if (void)
{
  printf ("\n=== Group: test_multi_array_if (dual array output, if-in-body) "
          "===\n");
  struct MULTI_ARRAY_results r = func_MAIN (4);
  double e0[] = { 0.5, 3.0, 1.5, 6.0 };
  int32_t e1[] = { 1, 4, 9, 16 };
  bool ok0 = (r.res_0.rank == 1) && ((int)r.res_0.size == 4);
  for (int k = 0; ok0 && k < 4; k++)
    ok0 = ok0 && (((double *)r.res_0.data)[k] == e0[k]);
  bool ok1 = (r.res_1.rank == 1) && ((int)r.res_1.size == 4);
  for (int k = 0; ok1 && k < 4; k++)
    ok1 = ok1 && (((int32_t *)r.res_1.data)[k] == e1[k]);
  check ("multi_array_if res_0 = [0.5,3,1.5,6]", ok0);
  check ("multi_array_if res_1 = [1,4,9,16]", ok1);
}
#endif

#ifdef TEST_FORALL_DV_AT
// for x in A at i returns array_dv of x + i  (i = 1-based index,
// lower_bound+k)
static void
test_forall_dv_at (void)
{
  printf ("\n=== Group: forall_dv_at (`for x in A at i`) ===\n");
  // the body is x + i, with i the 1-based position
  const std::vector<int32_t> a = { 10, 20, 30, -5, 0 };
  sisal_array_t A = ewref::mki (a);
  sisal_array_t r = func_MAIN (A);
  bool ok = (r.rank == 1) && ((size_t)r.size == a.size ());
  for (size_t k = 0; ok && k < a.size (); k++)
    ok = (ai (r, (int)k) == a[k] + (int32_t)(k + 1));
  check ("element == A[i] + i, with i the 1-based index", ok);
  free (A.data);
  if (r.data && r.data != A.data) free (r.data);
}
#endif

#ifdef TEST_FORALL_DV_CROSS
// for x in A cross y in B returns array_dv of x*y  (rank-2 cartesian product)
static void
test_forall_dv_cross (void)
{
  printf ("\n=== Group: forall_dv_cross (outer product) ===\n");
  const std::vector<int32_t> a = { 1, 2, -3 }, b = { 3, 4, 5, 0 };
  sisal_array_t A = ewref::mki (a), B = ewref::mki (b);
  sisal_array_t r = func_MAIN (A, B);
  bool ok = (r.rank == 2) && ((size_t)r.dims[0] == a.size ())
            && ((size_t)r.dims[1] == b.size ());
  for (size_t i = 0; ok && i < a.size (); i++)
    for (size_t j = 0; ok && j < b.size (); j++)
      ok = (ai (r, (int)(i * b.size () + j)) == a[i] * b[j]);
  check ("cross gives the outer product A[i]*B[j], shape (|A|,|B|)", ok);
  free (A.data); free (B.data);
  if (r.data) free (r.data);
}
#endif

#ifdef TEST_FORALL_DV_DOT
// for x in A dot y in B returns array_dv of x+y  (zip)
static void
test_forall_dv_dot (void)
{
  printf ("\n=== Group: forall_dv_dot (zip generator) ===\n");
  // `dot` zips: element k is A[k] + B[k], NOT a contraction
  const std::vector<int32_t> a = { 1, 2, 3, -4 }, b = { 10, 20, 30, 5 };
  sisal_array_t A = ewref::mki (a), B = ewref::mki (b);
  sisal_array_t r = func_MAIN (A, B);
  bool ok = (r.rank == 1) && ((size_t)r.size == a.size ());
  for (size_t k = 0; ok && k < a.size (); k++)
    ok = (ai (r, (int)k) == a[k] + b[k]);
  check ("dot zips: element k == A[k] + B[k]", ok);
  free (A.data); free (B.data);
  if (r.data) free (r.data);
}
#endif

#ifdef TEST_FORALL_DV_DOT3
// for x in A dot y in B dot z in C returns array_dv of x+y+z  (3-way zip)
static void
test_forall_dv_dot3 (void)
{
  printf ("\n=== Group: forall_dv_dot3 (three-way zip) ===\n");
  const std::vector<int32_t> a = { 1, 2, -3 }, b = { 10, 20, 30 }, c = { 100, 200, 0 };
  sisal_array_t A = ewref::mki (a), B = ewref::mki (b), C = ewref::mki (c);
  sisal_array_t r = func_MAIN (A, B, C);
  bool ok = (r.rank == 1) && ((size_t)r.size == a.size ());
  for (size_t k = 0; ok && k < a.size (); k++)
    ok = (ai (r, (int)k) == a[k] + b[k] + c[k]);
  check ("three-way dot: element k == A[k] + B[k] + C[k]", ok);
  free (A.data); free (B.data); free (C.data);
  if (r.data) free (r.data);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_XFA_B1_DECLDEF
  test_xfa_b1_decldef ();
#endif
#ifdef TEST_XFA_C3_3AXIS
  test_xfa_c3_3axis ();
#endif
#ifdef TEST_SLICE_STORE
  test_slice_store ();
#endif
#ifdef TEST_MR_TWO_ARRAY
  test_mr_two_array ();
#endif
#ifdef TEST_AA
  test_aa ();
#endif
#ifdef TEST_SUB_2D
  test_sub_2d ();
#endif
#ifdef TEST_SUB_3D
  test_sub_3d ();
#endif
#ifdef TEST_SLICE_DOTDOT
  test_slice_dotdot ();
#endif
#ifdef TEST_TEST_MULTI_ARRAY_IF
  test_test_multi_array_if ();
#endif
#ifdef TEST_FORALL_DV_AT
  test_forall_dv_at ();
#endif
#ifdef TEST_FORALL_DV_CROSS
  test_forall_dv_cross ();
#endif
#ifdef TEST_FORALL_DV_DOT
  test_forall_dv_dot ();
#endif
#ifdef TEST_FORALL_DV_DOT3
  test_forall_dv_dot3 ();
#endif
#if !defined(TEST_XFA_B1_DECLDEF) \
    && !defined(TEST_XFA_C3_3AXIS) \
    && !defined(TEST_SLICE_STORE) \
    && !defined(TEST_MR_TWO_ARRAY) \
    && !defined(TEST_AA) \
    && !defined(TEST_SUB_2D) \
    && !defined(TEST_SUB_3D) \
    && !defined(TEST_SLICE_DOTDOT) \
    && !defined(TEST_TEST_MULTI_ARRAY_IF) \
    && !defined(TEST_FORALL_DV_AT) \
    && !defined(TEST_FORALL_DV_CROSS) \
    && !defined(TEST_FORALL_DV_DOT) \
    && !defined(TEST_FORALL_DV_DOT3)
  g_no_macro = true;
#endif
}
