// dv_part_07.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: LOOP19S_DV, LOOP14_DV, LOOP23S_DV, LOOP18P_DV, LOOP8P_DV, CAP_NESTED_DV, CAP_ARRAY_DV, CAP_FORINIT_DV, MR_FORALL_DV, MR_FORINIT_DV, MR_1D2D_DV, FN_MULTIOUT_DV, IF_MULTIOUT_DV, FNCALL_FORALL_DV
#include "dv_harness.h"

#ifdef TEST_LOOP19S_DV
struct FUNC_MAIN_results
{
  sisal_array_t res_0;
  double res_1;
};
extern "C" struct FUNC_MAIN_results func_MAIN (int32_t REP, int32_t N,
                                               double STB5IN, sisal_array_t SA,
                                               sisal_array_t SB);
#endif
#ifdef TEST_LOOP18P_DV
struct FUNC_MAIN_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct FUNC_MAIN_results func_MAIN (int32_t REP, int32_t N, double S, double T,
                                               sisal_array_t ZAIN, sisal_array_t ZBIN, sisal_array_t ZM,
                                               sisal_array_t ZP, sisal_array_t ZQ, sisal_array_t ZRIN,
                                               sisal_array_t ZUIN, sisal_array_t ZVIN, sisal_array_t ZZIN);
#endif
#ifdef TEST_LOOP8P_DV
struct FUNC_MAIN_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
  sisal_array_t res_2;
};
extern "C" struct FUNC_MAIN_results func_MAIN (int32_t REP, int32_t N,
                                               double A11, double A12, double A13,
                                               double A21, double A22, double A23,
                                               double A31, double A32, double A33,
                                               double SIG,
                                               sisal_array_t U1IN, sisal_array_t U2IN, sisal_array_t U3IN);
#endif
#ifdef TEST_LOOP14_DV
struct FUNC_MAIN_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
  sisal_array_t res_2;
  sisal_array_t res_3;
  sisal_array_t res_4;
  sisal_array_t res_5;
  sisal_array_t res_6;
  sisal_array_t res_7;
  sisal_array_t res_8;
};
extern "C" struct FUNC_MAIN_results
func_MAIN (int32_t REP, int32_t N, double FLX, sisal_array_t DEX,
           sisal_array_t EX, sisal_array_t GRD, sisal_array_t RHIN);
#endif
#ifdef TEST_LOOP23S_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t ZAIN,
                                    sisal_array_t ZB, sisal_array_t ZR,
                                    sisal_array_t ZU, sisal_array_t ZV,
                                    sisal_array_t ZZ);
#endif
/* ---- language-feature regression tests (capture / multi-rank / multi-output) ---- */
#ifdef TEST_CAP_NESTED_DV
extern "C" int32_t func_MAIN();  // free-var capture, nested lets 3 deep
#endif
#ifdef TEST_CAP_ARRAY_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t A);  // grab arrays + multi-bind nested -> forall
#endif
#ifdef TEST_CAP_FORINIT_DV
extern "C" int32_t func_MAIN(sisal_array_t A);  // grab array into for-initial RHS
#endif
#ifdef TEST_MR_FORALL_DV
struct MRFA_results { int32_t res_0; sisal_array_t res_1; };
extern "C" struct MRFA_results func_MAIN();  // forall (scalar, 1-D)
#endif
#ifdef TEST_MR_FORINIT_DV
struct MRFI_results { int32_t res_0; sisal_array_t res_1; };
extern "C" struct MRFI_results func_MAIN();  // for-initial (scalar, 1-D gather)
#endif
#ifdef TEST_MR_1D2D_DV
struct MR12_results { sisal_array_t res_0; sisal_array_t res_1; };
extern "C" struct MR12_results func_MAIN();  // forall (1-D, 2-D)
#endif
#ifdef TEST_FN_MULTIOUT_DV
struct FNMO_results { int32_t res_0; sisal_array_t res_1; };
extern "C" struct FNMO_results func_MAIN();  // function multi-output (scalar, array)
#endif
#ifdef TEST_IF_MULTIOUT_DV
struct IFMO_results { int32_t res_0; int32_t res_1; };
extern "C" struct IFMO_results func_MAIN(int32_t c);  // if-expression multi-output
#endif
#ifdef TEST_FNCALL_FORALL_DV
extern "C" sisal_array_t func_MAIN();  // multi-output fn called inside a forall
#endif

#ifdef TEST_LOOP19S_DV
static void
test_loop19s_dv (void)
{
  printf ("\n=== Group: loop19s_dv (general linear recurrence, vs C "
          "reference) ===\n");
  const int n = 5;
  double STB5in = 1.5;
  double SA[5] = { 0.5, 1.2, -0.8, 2.0, 1.1 };
  double SB[5] = { 1.1, 0.9, 1.3, 0.8, 1.2 };

  // C Reference Implementation
  double B5[5] = { 0 };
  double STB5 = STB5in;
  double STB5_tmp = STB5;
  double B5_tmp[5];
  B5_tmp[0] = SA[0] + STB5_tmp * SB[0];
  STB5_tmp = B5_tmp[0] - STB5_tmp;
  for (int k = 2; k <= n; k++)
    {
      B5_tmp[k - 1] = SA[k - 1] + STB5_tmp * SB[k - 1];
      STB5_tmp = B5_tmp[k - 1] - STB5_tmp;
    }
  for (int i = 0; i < n; i++)
    B5[i] = B5_tmp[i];
  STB5 = STB5_tmp;
  for (int i = 1; i <= n; i++)
    {
      int k = n + 1 - i;
      double B5V = SA[k - 1] + STB5 * SB[k - 1];
      B5[k - 1] = B5V;
      STB5 = B5V - STB5;
    }

  sisal_array_t sa = make_double_arr (SA, 5);
  sisal_array_t sb = make_double_arr (SB, 5);
  struct FUNC_MAIN_results r = func_MAIN (1, n, STB5in, sa, sb);

  bool ok = ((int)r.res_0.size == n);
  for (int k = 0; ok && k < n; k++)
    {
      ok = ok && near_d (ad (r.res_0, k), B5[k]);
    }
  ok = ok && near_d (r.res_1, STB5);
  check ("loop19s_dv general linear recurrence matches C reference", ok);

  if (sa.data)
    free (sa.data);
  if (sb.data)
    free (sb.data);
  if (r.res_0.data)
    free (r.res_0.data);
}
#endif

#ifdef TEST_LOOP14_DV
static void
test_loop14_dv (void)
{
  printf ("\n=== Group: loop14_dv (1-D PIC, vs C reference) ===\n");
  const int n = 5;
  double FLX = 0.25;
  double DEX[1001], EX[1001], GRD[1001], RH[1001];
  for (int i = 0; i < 1001; i++)
    {
      DEX[i] = 0.1 * (i % 5);
      EX[i] = 1.0 + 0.05 * i;
      GRD[i] = 1.0 + 0.9 * i;
      RH[i] = 10.0 + 0.1 * i;
    }

// C Reference Implementation (with 1-based indexing helper)
#define A_14(arr, idx) arr[(idx) - 1]
  double DEX1[5], EX1[5], RX1[5], VX1[5], XI1[5], XX1[5];
  int32_t IR1[5], IX1[5];
  for (int i = 1; i <= n; i++)
    {
      int j = (int)A_14 (GRD, i);
      EX1[i - 1] = A_14 (EX, j);
      DEX1[i - 1] = A_14 (DEX, j);
      XI1[i - 1] = (double)j;
      double vx = A_14 (EX, j) - A_14 (DEX, j) * (double)j;
      VX1[i - 1] = vx;
      int k = (int)(vx + FLX);
      int ir;
      if (k < 0)
        {
          ir = k - (k / 512 * 512) + 256 + abs (256);
        }
      else
        {
          ir = k - (k / 512 * 512) + 256 - abs (256);
        }
      ir = ir + 1;
      IR1[i - 1] = ir;
      IX1[i - 1] = j;
      RX1[i - 1] = vx + FLX - (double)k;
      XX1[i - 1] = vx + FLX - (double)k + (double)ir;
    }
  double RH_ref[1001];
  for (int i = 0; i < 1001; i++)
    RH_ref[i] = RH[i];
  for (int i = 1; i <= n; i++)
    {
      int ir1 = IR1[i - 1];
      double rx1 = RX1[i - 1];
      double val1 = A_14 (RH_ref, ir1) - rx1 + 1.0;
      double val2 = A_14 (RH_ref, ir1 + 1) + rx1;
      A_14 (RH_ref, ir1) = val1;
      A_14 (RH_ref, ir1 + 1) = val2;
    }
#undef A_14

  sisal_array_t dex = make_double_arr (DEX, 1001);
  sisal_array_t ex = make_double_arr (EX, 1001);
  sisal_array_t grd = make_double_arr (GRD, 1001);
  sisal_array_t rh = make_double_arr (RH, 1001);
  struct FUNC_MAIN_results r = func_MAIN (1, n, FLX, dex, ex, grd, rh);

  bool ok = ((int)r.res_0.size == n) && ((int)r.res_1.size == n)
            && ((int)r.res_2.size == n) && ((int)r.res_3.size == n)
            && ((int)r.res_4.size == n) && ((int)r.res_5.size == n)
            && ((int)r.res_6.size == n) && ((int)r.res_7.size == n)
            && ((int)r.res_8.size == 1001);

  for (int k = 0; ok && k < n; k++)
    {
      ok = ok && near_d (ad (r.res_0, k), DEX1[k]);
      ok = ok && near_d (ad (r.res_1, k), EX1[k]);
      ok = ok && (((int32_t *)r.res_2.data)[k] == IR1[k]);
      ok = ok && (((int32_t *)r.res_3.data)[k] == IX1[k]);
      ok = ok && near_d (ad (r.res_4, k), RX1[k]);
      ok = ok && near_d (ad (r.res_5, k), VX1[k]);
      ok = ok && near_d (ad (r.res_6, k), XI1[k]);
      ok = ok && near_d (ad (r.res_7, k), XX1[k]);
    }
  for (int k = 0; ok && k < 1001; k++)
    {
      ok = ok && near_d (ad (r.res_8, k), RH_ref[k]);
    }

  check ("loop14_dv 1-D PIC results match C reference", ok);

  if (dex.data)
    free (dex.data);
  if (ex.data)
    free (ex.data);
  if (grd.data)
    free (grd.data);
  if (rh.data)
    free (rh.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
  if (r.res_2.data)
    free (r.res_2.data);
  if (r.res_3.data)
    free (r.res_3.data);
  if (r.res_4.data)
    free (r.res_4.data);
  if (r.res_5.data)
    free (r.res_5.data);
  if (r.res_6.data)
    free (r.res_6.data);
  if (r.res_7.data)
    free (r.res_7.data);
  if (r.res_8.data)
    free (r.res_8.data);
}
#endif

#ifdef TEST_LOOP23S_DV
static void
test_loop23s_dv (void)
{
  printf ("\n=== Group: loop23s_dv (2-D Implicit Hydrodynamics, vs C "
          "reference) ===\n");
  const int n = 5;
  // Dimensions: 8 rows (0..7), 6 columns (1..6)
  double ZAin[48], ZB[48], ZR[48], ZU[48], ZV[48], ZZ[48];
  for (int r = 0; r < 8; r++)
    {
      for (int c = 1; c <= 6; c++)
        {
          int idx = r * 6 + c - 1;
          ZAin[idx] = 1.0 + 0.1 * r + 0.02 * c;
          ZB[idx] = 0.5 + 0.05 * r;
          ZR[idx] = 0.2 + 0.01 * (r * c);
          ZU[idx] = 0.1 + 0.03 * r;
          ZV[idx] = 0.05 * c;
          ZZ[idx] = 0.01 * (r + c);
        }
    }

// C Reference Implementation
#define M23(arr, r, c) arr[(r) * 6 + (c) - 1]
  double ZAt[48];
  memcpy (ZAt, ZAin, 48 * sizeof (double));

  for (int j = 2; j <= 6; j++)
    {
      // slot 0 is the seed (ZA := old ZAt[j,1]), then k = 2..5
      double ZArc[5];
      double ZA = M23 (ZAt, j, 1);
      ZArc[0] = ZA;
      for (int k = 2; k <= 5; k++)
        {
          double QA = M23 (ZAt, j + 1, k) * M23 (ZR, j, k)
                      + M23 (ZAt, j - 1, k) * M23 (ZB, j, k)
                      + M23 (ZAt, j, k + 1) * M23 (ZU, j, k)
                      + ZA * M23 (ZV, j, k) + M23 (ZZ, j, k);
          ZA = M23 (ZAt, j, k) + 0.175 * (QA - M23 (ZAt, j, k));
          ZArc[k - 1] = ZA;
        }

      // ZAt[j: array_addh(ZArc, ZAt[j, 6])]
      // ZArc now carries the seed, so it is 5 long and the appended row covers
      // columns 1..6: the seed keeps column 1 at its own value and the k=2..5
      // results land at columns 2..5, i.e. at their natural indices.  Before
      // the seed was collected they were shifted down one column.
      double old_col6 = M23 (ZAt, j, 6);
      M23 (ZAt, j, 1) = ZArc[0];
      M23 (ZAt, j, 2) = ZArc[1];
      M23 (ZAt, j, 3) = ZArc[2];
      M23 (ZAt, j, 4) = ZArc[3];
      M23 (ZAt, j, 5) = ZArc[4];
      M23 (ZAt, j, 6) = old_col6;
    }
#undef M23

  sisal_array_t zain = make_double_2d_lb (ZAin, 8, 6, 0, 1);
  sisal_array_t zb = make_double_2d_lb (ZB, 8, 6, 0, 1);
  sisal_array_t zr = make_double_2d_lb (ZR, 8, 6, 0, 1);
  sisal_array_t zu = make_double_2d_lb (ZU, 8, 6, 0, 1);
  sisal_array_t zv = make_double_2d_lb (ZV, 8, 6, 0, 1);
  sisal_array_t zz = make_double_2d_lb (ZZ, 8, 6, 0, 1);

  sisal_array_t r = func_MAIN (1, n, zain, zb, zr, zu, zv, zz);

  bool ok = (r.rank == 2) && ((int)r.dims[0] == 8) && ((int)r.dims[1] == 6)
            && ((int)r.lower_bound[0] == 0) && ((int)r.lower_bound[1] == 1);

  for (int t = 0; ok && t < 48; t++)
    ok = ok && near_d (ad (r, t), ZAt[t]);

  check ("loop23s_dv 2-D implicit hydrodynamics matches C reference", ok);

  if (zain.data)
    free (zain.data);
  if (zb.data)
    free (zb.data);
  if (zr.data)
    free (zr.data);
  if (zu.data)
    free (zu.data);
  if (zv.data)
    free (zv.data);
  if (zz.data)
    free (zz.data);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_LOOP18P_DV
static void
test_loop18p_dv (void)
{
  printf ("\n=== Group: loop18p_dv (2-D Explicit Hydrodynamics, vs C reference) ===\n");
  const int n = 5;
  double S = 0.01;
  double T = 0.05;

  int rows = 8, cols = 6;
  int lb0 = 1, lb1 = 1;

  double ZA[48], ZB[48], ZM[48], ZP[48], ZQ[48], ZR[48], ZU[48], ZV[48], ZZ[48];
  for (int r = 1; r <= 8; r++)
    {
      for (int c = 1; c <= 6; c++)
        {
          int idx = (r - 1) * 6 + (c - 1);
          ZA[idx] = 1.0 + 0.1 * r + 0.02 * c;
          ZB[idx] = 0.5 + 0.05 * r + 0.01 * c;
          ZM[idx] = 2.0 + 0.1 * r;
          ZP[idx] = 0.1 * r * c;
          ZQ[idx] = 0.05 * r + 0.02 * c;
          ZR[idx] = 1.5 + 0.01 * r;
          ZU[idx] = 0.1 + 0.02 * c;
          ZV[idx] = 0.2 + 0.03 * r;
          ZZ[idx] = 3.0 + 0.05 * r * c;
        }
    }

  // C Reference Implementation
  #define M18(arr, r, c) arr[((r) - lb0) * cols + ((c) - lb1)]
  double ZANew[8 * 6], ZBNew[8 * 6];
  for (int j = 1; j <= 8; j++)
    {
      for (int i = 1; i <= 6; i++)
        {
          M18 (ZANew, j, i) = M18 (ZA, j, i);
          M18 (ZBNew, j, i) = M18 (ZB, j, i);
        }
    }

  for (int j = 2; j <= 6; j++)
    {
      double ZArc[6], ZBrc[6];
      for (int i = 2; i <= n; i++)
        {
          double term1_a = M18 (ZP, j + 1, i - 1) + M18 (ZQ, j + 1, i - 1) - M18 (ZP, j, i - 1) - M18 (ZQ, j, i - 1);
          double term2_a = M18 (ZR, j, i) + M18 (ZR, j, i - 1);
          double term3_a = M18 (ZM, j, i - 1) + M18 (ZM, j + 1, i - 1);
          ZArc[i] = term1_a * term2_a / term3_a;

          double term1_b = M18 (ZP, j, i - 1) + M18 (ZQ, j, i - 1) - M18 (ZP, j, i) - M18 (ZQ, j, i);
          double term2_b = M18 (ZR, j, i) + M18 (ZR, j - 1, i);
          double term3_b = M18 (ZM, j, i) + M18 (ZM, j, i - 1);
          ZBrc[i] = term1_b * term2_b / term3_b;
        }
      M18 (ZANew, j, 1) = M18 (ZA, j, 1);
      for (int i = 2; i <= n; i++)
        M18 (ZANew, j, i) = ZArc[i];
      M18 (ZANew, j, n + 1) = M18 (ZA, j, n + 1);

      M18 (ZBNew, j, 1) = M18 (ZB, j, 1);
      for (int i = 2; i <= n; i++)
        M18 (ZBNew, j, i) = ZBrc[i];
      M18 (ZBNew, j, n + 1) = M18 (ZB, j, n + 1);
    }

  double ZRNew[8 * 6], ZZNew[8 * 6];
  memcpy (ZRNew, ZR, 48 * sizeof (double));
  memcpy (ZZNew, ZZ, 48 * sizeof (double));

  for (int j = 2; j <= 6; j++)
    {
      for (int i = 2; i <= n; i++)
        {
          double ZUNew = M18 (ZU, j, i) + S *
                         (M18 (ZANew, j, i)  * (M18 (ZZ, j, i) - M18 (ZZ, j, i + 1)) -
                          M18 (ZANew, j, i - 1) * (M18 (ZZ, j, i) - M18 (ZZ, j, i - 1)) -
                          M18 (ZBNew, j, i)   * (M18 (ZZ, j, i) - M18 (ZZ, j - 1, i)) +
                          M18 (ZBNew, j + 1, i) * (M18 (ZZ, j, i) - M18 (ZZ, j + 1, i)));
          double ZVNew = M18 (ZV, j, i) + S *
                         (M18 (ZANew, j, i)  * (M18 (ZR, j, i) - M18 (ZR, j, i + 1)) -
                          M18 (ZANew, j, i - 1) * (M18 (ZR, j, i) - M18 (ZR, j, i - 1)) -
                          M18 (ZBNew, j, i)   * (M18 (ZR, j, i) - M18 (ZR, j - 1, i)) +
                          M18 (ZBNew, j + 1, i) * (M18 (ZR, j, i) - M18 (ZR, j + 1, i)));
          M18 (ZRNew, j, i) = M18 (ZR, j, i) + T * ZUNew;
          M18 (ZZNew, j, i) = M18 (ZZ, j, i) + T * ZVNew;
        }
    }
  #undef M18

  sisal_array_t zain = make_double_2d_lb (ZA, 8, 6, 1, 1);
  sisal_array_t zbin = make_double_2d_lb (ZB, 8, 6, 1, 1);
  sisal_array_t zm = make_double_2d_lb (ZM, 8, 6, 1, 1);
  sisal_array_t zp = make_double_2d_lb (ZP, 8, 6, 1, 1);
  sisal_array_t zq = make_double_2d_lb (ZQ, 8, 6, 1, 1);
  sisal_array_t zrin = make_double_2d_lb (ZR, 8, 6, 1, 1);
  sisal_array_t zuin = make_double_2d_lb (ZU, 8, 6, 1, 1);
  sisal_array_t zvin = make_double_2d_lb (ZV, 8, 6, 1, 1);
  sisal_array_t zzin = make_double_2d_lb (ZZ, 8, 6, 1, 1);

  struct FUNC_MAIN_results r = func_MAIN (1, n, S, T, zain, zbin, zm, zp, zq, zrin, zuin, zvin, zzin);

  bool ok = (r.res_0.rank == 2) && (r.res_1.rank == 2);
  for (int j = 2; ok && j <= 6; j++)
    {
      for (int i = 2; ok && i <= n; i++)
        {
          int row_offset = j - 2;
          int col_offset = i - 2;
          int flat_idx = row_offset * 4 + col_offset;
          double sisal_zr = ((double*)r.res_0.data)[flat_idx];
          double sisal_zz = ((double*)r.res_1.data)[flat_idx];
          
          double ref_zr = ZRNew[(j-1)*6 + (i-1)];
          double ref_zz = ZZNew[(j-1)*6 + (i-1)];
          ok = ok && near_d (sisal_zr, ref_zr) && near_d (sisal_zz, ref_zz);
        }
    }

  check ("loop18p_dv 2-D explicit hydrodynamics matches C reference", ok);

  if (zain.data) free (zain.data);
  if (zbin.data) free (zbin.data);
  if (zm.data) free (zm.data);
  if (zp.data) free (zp.data);
  if (zq.data) free (zq.data);
  if (zrin.data) free (zrin.data);
  if (zuin.data) free (zuin.data);
  if (zvin.data) free (zvin.data);
  if (zzin.data) free (zzin.data);
  if (r.res_0.data) free (r.res_0.data);
  if (r.res_1.data) free (r.res_1.data);
}
#endif

#ifdef TEST_LOOP8P_DV
static void
test_loop8p_dv (void)
{
  printf ("\n=== Group: loop8p_dv (ADI Integration, vs C reference) ===\n");
  const int n = 5;
  double A11 = 0.1, A12 = 0.2, A13 = 0.3;
  double A21 = 0.15, A22 = 0.25, A23 = 0.35;
  double A31 = 0.05, A32 = 0.15, A33 = 0.25;
  double SIG = 0.01;

  double U1[4 * 1 * 6], U2[4 * 1 * 6], U3[4 * 1 * 6];
  for (int i = 0; i < 24; i++)
    {
      U1[i] = 1.0 + 0.05 * i;
      U2[i] = 2.0 + 0.02 * i;
      U3[i] = 3.0 + 0.01 * i;
    }

  // C Reference Implementation
  double V1_ref[4][6], V2_ref[4][6], V3_ref[4][6];
  for (int kx = 2; kx <= 3; kx++)
    {
      for (int ky = 2; ky <= n; ky++)
        {
          double DU1 = U1[(kx - 1) * 6 + ky] - U1[(kx - 1) * 6 + ky - 2];
          double DU2 = U2[(kx - 1) * 6 + ky] - U2[(kx - 1) * 6 + ky - 2];
          double DU3 = U3[(kx - 1) * 6 + ky] - U3[(kx - 1) * 6 + ky - 2];

          double v1 = U1[(kx - 1) * 6 + ky - 1] + A11 * DU1 + A12 * DU2 + A13 * DU3 +
                      SIG * (U1[kx * 6 + ky - 1] - 2.0 * U1[(kx - 1) * 6 + ky - 1] + U1[(kx - 2) * 6 + ky - 1]);
          double v2 = U2[(kx - 1) * 6 + ky - 1] + A21 * DU1 + A22 * DU2 + A23 * DU3 +
                      SIG * (U2[kx * 6 + ky - 1] - 2.0 * U2[(kx - 1) * 6 + ky - 1] + U2[(kx - 2) * 6 + ky - 1]);
          double v3 = U3[(kx - 1) * 6 + ky - 1] + A31 * DU1 + A32 * DU2 + A33 * DU3 +
                      SIG * (U3[kx * 6 + ky - 1] - 2.0 * U3[(kx - 1) * 6 + ky - 1] + U3[(kx - 2) * 6 + ky - 1]);

          V1_ref[kx][ky] = v1;
          V2_ref[kx][ky] = v2;
          V3_ref[kx][ky] = v3;
        }
    }

  sisal_array_t u1in = make_double_3d_lb (U1, 4, 1, 6, 1, 1, 1);
  sisal_array_t u2in = make_double_3d_lb (U2, 4, 1, 6, 1, 1, 1);
  sisal_array_t u3in = make_double_3d_lb (U3, 4, 1, 6, 1, 1, 1);

  struct FUNC_MAIN_results r = func_MAIN (1, n, A11, A12, A13, A21, A22, A23, A31, A32, A33, SIG, u1in, u2in, u3in);

  bool ok = (r.res_0.rank == 3) && (r.res_1.rank == 3) && (r.res_2.rank == 3);
  for (int kx = 2; ok && kx <= 3; kx++)
    {
      for (int p = 1; ok && p <= 2; p++)
        {
          for (int ky = 1; ok && ky <= 6; ky++)
            {
              int row_offset = kx - 2;
              int flat_idx;
              if (p == 1)
                flat_idx = row_offset * 10 + (ky - 1);
              else
                flat_idx = row_offset * 10 + 6 + (ky - 2);

              double sisal_val1 = ((double*)r.res_0.data)[flat_idx];
              double sisal_val2 = ((double*)r.res_1.data)[flat_idx];
              double sisal_val3 = ((double*)r.res_2.data)[flat_idx];

              double ref_val1, ref_val2, ref_val3;
              if (p == 1)
                {
                  ref_val1 = U1[(kx - 1) * 6 + ky - 1];
                  ref_val2 = U2[(kx - 1) * 6 + ky - 1];
                  ref_val3 = U3[(kx - 1) * 6 + ky - 1];
                }
              else
                {
                  if (ky >= 2 && ky <= n)
                    {
                      ref_val1 = V1_ref[kx][ky];
                      ref_val2 = V2_ref[kx][ky];
                      ref_val3 = V3_ref[kx][ky];
                    }
                  else
                    {
                      continue;
                    }
                }
              ok = ok && near_d (sisal_val1, ref_val1) && near_d (sisal_val2, ref_val2) && near_d (sisal_val3, ref_val3);
            }
        }
    }

  check ("loop8p_dv ADI integration matches C reference", ok);

  if (u1in.data) free (u1in.data);
  if (u2in.data) free (u2in.data);
  if (u3in.data) free (u3in.data);
  if (r.res_0.data) free (r.res_0.data);
  if (r.res_1.data) free (r.res_1.data);
  if (r.res_2.data) free (r.res_2.data);
}
#endif

/* ---- language-feature regression tests ---- */
#ifdef TEST_CAP_NESTED_DV
static void test_cap_nested_dv(void) {
    printf("\n=== Group: cap_nested_dv (free-var capture, nested lets 3 deep) ===\n");
    check("cap_nested_dv a+b+c (a 3 levels deep) == 22", func_MAIN() == 22);
}
#endif
#ifdef TEST_CAP_ARRAY_DV
static void test_cap_array_dv(void) {
    printf("\n=== Group: cap_array_dv (grab arrays + multiple let binds) ===\n");
    int32_t A[3] = { 100, 200, 300 };
    sisal_array_t Aa = make_int_arr(A, 3);
    sisal_array_t r = func_MAIN(Aa);
    bool ok = ((int)r.size == 3);
    for (int k = 0; ok && k < 3; k++) ok = ok && (ai(r, k) == 2 * A[k] + 10);
    check("cap_array_dv B[i]+C[i]+s == 2*A[i]+10", ok);
    if (Aa.data) free(Aa.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_CAP_FORINIT_DV
static void
test_cap_forinit_dv (void)
{
  printf ("\n=== Group: cap_forinit_dv (grab an array into a for-initial) ===\n");
  // acc := sum B[i] for i = 1..3, where B is the captured A
  bool ok = true;
  for (int base : { 100, -5, 0 })
    {
      std::vector<int32_t> a = { base, base * 2, base * 3, 999 };
      int32_t want = a[0] + a[1] + a[2];   // only the first three are summed
      sisal_array_t A = ewref::mki (a);
      ok = ok && (func_MAIN (A) == want);
      free (A.data);
    }
  check ("captured array: acc == A[1]+A[2]+A[3], for three input sets", ok);
}
#endif
#ifdef TEST_MR_FORALL_DV
static void
test_mr_forall_dv (void)
{
  printf ("\n=== Group: mr_forall_dv (value of + array of, same body) ===\n");
  // x := i*10 over i = 1..3; `value of x` keeps the last, `array of x` gathers
  struct MRFA_results r = func_MAIN ();
  bool ok = (r.res_0 == 3 * 10) && ((int)r.res_1.size == 3);
  for (int i = 1; ok && i <= 3; i++) ok = (ai (r.res_1, i - 1) == i * 10);
  check ("value of x == the last x, array of x == every x", ok);
  if (r.res_1.data) free (r.res_1.data);
}
#endif
#ifdef TEST_MR_FORINIT_DV
static void
test_mr_forinit_dv (void)
{
  printf ("\n=== Group: mr_forinit_dv (value of + declared-extent gather) ===\n");
  // acc := old acc + i over i = 1..3 from a seed of 0.  The declared extent is
  // a SIZE DESCRIPTOR, so slot 0 is the seed and the gather is [0,1,3,6].
  int32_t acc = 0;
  std::vector<int32_t> hist = { acc };
  for (int i = 1; i <= 3; i++) { acc += i; hist.push_back (acc); }
  struct MRFI_results r = func_MAIN ();
  bool ok = (r.res_0 == acc) && ((size_t)r.res_1.size == hist.size ());
  for (size_t k = 0; ok && k < hist.size (); k++) ok = (ai (r.res_1, (int)k) == hist[k]);
  check ("value of acc == 6 and the gather is the whole history incl. the seed",
         ok);
  if (r.res_1.data) free (r.res_1.data);
}
#endif
#ifdef TEST_MR_1D2D_DV
static void
test_mr_1d2d_dv (void)
{
  printf ("\n=== Group: mr_1d2d_dv (rank-1 and rank-2 from one forall) ===\n");
  // x := i*10 gathered rank-1; row := fill(1,2,i) gathered rank-2 [3,2]
  struct MR12_results r = func_MAIN ();
  bool ok1 = ((int)r.res_0.size == 3);
  for (int i = 1; ok1 && i <= 3; i++) ok1 = (ai (r.res_0, i - 1) == i * 10);
  bool ok2 = ((int)r.res_1.size == 6);
  for (int i = 1; ok2 && i <= 3; i++)
    for (int j = 0; ok2 && j < 2; j++)
      ok2 = (ai (r.res_1, (i - 1) * 2 + j) == i);
  check ("rank-1 is i*10 and rank-2 rows are fill(1,2,i)", ok1 && ok2);
  if (r.res_0.data) free (r.res_0.data);
  if (r.res_1.data) free (r.res_1.data);
}
#endif
#ifdef TEST_FN_MULTIOUT_DV
static void
test_fn_multiout_dv (void)
{
  printf ("\n=== Group: fn_multiout_dv (scalar + array from one function) ===\n");
  // pair(n) = (n*2, fill(1,n,n))
  const int n = 3;
  struct FNMO_results r = func_MAIN ();
  bool ok = (r.res_0 == n * 2) && ((int)r.res_1.size == n);
  for (int k = 0; ok && k < n; k++) ok = (ai (r.res_1, k) == n);
  check ("pair(3) == (n*2, fill(1,n,n))", ok);
  if (r.res_1.data) free (r.res_1.data);
}
#endif
#ifdef TEST_IF_MULTIOUT_DV
static void
test_if_multiout_dv (void)
{
  printf ("\n=== Group: if_multiout_dv (both arms return a pair) ===\n");
  // if c > 0 then (1,2) else (3,4) -- swept across the boundary at c = 0
  bool ok = true;
  int taken_then = 0, taken_else = 0;
  for (int c = -3; c <= 3; c++)
    {
      struct IFMO_results r = func_MAIN (c);
      const int w0 = c > 0 ? 1 : 3, w1 = c > 0 ? 2 : 4;
      ok = ok && (r.res_0 == w0) && (r.res_1 == w1);
      if (c > 0) taken_then++; else taken_else++;
    }
  check ("both pair arms match, swept over c = -3..3", ok);
  check ("...with both arms taken, including c = 0 on the else side",
         taken_then && taken_else);
}
#endif
#ifdef TEST_FNCALL_FORALL_DV
static void
test_fncall_forall_dv (void)
{
  printf ("\n=== Group: fncall_forall_dv (multi-output fn inside a forall) ===\n");
  // pair(i) = (i*2, i*3); the body gathers a + b = i*5
  sisal_array_t r = func_MAIN ();
  bool ok = ((int)r.size == 3);
  for (int i = 1; ok && i <= 3; i++) ok = (ai (r, i - 1) == i * 2 + i * 3);
  check ("gathered a+b == i*2 + i*3 for i = 1..3", ok);
  if (r.data) free (r.data);
}
#endif

void
run_active_test (void)
{
#ifdef TEST_LOOP19S_DV
  test_loop19s_dv ();
#endif
#ifdef TEST_LOOP14_DV
  test_loop14_dv ();
#endif
#ifdef TEST_LOOP23S_DV
  test_loop23s_dv ();
#endif
#ifdef TEST_LOOP18P_DV
  test_loop18p_dv ();
#endif
#ifdef TEST_LOOP8P_DV
  test_loop8p_dv ();
#endif
#ifdef TEST_CAP_NESTED_DV
  test_cap_nested_dv ();
#endif
#ifdef TEST_CAP_ARRAY_DV
  test_cap_array_dv ();
#endif
#ifdef TEST_CAP_FORINIT_DV
  test_cap_forinit_dv ();
#endif
#ifdef TEST_MR_FORALL_DV
  test_mr_forall_dv ();
#endif
#ifdef TEST_MR_FORINIT_DV
  test_mr_forinit_dv ();
#endif
#ifdef TEST_MR_1D2D_DV
  test_mr_1d2d_dv ();
#endif
#ifdef TEST_FN_MULTIOUT_DV
  test_fn_multiout_dv ();
#endif
#ifdef TEST_IF_MULTIOUT_DV
  test_if_multiout_dv ();
#endif
#ifdef TEST_FNCALL_FORALL_DV
  test_fncall_forall_dv ();
#endif
#if !defined(TEST_LOOP19S_DV) \
    && !defined(TEST_LOOP14_DV) \
    && !defined(TEST_LOOP23S_DV) \
    && !defined(TEST_LOOP18P_DV) \
    && !defined(TEST_LOOP8P_DV) \
    && !defined(TEST_CAP_NESTED_DV) \
    && !defined(TEST_CAP_ARRAY_DV) \
    && !defined(TEST_CAP_FORINIT_DV) \
    && !defined(TEST_MR_FORALL_DV) \
    && !defined(TEST_MR_FORINIT_DV) \
    && !defined(TEST_MR_1D2D_DV) \
    && !defined(TEST_FN_MULTIOUT_DV) \
    && !defined(TEST_IF_MULTIOUT_DV) \
    && !defined(TEST_FNCALL_FORALL_DV)
  g_no_macro = true;
#endif
}
