// dv_part_30.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: TUPLE_KW_TESTS_DV, BUILTIN_SCALAR_DV, CPXCONV_DV, INTERPROC_PROVIDED_E2E, STREAM_SIMPLE_DV, STREAM_LOOP_DV, STREAM_SIEVE_DV, STREAM_INTEGERS_DV, STREAM_SIEVE_V2_DV, STREAM_UPRIME2_DV, FORALL_INTERPROC_E2E, FORALL_2D_INTERPROC_E2E
#include "dv_harness.h"

#ifdef TEST_TUPLE_KW_TESTS_DV
struct FUNC_TUPLE_KW_SWAP_results { int32_t res_0, res_1; };
struct FUNC_TUPLE_KW_TYPED_results { int32_t res_0, res_1; };
extern "C" struct FUNC_TUPLE_KW_SWAP_results func_TUPLE_KW_SWAP(int32_t A, int32_t B);
extern "C" struct FUNC_TUPLE_KW_TYPED_results func_TUPLE_KW_TYPED(int32_t A, int32_t B);
extern "C" int32_t func_TUPLE_KW_CHAIN(int32_t A, int32_t B, int32_t C);
#endif
#ifdef TEST_CPXCONV_DV
struct cc_rec { float REPART, IMPART; };
struct FUNC_COMPLEXING_CT_E_PT_ZTSP_results { sisal_array_t res_0, res_1, res_2, res_3; };
struct FUNC_DECOMPLEXING_P_ZDIFF_U_V_results { sisal_array_t res_0, res_1, res_2, res_3; };
extern "C" struct FUNC_COMPLEXING_CT_E_PT_ZTSP_results func_COMPLEXING_CT_E_PT_ZTSP(int32_t JXMX, sisal_array_t CT, sisal_array_t E, sisal_array_t PT, sisal_array_t ZT);
extern "C" struct FUNC_DECOMPLEXING_P_ZDIFF_U_V_results func_DECOMPLEXING_P_ZDIFF_U_V(int32_t JXMX, int32_t JXXMX, sisal_array_t P, sisal_array_t ZDIFF, sisal_array_t U, sisal_array_t V);
#endif
#ifdef TEST_BUILTIN_SCALAR_DV
extern "C" int32_t func_SCALAR_ABS_INT(int32_t); extern "C" float func_SCALAR_ABS_REAL(float); extern "C" double func_SCALAR_ABS_DOUBLE(double);
extern "C" int32_t func_SCALAR_MAX_INT(int32_t,int32_t); extern "C" float func_SCALAR_MAX_REAL(float,float);
extern "C" int32_t func_SCALAR_MIN_INT(int32_t,int32_t); extern "C" float func_SCALAR_MIN_REAL(float,float);
extern "C" int32_t func_SCALAR_MOD_INT(int32_t,int32_t);
extern "C" int32_t func_SCALAR_FLOOR_REAL(float); extern "C" int64_t func_SCALAR_FLOOR_DOUBLE(double);
extern "C" int32_t func_SCALAR_TRUNC_REAL(float); extern "C" int64_t func_SCALAR_TRUNC_DOUBLE(double);
extern "C" float func_SCALAR_EXP_REAL(float,int32_t); extern "C" double func_SCALAR_EXP_DOUBLE(double,int32_t);
#endif
#ifdef TEST_INTERPROC_PROVIDED_E2E
extern "C" sisal_array_t func_MAIN(int32_t N, int32_t Steps);
#endif
#ifdef TEST_STREAM_SIMPLE_DV
extern "C" sisal_generator<float> func_MAIN();
#endif
#ifdef TEST_STREAM_LOOP_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t N);
#endif
#ifdef TEST_STREAM_SIEVE_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t LIMIT);
#endif
#ifdef TEST_STREAM_INTEGERS_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t LIMIT);
#endif
#ifdef TEST_STREAM_SIEVE_V2_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t LIMIT);
#endif
#ifdef TEST_STREAM_UPRIME2_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t LIMIT);
#endif
#ifdef TEST_TUPLE_KW_TESTS_DV
// tuple() keyword variant: same three tests as tuple_hash via `tuple(x,y)`.
static void test_tuple_kw_tests_dv() {
  printf("\n=== Group: tuple_kw_tests_dv (tuple() keyword destructuring) ===\n");
  int cs[][3] = {{3, 7, 2}, {10, -4, 5}, {0, 0, 0}, {-2, -8, 100}};
  for (auto &c : cs) {
    struct FUNC_TUPLE_KW_SWAP_results s = func_TUPLE_KW_SWAP(c[0], c[1]);
    struct FUNC_TUPLE_KW_TYPED_results t = func_TUPLE_KW_TYPED(c[0], c[1]);
    int u = func_TUPLE_KW_CHAIN(c[0], c[1], c[2]);
    char tag[48]; snprintf(tag, sizeof tag, "a=%d b=%d c=%d", c[0], c[1], c[2]);
    check(tag, s.res_0 == c[1] && s.res_1 == c[0]
            && t.res_0 == c[0] + 1 && t.res_1 == c[1] + 1
            && u == c[0] + c[1] + c[2]);
  }
}
#endif
#ifdef TEST_BUILTIN_SCALAR_DV
// Scalar math intrinsics vs C references: abs, max, min, mod (=%), floor (->-inf),
// trunc (->0), exp (=pow, integer exponent), across int/real/double.
static void test_builtin_scalar_dv() {
  printf("\n=== Group: builtin_scalar_dv (scalar math intrinsics) ===\n");
  check("abs_int",    func_SCALAR_ABS_INT(-5)==5 && func_SCALAR_ABS_INT(7)==7);
  check("abs_real",   std::fabs(func_SCALAR_ABS_REAL(-2.5f)-2.5f)<1e-5);
  check("abs_double", std::fabs(func_SCALAR_ABS_DOUBLE(-3.5)-3.5)<1e-12);
  check("max_int",    func_SCALAR_MAX_INT(3,7)==7 && func_SCALAR_MAX_INT(-2,-9)==-2);
  check("min_int",    func_SCALAR_MIN_INT(3,7)==3 && func_SCALAR_MIN_INT(-2,-9)==-9);
  check("max_real",   std::fabs(func_SCALAR_MAX_REAL(2.5f,1.5f)-2.5f)<1e-5);
  check("min_real",   std::fabs(func_SCALAR_MIN_REAL(2.5f,1.5f)-1.5f)<1e-5);
  check("mod_int",    func_SCALAR_MOD_INT(17,5)==(17%5) && func_SCALAR_MOD_INT(-17,5)==(-17%5) && func_SCALAR_MOD_INT(17,-5)==(17%-5));
  check("floor_real", func_SCALAR_FLOOR_REAL(2.7f)==2 && func_SCALAR_FLOOR_REAL(-2.3f)==-3);
  check("floor_double", func_SCALAR_FLOOR_DOUBLE(3.9)==3 && func_SCALAR_FLOOR_DOUBLE(-3.1)==-4);
  check("trunc_real", func_SCALAR_TRUNC_REAL(2.7f)==2 && func_SCALAR_TRUNC_REAL(-2.7f)==-2);
  check("trunc_double", func_SCALAR_TRUNC_DOUBLE(3.9)==3 && func_SCALAR_TRUNC_DOUBLE(-3.9)==-3);
  check("exp_real",   std::fabs(func_SCALAR_EXP_REAL(2.0f,10)-1024.0f)<1e-2 && std::fabs(func_SCALAR_EXP_REAL(1.5f,3)-3.375f)<1e-4);
  check("exp_double", std::fabs(func_SCALAR_EXP_DOUBLE(3.0,4)-81.0)<1e-9);
}
#endif
#ifdef TEST_CPXCONV_DV
// Complex pack/unpack over array_dv of a flat record CplexReal{Repart,Impart}.
// Complexing: reals -> records (pairs); Decomplexing: records -> reals (interleave).
static sisal_array_t cc_mkreal(const float *v, int n) {
  sisal_array_t a = sisal_array_alloc_empty(1, 6, n); a.lower_bound[0]=1; a.dims[0]=n;
  for (int i = 0; i < n; i++) ((float *)a.data)[i] = v[i]; return a;
}
static sisal_array_t cc_mkrec(const cc_rec *v, int n) {
  sisal_array_t a = sisal_array_alloc_sized(1, 97, n, sizeof(cc_rec)); a.lower_bound[0]=1; a.dims[0]=n;
  for (int i = 0; i < n; i++) ((cc_rec *)a.data)[i] = v[i]; return a;
}
static void test_cpxconv_dv() {
  printf("\n=== Group: cpxconv_dv (array_dv of flat record; complex pack/unpack) ===\n");
  // Complexing jxmx=3: ct=[10..60] -> [{10,20},{30,40},{50,60}]; zt likewise.
  float ct[]={10,20,30,40,50,60}, e[]={1,2,3,4,5,6}, pt[]={-1,-2,-3,-4,-5,-6}, zt[]={7,8,9,10,11,12};
  struct FUNC_COMPLEXING_CT_E_PT_ZTSP_results c =
      func_COMPLEXING_CT_E_PT_ZTSP(3, cc_mkreal(ct,6), cc_mkreal(e,6), cc_mkreal(pt,6), cc_mkreal(zt,6));
  int cok = (int)c.res_0.size == 3;
  for (int i = 0; cok && i < 3; i++) {
    cc_rec r = ((cc_rec *)c.res_0.data)[i];
    cok = std::fabs(r.REPART-ct[2*i])<1e-4 && std::fabs(r.IMPART-ct[2*i+1])<1e-4;
  }
  cc_rec z2 = ((cc_rec *)c.res_3.data)[2];
  cok = cok && std::fabs(z2.REPART-zt[4])<1e-4 && std::fabs(z2.IMPART-zt[5])<1e-4;
  check("Complexing reals->records", cok);
  // Decomplexing jxmx=2,jxxmx=3: p=[{1,2},{3,4}]->[1,2,3,4]; u=[{7,8},{9,10},{11,12}]->[7..12]
  cc_rec p[]={{1,2},{3,4}}, zd[]={{5,6},{7,8}}, u[]={{7,8},{9,10},{11,12}}, v[]={{20,21},{22,23},{24,25}};
  struct FUNC_DECOMPLEXING_P_ZDIFF_U_V_results d =
      func_DECOMPLEXING_P_ZDIFF_U_V(2, 3, cc_mkrec(p,2), cc_mkrec(zd,2), cc_mkrec(u,3), cc_mkrec(v,3));
  float pexp[]={1,2,3,4}, uexp[]={7,8,9,10,11,12};
  int dok = (int)d.res_0.size == 4 && (int)d.res_2.size == 6;
  for (int i = 0; dok && i < 4; i++) dok = std::fabs(((float*)d.res_0.data)[i]-pexp[i])<1e-4;
  for (int i = 0; dok && i < 6; i++) dok = std::fabs(((float*)d.res_2.data)[i]-uexp[i])<1e-4;
  check("Decomplexing records->reals", dok);
}
#endif
#ifdef TEST_INTERPROC_PROVIDED_E2E
// DPS / provided-variant guard: an array-returning helper called every loop
// iteration as the carry, each step's output depending on the WHOLE previous
// array (Step(A)[i] = A[i] + sum(A)).  Value semantics are load-bearing — an
// in-place reuse of the carry buffer that overwrites while reading corrupts
// the compounding recurrence.  Reference = C mirror.
static void test_interproc_provided_e2e() {
  printf("\n=== Group: interproc_provided_e2e (DPS provided-variant recurrence) ===\n");
  auto run = [](int N, int Steps) {
    long V[64]; for (int i = 0; i < N; i++) V[i] = i + 1;
    for (int s = 0; s < Steps; s++) {
      long t = 0; for (int i = 0; i < N; i++) t += V[i];
      for (int i = 0; i < N; i++) V[i] += t;
    }
    sisal_array_t r = func_MAIN(N, Steps);
    int ok = (int)r.size == N;
    for (int i = 0; ok && i < N; i++) ok = ((int32_t*)r.data)[i] == (int32_t)V[i];
    return ok;
  };
  check("N=4 Steps=3 recurrence", run(4, 3));
  check("N=1 Steps=5 (single element)", run(1, 5));
  check("N=6 Steps=0 (seed only, INIT provided path)", run(6, 0));
  check("N=5 Steps=4 (compounded)", run(5, 4));
}
#endif
#ifdef TEST_STREAM_SIMPLE_DV
static void test_stream_simple_dv() {
  printf("\n=== Group: stream_simple_dv ===\n");
  std::vector<float> got;
  for (sisal_generator<float> r = func_MAIN(); !sisal_stream_empty_pred(r);
       r = sisal_stream_rest(r))
    got.push_back(sisal_stream_first<float>(r));
  check("size is 2", got.size() == 2);
  check("element 0 is 1.2", got.size() > 0 && fabs(got[0] - 1.2f) < 1e-5);
  check("element 1 is 3.2", got.size() > 1 && fabs(got[1] - 3.2f) < 1e-5);
}
#endif
#ifdef TEST_STREAM_LOOP_DV
static void test_stream_loop_dv() {
  printf("\n=== Group: stream_loop_dv ===\n");
  std::vector<int32_t> got;
  for (sisal_generator<int32_t> r = func_MAIN(5); !sisal_stream_empty_pred(r);
       r = sisal_stream_rest(r))
    got.push_back(sisal_stream_first<int32_t>(r));
  check("size is 5", (int)got.size() == 5);
  for (int i = 0; i < (int)got.size() && i < 5; i++) {
    char label[64];
    snprintf(label, sizeof(label), "element %d is %d", i, i + 1);
    check(label, got[i] == i + 1);
  }
}
#endif
#ifdef TEST_STREAM_SIEVE_DV
static void test_stream_sieve_dv() {
  printf("\n=== Group: stream_sieve_dv ===\n");
  std::vector<int32_t> got;
  for (sisal_generator<int32_t> r = func_MAIN(20); !sisal_stream_empty_pred(r);
       r = sisal_stream_rest(r))
    got.push_back(sisal_stream_first<int32_t>(r));
  check("size is 8", (int)got.size() == 8);
  int32_t expected[] = {2, 3, 5, 7, 11, 13, 17, 19};
  for (int i = 0; i < (int)got.size() && i < 8; i++) {
    char label[64];
    snprintf(label, sizeof(label), "prime %d is %d", i, expected[i]);
    check(label, got[i] == expected[i]);
  }
}
#endif
#ifdef TEST_STREAM_INTEGERS_DV
static void test_stream_integers_dv() {
  printf("\n=== Group: stream_integers_dv ===\n");
  // Reference model of Sisal `for initial ... returns stream of I`
  // (docs/loop_behavior_comparison.md): seed always gathered (Rule 1), then
  // each body-computed I gathered incl. the final out-of-bounds one (Rule 2).
  auto run = [](int32_t Limit) {
    int32_t ref[256];
    int n = 0;
    int32_t I = 3;
    ref[n++] = I;                 // Rule 1: initial seed
    while (I < Limit - 1) {
      I = I + 2;                  // body: old I + 2
      ref[n++] = I;               // Rule 2: gather body value (incl. out-of-bounds)
    }
    std::vector<int32_t> got;
    for (sisal_generator<int32_t> r = func_MAIN(Limit);
         !sisal_stream_empty_pred(r); r = sisal_stream_rest(r))
      got.push_back(sisal_stream_first<int32_t>(r));
    char label[96];
    snprintf(label, sizeof(label), "Limit=%d size is %d", Limit, n);
    check(label, (int)got.size() == n);
    for (int i = 0; i < n && i < (int)got.size(); i++) {
      snprintf(label, sizeof(label), "Limit=%d element %d is %d", Limit, i,
               ref[i]);
      check(label, got[i] == ref[i]);
    }
  };
  run(30);  // normal: 3 5 7 ... 27 29
  run(15);  // normal: 3 5 7 9 11 13 15
  run(4);   // zero-trip (I:=3, 3<3 false): just the seed [3]
}
#endif
#ifdef TEST_STREAM_SIEVE_V2_DV
static void test_stream_sieve_v2_dv() {
  printf("\n=== Group: stream_sieve_v2_dv ===\n");
  // Reference: the forall generator emits odd candidates 3,5,...,maxcand with
  // maxcand = 3 + 2*((Limit-3)/2) <= Limit, plus the seed 2.  Since every
  // composite candidate has a factor <= sqrt(Limit)=Maxt, the sieve is exact,
  // so the output is precisely the primes in [2, maxcand] (trial division).
  auto run = [](int32_t Limit) {
    int32_t maxcand = 3 + 2 * ((Limit - 3) / 2);
    int32_t ref[512];
    int n = 0;
    for (int32_t p = 2; p <= maxcand; p++) {
      bool prime = true;
      for (int32_t d = 2; (int64_t)d * d <= p; d++)
        if (p % d == 0) { prime = false; break; }
      if (prime) ref[n++] = p;
    }
    std::vector<int32_t> got;
    for (sisal_generator<int32_t> r = func_MAIN(Limit);
         !sisal_stream_empty_pred(r); r = sisal_stream_rest(r))
      got.push_back(sisal_stream_first<int32_t>(r));
    char label[96];
    snprintf(label, sizeof(label), "Limit=%d size is %d", Limit, n);
    check(label, (int)got.size() == n);
    for (int i = 0; i < n && i < (int)got.size(); i++) {
      snprintf(label, sizeof(label), "Limit=%d prime %d is %d", Limit, i,
               ref[i]);
      check(label, got[i] == ref[i]);
    }
  };
  run(10);  // 2 3 5 7
  run(30);  // 2 3 5 7 11 13 17 19 23 29
  run(50);  // 2 3 5 7 ... 43 47
}
#endif
#ifdef TEST_STREAM_UPRIME2_DV
static void test_stream_uprime2_dv() {
  printf("\n=== Group: stream_uprime2_dv ===\n");
  // Infinite-Integers sieve.  Reference = the ACTUAL sieve, not primality:
  // seed 2, then successive odd survivors while T < Limit, plus the first
  // survivor >= Limit (Rule 2 overshoot).  A survivor is an odd q with no
  // factor in [2, Maxt] below itself (Maxt = floor(sqrt(Limit))); that
  // overshoot survivor may be COMPOSITE (e.g. Limit=48 -> ...47 49).
  auto run = [](int32_t Limit) {
    int32_t Maxt = (int32_t)sqrt((double)Limit);
    int32_t ref[512];
    int n = 0;
    ref[n++] = 2;
    for (int32_t q = 3;; q += 2) {
      bool surv = true;
      for (int32_t d = 2; d <= Maxt && d < q; d++)
        if (q % d == 0) { surv = false; break; }
      if (surv) {
        ref[n++] = q;
        if (q >= Limit) break;
      }
    }
    std::vector<int32_t> got;
    for (sisal_generator<int32_t> r = func_MAIN(Limit);
         !sisal_stream_empty_pred(r); r = sisal_stream_rest(r))
      got.push_back(sisal_stream_first<int32_t>(r));
    char label[96];
    snprintf(label, sizeof(label), "Limit=%d size is %d", Limit, n);
    check(label, (int)got.size() == n);
    for (int i = 0; i < n && i < (int)got.size(); i++) {
      snprintf(label, sizeof(label), "Limit=%d element %d is %d", Limit, i,
               ref[i]);
      check(label, got[i] == ref[i]);
    }
  };
  run(20);  // 2 3 5 7 11 13 17 19 23
  run(30);  // 2 3 5 7 11 13 17 19 23 29 31
  run(48);  // 2 3 5 7 ... 47 49  (49 = 7*7 is a COMPOSITE overshoot)
}
#endif

#ifdef TEST_FORALL_INTERPROC_E2E
extern "C" sisal_array_t func_MAIN(int32_t N);
static void test_forall_interproc_e2e() {
  printf("\n=== Group: forall_interproc_e2e (Forall interprocedural DPS provided-variant) ===\n");
  auto run = [](int N) {
    sisal_array_t r = func_MAIN(N);
    int ok = (int)r.size == N;
    for (int i = 0; ok && i < N; i++) {
      double expected = (double)(i + 1) * (double)(N * (N + 1) / 2);
      double actual = ((double*)r.data)[i];
      ok = fabs(actual - expected) < 1e-6;
    }
    return ok;
  };
  check("N=4 forall interprocedural provided", run(4));
  check("N=10 forall interprocedural provided", run(10));
}
#endif

#ifdef TEST_FORALL_2D_INTERPROC_E2E
extern "C" sisal_array_t func_MAIN(int32_t Rows, int32_t Cols);
static void test_forall_2d_interproc_e2e() {
  printf("\n=== Group: forall_2d_interproc_e2e (2D Forall stencil row-builder provided-variant) ===\n");
  auto run = [](int Rows, int Cols) {
    sisal_array_t r = func_MAIN(Rows, Cols);
    int ok = (int)r.size == Rows;
    for (int i = 0; ok && i < Rows; i++) {
      float row_sum = 0.0f;
      for (int j = 1; j <= Cols; j++) row_sum += (float)((i + 1) * 10 + j);
      float actual = ((float*)r.data)[i];
      ok = fabsf(actual - row_sum) < 1e-5f;
    }
    return ok;
  };
  check("Rows=3 Cols=4 forall 2D provided", run(3, 4));
  check("Rows=5 Cols=5 forall 2D provided", run(5, 5));
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_TUPLE_KW_TESTS_DV
  test_tuple_kw_tests_dv ();
#endif
#ifdef TEST_BUILTIN_SCALAR_DV
  test_builtin_scalar_dv ();
#endif
#ifdef TEST_CPXCONV_DV
  test_cpxconv_dv ();
#endif
#ifdef TEST_INTERPROC_PROVIDED_E2E
  test_interproc_provided_e2e ();
#endif
#ifdef TEST_STREAM_SIMPLE_DV
  test_stream_simple_dv ();
#endif
#ifdef TEST_STREAM_LOOP_DV
  test_stream_loop_dv ();
#endif
#ifdef TEST_STREAM_SIEVE_DV
  test_stream_sieve_dv ();
#endif
#ifdef TEST_STREAM_INTEGERS_DV
  test_stream_integers_dv ();
#endif
#ifdef TEST_STREAM_SIEVE_V2_DV
  test_stream_sieve_v2_dv ();
#endif
#ifdef TEST_STREAM_UPRIME2_DV
  test_stream_uprime2_dv ();
#endif
#ifdef TEST_FORALL_INTERPROC_E2E
  test_forall_interproc_e2e ();
#endif
#ifdef TEST_FORALL_2D_INTERPROC_E2E
  test_forall_2d_interproc_e2e ();
#endif
#if !defined(TEST_TUPLE_KW_TESTS_DV) \
    && !defined(TEST_BUILTIN_SCALAR_DV) \
    && !defined(TEST_CPXCONV_DV) \
    && !defined(TEST_INTERPROC_PROVIDED_E2E) \
    && !defined(TEST_STREAM_SIMPLE_DV) \
    && !defined(TEST_STREAM_LOOP_DV) \
    && !defined(TEST_STREAM_SIEVE_DV) \
    && !defined(TEST_STREAM_INTEGERS_DV) \
    && !defined(TEST_STREAM_SIEVE_V2_DV) \
    && !defined(TEST_STREAM_UPRIME2_DV) \
    && !defined(TEST_FORALL_INTERPROC_E2E) \
    && !defined(TEST_FORALL_2D_INTERPROC_E2E)
  g_no_macro = true;
#endif
}
