// dv_part_19.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: ARRAY_SWAP_E2E, QUICKSORT_DV, HEAPSORT_DV, NESTED_CAPTURE_DV, STREAM_GURD_DV, TEST_IF_NESTED_CAPTURE_DV, TEST_IF_LET_CASCADE_DV, TAGCASE_BARE_DV, TAGCASE_BARE_MIXED_DV, TAGCASE_BARE_NESTED_DV, CRYPTO_DV, SQRT_DV, REC_FIELD_DV
#include "dv_harness.h"


#ifdef TEST_ARRAY_SWAP_E2E
struct FUNC_MAIN_results { sisal_array_t res_0, res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(sisal_array_t A, sisal_array_t B);
#endif
#ifdef TEST_QUICKSORT_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t Data);
#endif
#ifdef TEST_HEAPSORT_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t list);
#endif
#ifdef TEST_NESTED_CAPTURE_DV
extern "C" int32_t func_MAIN(int32_t n);
#endif
#ifdef TEST_STREAM_GURD_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t N);
#endif
#ifdef TEST_TEST_IF_NESTED_CAPTURE_DV
extern "C" int32_t func_MAIN(int32_t selector, bool flag, int32_t captured_val);
#endif
#ifdef TEST_TEST_IF_LET_CASCADE_DV
extern "C" int32_t func_MAIN(int32_t selector, bool flag, int32_t v1, int32_t v2, int32_t v3);
#endif
#ifdef TEST_TAGCASE_BARE_DV
struct FUNC_MAIN_results { int32_t res_0, res_1, res_2; bool res_3; };
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t s);
#endif
#ifdef TEST_TAGCASE_BARE_MIXED_DV
struct FUNC_MAIN_results { int32_t res_0, res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t s);
#endif
#ifdef TEST_TAGCASE_BARE_NESTED_DV
extern "C" int32_t func_MAIN(int32_t s);
#endif
#ifdef TEST_CRYPTO_DV
extern "C" bool func_MAIN(sisal_array_t password, sisal_array_t trial);
#endif
#ifdef TEST_SQRT_DV
struct FUNC_MAIN_results { double res_0, res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(double X, double Epsilon);
#endif
#ifdef TEST_REC_FIELD_DV
extern "C" double func_MAIN();
#endif

#ifdef TEST_ARRAY_SWAP_E2E
static void test_array_swap_e2e() {
  printf("\n=== Group: array_swap_e2e (synthetic array swap test) ===\n");
  int32_t dataA[] = {10, 20, 30};
  int32_t dataB[] = {100, 200};
  sisal_array_t A = sisal_array_alloc_empty(1, 6, 3);
  for (int i = 0; i < 3; i++) ((int32_t*)A.data)[i] = dataA[i];

  sisal_array_t B = sisal_array_alloc_empty(1, 6, 2);
  for (int i = 0; i < 2; i++) ((int32_t*)B.data)[i] = dataB[i];

  struct FUNC_MAIN_results res = func_MAIN(A, B);

  int size0 = (int)res.res_0.size;
  int size1 = (int)res.res_1.size;

  int32_t* ptr0 = (int32_t*)res.res_0.data;
  int32_t* ptr1 = (int32_t*)res.res_1.data;

  printf("Array 0 size=%d: [%d, %d]\n", size0, ptr0[0], ptr0[1]);
  printf("Array 1 size=%d: [%d, %d, %d]\n", size1, ptr1[0], ptr1[1], ptr1[2]);

  if (size0 == 2 && size1 == 3 &&
      ptr0[0] == 100 && ptr0[1] == 200 &&
      ptr1[0] == 10 && ptr1[1] == 20 && ptr1[2] == 30) {
    printf("ARRAY_SWAP_E2E: SUCCESS\n");
  } else {
    printf("ARRAY_SWAP_E2E: FAILED\n");
    exit(1);
  }
}
#endif
#if defined(TEST_QUICKSORT_DV) || defined(TEST_HEAPSORT_DV)
// Shared sort driver: build a 1-indexed array_dv, run func_MAIN, compare against
// std::sort of a copy.  quicksort exercises the masked-gather Split (array_dv of
// E when ...) + nested fn + recursion + ||; heapsort exercises nested-fn array
// carry + recursion where the nested params SHADOW captured outer vars of the
// same name (the capture-clobber this arc fixed).
static void run_sort_case(const char *tag, const int32_t *v, int n) {
  sisal_array_t a = sisal_array_alloc_empty(1, 6, (uint64_t)n);
  a.lower_bound[0] = 1; a.dims[0] = n;          // Sisal 1-indexed
  for (int i = 0; i < n; i++) ((int32_t*)a.data)[i] = v[i];
  int32_t ref[64];
  for (int i = 0; i < n; i++) ref[i] = v[i];
  std::sort(ref, ref + n);
  sisal_array_t r = func_MAIN(a);
  int ok = (int)r.size == n;
  for (int i = 0; ok && i < n; i++) ok = ((int32_t*)r.data)[i] == ref[i];
  check(tag, ok);
}
#endif
#ifdef TEST_QUICKSORT_DV
static void test_quicksort_dv() {
  printf("\n=== Group: quicksort_dv (masked-gather Split + recursion) ===\n");
  run_sort_case("quicksort 40 mixed +/- dups", sort_big40, 40);
  int32_t a[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
  run_sort_case("quicksort 9 shuffled", a, 9);
  int32_t b[] = {1};                    run_sort_case("quicksort singleton", b, 1);
  int32_t c[] = {2, 1};                 run_sort_case("quicksort pair", c, 2);
  int32_t d[] = {4, 4, 1, 4, 2, 4};     run_sort_case("quicksort duplicates", d, 6);
  int32_t e[] = {1, 2, 3, 4, 5};        run_sort_case("quicksort already sorted", e, 5);
  int32_t f[] = {5, 4, 3, 2, 1};        run_sort_case("quicksort reversed", f, 5);
}
#endif
#ifdef TEST_HEAPSORT_DV
static void test_heapsort_dv() {
  printf("\n=== Group: heapsort_dv (nested-fn capture/param shadow) ===\n");
  run_sort_case("heapsort 40 mixed +/- dups", sort_big40, 40);
  int32_t a[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
  run_sort_case("heapsort 9 shuffled", a, 9);
  int32_t d[] = {4, 4, 1, 4, 2, 4};     run_sort_case("heapsort duplicates", d, 6);
  int32_t e[] = {1, 2, 3, 4, 5, 6, 7};  run_sort_case("heapsort already sorted", e, 7);
  int32_t f[] = {7, 6, 5, 4, 3, 2, 1};  run_sort_case("heapsort reversed", f, 7);
}
#endif
#ifdef TEST_NESTED_CAPTURE_DV
// Nested functions capturing OUTER-SCOPE values (not their own args):
//   AddBase captures Main's n (parent); Inner captures Outer's base AND Main's n
//   (parent + grandparent).  Captured values are results computed earlier in the
//   let.  Regression for the capture/param-shadow fix: params must NOT be
//   clobbered, yet genuine captures (trailing boundary ports) must still flow.
static int nested_capture_ref(int n) {
  int seed = n * n;
  int a = seed + n;                              // AddBase(seed)
  int b = (seed + seed + n) + (1 + seed + n);    // Outer(seed) = Inner(seed)+Inner(1)
  return a + b;
}
static void test_nested_capture_dv() {
  printf("\n=== Group: nested_capture_dv (nested-fn outer-scope capture) ===\n");
  for (int n : {3, 5, 0, -4, 10, 100}) {
    char tag[64]; snprintf(tag, sizeof tag, "nested_capture n=%d", n);
    check(tag, func_MAIN(n) == nested_capture_ref(n));
  }
}
#endif
#ifdef TEST_STREAM_GURD_DV
// Stream sieve: StartList = 2..N*N; Filter drops multiples of each prime P<=N
// then recurses, prepending P; once P>N the tail is passed through unfiltered.
// Result = all primes in [2, N*N].  Exercises stream `||` catenation
// (sisal_stream_concat) -- the op that used to leak to array addh and hang.
static void test_stream_gurd_dv() {
  printf("\n=== Group: stream_gurd_dv (stream sieve, stream `||`) ===\n");
  auto run = [](int N) {
    int hi = N * N;
    std::vector<int32_t> ref;
    std::vector<char> sieve(hi + 1, 1);
    for (int p = 2; p <= hi; p++)
      if (sieve[p]) { ref.push_back(p); for (int m = 2*p; m <= hi; m += p) sieve[m] = 0; }
    std::vector<int32_t> got;
    for (sisal_generator<int32_t> r = func_MAIN(N); !sisal_stream_empty_pred(r);
         r = sisal_stream_rest(r))
      got.push_back(sisal_stream_first<int32_t>(r));
    int ok = got.size() == ref.size();
    for (size_t i = 0; ok && i < ref.size(); i++) ok = got[i] == ref[i];
    char tag[64]; snprintf(tag, sizeof tag, "primes in [2,%d] (N=%d)", hi, N);
    check(tag, ok);
  };
  run(2); run(3); run(5); run(10); run(13);
}
#endif
#ifdef TEST_TEST_IF_NESTED_CAPTURE_DV
// Nested if returning a captured outer scalar; pure scalar control flow.
static int if_nested_capture_ref(int sel, bool flag, int cap) {
  if (sel == 1) return flag ? cap : 42;
  return 0;
}
static void test_test_if_nested_capture_dv() {
  printf("\n=== Group: test_if_nested_capture_dv (nested if, captured scalar) ===\n");
  int sels[] = {1, 1, 2, 0}; bool fls[] = {true, false, true, false};
  int caps[] = {77, 77, 5, 9};
  for (int i = 0; i < 4; i++) {
    char tag[64]; snprintf(tag, sizeof tag, "sel=%d flag=%d cap=%d", sels[i], fls[i], caps[i]);
    check(tag, func_MAIN(sels[i], fls[i], caps[i]) == if_nested_capture_ref(sels[i], fls[i], caps[i]));
  }
}
#endif
#ifdef TEST_TEST_IF_LET_CASCADE_DV
// let-bound nested-if result feeding a second if; pure scalar.
static int if_let_cascade_ref(int sel, bool flag, int v1, int v2, int v3) {
  int fr = (sel == 1) ? (flag ? v1 : v2) : v3;
  return (fr > 50) ? fr * 2 : fr + 100;
}
static void test_test_if_let_cascade_dv() {
  printf("\n=== Group: test_if_let_cascade_dv (let-bound if cascade) ===\n");
  struct { int sel; bool fl; int v1, v2, v3; } cs[] = {
    {1, true, 60, 5, 9}, {1, false, 60, 5, 9}, {2, true, 60, 5, 9},
    {1, true, 10, 5, 9}, {3, false, 99, 1, 51},
  };
  for (auto &c : cs) {
    char tag[80]; snprintf(tag, sizeof tag, "sel=%d fl=%d v=%d,%d,%d", c.sel, c.fl, c.v1, c.v2, c.v3);
    check(tag, func_MAIN(c.sel, c.fl, c.v1, c.v2, c.v3)
              == if_let_cascade_ref(c.sel, c.fl, c.v1, c.v2, c.v3));
  }
}
#endif
#ifdef TEST_TAGCASE_BARE_DV
// Bare tagcase (no payload binding) over union[A:int;B:real;C:bool].
// Mk(s) = tag A iff s==1, else tag B (A's payload is always 42).
static void test_tagcase_bare_dv() {
  printf("\n=== Group: tagcase_bare_dv (bare tagcase dispatch) ===\n");
  for (int s : {1, 2, 0, 5}) {
    struct FUNC_MAIN_results r = func_MAIN(s);
    int e0 = (s == 1) ? 10 : 20;      // tagcase u = Mk(s)
    int e1 = (s == 0) ? 100 : 200;    // tagcase Mk(s+1)  (A iff s+1==1)
    int e2 = (s == 1) ? 1 : 2;        // DispatchParam(u)
    bool e3 = (s == 1);               // is A(u)
    char tag[48]; snprintf(tag, sizeof tag, "s=%d", s);
    check(tag, r.res_0 == e0 && r.res_1 == e1 && r.res_2 == e2 && r.res_3 == e3);
  }
}
#endif
#ifdef TEST_TAGCASE_BARE_MIXED_DV
// Bare/bound tagcase nesting; classification is per-instance.  Both helpers
// return 2 when s==1, else 3.
static void test_tagcase_bare_mixed_dv() {
  printf("\n=== Group: tagcase_bare_mixed_dv (mixed bare/bound nesting) ===\n");
  for (int s : {1, 2, 0, 3}) {
    struct FUNC_MAIN_results r = func_MAIN(s);
    int e = (s == 1) ? 2 : 3;
    char tag[48]; snprintf(tag, sizeof tag, "s=%d", s);
    check(tag, r.res_0 == e && r.res_1 == e);
  }
}
#endif
#ifdef TEST_TAGCASE_BARE_NESTED_DV
// Nested bare tagcases over an array_dv of unions.  u[1]=A(s), u[2]=B, so the
// outer A arm -> inner B arm -> 2, for every s.
static void test_tagcase_bare_nested_dv() {
  printf("\n=== Group: tagcase_bare_nested_dv (nested bare tagcase, array_dv of union) ===\n");
  for (int s : {1, 7, 0, -3}) {
    char tag[48]; snprintf(tag, sizeof tag, "s=%d", s);
    check(tag, func_MAIN(s) == 2);
  }
}
#endif
#ifdef TEST_CRYPTO_DV
// crypto string-equality over array_dv[character]: sizes equal AND every char
// equal (dot-zip + boolean `product a=b`).  Reference = strcmp.
static sisal_array_t crypto_mkstr(const char *s) {
  int n = (int)strlen(s);
  sisal_array_t a = sisal_array_alloc_empty(1, 3, (uint64_t)n);  // type_id 3 = char
  a.lower_bound[0] = 1; a.dims[0] = n;
  for (int i = 0; i < n; i++) ((char *)a.data)[i] = s[i];
  return a;
}
static void test_crypto_dv() {
  printf("\n=== Group: crypto_dv (array_dv[char] equality: dot-zip + product) ===\n");
  const char *pairs[][2] = {
    {"hello", "hello"}, {"hello", "world"}, {"abc", "ab"},
    {"a", "a"}, {"", ""}, {"abc", "abd"}, {"password", "password"},
  };
  for (auto &pr : pairs) {
    bool got = func_MAIN(crypto_mkstr(pr[0]), crypto_mkstr(pr[1]));
    bool exp = strcmp(pr[0], pr[1]) == 0;
    char tag[80]; snprintf(tag, sizeof tag, "crypto(\"%s\",\"%s\")", pr[0], pr[1]);
    check(tag, got == exp);
  }
}
#endif
#ifdef TEST_SQRT_DV
// Newton-iteration sqrt (for-initial convergence) + external `global sqrt`
// (libm).  Both must match std::sqrt: Newton to its epsilon, libm exactly.
static void test_sqrt_dv() {
  printf("\n=== Group: sqrt_dv (Newton for-initial + external sqrt) ===\n");
  for (double x : {2.0, 4.0, 100.0, 0.25, 1000.0, 1.0}) {
    struct FUNC_MAIN_results r = func_MAIN(x, 1e-9);
    double e = std::sqrt(x);
    char tag[64]; snprintf(tag, sizeof tag, "sqrt(%g)", x);
    check(tag, std::fabs(r.res_0 - e) < 1e-3 && std::fabs(r.res_1 - e) < 1e-9);
  }
}
#endif
#ifdef TEST_REC_FIELD_DV
// Record holding an array_dv field: r.v[i] must rank-reduce to a scalar.
static void test_rec_field_dv() {
  printf("\n=== Group: rec_field_dv (record-held array_dv, field subscript) ===\n");
  check("r.v[1]+r.v[2]+r.v[3]+r.w == 65", std::fabs(func_MAIN() - 65.0) < 1e-12);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_ARRAY_SWAP_E2E
  test_array_swap_e2e ();
#endif
#ifdef TEST_QUICKSORT_DV
  test_quicksort_dv ();
#endif
#ifdef TEST_HEAPSORT_DV
  test_heapsort_dv ();
#endif
#ifdef TEST_NESTED_CAPTURE_DV
  test_nested_capture_dv ();
#endif
#ifdef TEST_STREAM_GURD_DV
  test_stream_gurd_dv ();
#endif
#ifdef TEST_TEST_IF_NESTED_CAPTURE_DV
  test_test_if_nested_capture_dv ();
#endif
#ifdef TEST_TEST_IF_LET_CASCADE_DV
  test_test_if_let_cascade_dv ();
#endif
#ifdef TEST_TAGCASE_BARE_DV
  test_tagcase_bare_dv ();
#endif
#ifdef TEST_TAGCASE_BARE_MIXED_DV
  test_tagcase_bare_mixed_dv ();
#endif
#ifdef TEST_TAGCASE_BARE_NESTED_DV
  test_tagcase_bare_nested_dv ();
#endif
#ifdef TEST_CRYPTO_DV
  test_crypto_dv ();
#endif
#ifdef TEST_SQRT_DV
  test_sqrt_dv ();
#endif
#ifdef TEST_REC_FIELD_DV
  test_rec_field_dv ();
#endif
#if !defined(TEST_ARRAY_SWAP_E2E) \
    && !defined(TEST_QUICKSORT_DV) \
    && !defined(TEST_HEAPSORT_DV) \
    && !defined(TEST_NESTED_CAPTURE_DV) \
    && !defined(TEST_STREAM_GURD_DV) \
    && !defined(TEST_TEST_IF_NESTED_CAPTURE_DV) \
    && !defined(TEST_TEST_IF_LET_CASCADE_DV) \
    && !defined(TEST_TAGCASE_BARE_DV) \
    && !defined(TEST_TAGCASE_BARE_MIXED_DV) \
    && !defined(TEST_TAGCASE_BARE_NESTED_DV) \
    && !defined(TEST_CRYPTO_DV) \
    && !defined(TEST_SQRT_DV) \
    && !defined(TEST_REC_FIELD_DV)
  g_no_macro = true;
#endif
}
