// dv_part_17.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: PASSFREQ_DV, MDFFTFREQ_DV, MDFFTGRID_DV, NEWSIEVE_DV, CK_YB_DV, GAUSSJNEW_DV, TST_LOOPAT_DV, QUADRATURE_DV, OUTS_DV, QUADTREE_DV, TAG_SCOPE_DV, NOISEDUMP_DV, ZBUFFER_DV, HAM_DV, QUAD_DV, NEWGAUSS_DV, NEWGAUSSJ_DV, MMULT2_DV, CYK_DV, CROSSOVERS_DV, NANU_DV
#include "dv_harness.h"

#ifdef TEST_PASSFREQ_DV
extern "C" sisal_array_t func_MAIN(int32_t inc1, int32_t inc2, int32_t n,
                                   int32_t ifac, int32_t la, sisal_array_t a,
                                   sisal_array_t c, sisal_array_t trigs);
#endif
#ifdef TEST_MDFFTFREQ_DV
extern "C" sisal_array_t func_MAIN(int32_t nlev, int32_t nwave, int32_t nfax,
                                   int32_t n, sisal_array_t ifax,
                                   sisal_array_t trigs, sisal_array_t grid);
#endif
#ifdef TEST_GAUSSJNEW_DV
extern "C" sisal_array_t func_MAIN(int32_t n, sisal_array_t Ain, sisal_array_t Bin);
#endif
#ifdef TEST_TST_LOOPAT_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t Y);
#endif
#ifdef TEST_QUADRATURE_DV
extern "C" float func_MAIN(float Low, float High);
#endif
#ifdef TEST_OUTS_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t DATA);
#endif
#ifdef TEST_NOISEDUMP_DV
extern "C" sisal_generator<char> func_MAIN(sisal_array_t M);
#endif
#ifdef TEST_HAM_DV
extern "C" sisal_generator<int32_t> func_MAIN(int32_t J);
#endif
#ifdef TEST_NEWGAUSS_DV
struct FUNC_MAIN_sag_results {
  sisal_array_t res_0; sisal_array_t res_1; sisal_array_t res_2;
};
extern "C" struct FUNC_MAIN_sag_results func_MAIN(int32_t n);
#endif
#ifdef TEST_QUAD_DV
struct FUNC_MAIN_quad_results {
  sisal_array_t res_0; sisal_array_t res_1; sisal_array_t res_2; int32_t res_3;
};
extern "C" struct FUNC_MAIN_quad_results func_MAIN(sisal_array_t A,
                                                   sisal_array_t B);
#endif
#ifdef TEST_ZBUFFER_DV
struct zb_PtRec   { float xp, yp, zp; };
struct zb_PlnEqn  { float a, b, c, d; };
struct zb_TriRec  { int32_t vhi, vmid, vlo, mid_scan_line, last_scan_line;
                    float dxdy_lh, dxdy_lm, dxdy_mh; zb_PlnEqn pln; };
struct zb_DepthRec { int32_t tri; float depth; };
extern "C" sisal_array_t func_MAIN(int32_t x_pixels, int32_t y_pixels,
                                   sisal_array_t pts, sisal_array_t tris);
#endif
#ifdef TEST_TAG_SCOPE_DV
struct FUNC_MAIN_ts_results {
  float res_0; float res_1; int32_t res_2; float res_3; int32_t res_4;
  bool res_5; bool res_6;
};
extern "C" struct FUNC_MAIN_ts_results func_MAIN(int32_t n);
#endif
#ifdef TEST_QUADTREE_DV
struct FUNC_MAIN_qt_results { int32_t res_0; int32_t res_1; int32_t res_2; };
extern "C" struct FUNC_MAIN_qt_results func_MAIN(sisal_array_t A);
#endif
#ifdef TEST_MMULT2_DV
struct FUNC_MAIN_mm_results { sisal_array_t res_0; sisal_array_t res_1; sisal_array_t res_2; };
extern "C" struct FUNC_MAIN_mm_results func_MAIN(int32_t N);
#endif
#ifdef TEST_CYK_DV
struct FUNC_MAIN_cyk_results { bool res_0; sisal_array_t res_1; };
extern "C" struct FUNC_MAIN_cyk_results func_MAIN(sisal_array_t X);
#endif
#ifdef TEST_NANU_DV
struct FUNC_MAIN_nanu_results { sisal_array_t B, C, D, G; int32_t ncnt; };
extern "C" struct FUNC_MAIN_nanu_results func_MAIN(int32_t n, int32_t s);
#endif
#ifdef TEST_CROSSOVERS_DV
struct FUNC_MAIN_xo_results { sisal_array_t all, chk, rem; };
extern "C" struct FUNC_MAIN_xo_results func_MAIN(sisal_array_t Coords,
                                                 sisal_array_t Itin,
                                                 sisal_array_t Ex);
#endif
#ifdef TEST_NEWGAUSSJ_DV
struct FUNC_MAIN_ngj_results { sisal_array_t res_0; sisal_array_t res_1; };
extern "C" struct FUNC_MAIN_ngj_results func_MAIN(int32_t N, sisal_array_t A,
                                                  sisal_array_t B);
#endif
#ifdef TEST_CK_YB_DV
struct FUNC_MAIN_ckyb_results {
  int32_t res_0; int32_t res_1; int32_t res_2; int32_t res_3; sisal_array_t res_4;
};
extern "C" struct FUNC_MAIN_ckyb_results func_MAIN(sisal_array_t row_lens);
#endif
#ifdef TEST_NEWSIEVE_DV
struct FUNC_MAIN_newsieve_results { sisal_array_t res_0; sisal_array_t res_1; };
extern "C" struct FUNC_MAIN_newsieve_results func_MAIN(int32_t n);
#endif
#ifdef TEST_MDFFTGRID_DV
extern "C" sisal_array_t func_MAIN(int32_t nlev, int32_t nwave, int32_t nfax,
                                   int32_t n, sisal_array_t ifax,
                                   sisal_array_t trigs, sisal_array_t gridii);
#endif
#if defined(TEST_IFM_2ETC_DV) || defined(TEST_IFM_3_DV)                \
    || defined(TEST_IFM_4_DV) || defined(TEST_PASSFREQ_DV)             \
    || defined(TEST_IFG_2ETC_DV) || defined(TEST_IFG_3_DV)             \
    || defined(TEST_IFG_4_DV) || defined(TEST_PASSGRID_DV)
// Reference implementations of the three FFT butterfly passes, shared by
// their own groups and by passfreq_dv, which dispatches to them.  Each was
// validated against OSC 13.0.3 before use; see the individual groups.
namespace ifm2ref {
static std::vector<float>
kernel (int m, int la, int iink, int jink, int jump, int inc1, int inc2,
        const std::vector<float> &a, const std::vector<float> &ci,
        const std::vector<float> &trigs)
{
  std::vector<float> c = ci;
  int k = 0, ia = 1, ja = 1;
  while (k <= m / 2)
    {
      int k_old = k;
      k = k_old + la;
      int ia1 = ia, ja1 = ja;
      std::vector<float> c1 = c;
      if (k_old == 0)
        {
          for (int l = 1; l <= la; l++)
            {
              int ia1o = ia1, ja1o = ja1;
              ia1 = ia1o + inc1; ja1 = ja1o + inc2;
              int ib = ia1o + iink, jb = ja1o + jink;
              c1[ja1o] = a[ia1o] + a[ib];
              c1[jb] = a[ia1o] - a[ib];
            }
          ia = ia1 + jump; ja = ja1; c = c1;
        }
      else if (2 * k_old < m)
        {
          int kb = k_old * 2, lower = jink + 2, lupper = iink * 2 + jink - 2;
          for (int l = lower; l <= lupper; l += 4)
            {
              int ia1o = ia1, ja1o = ja1, lo = l;
              ia1 = ia1o + inc1; ja1 = ja1o + inc2;
              int ib = ia1o + iink, jbxx = lo - ja1o;
              float tempr = a[ib] * trigs[kb + 1] - a[ib + 1] * trigs[kb + 2];
              float tempi = a[ib] * trigs[kb + 2] + a[ib + 1] * trigs[kb + 1];
              c1[ja1o] = a[ia1o] + tempr;
              c1[jbxx] = a[ia1o] - tempr;
              c1[ja1o + 1] = a[ia1o + 1] + tempi;
              c1[jbxx + 1] = tempi - a[ia1o + 1];
            }
          ia = ia1 + jump; ja = ja1; c = c1;
        }
      else
        {
          for (int l = 1; l <= la; l++)
            {
              int ia1o = ia1, ja1o = ja1;
              ia1 = ia1o + inc1; ja1 = ja1o + inc2;
              int ib = ia1o + iink;
              c1[ja1o] = a[ia1o];
              c1[ja1o + 1] = -a[ib];
            }
          // No + jump here, unlike the other two arms.  It makes no
          // observable difference: arm 3 is chosen only when k_old == m/2
          // exactly, after which k = m/2 + la > m/2 and the loop exits, so ia
          // and ja written here are DEAD.  Perturbing them cannot be detected
          // by any test -- a fact about the algorithm, not a gap in this one.
          ia = ia1; ja = ja1; c = c1;
        }
    }
  return c;
}
}
namespace ifm3ref {
static std::vector<float>
kernel (int m, int la, int iink, int jink, int jump, int inc1, int inc2,
        const std::vector<float> &a, const std::vector<float> &ci,
        const std::vector<float> &trigs)
{
  const float sin60 = 0.866025403784437f;
  std::vector<float> c = ci;
  int k = 0, ia = 1, ja = 1;
  while (k <= m / 2)
    {
      int k_old = k;
      k = k_old + la;
      int ia1 = ia, ja1 = ja;
      std::vector<float> c1 = c;
      if (k_old == 0)
        {
          for (int l = 1; l <= la; l++)
            {
              int ia1o = ia1, ja1o = ja1;
              ia1 = ia1o + inc1; ja1 = ja1o + inc2;
              int ib = ia1o + iink, ic = ib + iink, jb = ja1o + jink;
              float a1 = a[ib] + a[ic];
              float a2 = a[ia1o] - 0.5f * a1;
              float a3 = sin60 * (a[ic] - a[ib]);
              c1[ja1o] = a[ia1o] + a1; c1[jb] = a2; c1[jb + 1] = a3;
            }
          ia = ia1 + jump; ja = ja1; c = c1;
        }
      else if (2 * k_old < m)
        {
          int kb = k_old * 2, kc = kb * 2, lower = jink + 2,
              lupper = iink * 2 + jink - 2;
          for (int l = lower; l <= lupper; l += 4)
            {
              int ia1o = ia1, ja1o = ja1, lo = l;
              ia1 = ia1o + inc1; ja1 = ja1o + inc2;
              int ib = ia1o + iink, ic = ib + iink, jb = ja1o + jink,
                  jcxx = lo - ja1o;
              float tempr1 = a[ib] * trigs[kb + 1] - a[ib + 1] * trigs[kb + 2];
              float tempi1 = a[ib] * trigs[kb + 2] + a[ib + 1] * trigs[kb + 1];
              float tempr2 = a[ic] * trigs[kc + 1] - a[ic + 1] * trigs[kc + 2];
              float tempi2 = a[ic] * trigs[kc + 2] + a[ic + 1] * trigs[kc + 1];
              float a1 = tempr1 + tempr2, b1 = tempi1 + tempi2;
              float a2 = a[ia1o] - 0.5f * a1, b2 = a[ia1o + 1] - 0.5f * b1;
              float a3 = sin60 * (tempr2 - tempr1),
                    b3 = sin60 * (tempi2 - tempi1);
              c1[ja1o] = a[ia1o] + a1;   c1[jb] = a2 - b3;  c1[jcxx] = a2 + b3;
              c1[ja1o + 1] = a[ia1o + 1] + b1;
              c1[jb + 1] = b2 + a3;      c1[jcxx + 1] = a3 - b2;
            }
          ia = ia1 + jump; ja = ja1; c = c1;
        }
      else
        {
          for (int l = 1; l <= la; l++)
            {
              int ia1o = ia1, ja1o = ja1;
              ia1 = ia1o + inc1; ja1 = ja1o + inc2;
              int ib = ia1o + iink, ic = ib + iink, jb = ja1o + jink;
              float a1 = a[ib] - a[ic];
              c1[ja1o] = a[ia1o] + 0.5f * a1;
              c1[jb] = a[ia1o] - a1;
              c1[ja1o + 1] = -sin60 * (a[ib] + a[ic]);
            }
          ia = ia1; ja = ja1; c = c1;   // ia/ja dead here, as in the radix-2 pass
        }
    }
  return c;
}
}
namespace ifm4ref {
static std::vector<float>
kernel (int m, int la, int iink, int jink, int jump, int inc1, int inc2,
        const std::vector<float> &a, const std::vector<float> &ci,
        const std::vector<float> &trigs)
{
  const float sin45 = 0.7071067812f;
  std::vector<float> c = ci;
  int k = 0, ia = 1, ja = 1;
  while (k <= m/2) {
    int k_old = k;  k = k_old + la;
    int ia1 = ia, ja1 = ja;
    std::vector<float> c1 = c;
    if (k_old == 0) {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, ic = ib + iink, id = ic + iink;
        int jb = ja1o + jink, jc = jb + jink;
        float a1 = a[ia1o] + a[ic], a2 = a[ib] + a[id];
        float a3 = a[ia1o] - a[ic], a4 = a[id] - a[ib];
        c1[ja1o] = a1 + a2; c1[jb] = a3; c1[jc] = a1 - a2; c1[jb+1] = a4;
      }
      ia = ia1 + jump; ja = ja1; c = c1;
    } else if (2*k_old < m) {
      int lower = jink + 2, lupper = iink*2 + jink - 2;
      for (int l = lower; l <= lupper; l += 4) {
        int ia1o = ia1, ja1o = ja1, lo = l;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, ic = ib + iink, id = ic + iink;
        int jb = ja1o + jink, jdxx = lo - ja1o, jcxx = jdxx + jink;
        int kb = k_old*2, kc = kb*2, kd = kc + kb;
        float tempr1 = a[ib]*trigs[kb+1] - a[ib+1]*trigs[kb+2];
        float tempi1 = a[ib]*trigs[kb+2] + a[ib+1]*trigs[kb+1];
        float tempr2 = a[ic]*trigs[kc+1] - a[ic+1]*trigs[kc+2];
        float tempi2 = a[ic]*trigs[kc+2] + a[ic+1]*trigs[kc+1];
        float tempr3 = a[id]*trigs[kd+1] - a[id+1]*trigs[kd+2];
        float tempi3 = a[id]*trigs[kd+2] + a[id+1]*trigs[kd+1];
        float a0 = a[ia1o] + tempr2, a1 = tempr1 + tempr3;
        float a2 = a[ia1o] - tempr2, a3 = tempr1 - tempr3;
        float b0 = a[ia1o+1] + tempi2, b1 = tempi1 + tempi3;
        float b2 = a[ia1o+1] - tempi2, b3 = tempi1 - tempi3;
        c1[ja1o]   = a0 + a1; c1[jb]     = a2 + b3;
        c1[jcxx]   = a0 - a1; c1[jdxx]   = a2 - b3;
        c1[ja1o+1] = b0 + b1; c1[jb+1]   = b2 - a3;
        c1[jcxx+1] = b1 - b0; c1[jdxx+1] = -b2 - a3;
      }
      ia = ia1 + jump; ja = ja1; c = c1;
    } else {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, ic = ib + iink, id = ic + iink;
        int jb = ja1o + jink;
        float a1 = sin45 * (a[ib] - a[id]);
        float a2 = sin45 * (a[ib] + a[id]);
        c1[ja1o]   = a[ia1o] + a1;  c1[jb]   = a[ia1o] - a1;
        c1[ja1o+1] = -a[ic] - a2;   c1[jb+1] = a[ic] - a2;
      }
      ia = ia1; ja = ja1; c = c1;
    }
  }
  return c;
}
}
namespace ifg4ref {
static std::vector<float>
kernel (int m, int la, int iink, int jink, int jump, int inc1, int inc2,
        const std::vector<float> &a, const std::vector<float> &ci,
        const std::vector<float> &trigs)
{
  const float sin45 = 0.7071067812f;
  std::vector<float> c = ci;
  int k = 0, ia = 1, ja = 1;
  while (k <= m/2) {
    int k_old = k;  k = k_old + la;
    int ia1 = ia, ja1 = ja;
    std::vector<float> c1 = c;
    if (k_old == 0) {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, ic = ib + iink;
        int jb = ja1o + jink, jc = jb + jink, jd = jc + jink;
        float a1 = a[ia1o] + a[ic], a2 = 2.0f*a[ib];
        float a3 = a[ia1o] - a[ic], a4 = 2.0f*a[ib+1];
        c1[ja1o] = a1 + a2; c1[jb] = a3 - a4; c1[jc] = a1 - a2; c1[jd] = a3 + a4;
      }
      ia = ia1; ja = ja1 + jump; c = c1;
    } else if (2*k_old < m) {
      int lower = iink + 2, lupper = iink + jink*2 - 2;
      for (int l = lower; l <= lupper; l += 4) {
        int ia1o = ia1, ja1o = ja1, lo = l;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, idxx = lo - ia1o, icxx = idxx + iink;
        int jb = ja1o + jink, jc = jb + jink, jd = jc + jink;
        int kb = k_old*2, kc = kb*2, kd = kc + kb;
        float a0 = a[ia1o] + a[icxx], a1 = a[ib] + a[idxx];
        float a2 = a[ia1o] - a[icxx], a3 = a[ib] - a[idxx];
        float b0 = a[ia1o+1] - a[icxx+1], b1 = a[ib+1] - a[idxx+1];
        float b2 = a[ia1o+1] + a[icxx+1], b3 = a[ib+1] + a[idxx+1];
        float cjb = a2 - b3, djb = b2 + a3;
        float cjc = a0 - a1, djc = b0 - b1;
        float cjd = a2 + b3, djd = b2 - a3;
        float tempr1 = cjb*trigs[kb+1] - djb*trigs[kb+2];
        float tempi1 = cjb*trigs[kb+2] + djb*trigs[kb+1];
        float tempr2 = cjc*trigs[kc+1] - djc*trigs[kc+2];
        float tempi2 = cjc*trigs[kc+2] + djc*trigs[kc+1];
        float tempr3 = cjd*trigs[kd+1] - djd*trigs[kd+2];
        float tempi3 = cjd*trigs[kd+2] + djd*trigs[kd+1];
        c1[ja1o] = a0 + a1; c1[jb] = tempr1; c1[jc] = tempr2; c1[jd] = tempr3;
        c1[ja1o+1] = b0 + b1; c1[jb+1] = tempi1; c1[jc+1] = tempi2; c1[jd+1] = tempi3;
      }
      ia = ia1; ja = ja1 + jump; c = c1;
    } else {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, jb = ja1o + jink, jc = jb + jink, jd = jc + jink;
        float a1 = sin45 * (a[ia1o+1] + a[ib+1]);
        float a2 = sin45 * (a[ia1o] - a[ib]);
        c1[ja1o] = 2.0f*(a[ia1o] + a[ib]);
        c1[jb]   = 2.0f*(a2 - a1);
        c1[jc]   = 2.0f*(a[ib+1] - a[ia1o+1]);
        c1[jd]   = -2.0f*(a1 + a2);
      }
      ia = ia1; ja = ja1; c = c1;
    }
  }
  return c;
}
}
namespace ifg3ref {
static std::vector<float>
kernel (int m, int la, int iink, int jink, int jump, int inc1, int inc2,
        const std::vector<float> &a, const std::vector<float> &ci,
        const std::vector<float> &trigs)
{
  const float sin60 = 0.866025403784437f;
  std::vector<float> c = ci;
  int k = 0, ia = 1, ja = 1;
  while (k <= m/2) {
    int k_old = k;  k = k_old + la;
    int ia1 = ia, ja1 = ja;
    std::vector<float> c1 = c;
    if (k_old == 0) {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, jb = ja1o + jink, jc = jb + jink;
        float a1 = a[ia1o] - a[ib];
        float b1 = 2.0f * sin60 * a[ib+1];
        c1[ja1o] = a[ia1o] + 2.0f*a[ib];  c1[jb] = a1 - b1;  c1[jc] = a1 + b1;
      }
      ia = ia1; ja = ja1 + jump; c = c1;
    } else if (2*k_old < m) {
      int kb = k_old*2, kc = kb*2, lower = iink + 2, lupper = iink + jink*2 - 2;
      for (int l = lower; l <= lupper; l += 4) {
        int ia1o = ia1, ja1o = ja1, lo = l;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, icxx = lo - ia1o, jb = ja1o + jink, jc = jb + jink;
        float a1 = a[ib] + a[icxx];
        float b1 = a[ib+1] - a[icxx+1];
        float a2 = a[ia1o] - 0.5f*a1;
        float b2 = a[ia1o+1] - 0.5f*b1;
        float a3 = sin60 * (a[ib] - a[icxx]);
        float b3 = sin60 * (a[ib+1] + a[icxx+1]);
        float cjb = a2 - b3, djb = b2 + a3, cjc = a2 + b3, djc = b2 - a3;
        float tempr1 = cjb*trigs[kb+1] - djb*trigs[kb+2];
        float tempi1 = cjb*trigs[kb+2] + djb*trigs[kb+1];
        float tempr2 = cjc*trigs[kc+1] - djc*trigs[kc+2];
        float tempi2 = cjc*trigs[kc+2] + djc*trigs[kc+1];
        c1[ja1o] = a[ia1o] + a1;  c1[jb] = tempr1;  c1[jc] = tempr2;
        c1[ja1o+1] = a[ia1o+1] + b1;  c1[jb+1] = tempi1;  c1[jc+1] = tempi2;
      }
      ia = ia1; ja = ja1 + jump; c = c1;
    } else {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, jb = ja1o + jink, jc = jb + jink;
        float a1 = 0.5f*a[ia1o] - a[ib];
        float b1 = sin60 * a[ia1o+1];
        c1[ja1o] = a[ia1o] + a[ib];  c1[jb] = a1 - b1;  c1[jc] = -a1 - b1;
      }
      ia = ia1; ja = ja1; c = c1;
    }
  }
  return c;
}
}
namespace ifg2ref {
static std::vector<float>
kernel (int m, int la, int iink, int jink, int jump, int inc1, int inc2,
        const std::vector<float> &a, const std::vector<float> &ci,
        const std::vector<float> &trigs)
{
  std::vector<float> c = ci;
  int k = 0, ia = 1, ja = 1;
  while (k <= m/2) {
    int k_old = k;  k = k_old + la;
    int ia1 = ia, ja1 = ja;
    std::vector<float> c1 = c;
    if (k_old == 0) {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int ib = ia1o + iink, jb = ja1o + jink;
        c1[ja1o] = a[ia1o] + a[ib];
        c1[jb]   = a[ia1o] - a[ib];
      }
      ia = ia1; ja = ja1 + jump; c = c1;          // jump on the OTHER axis
    } else if (2*k_old < m) {
      int kb = k_old*2, lower = iink + 2, lupper = iink + jink*2 - 2;
      for (int l = lower; l <= lupper; l += 4) {
        int ia1o = ia1, ja1o = ja1, lo = l;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int jb = ja1o + jink, ibxx = lo - ia1o;
        float cjb = a[ia1o] - a[ibxx];
        float djb = a[ia1o+1] + a[ibxx+1];
        float tempr = cjb*trigs[kb+1] - djb*trigs[kb+2];
        float tempi = cjb*trigs[kb+2] + djb*trigs[kb+1];
        c1[ja1o]   = a[ia1o] + a[ibxx];
        c1[jb]     = tempr;
        c1[ja1o+1] = a[ia1o+1] - a[ibxx+1];
        c1[jb+1]   = tempi;
      }
      ia = ia1; ja = ja1 + jump; c = c1;
    } else {
      for (int l = 1; l <= la; l++) {
        int ia1o = ia1, ja1o = ja1;
        ia1 = ia1o + inc1;  ja1 = ja1o + inc2;
        int jb = ja1o + jink;
        c1[ja1o] =  2.0f * a[ia1o];
        c1[jb]   = -2.0f * a[ia1o+1];
      }
      ia = ia1; ja = ja1; c = c1;
    }
  }
  return c;
}
}
#endif
#ifdef TEST_PASSFREQ_DV
// PassFreq, the FFT pass dispatcher (test/unit/PassFreq.sis).  This is what the
// three ifm_*_dv promotions were for: the unit original declares the kernels as
// `global` and relies on separate compilation, so with them inlined -- e2e
// files are self-contained, %$include being cwd-relative -- the dispatcher
// itself becomes testable.
//
// The reference is the same dispatch over the three kernel references already
// validated against OSC 13.0.3 for their own groups, so what is actually under
// test here is the PARAMETER DERIVATION and the three-way selection, which the
// kernel groups receive ready-made and never exercise:
//
//     m = n/ifac;  jink = inc2*m;  iink = inc1*la;
//     jump = (ifac-1)*iink;  igo = ifac-1
//     igo 2 -> radix 3,  igo 3 -> radix 4,  else -> radix 2
//
// A wrong igo mapping or a wrong jump/iink/jink formula shows up here and
// nowhere else in the suite.
static void test_passfreq_dv (void)
{
  printf ("\n=== Group: passfreq_dv (FFT pass dispatch + parameter derivation) ===\n");
  struct Cfg { int n, ifac, la, inc1, inc2; };
  const Cfg cfgs[] = { { 16, 2, 1, 2, 1 }, { 24, 3, 1, 2, 1 },
                       { 32, 4, 1, 2, 1 }, { 48, 3, 2, 2, 1 },
                       { 64, 4, 2, 2, 1 }, { 32, 2, 2, 1, 1 } };
  const int NEL = 400;
  for (const Cfg &cf : cfgs)
    {
      const int m = cf.n / cf.ifac, jink = cf.inc2 * m, iink = cf.inc1 * cf.la,
                jump = (cf.ifac - 1) * iink, igo = cf.ifac - 1;
      std::vector<float> a (NEL + 1), ci (NEL + 1, 0.f), trigs (NEL + 1);
      for (int i = 1; i <= NEL; i++)
        { a[i] = (float)i / 8.0f; trigs[i] = (float)i / 16.0f; }
      std::vector<float> ref
          = (igo == 2) ? ifm3ref::kernel (m, cf.la, iink, jink, jump, cf.inc1,
                                          cf.inc2, a, ci, trigs)
            : (igo == 3) ? ifm4ref::kernel (m, cf.la, iink, jink, jump, cf.inc1,
                                            cf.inc2, a, ci, trigs)
                         : ifm2ref::kernel (m, cf.la, iink, jink, jump, cf.inc1,
                                            cf.inc2, a, ci, trigs);
      auto mk = [&] (const std::vector<float> &src) {
        sisal_array_t A = sisal_array_alloc_empty (1, 3, (uint64_t)NEL);
        A.dims[0] = NEL; A.lower_bound[0] = 1;
        for (int i = 1; i <= NEL; i++) ((float *)A.data)[i - 1] = src[i];
        return A;
      };
      sisal_array_t aa = mk (a), cc = mk (ci), tt = mk (trigs);
      sisal_array_t r = func_MAIN (cf.inc1, cf.inc2, cf.n, cf.ifac, cf.la, aa,
                                   cc, tt);
      char msg[190];
      snprintf (msg, sizeof msg,
                "n=%-2d ifac=%d la=%d -> radix %d, result is %d reals", cf.n,
                cf.ifac, cf.la, igo == 2 ? 3 : igo == 3 ? 4 : 2, NEL);
      check (msg, (int)r.size == NEL && r.rank == 1);
      bool ok = ((int)r.size == NEL);
      for (int i = 1; ok && i <= NEL; i++)
        ok = ok && (fabs ((double)((const float *)r.data)[i - 1]
                          - (double)ref[i]) < 1e-5);
      snprintf (msg, sizeof msg,
                "n=%-2d ifac=%d la=%d dispatch and parameters match", cf.n,
                cf.ifac, cf.la);
      check (msg, ok);
    }
}
#endif
#ifdef TEST_MDFFTFREQ_DV
// MdFFTFreq, the multi-factor FFT driver (test/unit/MdFFTFreq.sis) -- the top
// of the frequency-direction stack, with the three butterfly kernels and
// PassFreq inlined so the WHOLE stack runs under one check.
//
// The reference here is a NAIVE DFT, not a snapshot and not another pass of the
// same algorithm.  That is the point: passfreq_dv and the three ifm_*_dv groups
// check each pass against a transcription of that pass, so a shared
// misunderstanding of the algorithm would satisfy all four.  Composing the
// passes has to produce the actual Fourier transform, and nothing below would
// survive a wrong composition.
//
// Conventions, both read off test/unit/InitFFT.sis rather than guessed:
//
//   trigs[2k-1] = cos(-2*pi*(k-1)/n),  trigs[2k] = sin(-2*pi*(k-1)/n)
//   output      = interleaved (re, im) for k = 0 .. nwave-1, UNSCALED,
//                 zero-padded out to n by the trailing `|| array_dv_fill`
//
// ifax must be a genuine factorisation with 4s hoisted first, which is what
// FACTR4 produces; the products are asserted below so a wrong table is a
// failure rather than a silently different transform.
//
// The configurations are chosen to cover all three structural arms, which no
// other group in the suite reaches:
//
//   nfax = 1        -- the THEN branch, a single PassFreq, no ping-pong at all
//   nfax = 2 (even) -- ELSE + even parity: first pass writes into work
//   nfax = 3 (odd)  -- ELSE + odd parity:  first pass writes into x
//
// plus radices 2, 3 and 4, and nwave < n/2 to exercise the zero padding.
//
// Verified to FAIL on a conjugated twiddle table (sin -> -sin): 8 of the 9
// configurations report mismatches, so the comparison is live rather than
// vacuous.  The n=4 case alone is insensitive to that particular flip.
static void test_mdfftfreq_dv (void)
{
  printf ("\n=== Group: mdfftfreq_dv (multi-factor FFT driver vs naive DFT) ===\n");
  struct Cfg { int n, nfax; int32_t ifax[4]; int nwave; };
  const Cfg cfgs[] = {
    { 4, 1, { 4 }, 2 },          // THEN branch: one pass, no ping-pong
    { 8, 2, { 4, 2 }, 4 },       // even parity, radix 4 then 2
    { 16, 2, { 4, 4 }, 8 },      // even parity, radix 4 twice
    { 12, 2, { 4, 3 }, 6 },      // even parity, radix 3 present
    { 6, 2, { 2, 3 }, 3 },       // even parity, no radix-4 pass at all
    { 32, 3, { 4, 4, 2 }, 16 },  // ODD parity: first pass writes into x
    { 24, 3, { 4, 2, 3 }, 12 },  // ODD parity, all three radices
    { 8, 2, { 4, 2 }, 2 },       // nwave < n/2 -> trailing zero padding
    { 16, 2, { 4, 4 }, 3 },      // nwave < n/2, odd truncation
  };
  for (const Cfg &cf : cfgs)
    {
      int prod = 1;
      for (int i = 0; i < cf.nfax; i++) prod *= cf.ifax[i];
      char msg[190];
      snprintf (msg, sizeof msg, "n=%-2d ifax product == n (valid factorisation)",
                cf.n);
      check (msg, prod == cf.n);

      std::vector<float> trigs (cf.n), grid (cf.n);
      for (int Lp = 1; Lp <= cf.n; Lp++)
        {
          int k = (Lp + 1) / 2;
          double ar = -2.0 * M_PI * (double)(k - 1) / (double)cf.n;
          trigs[Lp - 1] = (float)((Lp % 2 == 0) ? sin (ar) : cos (ar));
        }
      // a signal with DC, a ramp and one pure tone: every bin is nonzero, and
      // the tone pins the bin ORDER (a permuted spectrum moves its peak).
      for (int i = 0; i < cf.n; i++)
        grid[i] = (float)(1.0 + 0.5 * i
                          + 3.0 * cos (2.0 * M_PI * i * 2.0 / (double)cf.n));

      auto mkf = [&] (const std::vector<float> &src) {
        sisal_array_t a
            = sisal_array_alloc_empty (1, 8, (uint64_t)src.size ());
        a.dims[0] = (int64_t)src.size (); a.lower_bound[0] = 1;
        for (size_t i = 0; i < src.size (); i++) ((float *)a.data)[i] = src[i];
        return a;
      };
      sisal_array_t r
          = func_MAIN (1, cf.nwave, cf.nfax, cf.n,
                       sisal_array_build_i32 (1, cf.nfax, cf.ifax), mkf (trigs),
                       mkf (grid));

      snprintf (msg, sizeof msg, "n=%-2d nfax=%d nwave=%-2d -> %d reals, rank 1",
                cf.n, cf.nfax, cf.nwave, cf.n);
      check (msg, (int)r.size == cf.n && r.rank == 1);

      bool ok = ((int)r.size == cf.n);
      const float *out = (const float *)r.data;
      for (int k = 0; ok && k < cf.nwave; k++)
        {
          double R = 0, I = 0;
          for (int j = 0; j < cf.n; j++)
            {
              double th = -2.0 * M_PI * (double)j * (double)k / (double)cf.n;
              R += grid[j] * cos (th);
              I += grid[j] * sin (th);
            }
          // relative to the bin magnitude: `real` is float, and n up to 32
          // accumulates enough that an absolute bound would be either loose
          // on the big bins or false on the small ones.
          double sc = fmax (1.0, fabs (R) + fabs (I));
          ok = ok && fabs ((double)out[2 * k] - R) / sc < 1e-4
               && fabs ((double)out[2 * k + 1] - I) / sc < 1e-4;
        }
      snprintf (msg, sizeof msg,
                "n=%-2d nfax=%d ifax=[%d%s%s] spectrum matches naive DFT", cf.n,
                cf.nfax, cf.ifax[0],
                cf.nfax > 1 ? (cf.ifax[1] == 2 ? ",2" : cf.ifax[1] == 3 ? ",3" : ",4") : "",
                cf.nfax > 2 ? (cf.ifax[2] == 2 ? ",2" : cf.ifax[2] == 3 ? ",3" : ",4") : "");
      check (msg, ok);

      bool pad = true;
      for (int i = 2 * cf.nwave; i < (int)r.size; i++) pad = pad && out[i] == 0.f;
      snprintf (msg, sizeof msg, "n=%-2d nwave=%-2d tail [%d..%d] is zero-padded",
                cf.n, cf.nwave, 2 * cf.nwave + 1, cf.n);
      check (msg, pad);

      if (r.data) free (r.data);
    }
}
#endif
#ifdef TEST_NANU_DV
// nanu -- Dave Cann's A * B = C matrix multiply (test/unit/nanu.sis, LLNL 1991).
//
// The original's own oracle is too weak to be worth reproducing alone: Setupa
// builds the IDENTITY, so C = A * B is just B and Main returns 0 mismatches --
// but a transposed subscript in the inner reduction ALSO returns B when A is
// the identity.  So the port keeps that self-check and additionally multiplies
// a non-symmetric G[i,j] = i*10 + j by the same B, which a real matmul
// reference here has to match.  Transposing G in the reference fails 12 of the
// checks; the identity leg would not have noticed at all.
//
// Be's arithmetic is the second thing pinned.  `s*i/(i-10)` is an INTEGER
// division widened by real(...), not a real division -- Be(5,5) is
// 0 -1 -2 -3 -5, i.e. truncation TOWARD ZERO for the negative divisors
// (5*2/-8 = -1, not -2).  Substituting real division in the reference fails 45
// checks.  n = 10 and 12 exercise the (i-10) = 0 guard.
static std::vector<float> nanu_be (int n, int s)
{
  std::vector<float> v (n);
  for (int i = 1; i <= n; i++)
    {
      int den = (i - 10 == 0) ? 1 : (i - 10);
      v[i - 1] = (float)(s * i / den);          // INTEGER division, then widen
    }
  return v;
}
static void test_nanu_dv (void)
{
  printf ("\n=== Group: nanu_dv (A*B=C; identity leg plus a non-symmetric "
          "multiply) ===\n");
  int n_bad = 0, n_cnt_bad = 0, cases = 0;
  char msg[160];
  for (int n : { 1, 3, 5, 10, 12 })
    for (int s : { 3, 5, 7 })
      {
        const auto be = nanu_be (n, s);
        std::vector<float> B (n * n), G (n * n), C (n * n), D (n * n);
        for (int i = 0; i < n; i++)
          for (int j = 0; j < n; j++)
            {
              B[i * n + j] = be[j];                       // every row is Be
              G[i * n + j] = (float)((i + 1) * 10 + (j + 1));
            }
        for (int i = 0; i < n; i++)
          for (int k = 0; k < n; k++)
            {
              float c = 0, d = 0;
              for (int j = 0; j < n; j++)
                {
                  c += ((i == j) ? 1.0f : 0.0f) * B[j * n + k];
                  d += G[i * n + j] * B[j * n + k];
                }
              C[i * n + k] = c;
              D[i * n + k] = d;
            }

        auto r = func_MAIN (n, s);
        cases++;
        auto same = [&] (sisal_array_t a, const std::vector<float> &want) {
          if ((int)a.size != n * n || a.rank != 2 || (int)a.dims[0] != n
              || (int)a.dims[1] != n)
            return false;
          for (int t = 0; t < n * n; t++)
            if (((const float *)a.data)[t] != want[t]) return false;  // small ints: exact
          return true;
        };
        if (!same (r.B, B) || !same (r.C, C) || !same (r.D, D) || !same (r.G, G))
          n_bad++;
        if (r.ncnt != 0) n_cnt_bad++;

        if (r.B.data) free (r.B.data);
        if (r.C.data) free (r.C.data);
        if (r.D.data) free (r.D.data);
        if (r.G.data) free (r.G.data);
      }
  snprintf (msg, sizeof msg,
            "all four matrices match the reference over %d (n,s) cases", cases);
  check (msg, n_bad == 0);
  check ("identity leg: C == B, so the program's own mismatch count is 0",
         n_cnt_bad == 0);

  // Spell the two pinned facts out, so a regression names itself.
  {
    auto r = func_MAIN (5, 5);
    const float want_be[5] = { 0, -1, -2, -3, -5 };
    bool ok = r.B.size == 25;
    for (int j = 0; ok && j < 5; j++)
      ok = ((const float *)r.B.data)[j] == want_be[j];
    check ("Be(5,5) is 0 -1 -2 -3 -5 (INTEGER division, truncating to zero)", ok);
    // D[1,k] = sum_j G[1,j]*B[j,k] = be[k] * (10+1 + 10+2 + ... ) -- not B
    float row = 0;
    for (int j = 1; j <= 5; j++) row += (float)(10 + j);
    bool nz = r.D.size == 25
              && ((const float *)r.D.data)[1] == want_be[1] * row
              && ((const float *)r.D.data)[1] != ((const float *)r.B.data)[1];
    check ("the non-symmetric leg really multiplies (D != B)", nz);
    if (r.B.data) free (r.B.data);
    if (r.C.data) free (r.C.data);
    if (r.D.data) free (r.D.data);
    if (r.G.data) free (r.G.data);
  }
}
#endif
#ifdef TEST_CROSSOVERS_DV
// crossovers -- the crossed-edge geometry of the TSP annealing code
// (test/unit/crossovers.sis).  A crossing is a fixed 2 x 2 block of node
// indices, so a cross list is a rank-3 array_dv (ncross x 2 x 2) whose COUNT is
// data-dependent but whose shape is not ragged.  Find_All_Crosses builds it by
// accumulating a LIST (its candidate set is a triangle) and packing with
// array_addh; Check_Crossed and Remove_Edge build it dense-then-COMPRESS.
//
// The reference is an independent segment-intersection test: the Sisal side
// solves the two parametric equations by Cramer (the original's arithmetic),
// this side uses ORIENTATION predicates.  They agree exactly for non-parallel
// segments, which is the only case either calls a crossing.
//
// This group also pins the array_addh leading-axis lower bound.  The packed
// rank-3 is subscripted again by Remove_Edge (C[k,1,1] ...), so if the axis
// created by the first append ever goes back to 0-based, `rem` reads one slab
// high and this fails -- which is exactly how the bug was found.
struct xo_pt { int x, y; };
typedef std::array<int, 4> xo_cross;              // a1 a2 b1 b2
static long long xo_orient (long long px, long long py, long long qx,
                            long long qy, long long rx, long long ry)
{
  return (qx - px) * (ry - py) - (qy - py) * (rx - px);
}
static int xo_sgn (long long v) { return v > 0 ? 1 : (v < 0 ? -1 : 0); }
static bool xo_crossed (int a1, int a2, int b1, int b2,
                        const std::vector<xo_pt> &N)
{
  // edges sharing a node are settled on the INDICES, before any geometry
  if (a1 == b2 || a2 == b1 || a1 == b1 || a2 == b2) return false;
  const xo_pt &A = N[a1], &B = N[a2], &C = N[b1], &D = N[b2];
  long long cr = (long long)(B.x - A.x) * (D.y - C.y)
                 - (long long)(B.y - A.y) * (D.x - C.x);
  if (cr == 0) return false;                      // parallel is not a crossing
  int d1 = xo_sgn (xo_orient (A.x, A.y, B.x, B.y, C.x, C.y));
  int d2 = xo_sgn (xo_orient (A.x, A.y, B.x, B.y, D.x, D.y));
  int d3 = xo_sgn (xo_orient (C.x, C.y, D.x, D.y, A.x, A.y));
  int d4 = xo_sgn (xo_orient (C.x, C.y, D.x, D.y, B.x, B.y));
  return d1 * d2 <= 0 && d3 * d4 <= 0;            // closed: touching counts
}
static std::vector<xo_cross> xo_find_all (const std::vector<int> &it,
                                          const std::vector<xo_pt> &N)
{
  std::vector<xo_cross> out;
  const int L = (int)it.size ();
  for (int I = 1; I <= L - 3; I++)
    for (int J = I + 2; J <= L - 1; J++)
      if (xo_crossed (it[I - 1], it[I], it[J - 1], it[J], N))
        out.push_back ({ it[I - 1], it[I], it[J - 1], it[J] });
  return out;
}
static std::vector<xo_cross> xo_check (const int E[2], const std::vector<int> &it,
                                       const std::vector<xo_pt> &N)
{
  std::vector<xo_cross> out;
  const int L = (int)it.size ();
  for (int I = 1; I <= L - 1; I++)
    if (xo_crossed (E[0], E[1], it[I - 1], it[I], N))
      out.push_back ({ E[0], E[1], it[I - 1], it[I] });
  return out;
}
static std::vector<xo_cross> xo_remove (const std::vector<xo_cross> &C,
                                        const int E[2])
{
  std::vector<xo_cross> out;
  for (const auto &c : C)
    if (!((c[0] == E[0] && c[1] == E[1]) || (c[1] == E[0] && c[0] == E[1])
          || (c[2] == E[0] && c[3] == E[1]) || (c[3] == E[0] && c[2] == E[1])))
      out.push_back (c);
  return out;
}
static bool xo_same (sisal_array_t a, const std::vector<xo_cross> &want)
{
  const int n = (int)want.size ();
  if ((int)a.size != n * 4) return false;
  // a non-empty cross list must be a genuine rank-3 n x 2 x 2 block; an empty
  // one packs to the empty seed, which has no inner shape to report
  if (n > 0
      && (a.rank != 3 || (int)a.dims[0] != n || (int)a.dims[1] != 2
          || (int)a.dims[2] != 2))
    return false;
  for (int i = 0; i < n; i++)
    for (int k = 0; k < 4; k++)
      if (((const int32_t *)a.data)[i * 4 + k] != want[i][k]) return false;
  return true;
}
static void test_crossovers_dv (void)
{
  printf ("\n=== Group: crossovers_dv (cross lists: list-packed vs "
          "COMPRESS-compacted) ===\n");

  // 8 nodes on a box plus node 9 at the centre, so an edge can END on another
  // edge's interior -- the closed-interval boundary the original's D3/D4 test
  // accepts and a strict "proper intersection" test would reject.
  const std::vector<xo_pt> N = { { 0, 0 },                        // index 0 unused
                                 { 0, 0 }, { 4, 0 }, { 8, 0 }, { 8, 4 },
                                 { 8, 8 }, { 4, 8 }, { 0, 8 }, { 0, 4 },
                                 { 4, 4 } };
  std::vector<int32_t> coords;
  for (size_t i = 1; i < N.size (); i++)
    { coords.push_back (N[i].x); coords.push_back (N[i].y); }

  struct Case { std::vector<int32_t> it; int32_t E[2]; const char *nm; };
  const std::vector<Case> cases = {
    { { 1, 5, 3, 7, 2, 6, 4, 8, 1 }, { 1, 5 }, "star tour, many crossings" },
    { { 1, 2, 3, 4, 5, 6, 7, 8, 1 }, { 1, 3 }, "convex octagon, none" },
    { { 1, 3, 2, 4, 6, 5, 7, 8, 1 }, { 2, 4 }, "mixed tour" },
    { { 1, 5, 9, 2, 7, 4, 1 },       { 9, 2 }, "edge ending on another edge" },
    { { 1, 2, 3 },                   { 1, 3 }, "too short to hold a pair" },
  };

  int n_all_bad = 0, n_chk_bad = 0, n_rem_bad = 0;
  int tot_all = 0, tot_removed = 0, n_empty = 0;
  char msg[160];
  for (const auto &c : cases)
    {
      const auto want_all = xo_find_all (c.it, N);
      const auto want_chk = xo_check (c.E, c.it, N);
      const auto want_rem = xo_remove (want_all, c.E);
      tot_all += (int)want_all.size ();
      tot_removed += (int)(want_all.size () - want_rem.size ());
      if (want_all.empty ()) n_empty++;

      sisal_array_t Co = sisal_array_alloc_empty (1, 6, coords.size ());
      memcpy (Co.data, coords.data (), coords.size () * sizeof (int32_t));
      sisal_array_t It = sisal_array_alloc_empty (1, 6, c.it.size ());
      memcpy (It.data, c.it.data (), c.it.size () * sizeof (int32_t));
      sisal_array_t Ex = sisal_array_alloc_empty (1, 6, 2);
      memcpy (Ex.data, c.E, sizeof c.E);

      auto r = func_MAIN (Co, It, Ex);

      bool ok = xo_same (r.all, want_all);
      if (!ok) n_all_bad++;
      snprintf (msg, sizeof msg, "%-32s Find_All_Crosses == reference (%zu)",
                c.nm, want_all.size ());
      check (msg, ok);

      ok = xo_same (r.chk, want_chk);
      if (!ok) n_chk_bad++;
      snprintf (msg, sizeof msg, "%-32s Check_Crossed == reference (%zu)", c.nm,
                want_chk.size ());
      check (msg, ok);

      ok = xo_same (r.rem, want_rem);
      if (!ok) n_rem_bad++;
      snprintf (msg, sizeof msg, "%-32s Remove_Edge == reference (%zu)", c.nm,
                want_rem.size ());
      check (msg, ok);

      if (Co.data) free (Co.data);
      if (It.data) free (It.data);
      if (Ex.data) free (Ex.data);
      if (r.all.data) free (r.all.data);
      if (r.chk.data) free (r.chk.data);
      if (r.rem.data) free (r.rem.data);
    }

  // Matching the reference proves nothing if the geometry never crosses, or if
  // Remove_Edge never had anything to drop.
  snprintf (msg, sizeof msg,
            "the tours actually cross (%d crossings, %d of them removed, "
            "%d empty cases)", tot_all, tot_removed, n_empty);
  check (msg, tot_all > 0 && tot_removed > 0 && n_empty > 0);
  check ("no mismatches anywhere",
         n_all_bad == 0 && n_chk_bad == 0 && n_rem_bad == 0);
}
#endif
#ifdef TEST_CYK_DV
// CYK recognition (test/unit/cyk.sis), on Hopcroft & Ullman's grammar
//     S -> A B | B C     A -> B A | a
//     B -> C C | b       C -> A B | a
// with S=1 A=2 B=3 C=4 and a=1 b=2.  The unit test hard-codes the DEGENERATE
// grammar NV=1, A -> a, A -> A A, which accepts every string -- an oracle that
// cannot fail.  Here the grammar is real, so acceptance actually depends on the
// split points the DP finds.
//
// The reference below is an independent CYK over the same productions, and both
// sides are compared on EVERY string over {a,b} of length 1..6 (126 of them) --
// accept bit AND the whole n x n table of "how many variables derive x[i..i+j-1]".
// The table is what makes a wrong split point visible: a recurrence that pairs
// V[k,i] with the wrong partner still gets the accept bit right on many strings.
static const int cyk_NV = 4;
static bool cyk_P1ref (int t, int A)
{
  return (t == 1 && A == 2) || (t == 1 && A == 4) || (t == 2 && A == 3);
}
static bool cyk_P2ref (int A, int B, int C)
{
  return (A == 1 && B == 2 && C == 3) || (A == 1 && B == 3 && C == 4)
         || (A == 2 && B == 3 && C == 2) || (A == 3 && B == 4 && C == 4)
         || (A == 4 && B == 2 && C == 3);
}
static bool cyk_ref (const std::vector<int> &x, std::vector<int> &cnt)
{
  const int n = (int)x.size ();
  std::vector<char> V ((size_t)(n + 1) * (n + 1) * (cyk_NV + 1), 0);
  auto at = [&] (int j, int i, int A) -> char & {
    return V[((size_t)j * (n + 1) + i) * (cyk_NV + 1) + A];
  };
  for (int i = 1; i <= n; i++)
    for (int A = 1; A <= cyk_NV; A++)
      at (1, i, A) = cyk_P1ref (x[i - 1], A);
  for (int j = 2; j <= n; j++)
    for (int i = 1; i <= n - j + 1; i++)
      for (int A = 1; A <= cyk_NV; A++)
        {
          bool any = false;
          for (int k = 1; k <= j - 1 && !any; k++)
            for (int B = 1; B <= cyk_NV && !any; B++)
              for (int C = 1; C <= cyk_NV && !any; C++)
                any = at (k, i, B) && at (j - k, i + k, C) && cyk_P2ref (A, B, C);
          at (j, i, A) = any;
        }
  cnt.assign ((size_t)n * n, 0);
  for (int j = 1; j <= n; j++)
    for (int i = 1; i <= n; i++)
      {
        int c = 0;
        if (i <= n - j + 1)
          for (int A = 1; A <= cyk_NV; A++)
            if (at (j, i, A)) c++;
        cnt[(size_t)(j - 1) * n + (i - 1)] = c;
      }
  return at (n, 1, 1);
}
static void test_cyk_dv (void)
{
  printf ("\n=== Group: cyk_dv (CYK parsing; rank-3 boolean array_dv DP table) "
          "===\n");

  int n_acc_bad = 0, n_cnt_bad = 0, n_shape_bad = 0, n_yes = 0, n_no = 0;
  for (int n = 1; n <= 6; n++)
    for (int code = 0; code < (1 << n); code++)
      {
        std::vector<int> x (n);
        for (int i = 0; i < n; i++)
          x[i] = ((code >> i) & 1) ? 2 : 1;          // bit set = 'b'

        std::vector<int> cnt;
        const bool acc = cyk_ref (x, cnt);
        (acc ? n_yes : n_no)++;

        sisal_array_t X = sisal_array_alloc_empty (1, 6, (uint64_t)n);
        for (int i = 0; i < n; i++)
          ((int32_t *)X.data)[i] = x[i];
        auto r = func_MAIN (X);

        if (r.res_0 != acc) n_acc_bad++;
        if (r.res_1.rank != 2 || (int)r.res_1.dims[0] != n
            || (int)r.res_1.dims[1] != n || (int)r.res_1.size != n * n)
          n_shape_bad++;
        else
          for (int t = 0; t < n * n; t++)
            if (((const int32_t *)r.res_1.data)[t] != cnt[t]) { n_cnt_bad++; break; }

        if (X.data) free (X.data);
        if (r.res_1.data) free (r.res_1.data);
      }

  // The sweep is only meaningful if the grammar SPLITS the strings; if every
  // one landed on the same side, matching the reference would prove nothing.
  char msg[160];
  snprintf (msg, sizeof msg,
            "the 126 strings split both ways (%d accepted, %d rejected)",
            n_yes, n_no);
  check (msg, n_yes > 0 && n_no > 0);
  check ("every accept bit matches the reference CYK", n_acc_bad == 0);
  check ("every count table is n x n", n_shape_bad == 0);
  check ("every count table matches cell for cell", n_cnt_bad == 0);

  // The textbook run, spelled out: baaba, with the V sets of Hopcroft & Ullman
  //   j=1  {B} {A,C} {A,C} {B} {A,C}          j=2  {S,A} {B} {S,C} {S,A}
  //   j=3  {}  {B}   {B}                      j=4  {}    {S,A,C}
  //   j=5  {S,A,C}   -> S is in it, so baaba is in the language.
  {
    const int32_t s[5] = { 2, 1, 1, 2, 1 };
    sisal_array_t X = sisal_array_alloc_empty (1, 6, 5);
    memcpy (X.data, s, sizeof s);
    auto r = func_MAIN (X);
    check ("baaba is in the language (S derives all five symbols)", r.res_0);

    static const int want[25] = { 1, 2, 2, 1, 2,
                                  2, 1, 2, 2, 0,
                                  0, 1, 1, 0, 0,
                                  0, 3, 0, 0, 0,
                                  3, 0, 0, 0, 0 };
    bool ok = r.res_1.size == 25;
    for (int t = 0; ok && t < 25; t++)
      ok = ((const int32_t *)r.res_1.data)[t] == want[t];
    check ("baaba's V table is the textbook one", ok);
    // the dead corner (i > n-j+1) must be carried as false, not read as garbage
    bool corner = r.res_1.size == 25;
    for (int j = 1; corner && j <= 5; j++)
      for (int i = 6 - j + 1; corner && i <= 5; i++)
        corner = ((const int32_t *)r.res_1.data)[(j - 1) * 5 + (i - 1)] == 0;
    check ("the unreachable corner of the table stays empty", corner);

    if (X.data) free (X.data);
    if (r.res_1.data) free (r.res_1.data);
  }

  // A single 'a' is derived by A and C but not by S, so a one-symbol string is
  // rejected while the table row is non-empty -- accept is not just "V is set".
  {
    const int32_t s[1] = { 1 };
    sisal_array_t X = sisal_array_alloc_empty (1, 6, 1);
    memcpy (X.data, s, sizeof s);
    auto r = func_MAIN (X);           // n = 1: the while loop is ZERO-TRIP
    check ("zero-trip (n=1): \"a\" rejected, but two variables derive it",
           !r.res_0 && r.res_1.size == 1
               && ((const int32_t *)r.res_1.data)[0] == 2);
    if (X.data) free (X.data);
    if (r.res_1.data) free (r.res_1.data);
  }
}
#endif
#ifdef TEST_MMULT2_DV
// mmult2 -- matrix multiply via transpose and dot-product rows
// (test/unit/mmult2.sis).  Third of the rank-2 cluster, and the only INTEGER
// one: the two Gauss ports check float solvers against tolerances, where a
// small systematic indexing error can hide inside a 1e-4 bound.  Here every
// element must match exactly, so a transposed or off-by-one read fails.
//
// DEVIATIONS, one cause: scattering over a rank-2 is unsupported in ANY form --
// `for Element in A at I,J` (2-D element scatter) is rejected just as `for Row
// in A at I` is.  Transpose became a cross forall; MatMult's outer loops became
// index loops.  The inner `for Aik in Row dot Bkj in Col` is over two rank-1s
// and is kept as written: rank-1 scatter is fine.
static void test_mmult2_dv (void)
{
  printf ("\n=== Group: mmult2_dv (integer matrix multiply, exact) ===\n");
  for (int N = 2; N <= 6; N++)
    {
      struct FUNC_MAIN_mm_results r = func_MAIN (N);
      std::vector<long> b ((size_t)(N * N));
      for (int i = 1; i <= N; i++)
        for (int j = 1; j <= N; j++) b[(i - 1) * N + (j - 1)] = i + (j - 1) * 2;

      char msg[190];
      snprintf (msg, sizeof msg, "N=%d  A and B are rank 2, %dx%d", N, N, N);
      check (msg, r.res_0.rank == 2 && (int)r.res_0.dims[0] == N
                      && (int)r.res_0.dims[1] == N && r.res_1.rank == 2
                      && (int)r.res_2.dims[0] == N);

      bool ab = ((int)r.res_0.size == N * N && (int)r.res_1.size == N * N);
      for (int i = 0; ab && i < N * N; i++)
        ab = ab && ((const int32_t *)r.res_0.data)[i] == b[i]
             && ((const int32_t *)r.res_1.data)[i] == b[i];
      snprintf (msg, sizeof msg, "N=%d  A,B match i + (j-1)*2 exactly", N);
      check (msg, ab);

      bool cb = ((int)r.res_2.size == N * N);
      for (int i = 0; cb && i < N; i++)
        for (int k = 0; cb && k < N; k++)
          {
            long acc = 0;
            for (int j = 0; j < N; j++) acc += b[i * N + j] * b[j * N + k];
            cb = cb && ((const int32_t *)r.res_2.data)[i * N + k] == acc;
          }
      snprintf (msg, sizeof msg, "N=%d  C == A*B, every element exact", N);
      check (msg, cb);

      // `A := B` in Main, so res_0 and res_1 ALIAS THE SAME BUFFER -- freeing
      // both is a double free (exit 133).  Same trap as life1_dv, where a
      // zero-iteration result aliased its input.
      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data && r.res_1.data != r.res_0.data) free (r.res_1.data);
      if (r.res_2.data && r.res_2.data != r.res_0.data) free (r.res_2.data);
    }
}
#endif
#ifdef TEST_NEWGAUSSJ_DV
// newgaussj -- Gauss-Jordan returning the INVERSE as well as the solution
// (test/unit/newgaussj.sis).  Adds the property gaussjnew_dv cannot check:
// A * inv(A) = I.  Both references are independent of the algorithm -- the
// residual and the inverse identity, not a transcription of Gauss-Jordan.
//
// Deviations are all one thing: scatter over the ROWS of a rank-2 is
// unsupported, so the three `for Row in A at J` forms became index loops with
// Row := A[J,..].  See the .sis header.
//
// Systems all have a nonzero LEADING pivot on purpose.  The source's
// singularity guard tests old TmpA[Icol,Icol] -- the UNSWAPPED matrix -- while
// the pivot after Compute's swap is TmpA[Irow,Icol].  A matrix like
// {0,2,1; 1,0,3; 4,1,0} has a perfectly good pivot A[3,1]=4 but A[1,1]=0, so it
// takes the error[TwoD] branch, and that branch SEGFAULTS: an error[] array has
// a null data pointer which the next iteration indexes.  Unlike mdfftgrid_dv's
// source bug this one cannot be pinned -- a crash would take the runner down.
static void test_newgaussj_dv (void)
{
  printf ("\n=== Group: newgaussj_dv (Gauss-Jordan inverse + solution) ===\n");
  struct Sys { int n; std::vector<double> A, b; const char *nm; };
  const std::vector<Sys> systems = {
    { 2, { 2, 1, 1, 3 }, { 5, 10 }, "2x2" },
    { 3, { 2, 1, -1, -3, -1, 2, -2, 1, 2 }, { 8, -11, -3 }, "3x3 (x = 2,3,-1)" },
    { 3, { 4, 1, 2, 1, 5, 3, 2, 3, 6 }, { 7, 9, 11 }, "3x3 SPD" },
    { 3, { 10, 2, 1, 1, 8, 3, 2, 1, 9 }, { 13, 12, 12 }, "3x3 diag dominant" },
    { 4, { 2, 1, 0, 0, 1, 3, 1, 0, 0, 1, 4, 1, 0, 0, 1, 5 }, { 3, 5, 6, 6 },
      "4x4 tridiagonal" },
    { 4, { 4, 1, 2, 0, 1, 5, 0, 2, 2, 0, 6, 1, 0, 2, 1, 7 }, { 7, 8, 9, 10 },
      "4x4 SPD" },
  };
  for (const Sys &s : systems)
    {
      sisal_array_t A = sisal_array_alloc_empty (2, 8, (uint64_t)(s.n * s.n));
      A.rank = 2; A.dims[0] = s.n; A.dims[1] = s.n;
      A.lower_bound[0] = 1; A.lower_bound[1] = 1;
      for (int i = 0; i < s.n * s.n; i++) ((float *)A.data)[i] = (float)s.A[i];
      sisal_array_t B = sisal_array_alloc_empty (1, 8, (uint64_t)s.n);
      B.dims[0] = s.n; B.lower_bound[0] = 1;
      for (int i = 0; i < s.n; i++) ((float *)B.data)[i] = (float)s.b[i];

      struct FUNC_MAIN_ngj_results r = func_MAIN (s.n, A, B);
      const sisal_array_t inv = r.res_0, x = r.res_1;
      char msg[190];

      snprintf (msg, sizeof msg, "%-22s inverse is rank 2, %dx%d", s.nm, s.n, s.n);
      check (msg, inv.rank == 2 && (int)inv.dims[0] == s.n
                      && (int)inv.dims[1] == s.n && (int)x.size == s.n);

      bool ok = ((int)x.size == s.n && (int)inv.size == s.n * s.n);
      for (int j = 0; ok && j < s.n; j++)
        ok = ok && std::isfinite (((const float *)x.data)[j]);
      double wr = 0;
      for (int i = 0; ok && i < s.n; i++)
        {
          double acc = 0;
          for (int j = 0; j < s.n; j++)
            acc += s.A[i * s.n + j] * (double)((const float *)x.data)[j];
          wr = fmax (wr, fabs (acc - s.b[i]));
        }
      snprintf (msg, sizeof msg, "%-22s max|Ax-b| < 1e-4", s.nm);
      check (msg, ok && wr < 1e-4);

      bool iok = ok;
      double wi = 0;
      for (int i = 0; iok && i < s.n; i++)
        for (int k = 0; k < s.n; k++)
          {
            double acc = 0;
            for (int j = 0; j < s.n; j++)
              acc += s.A[i * s.n + j]
                     * (double)((const float *)inv.data)[j * s.n + k];
            wi = fmax (wi, fabs (acc - (i == k ? 1.0 : 0.0)));
          }
      snprintf (msg, sizeof msg, "%-22s max|A*inv(A) - I| < 1e-4", s.nm);
      check (msg, iok && wi < 1e-4);

      if (inv.data) free (inv.data);
      if (x.data) free (x.data);
      if (A.data) free (A.data);
      if (B.data) free (B.data);
    }
}
#endif
#ifdef TEST_NEWGAUSS_DV
// stand_alone_gauss -- LU with forward/back substitution
// (test/unit/stand_alone_gauss.sis).  The source shrinks the working block each
// step (array_setl on both axes), giving ragged AND offset rows; a flat rank-2
// dope has one lower_bound per axis, so that shape cannot be represented and an
// earlier attempt produced inf/nan.  The extents are known (n-i per axis), so
// the block stays full n x n -- no list needed.  See the .sis header.
//
// THE ORACLE IS THE ROUND TRIP: main solves A x = A e_m for each unit vector, so
// Check must be the IDENTITY.  Factorisation, forward and back substitution all
// have to be right together; an error in any one moves a column off the
// diagonal.  b must be the Vandermonde j^(i-1) and AMatrix must be b transposed
// (A e_m is column m).
static void test_newgauss_dv (void)
{
  printf ("\n=== Group: newgauss_dv (LU + substitution, round trip) ===\n");
  for (int n = 2; n <= 5; n++)
    {
      struct FUNC_MAIN_sag_results r = func_MAIN (n);
      const float *B = (const float *)r.res_0.data;
      const float *A = (const float *)r.res_1.data;
      const float *C = (const float *)r.res_2.data;
      char msg[190];

      bool fin = ((int)r.res_0.size == n * n && (int)r.res_2.size == n * n);
      for (int i = 0; fin && i < n * n; i++)
        fin = std::isfinite (B[i]) && std::isfinite (A[i])
              && std::isfinite (C[i]);
      snprintf (msg, sizeof msg, "n=%d  all three results are finite", n);
      check (msg, fin);

      double wb = 0, wa = 0, wc = 0;
      if (fin)
        for (int i = 1; i <= n; i++)
          for (int j = 1; j <= n; j++)
            {
              double e = pow ((double)j, (double)(i - 1));
              wb = fmax (wb, fabs ((double)B[(i - 1) * n + (j - 1)] - e));
              wa = fmax (wa, fabs ((double)A[(j - 1) * n + (i - 1)] - e));
              wc = fmax (wc, fabs ((double)C[(i - 1) * n + (j - 1)]
                                   - (i == j ? 1.0 : 0.0)));
            }
      snprintf (msg, sizeof msg, "n=%d  b is the Vandermonde j^(i-1)", n);
      check (msg, fin && wb < 1e-3);
      snprintf (msg, sizeof msg, "n=%d  AMatrix == b transposed (A e_m is column m)",
                n);
      check (msg, fin && wa < 1e-3);
      snprintf (msg, sizeof msg,
                "n=%d  ROUND TRIP: solving A x = A e_m returns the IDENTITY", n);
      check (msg, fin && wc < 1e-2);

      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data && r.res_1.data != r.res_0.data) free (r.res_1.data);
      if (r.res_2.data && r.res_2.data != r.res_0.data) free (r.res_2.data);
    }
}
#endif
#ifdef TEST_QUAD_DV
// quad -- arithmetic on quadtrees (test/unit/quad.sis).  Companion to
// quadtree_dv, which only builds the tree.  A Scalar node denotes c * I over its
// block, not a uniform block -- which is why NormalizeQ collapses on NW = SE
// with NE = SW = 0.  See the .sis header.
//
// THE ORACLE IS DENSE MATRIX ARITHMETIC computed here from the inputs: A+B
// elementwise, A*B by the triple loop, A-transpose.  Nothing re-walks the
// quadtree, so a wrong quadrant in QMult's eight-term expansion or a swapped
// pair in Transpose changes the answer.
static void test_quad_dv (void)
{
  printf ("\n=== Group: quad_dv (quadtree add / multiply / transpose) ===\n");
  struct Case { int n; std::vector<double> A, B; const char *nm; };
  const std::vector<Case> cases = {
    { 2, { 1, 2, 3, 4 }, { 5, 6, 7, 8 }, "2x2 dense" },
    { 2, { 1, 0, 0, 1 }, { 2, 0, 0, 2 },
      "2x2 diagonal -- BOTH collapse to Scalar nodes" },
    { 4, { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 },
      { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 },
      "4x4 dense x identity" },
    { 3, { 1, 2, 3, 4, 5, 6, 7, 8, 9 }, { 9, 8, 7, 6, 5, 4, 3, 2, 1 },
      "3x3 dense, pads to 4x4" },
  };
  auto mk = [] (int n, const std::vector<double> &v) {
    sisal_array_t a = sisal_array_alloc_empty (2, 8, (uint64_t)(n * n));
    a.rank = 2; a.dims[0] = n; a.dims[1] = n;
    a.lower_bound[0] = 1; a.lower_bound[1] = 1;
    for (int i = 0; i < n * n; i++) ((float *)a.data)[i] = (float)v[i];
    return a;
  };
  for (const Case &c : cases)
    {
      struct FUNC_MAIN_quad_results r
          = func_MAIN (mk (c.n, c.A), mk (c.n, c.B));
      const int N = r.res_3;
      char msg[190];
      snprintf (msg, sizeof msg, "%-42s pads %dx%d to %dx%d", c.nm, c.n, c.n, N,
                N);
      check (msg, N >= c.n && (int)r.res_0.size == N * N);

      // padding is PREPENDED, so the original sits in the bottom-right block
      const int off = N - c.n;
      std::vector<double> PA ((size_t)(N * N), 0.0), PB ((size_t)(N * N), 0.0);
      for (int i = 0; i < c.n; i++)
        for (int j = 0; j < c.n; j++)
          {
            PA[(size_t)((i + off) * N + (j + off))] = c.A[(size_t)(i * c.n + j)];
            PB[(size_t)((i + off) * N + (j + off))] = c.B[(size_t)(i * c.n + j)];
          }

      double ws = 0, wp = 0, wt = 0;
      for (int i = 0; i < N; i++)
        for (int j = 0; j < N; j++)
          {
            double sum = PA[(size_t)(i * N + j)] + PB[(size_t)(i * N + j)];
            double tr = PA[(size_t)(j * N + i)];
            double prod = 0;
            for (int k = 0; k < N; k++)
              prod += PA[(size_t)(i * N + k)] * PB[(size_t)(k * N + j)];
            ws = fmax (ws, fabs ((double)((const float *)r.res_0.data)[i * N + j]
                                 - sum));
            wp = fmax (wp, fabs ((double)((const float *)r.res_1.data)[i * N + j]
                                 - prod));
            wt = fmax (wt, fabs ((double)((const float *)r.res_2.data)[i * N + j]
                                 - tr));
          }
      snprintf (msg, sizeof msg, "%-42s QAdd == A + B", c.nm);
      check (msg, ws < 1e-4);
      snprintf (msg, sizeof msg, "%-42s QMult == A * B", c.nm);
      check (msg, wp < 1e-4);
      snprintf (msg, sizeof msg, "%-42s Transpose == A^T", c.nm);
      check (msg, wt < 1e-4);

      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data) free (r.res_1.data);
      if (r.res_2.data) free (r.res_2.data);
    }
}
#endif
#ifdef TEST_HAM_DV
// ham -- Hamming / 5-smooth numbers by three-way stream merge
// (test/unit/ham.sis).  Ported unchanged; it needed the STRM_APPEND operand-
// order fix, since IF1 wires stream_append VALUE-first and the lowering emitted
// the operands in port order.  No other e2e file uses stream_append.
//
// THE ORACLE IS SMOOTHNESS, not a second merge network: n belongs iff dividing
// out all 2s, 3s and 5s leaves 1.  7 is the discriminating case -- the first
// integer the sequence must SKIP.  The stream ends with the first 5-smooth
// number GREATER than J, because a for-initial also gathers the body value on
// the iteration that fails its test.
static bool ham_is_smooth (int n)
{
  if (n <= 0) return false;
  for (int p : { 2, 3, 5 })
    while (n % p == 0) n /= p;
  return n == 1;
}
static void test_ham_dv (void)
{
  printf ("\n=== Group: ham_dv (5-smooth numbers via stream merge) ===\n");
  for (int J : { 1, 2, 3, 5, 8, 12, 20 })
    {
      std::vector<int32_t> got;
      for (sisal_generator<int32_t> r = func_MAIN (J);
           !sisal_stream_empty_pred (r); r = sisal_stream_rest (r))
        got.push_back (sisal_stream_first<int32_t> (r));

      // reference: the 5-smooth numbers <= J, plus the first one above J
      std::vector<int32_t> expect;
      for (int n = 1;; n++)
        {
          if (!ham_is_smooth (n)) continue;
          expect.push_back (n);
          if (n > J) break;
        }

      char msg[190];
      snprintf (msg, sizeof msg, "J=%-2d yields %d values", J,
                (int)expect.size ());
      check (msg, got.size () == expect.size ());
      snprintf (msg, sizeof msg,
                "J=%-2d values are the 5-smooth numbers in order", J);
      check (msg, got == expect);

      bool all_smooth = true, ascending = true;
      for (size_t i = 0; i < got.size (); i++)
        {
          if (!ham_is_smooth (got[i])) all_smooth = false;
          if (i && got[i] <= got[i - 1]) ascending = false;
        }
      snprintf (msg, sizeof msg,
                "J=%-2d every value is 5-smooth and strictly ascending "
                "(no duplicate survives the merge)",
                J);
      check (msg, all_smooth && ascending);
    }
  // 7 is the point: a merge that failed to skip non-smooth values would emit it
  {
    std::vector<int32_t> got;
    for (sisal_generator<int32_t> r = func_MAIN (8);
         !sisal_stream_empty_pred (r); r = sisal_stream_rest (r))
      got.push_back (sisal_stream_first<int32_t> (r));
    bool has7 = false;
    for (int32_t v : got) if (v == 7) has7 = true;
    check ("J=8 skips 7 (the first non-5-smooth integer)", !has7);
  }
}
#endif
#ifdef TEST_ZBUFFER_DV
// zbuffer -- the z-buffer core of test/unit/zbuffer1.sis.  Per-triangle depth
// maps merged into a frontmost buffer.  See the .sis header for the scope
// (the source's `main` is a renderer needing common.sis) and for why the ragged
// per-scanline rows become a dense rank-2 with a no-coverage sentinel.
//
// THE ORACLE IS THE PLANE EQUATION, not a second scanline walk: depth is
// -(x*a + y*b + d)/c in closed form, coverage is the span test, and the
// frontmost pixel is the GREATEST depth over triangles.  A wrong edge slope,
// span or merge direction changes the answer.
static void test_zbuffer_dv (void)
{
  printf ("\n=== Group: zbuffer_dv (per-triangle depth maps, frontmost merge) ===\n");
  const int X = 6, Y = 6;

  // screen points, indexed from 1
  std::vector<zb_PtRec> pts = { { 0, 0, 0 }, { 1, 1, 0 }, { 5, 1, 0 },
                                { 1, 5, 0 } };
  auto mk_tri = [] (float depth, int lastscan) {
    zb_TriRec t{};
    t.vlo = 1; t.vmid = 2; t.vhi = 3;
    t.mid_scan_line = 1; t.last_scan_line = lastscan;
    t.dxdy_lh = 0.0f; t.dxdy_lm = 4.0f; t.dxdy_mh = -1.0f;
    // plane z = depth  ->  a=0, b=0, c=-1, d=depth
    t.pln = { 0.0f, 0.0f, -1.0f, depth };
    return t;
  };
  // two overlapping triangles at different depths; the FARTHER one is added
  // first, so a merge that replaced unconditionally would leave the wrong one
  std::vector<zb_TriRec> tris = { mk_tri (10.0f, 5), mk_tri (20.0f, 3) };

  sisal_array_t P = sisal_array_alloc_sized (1, 96, pts.size (),
                                             sizeof (zb_PtRec));
  P.lower_bound[0] = 0; P.dims[0] = (int64_t)pts.size ();
  for (size_t i = 0; i < pts.size (); i++) ((zb_PtRec *)P.data)[i] = pts[i];

  sisal_array_t T = sisal_array_alloc_sized (1, 97, tris.size (),
                                             sizeof (zb_TriRec));
  T.lower_bound[0] = 1; T.dims[0] = (int64_t)tris.size ();
  for (size_t i = 0; i < tris.size (); i++) ((zb_TriRec *)T.data)[i] = tris[i];

  sisal_array_t r = func_MAIN (X, Y, P, T);
  check ("frontmost buffer is rank 2, (y_pixels+1) x (x_pixels+1)",
         r.rank == 2 && (int)r.dims[0] == Y + 1 && (int)r.dims[1] == X + 1);

  int covered = 0, bad_depth = 0, bad_tri = 0, bad_empty = 0;
  for (int y = 0; y <= Y; y++)
    for (int x = 0; x <= X; x++)
      {
        const zb_DepthRec d = ((const zb_DepthRec *)r.data)[y * (X + 1) + x];
        // independent coverage + depth, per triangle
        int best_tri = 0;
        double best_depth = -1.0e10;
        for (size_t k = 0; k < tris.size (); k++)
          {
            const zb_TriRec &t = tris[k];
            double xl = pts[t.vlo].xp + t.dxdy_lh * ((double)y - pts[t.vlo].yp);
            double xs = (y <= t.mid_scan_line)
                            ? pts[t.vlo].xp
                                  + t.dxdy_lm * ((double)y - pts[t.vlo].yp)
                            : pts[t.vmid].xp
                                  + t.dxdy_mh * ((double)y - pts[t.vmid].yp);
            double lo = fmin (xl, xs), hi = fmax (xl, xs);
            bool inside = ((double)y >= pts[t.vlo].yp)
                          && (y <= t.last_scan_line) && ((double)x >= lo)
                          && ((double)x <= hi);
            if (!inside) continue;
            double z = -((double)x * t.pln.a + (double)y * t.pln.b + t.pln.d)
                       / t.pln.c;
            if (z > best_depth) { best_depth = z; best_tri = (int)k + 1; }
          }
        if (best_tri != 0)
          {
            covered++;
            if (d.tri != best_tri) bad_tri++;
            if (fabs ((double)d.depth - best_depth) > 1e-4) bad_depth++;
          }
        else if (d.tri != 0)
          bad_empty++;
      }

  char msg[190];
  snprintf (msg, sizeof msg, "%d pixels covered by at least one triangle",
            covered);
  check (msg, covered > 0);
  check ("every covered pixel names the FRONTMOST triangle", bad_tri == 0);
  check ("every covered pixel's depth matches the plane equation",
         bad_depth == 0);
  check ("uncovered pixels keep tri = 0 (sentinel never displaces)",
         bad_empty == 0);

  if (r.data) free (r.data);
  if (P.data) free (P.data);
  if (T.data) free (T.data);
}
#endif
#ifdef TEST_NOISEDUMP_DV
// noisedump -- a 0/1 matrix rendered as a character picture
// (test/unit/noisedump.sis).  Promoted for the OUTPUT TYPE: stream[character],
// which nothing else in e2e uses.  The array side of `character` is still
// miscompiled (arsieve_dv had to switch to integer flags); a character STREAM
// is a different path.
//
// Reference is built from the INPUT matrix, not from the program: 1 -> '*',
// 0 -> ' ', and a newline exactly at each row boundary (the appended 3s).  A
// wrong row length or a dropped catenate puts a newline in the wrong place.
static void test_noisedump_dv (void)
{
  printf ("\n=== Group: noisedump_dv (stream[character] output) ===\n");
  struct Case { int n, m; std::vector<int32_t> v; };
  const std::vector<Case> cases = {
    { 2, 3, { 1, 0, 1, 0, 1, 0 } },
    { 1, 4, { 1, 1, 0, 0 } },
    { 3, 1, { 0, 1, 0 } },
    { 2, 2, { 0, 0, 0, 0 } },
  };
  for (const Case &c : cases)
    {
      sisal_array_t a
          = sisal_array_alloc_empty (2, 6, (uint64_t)(c.n * c.m));
      a.rank = 2; a.dims[0] = c.n; a.dims[1] = c.m;
      a.lower_bound[0] = 1; a.lower_bound[1] = 1;
      for (int i = 0; i < c.n * c.m; i++)
        ((int32_t *)a.data)[i] = c.v[(size_t)i];

      std::string expect;
      for (int i = 0; i < c.n; i++)
        {
          for (int j = 0; j < c.m; j++)
            expect += (c.v[(size_t)(i * c.m + j)] == 1 ? '*' : ' ');
          expect += '\n';
        }

      std::string got;
      for (sisal_generator<char> r = func_MAIN (a);
           !sisal_stream_empty_pred (r); r = sisal_stream_rest (r))
        got += sisal_stream_first<char> (r);

      char msg[190];
      snprintf (msg, sizeof msg,
                "%dx%d picture is %d chars (%d cells + %d newlines)", c.n, c.m,
                c.n * (c.m + 1), c.n * c.m, c.n);
      check (msg, (int)got.size () == c.n * (c.m + 1));
      snprintf (msg, sizeof msg,
                "%dx%d characters match 1->'*' 0->' ' with newlines at row ends",
                c.n, c.m);
      check (msg, got == expect);

      if (a.data) free (a.data);
    }
}
#endif
#ifdef TEST_TAG_SCOPE_DV
// Tag and field scoping -- regression test for b2027f0 / 5db4f55.
//
// Tag names were resolved GLOBALLY across the typemap, so two unions sharing a
// tag name collided: a tagcase on TreeB picked up TreeA's Node arm, was typed
// record{L,R}, found no NE, and lowered the field access as a float.  Merely
// declaring the other union was enough.  `is <tag>` was worse -- any tag of any
// union was accepted for any subject.
//
// Everything here shares names and differs in structure.  The sums are picked
// so a wrong arm changes the ANSWER, not just the shape: SumA walks two
// children (1.5+2.5=4) and SumB four (1+2+3+4=10).
static void test_tag_scope_dv (void)
{
  printf ("\n=== Group: tag_scope_dv (unions/records sharing names) ===\n");
  struct FUNC_MAIN_ts_results r = func_MAIN (0);

  check ("TreeA: tagcase reads L,R -- SumA == 4.0",
         fabs ((double)r.res_0 - 4.0) < 1e-6);
  check ("TreeB: tagcase reads NE,SE,SW,NW (same tag names) -- SumB == 10.0",
         fabs ((double)r.res_1 - 10.0) < 1e-6);
  check ("PtI: integer x,y -- 3 + 4 == 7", r.res_2 == 7);
  check ("PtR: REAL x,y with the same names -- 1.5 + 2.5 == 4.0",
         fabs ((double)r.res_3 - 4.0) < 1e-6);
  check ("PtI3: x,y plus z (a superset of PtI's names) -- 7+8+9 == 24",
         r.res_4 == 24);
  check ("is Leaf(la) on TreeA", r.res_5);
  check ("is Node(ta) on TreeA", r.res_6);
}
#endif
#ifdef TEST_QUADTREE_DV
// quadtree -- matrix to quadtree (test/unit/quadtree.sis), with the row-of-trees
// intermediate as a CONS LIST: array_dv[BTree] is rejected because a recursive
// union has no fixed element size, so BList follows the moldyn_nbrlist_dv idiom.
// See the .sis header for that and for the index-bounds deviation.
//
// THE ORACLE IS THE MERGE RULE.  BtoQTree collapses a node only when NW = SE
// and NE = SW = 0 -- sparse/diagonal, NOT "all four equal".  The uniform and
// diagonal cases below are what distinguish those two readings; zeros-versus-
// distinct alone would pass against the wrong rule.
static void test_quadtree_dv (void)
{
  printf ("\n=== Group: quadtree_dv (recursive unions; rows as a cons list) ===\n");
  auto mk = [] (int n, const std::vector<double> &v) {
    sisal_array_t a = sisal_array_alloc_empty (2, 8, (uint64_t)(n * n));
    a.rank = 2; a.dims[0] = n; a.dims[1] = n;
    a.lower_bound[0] = 1; a.lower_bound[1] = 1;
    for (int i = 0; i < n * n; i++) ((float *)a.data)[i] = (float)v[i];
    return a;
  };
  struct Shape { const char *nm; int depth_is_log2; };
  for (int n : { 2, 3, 4 })
    {
      int log2 = 0, pow2 = 1;
      while (pow2 < n) { log2++; pow2 *= 2; }
      const int pad = pow2 - n;
      char msg[190];

      std::vector<double> zeros ((size_t)(n * n), 0.0);
      std::vector<double> uniform ((size_t)(n * n), 7.0);
      std::vector<double> diag ((size_t)(n * n), 0.0);
      std::vector<double> distinct ((size_t)(n * n));
      for (int i = 0; i < n; i++) diag[i * n + i] = 7.0;
      for (int i = 0; i < n * n; i++) distinct[i] = i + 1;

      struct FUNC_MAIN_qt_results rz = func_MAIN (mk (n, zeros));
      snprintf (msg, sizeof msg,
                "n=%d  Log2 = ceil(log2(n)) = %d and Pad = 2^Log2 - n = %d", n,
                log2, pad);
      check (msg, rz.res_0 == log2 && rz.res_1 == pad);

      snprintf (msg, sizeof msg, "n=%d  all zeros collapse to Depth 0", n);
      check (msg, rz.res_2 == 0);

      // A diagonal collapses ONLY when n is already a power of two.  Padding
      // is prepended (ColumnFiller || row, RowFill || rows), so a 3x3 diagonal
      // lands in the BOTTOM-RIGHT of the 4x4 as diag(0,7,7,7); its NW quadrant
      // is [[0,0],[0,7]], not a uniform scalar, so DiagonalOK fails and the
      // node cannot merge.  Depth is then Log2, exactly as for a dense matrix.
      const bool pow2_n = (pad == 0);
      struct FUNC_MAIN_qt_results rd = func_MAIN (mk (n, diag));
      snprintf (msg, sizeof msg,
                pow2_n ? "n=%d  diagonal collapses to Depth 0 (NW=SE, NE=SW=0)"
                       : "n=%d  PADDED diagonal cannot collapse: shifted to the "
                         "bottom-right, so Depth = Log2",
                n);
      check (msg, rd.res_2 == (pow2_n ? 0 : log2));

      struct FUNC_MAIN_qt_results ru = func_MAIN (mk (n, uniform));
      snprintf (msg, sizeof msg,
                "n=%d  UNIFORM 7 does NOT collapse: Depth = Log2 = %d "
                "(merge is not 'all equal')",
                n, log2);
      check (msg, ru.res_2 == log2);

      struct FUNC_MAIN_qt_results rr = func_MAIN (mk (n, distinct));
      snprintf (msg, sizeof msg, "n=%d  all distinct: Depth = Log2 = %d", n,
                log2);
      check (msg, rr.res_2 == log2);
    }
}
#endif
#ifdef TEST_OUTS_DV
// outs -- quicksort by masked partition (test/unit/outs.sis).  Four levels of
// nested functions (MAIN > SPLIT > MOSHAN > MASHAN, the inner two never called
// but still lowered) and a THREE-OUTPUT masked gather, which the plain-`array`
// path cannot wire.  SPLIT's formal DATA shadows MAIN's at every level -- the
// shape that broke quadrature_dv.
//
// The base case is `size <= 2 returns DATA unchanged`, so this does NOT fully
// sort.  Expected values are derived BY HAND from the spec rather than by
// re-running the algorithm; see the .sis header for the [5,4,3,2,1] derivation.
// Three properties per case, because no one of them is sufficient:
//   permutation  -- catches a dropped or duplicated bucket
//   exact array  -- catches a wrong order that is still a permutation
//   sortedness   -- asserted only where it actually holds
static void test_outs_dv (void)
{
  printf ("\n=== Group: outs_dv (quicksort; 4-deep nesting, 3-output masked gather) ===\n");
  struct Case { std::vector<int32_t> in, expect; bool sorted; const char *why; };
  const std::vector<Case> cases = {
    { { 5, 3, 8, 1, 9, 2, 7 }, { 1, 2, 3, 5, 7, 8, 9 }, true, "sorts fully" },
    { { 1, 2, 3, 4, 5 }, { 1, 2, 3, 4, 5 }, true, "already ordered" },
    { { 5, 4, 3, 2, 1 }, { 2, 1, 3, 4, 5 }, false,
      "base case size<=2 leaves [2,1] unsorted" },
    { { 3, 1 }, { 3, 1 }, false, "size 2 -> returned unchanged" },
    { { 7 }, { 7 }, true, "singleton" },
    { { 4, 4, 2, 9, 4 }, { 2, 4, 4, 4, 9 }, true,
      "equal-key bucket keeps all three 4s" },
  };
  for (const Case &c : cases)
    {
      std::vector<int32_t> in = c.in;
      sisal_array_t a = sisal_array_build_i32 (1, (int)in.size (), in.data ());
      sisal_array_t r = func_MAIN (a);
      std::vector<int32_t> got;
      for (int i = 0; i < (int)r.size; i++)
        got.push_back (((const int32_t *)r.data)[i]);

      char msg[190];
      std::vector<int32_t> sa = c.in, sg = got;
      std::sort (sa.begin (), sa.end ());
      std::sort (sg.begin (), sg.end ());
      snprintf (msg, sizeof msg, "%-18s result is a permutation of the input",
                c.why);
      check (msg, sa == sg);

      snprintf (msg, sizeof msg, "%-18s exact expected array", c.why);
      check (msg, got == c.expect);

      snprintf (msg, sizeof msg, "%-18s sortedness is %s", c.why,
                c.sorted ? "yes" : "no (base case)");
      check (msg, std::is_sorted (got.begin (), got.end ()) == c.sorted);

      if (r.data && r.data != a.data) free (r.data);
      if (a.data) free (a.data);
    }
}
#endif
#ifdef TEST_QUADRATURE_DV
// quadrature -- adaptive-trapezoid integration of x^2+1 (test/unit/quadrature.sis).
// The suite's check on NESTED FUNCTIONS in anger: F/Area/Quad all nested, Quad
// recurses twice per level in one expression, calls its siblings, and its
// Low/High SHADOW Main's parameters of the same name.  That shadowing is what
// broke -- a capture copy-in overwrote the argument, so every recursive call
// re-read Main's bounds and the recursion never terminated.  See the .sis header.
//
// Reference is the CLOSED FORM (x^3/3 + x), not another quadrature rule, and the
// structural check is the sharper of the two: the trapezoid rule OVERESTIMATES a
// convex integrand, and x^2+1 is convex everywhere, so result >= exact must hold
// on every range.  A mis-threaded bound or a truncated recursion breaks that
// inequality even where the magnitude still looks plausible.
static void test_quadrature_dv (void)
{
  printf ("\n=== Group: quadrature_dv (nested + recursive fns; adaptive integration) ===\n");
  struct R { double lo, hi; };
  const R ranges[] = { { 0, 1 },  { 0, 2 }, { -1, 1 },   { 1, 3 },
                       { -2, 2 }, { 0, 0.5 }, { 2, 2 } };
  for (const R &r : ranges)
    {
      float got = func_MAIN ((float)r.lo, (float)r.hi);
      double exact = (r.hi * r.hi * r.hi - r.lo * r.lo * r.lo) / 3.0
                     + (r.hi - r.lo);
      char msg[190];

      snprintf (msg, sizeof msg, "[%5.2f,%5.2f] finite and within tolerance of "
                                 "the closed form", r.lo, r.hi);
      check (msg, std::isfinite (got) && fabs ((double)got - exact) < 2e-3);

      // trapezoid on a CONVEX integrand can only overestimate
      snprintf (msg, sizeof msg,
                "[%5.2f,%5.2f] >= exact (trapezoid overestimates convex)", r.lo,
                r.hi);
      check (msg, (double)got >= exact - 1e-6);
    }
}
#endif
#ifdef TEST_TST_LOOPAT_DV
// tst_loopat_dv -- MULTI-INDEX `at` over a rank-3 array_dv.
//
// `for Elem in Y At I,J,K returns array_dv of Y[I,J,K] * Y[J,I,K]` is the whole
// point: one scatter binding per rank, values only, going all the way to the
// elements.  Until the multi-index `at` work this raised
// Sem_error("Array type expected when constructing scatter node") -- the k-name
// form expanded into k loop axes, each peeling an array layer, which a rank-k
// array_dv (one type layer, rank in the dope) cannot satisfy.
//
// What it pins, none of which the single-index scatters reach:
//   * one DV_SCATTER with ports 0=Elem, 1=I, 2=J, 3=K
//   * DV_GATHER Portmap[index:0;value:1;extent:2;index1:3;index2:4], every
//     index port actually WIRED from the boundary
//   * the element loop over the FLAT size with row-major decomposition of the
//     counter into I,J,K
//   * one extent PER RANK, so the result is rank 3 sized n*n*n -- with a single
//     extent the loop ran size times into a dims[0]-sized buffer, an overrun
//
// Y[I,J,K] * Y[J,I,K] is deliberately NOT symmetric in I and J elementwise, so
// swapping the two index ports changes the answer rather than preserving it.
static void test_tst_loopat_dv (void)
{
  printf ("\n=== Group: tst_loopat_dv (multi-index `at` on a rank-3 array_dv) ===\n");
  for (int n = 2; n <= 4; n++)
    {
      const int N = n * n * n;
      std::vector<double> v ((size_t)N);
      for (int i = 0; i < N; i++) v[i] = 1.0 + i;  // all distinct
      sisal_array_t a = sisal_array_alloc_empty (3, 4, (uint64_t)N);
      a.rank = 3;
      a.dims[0] = n; a.dims[1] = n; a.dims[2] = n;
      a.lower_bound[0] = 1; a.lower_bound[1] = 1; a.lower_bound[2] = 1;
      for (int i = 0; i < N; i++) ((double *)a.data)[i] = v[i];

      sisal_array_t r = func_MAIN (a);
      char msg[190];
      snprintf (msg, sizeof msg,
                "n=%d  result is rank 3, %dx%dx%d (one extent per rank)", n, n,
                n, n);
      check (msg, r.rank == 3 && (int)r.size == N && (int)r.dims[0] == n
                      && (int)r.dims[1] == n && (int)r.dims[2] == n);

      bool ok = ((int)r.size == N);
      for (int i = 0; ok && i < n; i++)
        for (int j = 0; j < n; j++)
          for (int k = 0; k < n; k++)
            {
              double e = v[(i * n + j) * n + k] * v[(j * n + i) * n + k];
              if (fabs (((const double *)r.data)[(i * n + j) * n + k] - e)
                  > 1e-12)
                ok = false;
            }
      snprintf (msg, sizeof msg,
                "n=%d  every element == Y[I,J,K] * Y[J,I,K]", n);
      check (msg, ok);

      if (r.data) free (r.data);
      if (a.data) free (a.data);
    }

}
#endif
#ifdef TEST_GAUSSJNEW_DV
// gaussjnew -- Gauss-Jordan with full row pivoting (test/unit/gaussjnew.sis).
// First of the Gauss/LU cluster and the file that sets the pattern for it.
//
// THE REFERENCE IS THE RESIDUAL, max|Ax - b|, not a transcription of the
// algorithm.  Re-implementing Gauss-Jordan here would agree with any shared
// misunderstanding of it; the residual checks only that the returned x actually
// solves the system -- the property that matters, independent of how x was
// obtained.  The same reference serves the rest of the cluster.
//
// The rank-2 handling is described in the .sis header: rank lives in the dope,
// so OneD and TwoD are both array_dv[double].  Building rank 2 by gathering rows
// is legal -- nested `returns array_dv of (for ... returns array_dv of ...)`
// gives a rank-2 array_dv, not an array of arrays -- so Compute and the
// row-valued pivot swap are the original unchanged.  The one real deviation is
// `for row in A at i`, scatter over rows, which is unsupported.
//
// Case 3 has a ZERO on the diagonal and is unsolvable without the pivot swap,
// so a wrong GetPivot or a wrong swap fails it outright rather than quietly
// degrading accuracy.
static void test_gaussjnew_dv (void)
{
  printf ("\n=== Group: gaussjnew_dv (Gauss-Jordan, checked by residual) ===\n");
  struct Sys { int n; std::vector<double> A, b; const char *nm; };
  const std::vector<Sys> systems = {
    { 2, { 2, 1, 1, 3 }, { 5, 10 }, "2x2" },
    { 3, { 2, 1, -1, -3, -1, 2, -2, 1, 2 }, { 8, -11, -3 }, "3x3 (x = 2,3,-1)" },
    { 3, { 0, 2, 1, 1, 0, 3, 4, 1, 0 }, { 7, 13, 9 },
      "3x3 ZERO on the diagonal -- needs the pivot swap" },
    { 4, { 4, 1, 2, 0, 1, 5, 0, 2, 2, 0, 6, 1, 0, 2, 1, 7 }, { 7, 8, 9, 10 },
      "4x4 SPD (x = 1,1,1,1)" },
    { 3, { 1, 100, 3, 2, 1, 50, 80, 2, 1 }, { 104, 53, 83 },
      "3x3 largest element OFF the diagonal" },
  };
  for (const Sys &s : systems)
    {
      sisal_array_t A = sisal_array_alloc_empty (2, 4, (uint64_t)(s.n * s.n));
      A.rank = 2; A.dims[0] = s.n; A.dims[1] = s.n;
      A.lower_bound[0] = 1; A.lower_bound[1] = 1;
      for (int i = 0; i < s.n * s.n; i++) ((double *)A.data)[i] = s.A[i];
      sisal_array_t B = sisal_array_build_double (1, s.n, s.b.data ());

      sisal_array_t r = func_MAIN (s.n, A, B);
      char msg[190];
      snprintf (msg, sizeof msg, "%-46s solution has %d entries", s.nm, s.n);
      check (msg, (int)r.size == s.n && r.rank == 1);

      bool ok = ((int)r.size == s.n);
      // NaN GUARD, and it is not theoretical: a no-pivot solver on a system
      // with a zero on the diagonal returns all-NaN, and `fmax(worst, nan)`
      // yields the OTHER operand -- so worst stays 0 and the residual check
      // passes an entirely bogus answer.  Require every entry to be finite
      // before the residual means anything.
      for (int j = 0; ok && j < s.n; j++)
        ok = ok && std::isfinite (((const double *)r.data)[j]);
      double worst = 0;
      for (int i = 0; ok && i < s.n; i++)
        {
          double acc = 0;
          for (int j = 0; j < s.n; j++)
            acc += s.A[i * s.n + j] * ((const double *)r.data)[j];
          worst = fmax (worst, fabs (acc - s.b[i]));
        }
      ok = ok && worst < 1e-9;
      snprintf (msg, sizeof msg, "%-46s max|Ax-b| < 1e-9", s.nm);
      check (msg, ok);

      if (r.data) free (r.data);
      if (A.data) free (A.data);
      if (B.data) free (B.data);
    }
}
#endif
#ifdef TEST_CK_YB_DV
// ck_yb -- Y-bucket statistics (test/unit/ck_yb.sis), the last ragged-array
// holdout, ported by the house rule that RAGGED ARRAYS ARE REWRITTEN WITH LISTS
// (backtrack_dv, ml_list_dv).
//
// The original takes `array[array[integer]]`: a Y bucket whose rows are the
// triangles on each scan line, so row lengths vary with the picture.  ck_yb
// never reads a row's CONTENTS though -- only array_size(yb[i]) and
// array_size(yb) -- so the bucket becomes a list of array_dv rows, with the rows
// kept as real array_dvs of their stated length (length 0 being the zero-trip
// gather).  Everything downstream is the original unchanged: same sum, same
// `array_dv of s when s~=0` masked gather, same least/greatest pair.
//
// The bucket is built IN SISAL from a vector of row lengths.  Handing a boxed
// union in from here would test this harness's idea of the representation
// rather than the compiler's.
//
// `width` pins the row ORDER: the list is built by iterating descending and
// consing, so it comes out ascending, and a reversed list would turn {3,2,5,1}
// into {1,5,2,3}.
//
// ZERO-TRIP EDGE: with every row empty, `width` is empty and the min/max loop
// runs zero times.  The identities surface as least -> INT_MAX and greatest ->
// -2147483647 -- note that is NOT INT_MIN.  Both are pinned below.
static void test_ck_yb_dv (void)
{
  printf ("\n=== Group: ck_yb_dv (ragged Y bucket as a list of array_dv rows) ===\n");
  const std::vector<std::vector<int32_t>> cases = {
    { 3, 0, 2, 0, 5, 1 },  // mixed, zeros interspersed, order-sensitive
    { 1, 1, 1, 1 },        // no empty rows
    { 0, 0, 0 },           // ALL empty -> width empty, reductions zero-trip
    { 7 },                 // single row
    { 0, 4 },              // leading empty row
    { 4, 0 },              // trailing empty row
  };
  for (const auto &L : cases)
    {
      std::vector<int32_t> lens = L;
      sisal_array_t a
          = sisal_array_build_i32 (1, (int)lens.size (), lens.data ());
      struct FUNC_MAIN_ckyb_results r = func_MAIN (a);

      long tri = 0; int zer = 0;
      std::vector<int32_t> w;
      for (int32_t s : L)
        { tri += s; if (s != 0) w.push_back (s); else zer++; }

      char msg[190], shape[80]; int off = 0;
      off += snprintf (shape + off, sizeof shape - off, "[");
      for (size_t i = 0; i < L.size () && off < 60; i++)
        off += snprintf (shape + off, sizeof shape - off, "%s%d", i ? "," : "",
                         L[i]);
      snprintf (shape + off, sizeof shape - off, "]");

      snprintf (msg, sizeof msg, "lens=%-16s total triangles == %ld", shape, tri);
      check (msg, r.res_0 == (int32_t)tri);
      snprintf (msg, sizeof msg, "lens=%-16s empty rows == %d", shape, zer);
      check (msg, r.res_1 == zer);

      bool wok = ((int)r.res_4.size == (int)w.size ());
      for (size_t i = 0; wok && i < w.size (); i++)
        wok = wok && ((const int32_t *)r.res_4.data)[i] == w[i];
      snprintf (msg, sizeof msg,
                "lens=%-16s nonzero widths compacted IN ROW ORDER", shape);
      check (msg, wok);

      if (!w.empty ())
        {
          int32_t mn = w[0], mx = w[0];
          for (int32_t v : w) { if (v < mn) mn = v; if (v > mx) mx = v; }
          snprintf (msg, sizeof msg, "lens=%-16s min/max width == %d/%d", shape,
                    mn, mx);
          check (msg, r.res_2 == mn && r.res_3 == mx);
        }
      else
        {
          // zero-trip least/greatest: the identities, and greatest is NOT INT_MIN
          snprintf (msg, sizeof msg,
                    "lens=%-16s zero-trip least/greatest == %d/%d", shape,
                    2147483647, -2147483647);
          check (msg, r.res_2 == 2147483647 && r.res_3 == -2147483647);
        }

      if (r.res_4.data) free (r.res_4.data);
      if (a.data) free (a.data);
    }
}
#endif
#ifdef TEST_NEWSIEVE_DV
// newsieve -- sieve of Eratosthenes over BOOLEAN flags (test/unit/newsieve.sis).
//
// Promoted for the ELEMENT TYPE.  arsieve_dv already covers a sieve, but with
// integer flags; it was promoted that way because the character-flag version is
// miscompiled -- fill and replace write every 4th BYTE of a 1-byte element
// array.  This runs the whole algorithm on array_dv[boolean], making it the
// suite's end-to-end check that the 1-byte path is right: 1-byte fill, 1-byte
// gather build, 1-byte subscript used as a loop guard, and a boolean array
// carried through a for-initial and in and out of a called function.
//
// The flag array is returned alongside the primes (a deliberate deviation from
// the source, which returns only the list).  A wrong boolean LAYOUT could still
// yield a right answer if the compaction read it consistently; checking the
// flags pins elem_bytes == 1 and every slot's value across the C boundary.
//
// Reference is exact primality, computed here.  Verified live: seeding the
// flags all false collapses the output to just [2].
//
// The source covers odd numbers up to 2*max_k+1, which for EVEN n is n+1 -- so
// sieve(100) legitimately ends in 101.  That is the source's index range, and
// the reference models the same range rather than "primes <= n".
static bool newsieve_is_prime (int v)
{
  if (v < 2) return false;
  for (int d = 2; (long)d * d <= v; d++)
    if (v % d == 0) return false;
  return true;
}
static void test_newsieve_dv (void)
{
  printf ("\n=== Group: newsieve_dv (sieve on array_dv[boolean], 1-byte elements) ===\n");
  const int ns[] = { 10, 11, 20, 25, 30, 49, 50, 100, 101 };
  for (int n : ns)
    {
      struct FUNC_MAIN_newsieve_results r = func_MAIN (n);
      const int max_k = (n % 2 == 0) ? n / 2 : (n - 1) / 2;
      char msg[190];

      // the flags: one per odd number 2i+1, i = 1..max_k, ONE BYTE each
      snprintf (msg, sizeof msg,
                "n=%-3d flags are %d booleans at 1 byte each", n, max_k);
      check (msg, (int)r.res_0.size == max_k && r.res_0.rank == 1
                      && r.res_0.elem_bytes == 1);
      bool fok = ((int)r.res_0.size == max_k);
      for (int i = 0; fok && i < max_k; i++)
        fok = fok
              && (((const bool *)r.res_0.data)[i]
                  == newsieve_is_prime (2 * (i + 1) + 1));
      snprintf (msg, sizeof msg,
                "n=%-3d every flag matches primality of 2i+1", n);
      check (msg, fok);

      // the primes: 2, then the surviving odd numbers, via a masked compaction
      std::vector<int> exp{ 2 };
      for (int i = 1; i <= max_k; i++)
        if (newsieve_is_prime (2 * i + 1)) exp.push_back (2 * i + 1);
      snprintf (msg, sizeof msg, "n=%-3d yields %d primes (odds covered up to %d)",
                n, (int)exp.size (), 2 * max_k + 1);
      check (msg, (int)r.res_1.size == (int)exp.size ());
      bool pok = ((int)r.res_1.size == (int)exp.size ());
      for (int i = 0; pok && i < (int)exp.size (); i++)
        pok = pok && ((const int32_t *)r.res_1.data)[i] == exp[i];
      snprintf (msg, sizeof msg,
                "n=%-3d compacted list equals the primes, 2 prepended", n);
      check (msg, pok);

      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data) free (r.res_1.data);
    }
}
#endif
#ifdef TEST_MDFFTGRID_DV
// MdFFTGrid, the multi-factor INVERSE FFT driver (test/unit/MdFFTGrid.sis) --
// the grid-direction dual of mdfftfreq_dv, with the three IFACTg_* butterflies
// and PassGrid inlined so the whole grid-direction stack runs as a composition.
//
// Reference is a naive INVERSE DFT.  The transform reconstructs a real signal
// from nwave complex coefficients assuming Hermitian symmetry, UNSCALED:
//
//   g[j] = X[0].re + sum_{k=1..nwave-1} 2*( X[k].re*cos(2pi jk/n)
//                                          - X[k].im*sin(2pi jk/n) )
//
// read off by probing DC-only and single-bin spectra rather than assumed.  The
// result buffer is (n+1)*2 long; the first n entries are the grid values and
// the tail is zero.
//
// trigs is the BACKWARD table (trigb in InitFFT: +sin, i.e. -SINtheta of the
// negative angle), not the forward one MdFFTFreq takes.  That is load-bearing
// and doubles as the liveness evidence: substituting the forward table breaks
// n=12, 16, 6 and 24 outright.  (n=8 is insensitive to the flip, which is why
// the table was pinned across radices instead of on one size.)
//
// The differences from the frequency direction are the point -- each is a place
// a carry can go wrong that mdfftfreq_dv never reaches:
//   * la GROWS (la3 := old la3 * ifax[old loop - 1]), read from the PREVIOUS
//     factor, where MdFFTFreq divides it down
//   * the loop stops at nfax-1 and a final PassGrid runs after it at inc2=1
//   * the for-initial returns TWO values (la3 and work_la3), a scalar and an
//     array out together
//   * the input spectrum is zero-padded from nwave*2 up to n*2+2 on the way in
static void test_mdfftgrid_dv (void)
{
  printf ("\n=== Group: mdfftgrid_dv (multi-factor inverse FFT vs naive IDFT) ===\n");
  struct Cfg { int n, nfax; int32_t ifax[4]; int nwave; };
  const Cfg cfgs[] = {
    { 8, 2, { 4, 2 }, 4 },       // radix 4 then 2
    { 12, 2, { 4, 3 }, 6 },      // radix 3 present
    { 16, 2, { 4, 4 }, 8 },      // radix 4 twice
    { 6, 2, { 2, 3 }, 3 },       // no radix-4 pass at all
    { 24, 3, { 4, 2, 3 }, 12 },  // three passes, all three radices
    { 32, 3, { 4, 4, 2 }, 16 },  // three passes
    { 16, 2, { 4, 4 }, 3 },      // spectral truncation, nwave << n/2
    { 12, 2, { 4, 3 }, 2 },      // truncation down to two coefficients
    { 8, 2, { 4, 2 }, 2 },       // truncation on the smallest case
  };
  for (const Cfg &cf : cfgs)
    {
      int prod = 1;
      for (int i = 0; i < cf.nfax; i++) prod *= cf.ifax[i];
      char msg[190];
      snprintf (msg, sizeof msg, "n=%-2d ifax product == n (valid factorisation)",
                cf.n);
      check (msg, prod == cf.n);

      std::vector<float> trigs (cf.n), spec (cf.nwave * 2);
      for (int Lp = 1; Lp <= cf.n; Lp++)
        {
          int k = (Lp + 1) / 2;
          double ar = -2.0 * M_PI * (double)(k - 1) / (double)cf.n;
          // BACKWARD table: +sin of the positive angle
          trigs[Lp - 1] = (float)((Lp % 2 == 0) ? -sin (ar) : cos (ar));
        }
      for (int k = 0; k < cf.nwave; k++)
        {
          spec[2 * k] = (float)(1.0 / (k + 1));
          spec[2 * k + 1] = (float)(0.3 * k - 0.2);
        }
      spec[1] = 0.f;  // the DC coefficient must be real

      auto mkf = [&] (const std::vector<float> &src) {
        sisal_array_t a
            = sisal_array_alloc_empty (1, 8, (uint64_t)src.size ());
        a.dims[0] = (int64_t)src.size (); a.lower_bound[0] = 1;
        for (size_t i = 0; i < src.size (); i++) ((float *)a.data)[i] = src[i];
        return a;
      };
      sisal_array_t r
          = func_MAIN (1, cf.nwave, cf.nfax, cf.n,
                       sisal_array_build_i32 (1, cf.nfax, cf.ifax), mkf (trigs),
                       mkf (spec));

      snprintf (msg, sizeof msg,
                "n=%-2d nfax=%d nwave=%-2d -> (n+1)*2 = %d reals, rank 1", cf.n,
                cf.nfax, cf.nwave, (cf.n + 1) * 2);
      check (msg, (int)r.size == (cf.n + 1) * 2 && r.rank == 1);

      bool ok = ((int)r.size == (cf.n + 1) * 2);
      const float *out = (const float *)r.data;
      for (int j = 0; ok && j < cf.n; j++)
        {
          double v = spec[0];
          for (int k = 1; k < cf.nwave; k++)
            {
              double th = 2.0 * M_PI * (double)j * (double)k / (double)cf.n;
              v += 2.0 * (spec[2 * k] * cos (th) - spec[2 * k + 1] * sin (th));
            }
          ok = ok && fabs ((double)out[j] - v) / fmax (1.0, fabs (v)) < 1e-5;
        }
      snprintf (msg, sizeof msg,
                "n=%-2d nfax=%d nwave=%-2d reconstructs the signal (naive IDFT)",
                cf.n, cf.nfax, cf.nwave);
      check (msg, ok);

      bool pad = true;
      for (int i = cf.n; i < (int)r.size; i++) pad = pad && out[i] == 0.f;
      snprintf (msg, sizeof msg, "n=%-2d tail [%d..%d] past the grid is zero",
                cf.n, cf.n + 1, (cf.n + 1) * 2);
      check (msg, pad);

      if (r.data) free (r.data);
    }

  // nfax = 1 is DELIBERATELY pinned to what the source actually does, which is
  // wrong.  The `nfax <= 1` branch calls PassGrid with inc2 = 2, while the
  // multi-factor path's FINAL pass uses inc2 = 1 -- and it is that last pass
  // which un-interleaves the result into contiguous grid values.  With one
  // factor the single pass IS the final pass, so it should use inc2 = 1 too;
  // using 2 leaves the grid at STRIDE 2 with zeros between.
  //
  // This is a bug in test/unit/MdFFTGrid.sis, not in the compiler -- we
  // reproduce it faithfully.  Pinning the stride-2 layout records the deviation
  // instead of hiding it: if the source is ever corrected, this check fails and
  // says so, rather than the case silently going untested.
  {
    const int n = 4, nfax = 1, nwave = 2;
    int32_t ifax[1] = { 4 };
    std::vector<float> trigs (n), spec (nwave * 2);
    for (int Lp = 1; Lp <= n; Lp++)
      {
        int k = (Lp + 1) / 2;
        double ar = -2.0 * M_PI * (double)(k - 1) / (double)n;
        trigs[Lp - 1] = (float)((Lp % 2 == 0) ? -sin (ar) : cos (ar));
      }
    spec[0] = 1.f; spec[1] = 0.f; spec[2] = 0.5f; spec[3] = 0.25f;
    auto mkf = [&] (const std::vector<float> &src) {
      sisal_array_t a = sisal_array_alloc_empty (1, 8, (uint64_t)src.size ());
      a.dims[0] = (int64_t)src.size (); a.lower_bound[0] = 1;
      for (size_t i = 0; i < src.size (); i++) ((float *)a.data)[i] = src[i];
      return a;
    };
    sisal_array_t r
        = func_MAIN (1, nwave, nfax, n, sisal_array_build_i32 (1, nfax, ifax),
                     mkf (trigs), mkf (spec));
    bool ok = ((int)r.size == (n + 1) * 2);
    const float *out = (const float *)r.data;
    for (int j = 0; ok && j < n; j++)
      {
        double v = spec[0];
        for (int k = 1; k < nwave; k++)
          {
            double th = 2.0 * M_PI * (double)j * (double)k / (double)n;
            v += 2.0 * (spec[2 * k] * cos (th) - spec[2 * k + 1] * sin (th));
          }
        // the values are right, but at stride 2, with zeros interleaved
        ok = ok && fabs ((double)out[2 * j] - v) < 1e-5
             && fabs ((double)out[2 * j + 1]) < 1e-5;
      }
    check ("nfax=1 returns the grid at STRIDE 2 (source bug: inc2=2 on the "
           "single pass, should be 1)",
           ok);
    if (r.data) free (r.data);
  }
}
#endif

void
run_active_test (void)
{
#ifdef TEST_PASSFREQ_DV
  test_passfreq_dv ();
#endif
#ifdef TEST_MDFFTFREQ_DV
  test_mdfftfreq_dv ();
#endif
#ifdef TEST_MDFFTGRID_DV
  test_mdfftgrid_dv ();
#endif
#ifdef TEST_NEWSIEVE_DV
  test_newsieve_dv ();
#endif
#ifdef TEST_CK_YB_DV
  test_ck_yb_dv ();
#endif
#ifdef TEST_GAUSSJNEW_DV
  test_gaussjnew_dv ();
#endif
#ifdef TEST_TST_LOOPAT_DV
  test_tst_loopat_dv ();
#endif
#ifdef TEST_QUADRATURE_DV
  test_quadrature_dv ();
#endif
#ifdef TEST_OUTS_DV
  test_outs_dv ();
#endif
#ifdef TEST_QUADTREE_DV
  test_quadtree_dv ();
#endif
#ifdef TEST_TAG_SCOPE_DV
  test_tag_scope_dv ();
#endif
#ifdef TEST_NOISEDUMP_DV
  test_noisedump_dv ();
#endif
#ifdef TEST_ZBUFFER_DV
  test_zbuffer_dv ();
#endif
#ifdef TEST_HAM_DV
  test_ham_dv ();
#endif
#ifdef TEST_QUAD_DV
  test_quad_dv ();
#endif
#ifdef TEST_NEWGAUSS_DV
  test_newgauss_dv ();
#endif
#ifdef TEST_NEWGAUSSJ_DV
  test_newgaussj_dv ();
#endif
#ifdef TEST_MMULT2_DV
  test_mmult2_dv ();
#endif
#ifdef TEST_CYK_DV
  test_cyk_dv ();
#endif
#ifdef TEST_CROSSOVERS_DV
  test_crossovers_dv ();
#endif
#ifdef TEST_NANU_DV
  test_nanu_dv ();
#endif
#if !defined(TEST_PASSFREQ_DV) \
    && !defined(TEST_MDFFTFREQ_DV) \
    && !defined(TEST_MDFFTGRID_DV) \
    && !defined(TEST_NEWSIEVE_DV) \
    && !defined(TEST_CK_YB_DV) \
    && !defined(TEST_GAUSSJNEW_DV) \
    && !defined(TEST_TST_LOOPAT_DV) \
    && !defined(TEST_QUADRATURE_DV) \
    && !defined(TEST_OUTS_DV) \
    && !defined(TEST_QUADTREE_DV) \
    && !defined(TEST_TAG_SCOPE_DV) \
    && !defined(TEST_NOISEDUMP_DV) \
    && !defined(TEST_ZBUFFER_DV) \
    && !defined(TEST_HAM_DV) \
    && !defined(TEST_QUAD_DV) \
    && !defined(TEST_NEWGAUSS_DV) \
    && !defined(TEST_NEWGAUSSJ_DV) \
    && !defined(TEST_MMULT2_DV) \
    && !defined(TEST_CYK_DV) \
    && !defined(TEST_CROSSOVERS_DV) \
    && !defined(TEST_NANU_DV)
  g_no_macro = true;
#endif
}
