// dv_part_17.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: RED_SUM, RED_PRODUCT, RED_GREATEST, RED_LEAST, RED_ARGMAX, RED_ARGMIN, RED_SUM_CROSS, FOR_INITIAL, GAUSSJ_PARTS, GAUSSJ, SWAPLOOP, GEN_EXTENT, BROADCAST_PARTS
#include "dv_harness.h"


#ifdef TEST_FOR_INITIAL
extern "C" int32_t func_FI_SUM (int32_t N);
extern "C" int32_t func_FI_PRODUCT (int32_t N);
extern "C" int32_t func_FI_FINAL_I (int32_t N);
extern "C" int32_t func_FI_PASSTHRU (int32_t N);
extern "C" int32_t func_FI_SWAP (int32_t N);
extern "C" int32_t func_FI_FIB (int32_t N);
extern "C" int32_t func_FI_FIB_A (int32_t N);
extern "C" sisal_array_t func_FI_PARAM_IDENTITY (int32_t N, sisal_array_t Ain);
extern "C" sisal_array_t func_FI_PARAM_BUMP (int32_t N, sisal_array_t Ain);
extern "C" sisal_array_t func_FI_GATHER_ZERO (int32_t N);
extern "C" sisal_array_t func_FI_GATHER_BODY_TEMP (int32_t N);
#endif

// Scalar forall reductions (red_*.sis): each folds a forall body to one
// integer.
#ifdef TEST_RED_SUM
extern "C" int32_t func_MAIN (int32_t N); // value of sum i
#endif
#ifdef TEST_RED_PRODUCT
extern "C" int32_t func_MAIN (int32_t N); // value of product i
#endif
#ifdef TEST_RED_GREATEST
extern "C" int32_t func_MAIN (int32_t N); // value of greatest i*(N+1-i)
#endif
#ifdef TEST_RED_LEAST
extern "C" int32_t func_MAIN (int32_t N); // value of least (i-3)*(i-3)
#endif
#ifdef TEST_RED_ARGMAX
extern "C" int32_t func_MAIN (int32_t N); // value of argmax i*(N+1-i)
#endif
#ifdef TEST_RED_ARGMIN
extern "C" int32_t func_MAIN (int32_t N); // value of argmin i*i-6*i
#endif
#ifdef TEST_RED_SUM_CROSS
extern "C" int32_t func_MAIN (int32_t N,
                              int32_t M); // value of sum i*j over i cross j
#endif

#ifdef TEST_FOR_INITIAL
static void
test_for_initial (void)
{
  printf ("\n=== Group: for_initial (loop-carry semantics; vs C mirrors) ===\n");
  // Fifty-four checks against constants, each with its derivation in a comment.
  // Every one is now a C mirror of the same loop, swept over n so the zero-trip
  // case is one point on a curve rather than a special-cased literal.
  //
  // The mirrors follow the .sis exactly, including that the body increments i
  // FIRST and then reads `old i` -- fi_sum accumulates old s + old i, which is
  // why it sums 1..n and not 0..n-1.
  int bad = 0;
  auto want = [&] (const char *nm, bool ok) { if (!ok) { bad++; printf ("    (failed: %s)\n", nm); } };

  for (int n = 0; n <= 12; n++)
    {
      { int i = 1, sum = 0;
        while (i <= n) { const int oi = i; i = oi + 1; sum = sum + oi; }
        want ("fi_sum", func_FI_SUM (n) == sum); }
      { int i = 1, p = 1;
        while (i <= n) { const int oi = i; i = oi + 1; p = p * oi; }
        want ("fi_product", func_FI_PRODUCT (n) == p); }
      { int i = 1;
        while (i <= n) i = i + 1;
        want ("fi_final_i", func_FI_FINAL_I (n) == i); }
      { int i = 1, k = 42;
        while (i <= n) { i = i + 1; k = k; }
        want ("fi_passthru", func_FI_PASSTHRU (n) == k); }
      // parallel carries: a and b exchange, so a alternates 10, 20, 10, ...
      { int i = 1, a = 10, b = 20;
        while (i <= n) { const int oa = a, ob = b; i = i + 1; a = ob; b = oa; }
        want ("fi_swap", func_FI_SWAP (n) == a); }
      { int i = 1, a = 0, b = 1;
        while (i <= n) { const int oa = a, ob = b; i = i + 1; a = ob; b = oa + ob; }
        want ("fi_fib", func_FI_FIB (n) == a); }
      // fi_fib_a is the POST-TEST form: its body runs at least once, so n = 0
      // gives the first body value rather than the seed
      { int i = 1, a = 0, b = 1;
        do { const int oa = a, ob = b; i = i + 1; a = ob; b = oa + ob; }
        while (i <= n);
        want ("fi_fib_a (post-test: one mandatory trip)", func_FI_FIB_A (n) == a); }
    }
  check ("seven scalar carry forms match their C mirrors for n = 0..12, "
         "zero trip included",
         bad == 0);

  // array-valued carries, with and without a body update
  {
    const std::vector<int32_t> a = { 10, 20, 30 };
    bool ok = true;
    for (int n : { 0, 1, 3 })
      {
        sisal_array_t A = ewref::mki (a);
        sisal_array_t id = func_FI_PARAM_IDENTITY (n, A);
        ok = ok && ((size_t)id.size == a.size ());
        for (size_t k = 0; ok && k < a.size (); k++) ok = (ai (id, (int)k) == a[k]);
        free (A.data);
        if (id.data && id.data != A.data) free (id.data);
      }
    check ("identity array carry returns the input for n = 0, 1, 3", ok);
  }
  {
    // fi_param_bump's body is `for j in 1, n ... old A[j] + 1`, so the inner
    // forall is sized by N and not by array_size(A) -- the same coupling as
    // loopcarry_used.  It is well defined only when n == array_size(Ain):
    //     n < size   shrinks the carry (n = 1 on a 3-element input gives [11])
    //     n > size   reads past the end (n = 4 gives [14,24,34,4], the 4 from
    //                off the end)
    // n > size is excluded as a bad input.  Where they agree, each trip adds
    // one to every element, so the result is a[k] + n.
    bool ok = true;
    for (int n = 1; n <= 5; n++)
      {
        std::vector<int32_t> a;
        for (int k = 0; k < n; k++) a.push_back (10 * (k + 1));
        sisal_array_t A = ewref::mki (a);
        sisal_array_t bp = func_FI_PARAM_BUMP (n, A);
        ok = ok && ((int)bp.size == n);
        for (int k = 0; ok && k < n; k++) ok = (ai (bp, k) == a[k] + n);
        free (A.data);
        if (bp.data && bp.data != A.data) free (bp.data);
      }
    check ("bumping carry adds one per trip, for n = 1..5 with n == size(A)",
           ok);
    // the zero trip returns the seed untouched, at whatever size it came in
    {
      const std::vector<int32_t> a = { 10, 20, 30 };
      sisal_array_t A = ewref::mki (a);
      sisal_array_t bp = func_FI_PARAM_BUMP (0, A);
      bool z = ((size_t)bp.size == a.size ());
      for (size_t k = 0; z && k < a.size (); k++) z = (ai (bp, (int)k) == a[k]);
      check ("n = 0 is the zero trip and returns the seed unchanged", z);
      free (A.data);
      if (bp.data && bp.data != A.data) free (bp.data);
    }
  }

  // gathers: the seed is body_0, so a carry gather is [seed, then each body
  // value] and a zero trip is [seed] alone -- see
  // docs/for_initial_seed_semantics.md
  {
    bool ok = true;
    for (int n = 0; n <= 4; n++)
      {
        std::vector<int32_t> hist = { 1 };     // the seed i := 1
        int i = 1;
        while (i <= n) { i = i + 1; hist.push_back (i); }
        sisal_array_t g = func_FI_GATHER_ZERO (n);
        ok = ok && ((size_t)g.size == hist.size ());
        for (size_t k = 0; ok && k < hist.size (); k++)
          ok = (ai (g, (int)k) == hist[k]);
        if (g.data) free (g.data);
      }
    check ("carry gather == [seed, then each body value], for n = 0..4", ok);
  }
  {
    // k is seeded in INIT and assigned in the body, so it is a CARRY too and
    // its history starts at its own seed (0), not at the first body value
    bool ok = true;
    for (int n = 0; n <= 4; n++)
      {
        std::vector<int32_t> hist = { 0 };     // the seed k := 0
        int i = 1;
        while (i <= n) { i = i + 1; hist.push_back (i); }
        sisal_array_t g = func_FI_GATHER_BODY_TEMP (n);
        ok = ok && ((size_t)g.size == hist.size ());
        for (size_t k = 0; ok && k < hist.size (); k++)
          ok = (ai (g, (int)k) == hist[k]);
        if (g.data) free (g.data);
      }
    check ("a carry seeded in INIT and assigned in the body gathers from ITS "
           "seed (0), not from the first body value",
           ok);
  }
}
#endif

#ifdef TEST_RED_SUM
static void
test_red_sum (void)
{
  printf ("\n=== Group: red_sum (value of sum i) ===\n");
  bool ok = true;
  for (int n = 0; n <= 12; n++)
    {
      int32_t want = 0;
      for (int i = 1; i <= n; i++) want += i;
      ok = ok && (func_MAIN (n) == want);
    }
  check ("sum 1..n for n = 0..12 (n = 0 is the empty sum, identity 0)", ok);
}
#endif

#ifdef TEST_RED_PRODUCT
static void
test_red_product (void)
{
  printf ("\n=== Group: red_product (value of product i) ===\n");
  bool ok = true;
  for (int n = 0; n <= 10; n++)
    {
      int32_t want = 1;
      for (int i = 1; i <= n; i++) want *= i;
      ok = ok && (func_MAIN (n) == want);
    }
  check ("product 1..n for n = 0..10 (n = 0 is the empty product, identity 1)",
         ok);
}
#endif

#ifdef TEST_RED_GREATEST
static void
test_red_greatest (void)
{
  printf ("\n=== Group: red_greatest (value of greatest) ===\n");
  // body is i*(N+1-i), a parabola peaking in the middle
  bool ok = true;
  for (int N = 1; N <= 12; N++)
    {
      int32_t want = INT32_MIN;
      for (int i = 1; i <= N; i++) want = std::max (want, i * (N + 1 - i));
      ok = ok && (func_MAIN (N) == want);
    }
  check ("greatest of i*(N+1-i) for N = 1..12", ok);
}
#endif

#ifdef TEST_RED_LEAST
static void
test_red_least (void)
{
  printf ("\n=== Group: red_least (value of least) ===\n");
  // body is (i-3)^2, whose minimum sits at i = 3 when N >= 3
  bool ok = true;
  for (int N = 1; N <= 12; N++)
    {
      int32_t want = INT32_MAX;
      for (int i = 1; i <= N; i++) want = std::min (want, (i - 3) * (i - 3));
      ok = ok && (func_MAIN (N) == want);
    }
  check ("least of (i-3)^2 for N = 1..12 (minimum inside the range only once "
         "N >= 3)",
         ok);
}
#endif

#ifdef TEST_RED_ARGMAX
static void
test_red_argmax (void)
{
  printf ("\n=== Group: red_argmax (value of argmax) ===\n");
  // argmax returns the INDEX; ties must resolve to the FIRST maximum, which
  // i*(N+1-i) produces whenever N is odd
  bool ok = true;
  int ties = 0;
  for (int N = 1; N <= 12; N++)
    {
      int32_t best = INT32_MIN, want = 1, seen = 0;
      for (int i = 1; i <= N; i++)
        {
          const int32_t v = i * (N + 1 - i);
          if (v > best) { best = v; want = i; seen = 1; }
          else if (v == best) seen++;
        }
      if (seen > 1) ties++;
      ok = ok && (func_MAIN (N) == want);
    }
  check ("argmax of i*(N+1-i) is the FIRST maximum, for N = 1..12", ok);
  check ("...and the sweep includes ties, where first-vs-last would differ",
         ties > 0);
}
#endif

#ifdef TEST_RED_ARGMIN
static void
test_red_argmin (void)
{
  printf ("\n=== Group: red_argmin (value of argmin) ===\n");
  // body is i^2 - 6i, minimised at i = 3
  bool ok = true;
  for (int N = 1; N <= 12; N++)
    {
      int32_t best = INT32_MAX, want = 1;
      for (int i = 1; i <= N; i++)
        { const int32_t v = i * i - 6 * i; if (v < best) { best = v; want = i; } }
      ok = ok && (func_MAIN (N) == want);
    }
  check ("argmin of i^2-6i is the FIRST minimum, for N = 1..12", ok);
}
#endif

#ifdef TEST_RED_SUM_CROSS
static void
test_red_sum_cross (void)
{
  printf ("\n=== Group: red_sum_cross (reduction over a cross) ===\n");
  bool ok = true;
  for (int N = 1; N <= 6; N++)
    for (int M = 1; M <= 6; M++)
      {
        int32_t want = 0;
        for (int i = 1; i <= N; i++)
          for (int j = 1; j <= M; j++) want += i * j;
        ok = ok && (func_MAIN (N, M) == want);
      }
  check ("sum of i*j over the full cross, for 36 (N,M) shapes", ok);
}
#endif

#ifdef TEST_GAUSSJ_PARTS
struct gp_arr2
{
  sisal_array_t res_0, res_1;
};
struct gp_int2
{
  int32_t res_0, res_1;
};
extern "C" int32_t func_IDFAMAX (sisal_array_t A, int32_t N);
extern "C" int32_t func_IDFMAX (sisal_array_t A, int32_t N);
extern "C" gp_arr2 func_GP_TWO (int32_t N, sisal_array_t A);
extern "C" sisal_array_t func_GP_AOR (int32_t N);
extern "C" gp_int2 func_GETPIVOT (int32_t N, sisal_array_t A,
                                  sisal_array_t PIVR);
extern "C" gp_arr2 func_COMPUTE (int32_t N, int32_t PVTROW, sisal_array_t AIN,
                                 sisal_array_t BIN);

static void
test_gaussj_parts (void)
{
  printf ("\n=== Group GJ: gaussj component pieces ===\n");

  // argmax over a row [1,-5,3]: max|.| at idx 2, max at idx 3
  double row[] = { 1.0, -5.0, 3.0 };
  sisal_array_t r = make_double_arr (row, 3);
  check ("idfamax([1,-5,3])=2", func_IDFAMAX (r, 3) == 2);
  check ("idfmax([1,-5,3])=3", func_IDFMAX (r, 3) == 3);
  free (r.data);

  // multi-output 2-array gather: P=A+1, Q=A*2 over [10,20,30]
  double a3[] = { 10.0, 20.0, 30.0 };
  sisal_array_t va = make_double_arr (a3, 3);
  gp_arr2 t = func_GP_TWO (3, va);
  check ("gp_two P[0]=11", ad (t.res_0, 0) == 11.0);
  check ("gp_two P[2]=31", ad (t.res_0, 2) == 31.0);
  check ("gp_two Q[0]=20", ad (t.res_1, 0) == 20.0);
  check ("gp_two Q[2]=60", ad (t.res_1, 2) == 60.0);
  free (va.data);
  free (t.res_0.data);
  free (t.res_1.data);

  // box-then-flatten: array-of-rows -> flat rank-2 [11,12,21,22]
  sisal_array_t ar = func_GP_AOR (2);
  check ("gp_aor rank=2", ar.rank == 2);
  check ("gp_aor size=4", (int)ar.size == 4);
  check ("gp_aor=11 12 21 22", ad (ar, 0) == 11.0 && ad (ar, 1) == 12.0
                                   && ad (ar, 2) == 21.0
                                   && ad (ar, 3) == 22.0);
  free (ar.data);

  // GetPivot on [[0,2],[3,0]], PIVR=[0,0] -> (Icol=1, Irow=2)
  double m[] = { 0, 2, 3, 0 };
  sisal_array_t A2 = make_double_2d (m, 2, 2);
  int32_t pv[] = { 0, 0 };
  sisal_array_t Pv = make_int_arr (pv, 2);
  gp_int2 gp = func_GETPIVOT (2, A2, Pv);
  check ("GetPivot Icol=1", gp.res_0 == 1);
  check ("GetPivot Irow=2", gp.res_1 == 2);
  free (A2.data);
  free (Pv.data);

  // Compute(n=2, pvtrow=1, [[2,4],[1,3]], [2,3]) -> A'=[1,2,0,1], B'=[1,2]
  double cm[] = { 2, 4, 1, 3 };
  sisal_array_t Ac = make_double_2d (cm, 2, 2);
  double cb[] = { 2, 3 };
  sisal_array_t Bc = make_double_arr (cb, 2);
  gp_arr2 c = func_COMPUTE (2, 1, Ac, Bc);
  check ("Compute A'=1 2 0 1", ad (c.res_0, 0) == 1.0 && ad (c.res_0, 1) == 2.0
                                   && ad (c.res_0, 2) == 0.0
                                   && ad (c.res_0, 3) == 1.0);
  check ("Compute B'=1 2", ad (c.res_1, 0) == 1.0 && ad (c.res_1, 1) == 2.0);
  free (Ac.data);
  free (Bc.data);
  free (c.res_0.data);
  free (c.res_1.data);
}
#endif

#ifdef TEST_GAUSSJ
extern "C" sisal_array_t func_MAIN (int32_t N, sisal_array_t A,
                                    sisal_array_t B);
static void
test_gaussj (void)
{
  printf ("\n=== Group GJX: gaussj full solve (gaussj_dv_rr) ===\n");
  // 2x2 swap-forcing [[0,2],[3,0]] b=[4,9] -> x=[3,2]
  {
    double A[] = { 0, 2, 3, 0 }, B[] = { 4, 9 };
    sisal_array_t Aa = make_double_2d (A, 2, 2), Bb = make_double_arr (B, 2);
    sisal_array_t r = func_MAIN (2, Aa, Bb);
    check ("gaussj 2x2 swap x=[3,2]",
           fabs (ad (r, 0) - 3.0) < 1e-9 && fabs (ad (r, 1) - 2.0) < 1e-9);
    free (Aa.data);
    free (Bb.data);
    free (r.data);
  }
  // 2x2 diagonal -> x=[2,3]
  {
    double A[] = { 2, 0, 0, 3 }, B[] = { 4, 9 };
    sisal_array_t Aa = make_double_2d (A, 2, 2), Bb = make_double_arr (B, 2);
    sisal_array_t r = func_MAIN (2, Aa, Bb);
    check ("gaussj 2x2 diag x=[2,3]",
           fabs (ad (r, 0) - 2.0) < 1e-9 && fabs (ad (r, 1) - 3.0) < 1e-9);
    free (Aa.data);
    free (Bb.data);
    free (r.data);
  }
  // 3x3 dense [[2,1,1],[1,3,2],[1,0,0]] b=[4,5,1] -> x=[1,0,2]
  {
    double A[] = { 2, 1, 1, 1, 3, 2, 1, 0, 0 }, B[] = { 4, 5, 1 };
    sisal_array_t Aa = make_double_2d (A, 3, 3), Bb = make_double_arr (B, 3);
    sisal_array_t r = func_MAIN (3, Aa, Bb);
    check ("gaussj 3x3 dense x=[1,0,2]", fabs (ad (r, 0) - 1.0) < 1e-9
                                             && fabs (ad (r, 1) - 0.0) < 1e-9
                                             && fabs (ad (r, 2) - 2.0) < 1e-9);
    free (Aa.data);
    free (Bb.data);
    free (r.data);
  }
  // larger B = A*x round-trip: diagonally dominant, x = 1..n, recover x
  {
    const int n = 12;
    double A[n * n], B[n], x[n];
    for (int i = 0; i < n; i++)
      x[i] = i + 1;
    for (int i = 0; i < n; i++)
      for (int j = 0; j < n; j++)
        A[i * n + j] = (i == j) ? (double)(n + 1) : 1.0;
    for (int i = 0; i < n; i++)
      {
        double s = 0;
        for (int j = 0; j < n; j++)
          s += A[i * n + j] * x[j];
        B[i] = s;
      }
    sisal_array_t Aa = make_double_2d (A, n, n), Bb = make_double_arr (B, n);
    sisal_array_t r = func_MAIN (n, Aa, Bb);
    double e = 0;
    for (int i = 0; i < n; i++)
      {
        double d = fabs (ad (r, i) - x[i]);
        if (d > e)
          e = d;
      }
    check ("gaussj 12x12 B=A*x round-trip (err<1e-9)", e < 1e-9);
    free (Aa.data);
    free (Bb.data);
    free (r.data);
  }
}
#endif

#ifdef TEST_SWAPLOOP
extern "C" sisal_array_t func_MAIN (int32_t N, sisal_array_t A);
static void
test_swaploop (void)
{
  printf (
      "\n=== Group SWAP: in-loop row swap (DV_RANK_REPLACE, aliasing) ===\n");
  double A[] = { 11, 12, 21, 22 };
  {
    sisal_array_t Aa = make_double_2d (A, 2, 2);
    sisal_array_t r = func_MAIN (1, Aa); // one swap
    check ("swaploop n=1 -> 21 22 11 12",
           ad (r, 0) == 21.0 && ad (r, 1) == 22.0 && ad (r, 2) == 11.0
               && ad (r, 3) == 12.0);
    free (Aa.data);
    free (r.data);
  }
  {
    sisal_array_t Aa = make_double_2d (A, 2, 2);
    sisal_array_t r = func_MAIN (2, Aa); // two swaps -> original
    check ("swaploop n=2 -> original (round-trip)",
           ad (r, 0) == 11.0 && ad (r, 1) == 12.0 && ad (r, 2) == 21.0
               && ad (r, 3) == 22.0);
    free (Aa.data);
    free (r.data);
  }
}
#endif

#ifdef TEST_GEN_EXTENT
extern "C" sisal_array_t func_GENEXT_SUB (int32_t n);
extern "C" sisal_array_t func_GENEXT_LB (int32_t n);
extern "C" sisal_array_t func_GENEXT_CROSS (int32_t n, int32_t m);
static void
test_gen_extent (void)
{
  printf ("\n=== Group GE: generator expression-bound lowering ===\n");
  // single-level expr upper bound: i in 1..(n-1).  n=5 -> [1,4,9,16]
  {
    sisal_array_t r = func_GENEXT_SUB (5);
    check ("genext_sub n=5 -> 1 4 9 16",
           (int)r.size == 4 && ai (r, 0) == 1 && ai (r, 1) == 4
               && ai (r, 2) == 9 && ai (r, 3) == 16);
    free (r.data);
  }
  // expr LOWER bound: i in (n-3)..n.  n=6 -> [3,4,5,6]
  {
    sisal_array_t r = func_GENEXT_LB (6);
    check ("genext_lb n=6 -> 3 4 5 6", (int)r.size == 4 && ai (r, 0) == 3
                                           && ai (r, 1) == 4 && ai (r, 2) == 5
                                           && ai (r, 3) == 6);
    free (r.data);
  }
  // cross nest, expr bound on inner axis: i in 1..n, j in 1..(m-1).
  // n=2,m=4 -> rank2 [2,3]: 11 12 13 21 22 23
  {
    sisal_array_t r = func_GENEXT_CROSS (2, 4);
    check ("genext_cross n=2,m=4 rank/dims",
           r.rank == 2 && r.dims[0] == 2 && r.dims[1] == 3);
    check ("genext_cross -> 11 12 13 21 22 23",
           (int)r.size == 6 && ai (r, 0) == 11 && ai (r, 1) == 12
               && ai (r, 2) == 13 && ai (r, 3) == 21 && ai (r, 4) == 22
               && ai (r, 5) == 23);
    free (r.data);
  }
}
#endif

#ifdef TEST_BROADCAST_PARTS
extern "C" int32_t func_BP_RANK (sisal_array_t A);
extern "C" int32_t func_BP_PRODUCT (sisal_array_t S);
extern "C" sisal_array_t func_BP_RESHAPE (sisal_array_t A, sisal_array_t S);
extern "C" int32_t func_BP_OFFSET (sisal_array_t A, int32_t k,
                                   sisal_array_t S);
extern "C" int32_t func_BP_LOAD (sisal_array_t A, int32_t off);
extern "C" sisal_array_t func_BP_BCAST_ADD (sisal_array_t A, sisal_array_t B,
                                            sisal_array_t S, int32_t total);
static void
test_broadcast_parts (void)
{
  printf ("\n=== Group BP: A+B broadcast pieces (bottom-up) ===\n");
  int32_t d1[] = { 1, 2, 3 }, d2[] = { 1, 2, 3, 4, 5, 6 };
  sisal_array_t v3 = make_int_arr (d1, 3);
  sisal_array_t v6 = make_int_arr (d2, 6);
  // Step 0 — rank
  {
    sisal_array_t m = make_int_2d (d2, 2, 3);
    check ("bp_rank([3])=1", func_BP_RANK (v3) == 1);
    check ("bp_rank([2x3])=2", func_BP_RANK (m) == 2);
    free (m.data);
  }
  // Step 1 — product over shape
  {
    int32_t s[] = { 2, 3 }, s2[] = { 2, 3, 4 };
    sisal_array_t S = make_int_arr (s, 2), S2 = make_int_arr (s2, 3);
    check ("bp_product([2,3])=6", func_BP_PRODUCT (S) == 6);
    check ("bp_product([2,3,4])=24", func_BP_PRODUCT (S2) == 24);
    free (S.data);
    free (S2.data);
  }
  // Step 2 — reshape flat[6] by [2,3]
  {
    int32_t s[] = { 2, 3 };
    sisal_array_t S = make_int_arr (s, 2);
    sisal_array_t r = func_BP_RESHAPE (v6, S);
    check ("bp_reshape rank/dims",
           r.rank == 2 && r.dims[0] == 2 && r.dims[1] == 3);
    check ("bp_reshape data 1..6", ai (r, 0) == 1 && ai (r, 1) == 2
                                       && ai (r, 2) == 3 && ai (r, 3) == 4
                                       && ai (r, 4) == 5 && ai (r, 5) == 6);
    // NOTE: reshape aliases the input's data (res = a), so r.data == v6.data
    // -- do NOT free r.data here; v6 is freed once at the end.
    free (S.data);
  }
  // Step 3a — offset (broadcast a [3] across result shape [2,3] -> 0 1 2 0 1
  // 2)
  {
    int32_t a[] = { 10, 20, 30 }, s[] = { 2, 3 };
    sisal_array_t A = make_int_arr (a, 3), S = make_int_arr (s, 2);
    bool ok = true;
    int exp[] = { 0, 1, 2, 0, 1, 2 };
    for (int k = 0; k < 6; k++)
      ok = ok && (func_BP_OFFSET (A, k, S) == exp[k]);
    check ("bp_offset broadcast 0 1 2 0 1 2", ok);
    free (A.data);
    free (S.data);
  }
  // Step 3b — linear load
  {
    int32_t a[] = { 10, 20, 30, 40 };
    sisal_array_t A = make_int_arr (a, 4);
    check ("bp_load(a,0)=10", func_BP_LOAD (A, 0) == 10);
    check ("bp_load(a,2)=30", func_BP_LOAD (A, 2) == 30);
    free (A.data);
  }
  // Step 4 — offset element-wise forall (same-shape + real broadcast)
  {
    int32_t a[] = { 10, 20, 30 }, b[] = { 1, 2, 3 }, s[] = { 3 };
    sisal_array_t A = make_int_arr (a, 3), B = make_int_arr (b, 3),
                  S = make_int_arr (s, 1);
    sisal_array_t r = func_BP_BCAST_ADD (A, B, S, 3);
    check ("bp_bcast_add same-shape -> 11 22 33",
           (int)r.size == 3 && ai (r, 0) == 11 && ai (r, 1) == 22
               && ai (r, 2) == 33);
    free (A.data);
    free (B.data);
    free (S.data);
    free (r.data);
  }
  {
    int32_t a[] = { 1, 2, 3, 4, 5, 6 }, b[] = { 10, 20, 30 }, s[] = { 2, 3 };
    sisal_array_t A = make_int_2d (a, 2, 3), B = make_int_arr (b, 3),
                  S = make_int_arr (s, 2);
    sisal_array_t r = func_BP_BCAST_ADD (A, B, S, 6);
    check ("bp_bcast_add broadcast -> 11 22 33 14 25 36",
           (int)r.size == 6 && ai (r, 0) == 11 && ai (r, 1) == 22
               && ai (r, 2) == 33 && ai (r, 3) == 14 && ai (r, 4) == 25
               && ai (r, 5) == 36);
    free (A.data);
    free (B.data);
    free (S.data);
    free (r.data);
  }
  free (v3.data);
  free (v6.data);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_RED_SUM
  test_red_sum ();
#endif
#ifdef TEST_RED_PRODUCT
  test_red_product ();
#endif
#ifdef TEST_RED_GREATEST
  test_red_greatest ();
#endif
#ifdef TEST_RED_LEAST
  test_red_least ();
#endif
#ifdef TEST_RED_ARGMAX
  test_red_argmax ();
#endif
#ifdef TEST_RED_ARGMIN
  test_red_argmin ();
#endif
#ifdef TEST_RED_SUM_CROSS
  test_red_sum_cross ();
#endif
#ifdef TEST_FOR_INITIAL
  test_for_initial ();
#endif
#ifdef TEST_GAUSSJ_PARTS
  test_gaussj_parts ();
#endif
#ifdef TEST_GAUSSJ
  test_gaussj ();
#endif
#ifdef TEST_SWAPLOOP
  test_swaploop ();
#endif
#ifdef TEST_GEN_EXTENT
  test_gen_extent ();
#endif
#ifdef TEST_BROADCAST_PARTS
  test_broadcast_parts ();
#endif
#if !defined(TEST_RED_SUM) \
    && !defined(TEST_RED_PRODUCT) \
    && !defined(TEST_RED_GREATEST) \
    && !defined(TEST_RED_LEAST) \
    && !defined(TEST_RED_ARGMAX) \
    && !defined(TEST_RED_ARGMIN) \
    && !defined(TEST_RED_SUM_CROSS) \
    && !defined(TEST_FOR_INITIAL) \
    && !defined(TEST_GAUSSJ_PARTS) \
    && !defined(TEST_GAUSSJ) \
    && !defined(TEST_SWAPLOOP) \
    && !defined(TEST_GEN_EXTENT) \
    && !defined(TEST_BROADCAST_PARTS)
  g_no_macro = true;
#endif
}
