// dv_part_10.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: GAUSSJ_PERM_DV, FORINIT_HISTORY_DV, MATMULT_DV, MM_DV, TRANSPOSE_DV, SP_DV, INVERSE_DV, BADFFT_DV, FLOAT_SCATTER_DV, SUB_R3_PERM, SUB_R4_PERM, SUB_R5_PERM, IF_ARRAY_DV, MIX_SCALAR_ARRAY_DV, IF_MULTI_ARRAY_DV, MULTI_ARRAY_IF_DV, UNION_ARRAY_IF_DV, RECORD_E2E, TAGCASE_E2E, COMPLEX_FEATURES_E2E, COMPLEX_OPS_E2E
#include "dv_harness.h"


#ifdef TEST_GAUSSJ_PERM_DV
extern "C" sisal_array_t func_GAUSSJ_PERM(int32_t n, sisal_array_t A, sisal_array_t B);
#endif

#ifdef TEST_FORINIT_HISTORY_DV
extern "C" sisal_array_t func_MAIN(int32_t n);
extern "C" int32_t func_LAST_VAL(int32_t n);
#endif

#ifdef TEST_MATMULT_DV
extern "C" sisal_array_t func_MULTIPLY(int32_t x, int32_t y, int32_t z,
                                        sisal_array_t A, sisal_array_t B);
#endif

#ifdef TEST_MM_DV
extern "C" float func_MAIN(int32_t rowsize);
#endif

#ifdef TEST_TRANSPOSE_DV
extern "C" sisal_array_t func_TRANSPOSE(int32_t n, int32_t m, sisal_array_t A);
#endif

#ifdef TEST_SP_DV
struct FUNC_MAIN_results { int32_t res_0; sisal_array_t res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t n, sisal_array_t A,
                                              sisal_array_t AJ,
                                              sisal_array_t x0,
                                              sisal_array_t g);
#endif

#ifdef TEST_INVERSE_DV
extern "C" sisal_array_t func_FIND_INVERSE(sisal_array_t A, int32_t n);
#endif

#ifdef TEST_BADFFT_DV
extern "C" bool func_MAIN(int32_t m);
#endif

#ifdef TEST_FLOAT_SCATTER_DV
extern "C" sisal_array_t func_F(sisal_array_t v, sisal_array_t w);
#endif

#if defined(TEST_SUB_R3_PERM) || defined(TEST_SUB_R4_PERM) || defined(TEST_SUB_R5_PERM)
extern "C" int32_t func_MAIN(int32_t n);
#endif

#ifdef TEST_IF_ARRAY_DV
extern "C" sisal_array_t func_MAIN(bool flag);
#endif

#ifdef TEST_MIX_SCALAR_ARRAY_DV
// res_2 is FLOAT: the Sisal literal 3.14 is REAL even though the function
// declares double_real (frontend typing quirk).
struct FUNC_MAIN_results { int32_t res_0; sisal_array_t res_1; float res_2; };
extern "C" struct FUNC_MAIN_results func_MAIN(bool flag);
#endif

#ifdef TEST_IF_MULTI_ARRAY_DV
struct FUNC_MAIN_results { sisal_array_t res_0, res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(bool flag);
#endif

#if defined(TEST_MULTI_ARRAY_IF_DV) || defined(TEST_UNION_ARRAY_IF_DV)
struct FUNC_MAIN_results { sisal_array_t res_0, res_1; };
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t n);
#endif
#ifdef TEST_RECORD_E2E
struct FUNC_MAIN_results { int32_t r0; float r1; };
extern "C" struct FUNC_MAIN_results func_MAIN ();
#endif
#ifdef TEST_TAGCASE_E2E
struct FUNC_MAIN_results { float r0; float r1; };
extern "C" struct FUNC_MAIN_results func_MAIN (int32_t SEL, float VAL);
#endif
#ifdef TEST_COMPLEX_FEATURES_E2E
extern "C" float func_MAIN (int32_t SEL, float VAL, int32_t SIZE);
#endif
#ifdef TEST_COMPLEX_OPS_E2E
struct FUNC_MAIN_results { float r0; float r1; float r2; float r3; float r4; float r5; };
extern "C" struct FUNC_MAIN_results func_MAIN (float re1, float im1, float re2, float im2);
#endif
#ifdef TEST_RECORD_E2E
static void
test_record_e2e (void)
{
  printf ("\n=== Group: record_e2e (flat record construct and replace) ===\n");
  struct FUNC_MAIN_results r = func_MAIN ();
  check ("val_x == 84", r.r0 == 84);
  check ("val_y == 3.0", r.r1 == 3.0f);
}
#endif
#ifdef TEST_TAGCASE_E2E
static void
test_tagcase_e2e (void)
{
  printf ("\n=== Group: tagcase_e2e (union match and tagcase selection) ===\n");
  struct FUNC_MAIN_results r1 = func_MAIN (1, 3.14f);
  check ("sel=1, res_0 == 2.0", r1.r0 == 2.0f);
  check ("sel=1, res_1 == 4.0", r1.r1 == 4.0f);

  struct FUNC_MAIN_results r2 = func_MAIN (2, 3.14f);
  check ("sel=2, res_0 == 3.14", fabs(r2.r0 - 3.14f) < 1e-5);
  check ("sel=2, res_1 == 3.14", fabs(r2.r1 - 3.14f) < 1e-5);

  struct FUNC_MAIN_results r3 = func_MAIN (3, 3.14f);
  check ("sel=3, res_0 == 5.0", r3.r0 == 5.0f);
  check ("sel=3, res_1 == 3.0", r3.r1 == 3.0f);
}
#endif
#ifdef TEST_COMPLEX_FEATURES_E2E
static void
test_complex_features_e2e (void)
{
  printf ("\n=== Group: complex_features_e2e (combined conditional, tagcase, for-initial, and for-all) ===\n");
  float r1 = func_MAIN (1, 3.14f, 4);
  check ("sel=1 (for initial sum of 1..4) == 10.0", fabs (r1 - 10.0f) < 1e-5);

  float r2 = func_MAIN (2, 3.14f, 4);
  check ("sel=2 (scalar payload * 2) == 6.28", fabs (r2 - 6.28f) < 1e-5);

  float r3 = func_MAIN (3, 3.14f, 4);
  check ("sel=3 (for all array sum) == 12.56", fabs (r3 - 12.56f) < 1e-5);
}
#endif
#ifdef TEST_COMPLEX_OPS_E2E
static void
test_complex_ops_e2e (void)
{
  printf ("\n=== Group: complex_ops_e2e ===\n");
  struct FUNC_MAIN_results r = func_MAIN (1.5f, 2.5f, 3.0f, -4.0f);
  check ("Add real == 4.5", fabs (r.r0 - 4.5f) < 1e-5);
  check ("Add imag == -1.5", fabs (r.r1 - -1.5f) < 1e-5);
  check ("Mul real == 14.5", fabs (r.r2 - 14.5f) < 1e-5);
  check ("Mul imag == 1.5", fabs (r.r3 - 1.5f) < 1e-5);
  check ("Sum real == 6.0", fabs (r.r4 - 6.0f) < 1e-5);
  check ("Sum imag == 10.0", fabs (r.r5 - 10.0f) < 1e-5);
}
#endif
#ifdef TEST_GAUSSJ_PERM_DV
static void test_gaussj_perm_dv(void) {
    printf("\n=== Group: gaussj_perm_dv (Gauss-Jordan, permutation-free pivoting, float; vs C reference) ===\n");
    // Also the regression test for the for-initial FinalVal ZERO-TRIP bug:
    // find_pivot(N,N,..) never enters its while loop and must return the
    // INIT seed (the MERGE carry), not a zeroed bodycap.
    const int N = 4;
    double Ad[N][N] = {{2,1,-1,3},{-3,-1,2,-11},{-2,1,2,-3},{1,2,3,4}};
    double bd[N]    = {13, -34, -4, 20};
    // reference C: Gaussian elimination, partial pivoting, back-substitution
    double M[N][N+1];
    for (int i=0;i<N;i++){ for(int j=0;j<N;j++) M[i][j]=Ad[i][j]; M[i][N]=bd[i]; }
    for (int k=0;k<N;k++){
        int p=k; for(int i=k+1;i<N;i++) if (fabs(M[i][k])>fabs(M[p][k])) p=i;
        for(int j=0;j<=N;j++){ double t=M[k][j]; M[k][j]=M[p][j]; M[p][j]=t; }
        for(int i=0;i<N;i++) if(i!=k){ double f=M[i][k]/M[k][k];
            for(int j=k;j<=N;j++) M[i][j]-=f*M[k][j]; }
    }
    double ref[N]; for(int i=0;i<N;i++) ref[i]=M[i][N]/M[i][i];
    // inputs are array_dv[real] = FLOAT (tid 8)
    sisal_array_t A = sisal_array_alloc_empty(2, 8, N*N);
    A.dims[0]=N; A.dims[1]=N; A.lower_bound[0]=1; A.lower_bound[1]=1;
    for(int i=0;i<N;i++) for(int j=0;j<N;j++) ((float*)A.data)[i*N+j]=(float)Ad[i][j];
    sisal_array_t B = sisal_array_alloc_empty(1, 8, N);
    for(int i=0;i<N;i++) ((float*)B.data)[i]=(float)bd[i];
    sisal_array_t x = func_GAUSSJ_PERM(N, A, B);
    bool ok = (x.rank == 1 && (int)x.size == N);
    for (int i = 0; ok && i < N; i++)
        ok = fabs(((float*)x.data)[i] - ref[i]) < 1e-4;   // float arithmetic
    check("4x4 solve matches C reference (1e-4)", ok);
    free(A.data); free(B.data); if (x.data) free(x.data);
}
#endif
#ifdef TEST_FORINIT_HISTORY_DV
static void test_forinit_history_dv(void) {
    printf("\n=== Group: forinit_history_dv (1.2 history: seed = body_0 of the gather; vs C reference) ===\n");
    // reference C mirrors the SISAL 1.2 history model: the initial clause is
    // body_0, so the sequence is seed, then each body iteration's value.
    {
        const int n = 13;
        int32_t ref[16]; int cnt = 0;
        int i = 10;
        ref[cnt++] = i;                    // body_0: the seed
        while (i < n) { i = i + 1; ref[cnt++] = i; }
        sisal_array_t r = func_MAIN(n);
        bool ok = ((int)r.size == cnt);
        for (int k = 0; ok && k < cnt; k++) ok = (((int32_t*)r.data)[k] == ref[k]);
        check("n=13: gather = [10,11,12,13] (seed included)", ok);
        if (r.data) free(r.data);
    }
    {
        sisal_array_t r = func_MAIN(10);   // guard false on entry: zero body trips
        bool ok = ((int)r.size == 1 && ((int32_t*)r.data)[0] == 10);
        check("n=10 zero-trip: gather = [seed]", ok);
        if (r.data) free(r.data);
    }
    {
        // value-of zero-trip pin (was gaussj_perm's find_pivot(N,N) case
        // before its if-guard rewrite): reference C mirrors the history
        // model -- the seed, then a doubling per body iteration.
        int32_t ref0 = 42;                 // n=0: body never runs -> seed
        int32_t ref3;
        { int i = 42, k = 1; while (k <= 3) { k++; i *= 2; } ref3 = i; }
        check("value-of zero-trip = seed (42)", func_LAST_VAL(0) == ref0);
        check("value-of n=3 = last body value", func_LAST_VAL(3) == ref3);
    }
}
#endif
#ifdef TEST_MATMULT_DV
static void test_matmult_dv(void) {
    printf("\n=== Group: matmult_dv (rank-2 dv matmul across a call boundary; vs C reference) ===\n");
    const int X=2, Y=3, Z=2;
    double Av[X*Y] = {1,2,3, 4,5,6};
    double Bv[Y*Z] = {7,8, 9,10, 11,12};
    // reference C implementation
    double ref[X*Z];
    for (int i=0;i<X;i++) for (int j=0;j<Z;j++) {
        double s=0; for (int k=0;k<Y;k++) s += Av[i*Y+k]*Bv[k*Z+j];
        ref[i*Z+j]=s;
    }
    sisal_array_t A = sisal_array_alloc_empty(2, 4, X*Y);
    A.dims[0]=X; A.dims[1]=Y;
    for (int i=0;i<X*Y;i++) ((double*)A.data)[i]=Av[i];
    sisal_array_t B = sisal_array_alloc_empty(2, 4, Y*Z);
    B.dims[0]=Y; B.dims[1]=Z;
    for (int i=0;i<Y*Z;i++) ((double*)B.data)[i]=Bv[i];
    sisal_array_t r = func_MULTIPLY(X, Y, Z, A, B);
    bool ok = ((int)r.size == X*Z);
    for (int i=0;ok&&i<X*Z;i++) ok = fabs(((double*)r.data)[i]-ref[i])<1e-12;
    check("2x3 * 3x2 matches C reference", ok);
    free(A.data); free(B.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_MM_DV
static void test_mm_dv(void) {
    printf("\n=== Group: mm_dv (dv matmul of constant matrices; vs C reference) ===\n");
    const int n = 5;
    // reference C: every entry of the product is sum of n 1.1*1.1 terms (float)
    float acc = 0; for (int i=0;i<n;i++) acc += 1.1f*1.1f;
    check("rmc[1,1] matches C reference", fabsf(func_MAIN(n) - acc) < 1e-5f);
}
#endif
#ifdef TEST_TRANSPOSE_DV
static void test_transpose_dv(void) {
    printf("\n=== Group: transpose_dv (rank-2 dv transpose by permuted read; vs C reference) ===\n");
    const int N=2, M=3;
    double Av[N*M] = {1,2,3, 4,5,6};
    // reference C implementation
    double ref[M*N];
    for (int i=0;i<M;i++) for (int j=0;j<N;j++) ref[i*N+j] = Av[j*M+i];
    sisal_array_t A = sisal_array_alloc_empty(2, 4, N*M);
    A.dims[0]=N; A.dims[1]=M;
    for (int i=0;i<N*M;i++) ((double*)A.data)[i]=Av[i];
    sisal_array_t r = func_TRANSPOSE(N, M, A);
    bool ok = (r.rank==2 && (int)r.dims[0]==M && (int)r.dims[1]==N);
    for (int i=0;ok&&i<M*N;i++) ok = (((double*)r.data)[i]==ref[i]);
    check("2x3 -> 3x2, elements a[i,j]=b[j,i]", ok);
    free(A.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_SP_DV
static void test_sp_dv(void) {
    printf("\n=== Group: sp_dv (sparse matvec, 10 repeat-until iterations; vs C reference) ===\n");
    const int n = 5;
    float Av[4*n]; int32_t AJv[4*n]; float x0v[n], gv[n];
    for (int k=0;k<4;k++) for (int i=0;i<n;i++) {
        Av[k*n+i]  = 0.1f*(k+1) + 0.01f*i;
        AJv[k*n+i] = (i + k) % n + 1;          // 1-based column index
    }
    for (int i=0;i<n;i++) { x0v[i]=1.0f+i; gv[i]=0.5f*i; }
    // reference C: 10 iterations of x = g + sum_k A[k,i]*x[AJ[k,i]]
    float x[n], xn[n]; for (int i=0;i<n;i++) x[i]=x0v[i];
    for (int it=0;it<10;it++) {
        for (int i=0;i<n;i++) {
            float ax=0; for (int k=0;k<4;k++) ax += Av[k*n+i]*x[AJv[k*n+i]-1];
            xn[i]=gv[i]+ax;
        }
        for (int i=0;i<n;i++) x[i]=xn[i];
    }
    sisal_array_t A = sisal_array_alloc_empty(2, 8, 4*n);
    A.dims[0]=4; A.dims[1]=n;
    for (int i=0;i<4*n;i++) ((float*)A.data)[i]=Av[i];
    sisal_array_t AJ = sisal_array_alloc_empty(2, 6, 4*n);
    AJ.dims[0]=4; AJ.dims[1]=n;
    for (int i=0;i<4*n;i++) ((int32_t*)AJ.data)[i]=AJv[i];
    sisal_array_t x0 = sisal_array_alloc_empty(1, 8, n);
    for (int i=0;i<n;i++) ((float*)x0.data)[i]=x0v[i];
    sisal_array_t g = sisal_array_alloc_empty(1, 8, n);
    for (int i=0;i<n;i++) ((float*)g.data)[i]=gv[i];
    FUNC_MAIN_results r = func_MAIN(n, A, AJ, x0, g);
    bool ok = (r.res_0 == 10 && (int)r.res_1.size == n);
    for (int i=0;ok&&i<n;i++)
        ok = fabsf(((float*)r.res_1.data)[i]-x[i]) < 1e-3f * fabsf(x[i]);
    check("ncount=10 and final x matches C reference (rel 1e-3, float)", ok);
    free(A.data); free(AJ.data); free(x0.data); free(g.data);
    if (r.res_1.data) free(r.res_1.data);
}
#endif
#ifdef TEST_INVERSE_DV
static void test_inverse_dv(void) {
    printf("\n=== Group: inverse_dv (Gauss-Jordan matrix inverse, full pivoting, rank-2 dv; vs C reference) ===\n");
    const int N = 4;
    double Ad[N][N] = {{4,2,1,3},{2,5,2,1},{1,2,6,2},{3,1,2,7}};
    // reference C: Gauss-Jordan inverse with partial pivoting, in double
    double M[N][2*N];
    for (int i=0;i<N;i++) { for (int j=0;j<N;j++) M[i][j]=Ad[i][j];
        for (int j=0;j<N;j++) M[i][N+j] = (i==j) ? 1.0 : 0.0; }
    for (int k=0;k<N;k++) {
        int p=k; for (int i=k+1;i<N;i++) if (fabs(M[i][k])>fabs(M[p][k])) p=i;
        for (int j=0;j<2*N;j++) { double t=M[k][j]; M[k][j]=M[p][j]; M[p][j]=t; }
        double d = M[k][k];
        for (int j=0;j<2*N;j++) M[k][j] /= d;
        for (int i=0;i<N;i++) if (i!=k) {
            double f=M[i][k];
            for (int j=0;j<2*N;j++) M[i][j] -= f*M[k][j];
        }
    }
    sisal_array_t A = sisal_array_alloc_empty(2, 8, N*N);
    A.dims[0]=N; A.dims[1]=N; A.lower_bound[0]=1; A.lower_bound[1]=1;
    for (int i=0;i<N;i++) for (int j=0;j<N;j++) ((float*)A.data)[i*N+j]=(float)Ad[i][j];
    sisal_array_t r = func_FIND_INVERSE(A, N);
    bool ok = (r.rank == 2 && (int)r.size == N*N);
    for (int i=0;i<N && ok;i++) for (int j=0;j<N && ok;j++)
        ok = fabs(((float*)r.data)[i*N+j] - M[i][N+j]) < 1e-4;
    check("4x4 inverse matches C reference (1e-4, float)", ok);
    free(A.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_FLOAT_SCATTER_DV
static void test_float_scatter_dv(void) {
    printf("\n=== Group: float_scatter_dv (element scatter over array_dv[real]; vs C reference) ===\n");
    float vv[2] = {1.5f, 2.5f}, wv[1] = {10.0f};
    sisal_array_t v = sisal_array_alloc_empty(1, 8, 2);
    ((float*)v.data)[0] = vv[0]; ((float*)v.data)[1] = vv[1];
    sisal_array_t w = sisal_array_alloc_empty(1, 8, 1);
    ((float*)w.data)[0] = wv[0];
    sisal_array_t r = func_F(v, w);
    // reference C: g(x) = x + 1; r[i] = v[i] + 1 + w[1]
    bool ok = ((int)r.size == 2);
    for (int i = 0; i < 2 && ok; i++)
        ok = fabsf(((float*)r.data)[i] - (vv[i] + 1.0f + wv[0])) < 1e-6f;
    check("g(vel) + w[1] over float elements matches C reference", ok);
    free(v.data); free(w.data); if (r.data) free(r.data);
}
#endif
#ifdef TEST_BADFFT_DV
static void test_badfft_dv(void) {
    printf("\n=== Group: badfft_dv (Cooley-Tukey FFT over array_dv[complex record]; analytic reference) ===\n");
    // The .sis main is self-checking against the ANALYTIC reference: for the
    // signal sin(j*pi/8) of length n = 2^m, |F| at bins n/16 and n - n/16 is
    // exactly n/2.  Verified against OSC 13.0.3 (original badfft.sis -> T).
    for (int m = 4; m <= 7; m++) {
        char label[64];
        snprintf(label, sizeof label, "m=%d (n=%d): FFT peaks = n/2", m, 1 << m);
        check(label, func_MAIN(m));
    }
}
#endif
#ifdef TEST_SUB_R3_PERM
static void test_sub_r3_perm(void) {
    printf("\n=== Group: sub_r3_perm (rank-3 permuted subscript a[i,j,k]=b[k,j,i]; vs C reference) ===\n");
    // reference C: b[i,j,k] = i*100+j*10+k; a[1,2,3] = b[3,2,1]
    int32_t ref = 3*100 + 2*10 + 1;
    check("a[1,2,3] == b[3,2,1]", func_MAIN(3) == ref);
}
#endif
#ifdef TEST_SUB_R4_PERM
static void test_sub_r4_perm(void) {
    printf("\n=== Group: sub_r4_perm (rank-4 two-source permute; vs C reference) ===\n");
    // reference C: b[i,j,k,l]=i*1000+j*100+k*10+l; c[..]=i+j+k+l;
    // a[1,2,1,2] = b[2,1,1,2] + c[1,2,2,1]
    int32_t ref = (2*1000 + 1*100 + 1*10 + 2) + (1 + 2 + 2 + 1);
    check("a[1,2,1,2] == b[2,1,1,2] + c[1,2,2,1]", func_MAIN(2) == ref);
}
#endif
#ifdef TEST_SUB_R5_PERM
static void test_sub_r5_perm(void) {
    printf("\n=== Group: sub_r5_perm (rank-5 full index reverse; vs C reference) ===\n");
    // reference C: b[i,j,k,l,m]=i*10000+j*1000+k*100+l*10+m; a[1,2,3,1,2]=b[2,1,3,2,1]
    int32_t ref = 2*10000 + 1*1000 + 3*100 + 2*10 + 1;
    check("a[1,2,3,1,2] == b[2,1,3,2,1]", func_MAIN(3) == ref);
}
#endif
#ifdef TEST_IF_ARRAY_DV
static void test_if_array_dv(void) {
    printf("\n=== Group: test_if_array_dv (IF arms return dv literals) ===\n");
    sisal_array_t a = func_MAIN(true), b = func_MAIN(false);
    int32_t refa[3] = {1,2,3}, refb[3] = {4,5,6};
    bool ok = ((int)a.size == 3 && (int)b.size == 3);
    for (int i = 0; i < 3 && ok; i++)
        ok = (((int32_t*)a.data)[i] == refa[i] && ((int32_t*)b.data)[i] == refb[i]);
    check("then [1,2,3] / else [4,5,6]", ok);
    if (a.data) free(a.data);
    if (b.data) free(b.data);
}
#endif
#ifdef TEST_MIX_SCALAR_ARRAY_DV
static void test_mix_scalar_array_dv(void) {
    printf("\n=== Group: test_mix_scalar_array_dv (IF returning scalar + dv + real) ===\n");
    FUNC_MAIN_results a = func_MAIN(true), b = func_MAIN(false);
    int32_t refa[3] = {1,2,3};
    bool ok = (a.res_0 == 42 && (int)a.res_1.size == 3
               && fabsf(a.res_2 - 3.14f) < 1e-6f);
    for (int i = 0; i < 3 && ok; i++) ok = (((int32_t*)a.res_1.data)[i] == refa[i]);
    ok = ok && b.res_0 == 0 && (int)b.res_1.size == 1
         && ((int32_t*)b.res_1.data)[0] == 0 && b.res_2 == 0.0f;
    check("then (42,[1,2,3],3.14) / else (0,[0],0.0)", ok);
    if (a.res_1.data) free(a.res_1.data);
    if (b.res_1.data) free(b.res_1.data);
}
#endif
#ifdef TEST_IF_MULTI_ARRAY_DV
static void test_if_multi_array_dv(void) {
    printf("\n=== Group: test_if_multi_array_dv (IF returning dvi + dvd) ===\n");
    FUNC_MAIN_results a = func_MAIN(true), b = func_MAIN(false);
    int32_t refi[3] = {1,2,3};   double refd[3] = {1.1, 2.2, 3.3};
    int32_t refi2[2] = {10,20};  double refd2[2] = {10.1, 20.2};
    bool ok = ((int)a.res_0.size == 3 && (int)a.res_1.size == 3
               && (int)b.res_0.size == 2 && (int)b.res_1.size == 2);
    // 1e-5 tolerance: double literals are currently emitted through FLOAT
    // precision (the C printer suffixes every literal with 'f'), so 20.2d0
    // arrives as (double)20.2f = 20.200001.
    for (int i = 0; i < 3 && ok; i++)
        ok = (((int32_t*)a.res_0.data)[i] == refi[i]
              && fabs(((double*)a.res_1.data)[i] - refd[i]) < 1e-5);
    for (int i = 0; i < 2 && ok; i++)
        ok = (((int32_t*)b.res_0.data)[i] == refi2[i]
              && fabs(((double*)b.res_1.data)[i] - refd2[i]) < 1e-5);
    check("then ([1,2,3],[1.1,2.2,3.3]) / else ([10,20],[10.1,20.2])", ok);
    if (a.res_0.data) free(a.res_0.data);
    if (a.res_1.data) free(a.res_1.data);
    if (b.res_0.data) free(b.res_0.data);
    if (b.res_1.data) free(b.res_1.data);
}
#endif
#ifdef TEST_MULTI_ARRAY_IF_DV
static void test_multi_array_if_dv(void) {
    printf("\n=== Group: test_multi_array_if_dv (forall with IF body, dvd + dvi outputs; vs C reference) ===\n");
    const int n = 6;
    // reference C implementation
    double refd[n]; int32_t refi[n];
    for (int i = 1; i <= n; i++) {
        refd[i-1] = (i % 2 == 0) ? i * 1.5 : i * 0.5;
        refi[i-1] = i * i;
    }
    FUNC_MAIN_results r = func_MAIN(n);
    bool ok = ((int)r.res_0.size == n && (int)r.res_1.size == n);
    for (int i = 0; i < n && ok; i++)
        ok = (fabs(((double*)r.res_0.data)[i] - refd[i]) < 1e-9
              && ((int32_t*)r.res_1.data)[i] == refi[i]);
    check("dvd = i*1.5/i*0.5 and dvi = i*i match C reference", ok);
    if (r.res_0.data) free(r.res_0.data);
    if (r.res_1.data) free(r.res_1.data);
}
#endif
#ifdef TEST_UNION_ARRAY_IF_DV
static void test_union_array_if_dv(void) {
    printf("\n=== Group: test_union_array_if_dv (array_dv of tagged unions; vs C reference) ===\n");
    // ABI of the emitted union_un_<N>: {int32 tag; union {int32 I; double D};}
    // tag values: I-arm = 95, D-arm = 94 (see the emitted enum).
    struct un { int32_t tag; union { int32_t I; double D; } val; };
    const int n = 6;
    FUNC_MAIN_results r = func_MAIN(n);
    bool ok = ((int)r.res_0.size == n && (int)r.res_1.size == n
               && r.res_1.elem_bytes == sizeof(struct un));
    for (int i = 1; i <= n && ok; i++) {
        // reference C: even i -> 1.5*i and union[i: i]; odd -> 0.5*i and union[d: i]
        double refd = (i % 2 == 0) ? i * 1.5 : i * 0.5;
        ok = fabs(((double*)r.res_0.data)[i-1] - refd) < 1e-9;
        struct un u = ((struct un*)r.res_1.data)[i-1];
        if (ok) {
            if (i % 2 == 0) ok = (u.tag == 95 && u.val.I == i);
            else            ok = (u.tag == 94 && fabs(u.val.D - (double)i) < 1e-9);
        }
    }
    check("dvd values + union tags/payloads match C reference", ok);
    if (r.res_0.data) free(r.res_0.data);
    if (r.res_1.data) free(r.res_1.data);
}
#endif

void
run_active_test (void)
{
#ifdef TEST_GAUSSJ_PERM_DV
  test_gaussj_perm_dv ();
#endif
#ifdef TEST_FORINIT_HISTORY_DV
  test_forinit_history_dv ();
#endif
#ifdef TEST_MATMULT_DV
  test_matmult_dv ();
#endif
#ifdef TEST_MM_DV
  test_mm_dv ();
#endif
#ifdef TEST_TRANSPOSE_DV
  test_transpose_dv ();
#endif
#ifdef TEST_SP_DV
  test_sp_dv ();
#endif
#ifdef TEST_INVERSE_DV
  test_inverse_dv ();
#endif
#ifdef TEST_BADFFT_DV
  test_badfft_dv ();
#endif
#ifdef TEST_FLOAT_SCATTER_DV
  test_float_scatter_dv ();
#endif
#ifdef TEST_SUB_R3_PERM
  test_sub_r3_perm ();
#endif
#ifdef TEST_SUB_R4_PERM
  test_sub_r4_perm ();
#endif
#ifdef TEST_SUB_R5_PERM
  test_sub_r5_perm ();
#endif
#ifdef TEST_IF_ARRAY_DV
  test_if_array_dv ();
#endif
#ifdef TEST_MIX_SCALAR_ARRAY_DV
  test_mix_scalar_array_dv ();
#endif
#ifdef TEST_IF_MULTI_ARRAY_DV
  test_if_multi_array_dv ();
#endif
#ifdef TEST_MULTI_ARRAY_IF_DV
  test_multi_array_if_dv ();
#endif
#ifdef TEST_UNION_ARRAY_IF_DV
  test_union_array_if_dv ();
#endif

#ifdef TEST_RECORD_E2E
  test_record_e2e ();
#endif
#ifdef TEST_TAGCASE_E2E
  test_tagcase_e2e ();
#endif
#ifdef TEST_COMPLEX_FEATURES_E2E
  test_complex_features_e2e ();
#endif
#ifdef TEST_COMPLEX_OPS_E2E
  test_complex_ops_e2e ();
#endif
#if !defined(TEST_GAUSSJ_PERM_DV) \
    && !defined(TEST_FORINIT_HISTORY_DV) \
    && !defined(TEST_MATMULT_DV) \
    && !defined(TEST_MM_DV) \
    && !defined(TEST_TRANSPOSE_DV) \
    && !defined(TEST_SP_DV) \
    && !defined(TEST_INVERSE_DV) \
    && !defined(TEST_BADFFT_DV) \
    && !defined(TEST_FLOAT_SCATTER_DV) \
    && !defined(TEST_SUB_R3_PERM) \
    && !defined(TEST_SUB_R4_PERM) \
    && !defined(TEST_SUB_R5_PERM) \
    && !defined(TEST_IF_ARRAY_DV) \
    && !defined(TEST_MIX_SCALAR_ARRAY_DV) \
    && !defined(TEST_IF_MULTI_ARRAY_DV) \
    && !defined(TEST_MULTI_ARRAY_IF_DV) \
    && !defined(TEST_UNION_ARRAY_IF_DV) \
    && !defined(TEST_RECORD_E2E) \
    && !defined(TEST_TAGCASE_E2E) \
    && !defined(TEST_COMPLEX_FEATURES_E2E) \
    && !defined(TEST_COMPLEX_OPS_E2E)
  g_no_macro = true;
#endif
}
