// dv_part_09.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: SIMPSON, MINMAX_DV, INSERTION1_DV, MESORT_DV, FOR_ALL_ARGMAX, TUPLE_MIXED3, RECORD1, UNION1, TUPLE_MIXED2, UNION0, TUPLE_ADD_DV, IDIV, FORALL_SIMPLE_DV, FORALL_DOT_DV
#include "dv_harness.h"

#ifdef TEST_SIMPSON
extern "C" float func_SIMPSON(float A, float B, int32_t N);
#endif
#ifdef TEST_MINMAX_DV
struct FUNC_MAIN_results {   // imin, iamin, imax, iamax (1-based indices)
  int32_t res_0;
  int32_t res_1;
  int32_t res_2;
  int32_t res_3;
};
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t N, sisal_array_t X);
#endif
#ifdef TEST_INSERTION1_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t INPUT);
#endif
#ifdef TEST_MESORT_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t X);
#endif
#ifdef TEST_FOR_ALL_ARGMAX
extern "C" int32_t func_MAIN(int32_t X);
#endif
#ifdef TEST_TUPLE_MIXED3
struct FUNC_TUPLEMIXED_results {
  int32_t res_0;
  float res_1;
};
extern "C" struct FUNC_TUPLEMIXED_results func_TUPLEMIXED(int32_t X);
#endif
#ifdef TEST_RECORD1
struct struct_rec_96 { float R; };
struct struct_rec_98 { struct struct_rec_96 L; float S; };
extern "C" struct struct_rec_98 func_MAIN(void);
#endif
#ifdef TEST_UNION1
extern "C" float func_MAIN(float X, float EPS);
#endif
#ifdef TEST_TUPLE_MIXED2
struct FUNC_TUPLEMIXED_results {
  int32_t res_0;
  float res_1;
};
extern "C" struct FUNC_TUPLEMIXED_results func_TUPLEMIXED(void);
#endif
#ifdef TEST_UNION0
struct FUNC_MAIN_results { bool res_0; bool res_1; bool res_2; };
extern "C" struct FUNC_MAIN_results func_MAIN(int32_t X, float Y, sisal_array_t Z);
#endif
#ifdef TEST_TUPLE_ADD_DV
extern "C" sisal_array_t func_TUPLE_ADD(sisal_array_t A, sisal_array_t B);
#endif
#ifdef TEST_IDIV
extern "C" int32_t func_IDIV(int32_t A, int32_t B);
#endif
#ifdef TEST_FORALL_SIMPLE_DV
extern "C" sisal_array_t func_MAIN(sisal_array_t A);
#endif
#ifdef TEST_FORALL_DOT_DV
extern "C" int32_t func_MAIN(sisal_array_t A, sisal_array_t B);
#endif
#ifdef TEST_SIMPSON
// Simpson's 1/3 rule over sin on [a,b], n panels — reference mirrors the
// exact summation order in double, float-tolerance compare.
static void test_simpson(void) {
    printf("\n=== Group: simpson (Simpson integration of sin) ===\n");
    double a = 0.0, b = 3.141592653589793; int n = 64;
    double delta = (b - a) / n;
    double s_odd = 0, s_even = 0;
    for (int i = 1; i <= (n + 1) / 2; i++) s_odd += sin(a + (2*(i-1)+1) * delta);
    for (int i = 1; i <= n / 2; i++)       s_even += sin(a + (2*i) * delta);
    double ref = (sin(a) + sin(b) + 4.0*s_odd + 2.0*s_even) * delta / 3.0;
    float got = func_SIMPSON((float)a, (float)b, n);
    check("simpson(0, pi, 64) == reference (~2.0)", fabs(got - ref) < 1e-4);
}
#endif
#ifdef TEST_MINMAX_DV
// First-occurrence argmin/argmax (plain and |.|), 1-based; C mirror.
static void test_minmax_dv(void) {
    printf("\n=== Group: minmax_dv (argmin/argmax first occurrence) ===\n");
    double v[8] = { 3.0, -7.0, 2.0, 9.0, -7.0, 0.5, 9.0, -1.0 };
    int n = 8;
    int imin=1, iamin=1, imax=1, iamax=1;
    for (int k = 2; k <= n; k++) {
        if (v[k-1] < v[imin-1]) imin = k;
        if (fabs(v[k-1]) < fabs(v[iamin-1])) iamin = k;
        if (v[k-1] > v[imax-1]) imax = k;
        if (fabs(v[k-1]) > fabs(v[iamax-1])) iamax = k;
    }
    sisal_array_t X = sisal_array_alloc_empty(1, 4, n);
    for (int i = 0; i < n; i++) ((double*)X.data)[i] = v[i];
    struct FUNC_MAIN_results r = func_MAIN(n, X);
    check("minmax imin == C reference",  r.res_0 == imin);
    check("minmax iamin == C reference", r.res_1 == iamin);
    check("minmax imax == C reference",  r.res_2 == imax);
    check("minmax iamax == C reference", r.res_3 == iamax);
    free(X.data);
}
#endif
#ifdef TEST_INSERTION1_DV
// Insertion sort via multi-value replace swaps; C reference sorts a copy.
static void test_insertion1_dv(void) {
    printf("\n=== Group: insertion1_dv (insertion sort, dv swaps) ===\n");
    double v[9] = { 5.5, -2.0, 9.25, 0.0, 3.5, 3.5, -8.75, 1.0, 7.0 };
    int n = 9;
    double ref[9];
    for (int i = 0; i < n; i++) ref[i] = v[i];
    for (int i = 1; i < n; i++) {           // reference insertion sort
        double x = ref[i]; int j = i - 1;
        while (j >= 0 && ref[j] > x) { ref[j+1] = ref[j]; j--; }
        ref[j+1] = x;
    }
    sisal_array_t in = sisal_array_alloc_empty(1, 4, n);
    for (int i = 0; i < n; i++) ((double*)in.data)[i] = v[i];
    sisal_array_t out = func_MAIN(in);
    bool ok = ((int)out.size == n);
    for (int i = 0; ok && i < n; i++)
        ok = (((double*)out.data)[i] == ref[i]);
    check("insertion1 sorts to C-reference order", ok);
    free(in.data);
    if (out.data && out.data != in.data) free(out.data);
}
#endif
#ifdef TEST_MESORT_DV
// Batcher merge-exchange sort; reference = C qsort on a copy.
static int cmp_i32(const void* a, const void* b) {
    int32_t x = *(const int32_t*)a, y = *(const int32_t*)b;
    return (x > y) - (x < y);
}
static void test_mesort_dv(void) {
    printf("\n=== Group: mesort_dv (Batcher merge-exchange sort) ===\n");
    int32_t v[16] = { 9, -3, 14, 0, 7, 7, -12, 5, 3, 3, 22, -1, 8, 2, 6, 1 };
    int n = 16;   // power of two exercises every stage
    int32_t ref[16];
    for (int i = 0; i < n; i++) ref[i] = v[i];
    qsort(ref, n, sizeof(int32_t), cmp_i32);
    sisal_array_t X = sisal_array_alloc_empty(1, 6, n);
    for (int i = 0; i < n; i++) ((int32_t*)X.data)[i] = v[i];
    sisal_array_t out = func_MAIN(X);
    bool ok = ((int)out.size == n);
    for (int i = 0; ok && i < n; i++) ok = (((int32_t*)out.data)[i] == ref[i]);
    check("mesort(16 mixed ints) == qsort reference", ok);
    free(X.data);
    if (out.data && out.data != X.data) free(out.data);
}
#endif
#ifdef TEST_FOR_ALL_ARGMAX
// argmax reduction: val = 10 - i over i in 1..10 maximizes at i = 1.
static void
test_for_all_argmax (void)
{
  printf ("\n=== Group: for_all_argmax (argmax reduction) ===\n");
  // the body is 10 - i over i = 1..10, so the maximum is at i = 1; the
  // reference scans for the first maximum rather than asserting the answer
  int want = 1, best = 10 - 1;
  for (int i = 2; i <= 10; i++)
    if (10 - i > best) { best = 10 - i; want = i; }
  check ("argmax of (10 - i) over i = 1..10 == the first maximum",
         func_MAIN (0) == want);
}
#endif
#ifdef TEST_TUPLE_MIXED3
// THE historic tuple slot-1 bug pin: #(A,B) := #(X, 3.14) mis-bound B to
// slot 0 and returned (11, 20.0) instead of (11, 6.28).  Fixed by the
// parallel-copy binder (tuple items unpack by port).
static void test_tuple_mixed3(void) {
    printf("\n=== Group: tuple_mixed3 (tuple destructure slots) ===\n");
    struct FUNC_TUPLEMIXED_results r = func_TUPLEMIXED(10);
    check("A + 1 == 11", r.res_0 == 11);
    check("B * 2.0 == 6.28 (slot-1 payload, not slot-0)", fabs(r.res_1 - 6.28f) < 1e-5);
}
#endif
#ifdef TEST_RECORD1
// nested-record replace: {L:{R:0.2}, S:3.14} replace [l.r:3.2; s:1.23]
static void test_record1(void) {
    printf("\n=== Group: record1 (nested record replace) ===\n");
    struct struct_rec_98 r = func_MAIN();
    check("bb.L.R replaced to 3.2", fabs(r.L.R - 3.2f) < 1e-6);
    check("bb.S replaced to 1.23", fabs(r.S - 1.23f) < 1e-6);
}
#endif
#ifdef TEST_UNION1
// until-loop Newton sqrt; reference mirrors the exact float iteration.
static void test_union1(void) {
    printf("\n=== Group: union1 (until-loop Newton sqrt + is-tests) ===\n");
    float x = 2.0f, eps = 1e-4f;
    float root = x / 2.0f;
    do { root = (x / root + root) / 2.0f; } while (!((x - root * root) < eps));
    float got = func_MAIN(x, eps);
    check("newton-until sqrt(2) == mirrored float iteration", fabs(got - root) < 1e-6);
}
#endif
#ifdef TEST_TUPLE_MIXED2
static void test_tuple_mixed2(void) {
    printf("\n=== Group: tuple_mixed2 (all-literal tuple destructure) ===\n");
    struct FUNC_TUPLEMIXED_results r = func_TUPLEMIXED();
    check("#(A,B) := #(1, 2.0) gives (1, 2.0)",
          r.res_0 == 1 && fabs(r.res_1 - 2.0f) < 1e-6);
}
#endif
#ifdef TEST_UNION0
// is-tag tests on freshly built unions of all three payload kinds
// (int, real, array_dv) -> all true.
static void test_union0(void) {
    printf("\n=== Group: union0 (is-tests over three union tags) ===\n");
    sisal_array_t z = sisal_array_alloc_empty(1, 6, 2);
    ((int32_t*)z.data)[0] = 4; ((int32_t*)z.data)[1] = 5;
    struct FUNC_MAIN_results r = func_MAIN(7, 2.5f, z);
    check("is a(union[a:x]) == true", r.res_0);
    check("is b(union[b:y]) == true", r.res_1);
    check("is d(union[d:z]) == true", r.res_2);
    free(z.data);
}
#endif
#ifdef TEST_TUPLE_ADD_DV
// broadcasting elementwise add: equal sizes zip; a 1-element side splats.
static void
test_tuple_add_dv (void)
{
  printf ("\n=== Group: tuple_add_dv (elementwise add with splat) ===\n");
  // equal sizes add elementwise; a size-1 operand on either side splats
  auto run = [&] (const std::vector<float> &a, const std::vector<float> &b) {
    sisal_array_t A = ewref::mkf (a), B = ewref::mkf (b);
    sisal_array_t r = func_TUPLE_ADD (A, B);
    const size_t n = std::max (a.size (), b.size ());
    bool ok = ((size_t)r.size == n);
    for (size_t k = 0; ok && k < n; k++)
      {
        const float u = a.size () == 1 ? a[0] : a[k];
        const float v = b.size () == 1 ? b[0] : b[k];
        ok = near_f (af (r, (int)k), u + v);
      }
    free (A.data); free (B.data); if (r.data) free (r.data);
    return ok; };
  check ("equal sizes add elementwise",
         run ({ 1, 2, 3, -4 }, { 10, 20, 30, 0.5f }));
  check ("size-1 LEFT operand splats across the right",
         run ({ 5 }, { 10, 20, 30, -1 }));
  check ("size-1 RIGHT operand splats across the left",
         run ({ 1, 2, 3, -4 }, { 5 }));
}
#endif
#ifdef TEST_IDIV
// integer division semantics incl. negatives (truncation toward zero)
static void test_idiv(void) {
    printf("\n=== Group: idiv (integer division semantics) ===\n");
    check("7/2 == 3",   func_IDIV(7, 2) == 3);
    check("-7/2 == -3 (truncate toward zero)", func_IDIV(-7, 2) == -3);
    check("7/-2 == -3", func_IDIV(7, -2) == -3);
    check("-7/-2 == 3", func_IDIV(-7, -2) == 3);
}
#endif
#if defined(TEST_FORALL_SIMPLE_DV) || defined(TEST_FORALL_CROSS_DV) || defined(TEST_FORALL_DOT_DV)
static sisal_array_t mk_i32v(const int32_t* v, int n) {
    sisal_array_t a = sisal_array_alloc_empty(1, 6, n);
    for (int i = 0; i < n; i++) ((int32_t*)a.data)[i] = v[i];
    return a;
}
#endif
#ifdef TEST_FORALL_SIMPLE_DV
static void
test_forall_simple_dv (void)
{
  printf ("\n=== Group: forall_simple_dv (map x*2) ===\n");
  const std::vector<int32_t> a = { 1, 5, -3, 7, 0, -12 };
  sisal_array_t A = ewref::mki (a);
  sisal_array_t r = func_MAIN (A);
  check ("map == x*2 elementwise (negatives and zero included)",
         ewref::binary_i (r, a, [] (int32_t x) { return x * 2; }));
  free (A.data);
  if (r.data && r.data != A.data) free (r.data);
}
#endif
#ifdef TEST_FORALL_DOT_DV
static void
test_forall_dot_dv (void)
{
  printf ("\n=== Group: forall_dot_dv (dot generator + sum reduction) ===\n");
  bool ok = true;
  for (int n : { 1, 3, 6 })
    {
      std::vector<int32_t> a, b;
      for (int i = 0; i < n; i++) { a.push_back (i * 2 - 3); b.push_back (5 - i); }
      const int32_t want = laref::ref_dot (a, b);
      sisal_array_t A = ewref::mki (a), B = ewref::mki (b);
      ok = ok && (func_MAIN (A, B) == want);
      free (A.data); free (B.data);
    }
  check ("dot == sum a[i]*b[i] for n = 1, 3, 6 with signed entries", ok);
}
#endif

void
run_active_test (void)
{
#ifdef TEST_SIMPSON
  test_simpson ();
#endif
#ifdef TEST_MINMAX_DV
  test_minmax_dv ();
#endif
#ifdef TEST_INSERTION1_DV
  test_insertion1_dv ();
#endif
#ifdef TEST_MESORT_DV
  test_mesort_dv ();
#endif
#ifdef TEST_FOR_ALL_ARGMAX
  test_for_all_argmax ();
#endif
#ifdef TEST_TUPLE_MIXED3
  test_tuple_mixed3 ();
#endif
#ifdef TEST_RECORD1
  test_record1 ();
#endif
#ifdef TEST_UNION1
  test_union1 ();
#endif
#ifdef TEST_TUPLE_MIXED2
  test_tuple_mixed2 ();
#endif
#ifdef TEST_UNION0
  test_union0 ();
#endif
#ifdef TEST_TUPLE_ADD_DV
  test_tuple_add_dv ();
#endif
#ifdef TEST_IDIV
  test_idiv ();
#endif
#ifdef TEST_FORALL_SIMPLE_DV
  test_forall_simple_dv ();
#endif
#ifdef TEST_FORALL_DOT_DV
  test_forall_dot_dv ();
#endif
#if !defined(TEST_SIMPSON) \
    && !defined(TEST_MINMAX_DV) \
    && !defined(TEST_INSERTION1_DV) \
    && !defined(TEST_MESORT_DV) \
    && !defined(TEST_FOR_ALL_ARGMAX) \
    && !defined(TEST_TUPLE_MIXED3) \
    && !defined(TEST_RECORD1) \
    && !defined(TEST_UNION1) \
    && !defined(TEST_TUPLE_MIXED2) \
    && !defined(TEST_UNION0) \
    && !defined(TEST_TUPLE_ADD_DV) \
    && !defined(TEST_IDIV) \
    && !defined(TEST_FORALL_SIMPLE_DV) \
    && !defined(TEST_FORALL_DOT_DV)
  g_no_macro = true;
#endif
}
