// dv_part_03.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: LET_SEQ_BIND, XFA_B2_COND, AGGREGATE_ADD, AREA, MULTIDECL, LOOPCARRY_USED, LOOPCARRY_IDENTITY, SUB_MATMUL, PI, TEST_MIX_ARRAY_DV, TST_LOOP1_DV, LOOP2_INNER, LOOP1_DV
#include "dv_harness.h"

#ifdef TEST_LET_SEQ_BIND
extern "C" int32_t func_MAIN (); // sequential let -> 25
#endif
#ifdef TEST_XFA_B2_COND
extern "C" sisal_array_t func_MAIN (int32_t N,
                                    int32_t M); // if inside forall cross body
#endif
#ifdef TEST_AGGREGATE_ADD
extern "C" sisal_array_t
func_VECTORADD_CPU (sisal_array_t A, sisal_array_t B); // real vector add
#endif
#ifdef TEST_AREA
extern "C" float func_MAIN (float start, float finish,
                            int32_t gran); // Riemann sum of x^2+1
#endif
#ifdef TEST_MULTIDECL
struct MULTIDECL_results
{
  double res_0;
  int32_t res_1;
};
extern "C" struct MULTIDECL_results
func_MAIN (); // returns (double, integer) reordered
#endif
#ifdef TEST_LOOPCARRY_USED
extern "C" sisal_array_t
func_MAIN (int32_t N, sisal_array_t AIN); // double array_dv carry, x2/iter
#endif
#ifdef TEST_LOOPCARRY_IDENTITY
extern "C" sisal_array_t
func_MAIN (int32_t N, sisal_array_t AIN,
           sisal_array_t BIN); // parallel multi-carry, returns B
#endif
#ifdef TEST_SUB_MATMUL
extern "C" int32_t
func_MAIN (int32_t N); // matmul via 2-D subscripts, read C[1,1]
#endif
#ifdef TEST_PI
extern "C" float func_MAIN (int32_t Cycles); // Leibniz pi (for-initial) * 4
#endif
#ifdef TEST_TEST_MIX_ARRAY_DV
struct MIX_ARRAY_DV_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct MIX_ARRAY_DV_results
func_MAIN (int32_t N); // (array of i, array_dv of i*10)
#endif
#ifdef TEST_TST_LOOP1_DV
extern "C" sisal_array_t func_MAIN (int32_t N, double Q, double R, double T,
                                    sisal_array_t Y,
                                    sisal_array_t Z); // for K in Y -> K+K
#endif
#ifdef TEST_LOOP2_INNER
extern "C" sisal_array_t
func_MAIN (int32_t IPNT, int32_t IPNTP, sisal_array_t V,
           sisal_array_t X); // loop2 inner for-initial
#endif

// ---- Livermore loop kernels (array_dv), each vs an independent C reference
// ----
#ifdef TEST_LOOP1_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, double Q, double R,
                                    double T, sisal_array_t Y,
                                    sisal_array_t Z); // hydro fragment
#endif

#ifdef TEST_LET_SEQ_BIND
static void
test_let_seq_bind (void)
{
  printf ("\n=== Group: let_seq_bind (sequential let) ===\n");
  // Base=5; Doubled=10; Tripled=15; -> 25
  check ("Doubled+Tripled=25", func_MAIN () == 25);
}
#endif

#ifdef TEST_XFA_B2_COND
// for i in 1,n cross j in 1,m returns array_dv of (if i<j then i else j)
static void
test_xfa_b2_cond (void)
{
  printf ("\n=== Group: xfa_b2_cond (if inside a forall cross body; vs min) ===\n");
  // the body is min(i, j) over i in 1..R cross j in 1..C; the expected 2x3
  // table used to be written out
  bool ok = true;
  for (int R : { 1, 2, 4 })
    for (int C = 1; C <= 4; C++)
      {
        sisal_array_t r = func_MAIN (R, C);
        ok = ok && (r.rank == 2) && ((int)r.dims[0] == R) && ((int)r.dims[1] == C);
        for (int i = 1; ok && i <= R; i++)
          for (int j = 1; ok && j <= C; j++)
            ok = (ai (r, (i - 1) * C + (j - 1)) == std::min (i, j));
        if (r.data) free (r.data);
      }
  check ("body == min(i,j) over 12 shapes, both branches of the if taken", ok);
}
#endif

#ifdef TEST_AGGREGATE_ADD
static void
test_aggregate_add (void)
{
  printf ("\n=== Group: aggregate_add (real vector add; vs a + b) ===\n");
  std::vector<float> a, b;
  for (int i = 0; i < 9; i++) { a.push_back (1.5f * i - 4.0f); b.push_back (10.0f - 2.5f * i); }
  sisal_array_t A = ewref::mkf (a), B = ewref::mkf (b);
  sisal_array_t r = func_VECTORADD_CPU (A, B);
  check ("vadd == a[i] + b[i] over 9 elements incl. negatives",
         r.rank == 1 && ewref::binary_f (r, a, b, [] (float u, float v) { return u + v; }));
  free (A.data); free (B.data);
  if (r.data) free (r.data);
}
#endif

#ifdef TEST_AREA
// Left-Riemann sum of x^2+1 over [start,finish] in `gran` steps; -> integral
// as gran grows.
static void
test_area (void)
{
  printf ("\n=== Group: area (real Riemann sum) ===\n");
  // integral_1^2 (x^2+1) dx = 10/3; integral_0^1 = 4/3
  check ("area(1,2,100000) ~ 3.3333",
         fabs (func_MAIN (1.0f, 2.0f, 100000) - 3.33333f) < 1e-3f);
  check ("area(0,1,10000)  ~ 1.3333",
         fabs (func_MAIN (0.0f, 1.0f, 10000) - 1.33333f) < 1e-2f);
}
#endif

#ifdef TEST_MULTIDECL
// GetValues() = (10, double(3.14159f)); Main returns (y,x) = (3.14159, 10)
// reordered.
static void
test_multidecl (void)
{
  printf ("\n=== Group: multidecl (mixed multi-result, reordered) ===\n");
  struct MULTIDECL_results r = func_MAIN ();
  check ("multidecl res_0 ~ 3.14159", fabs (r.res_0 - 3.14159) < 1e-4);
  check ("multidecl res_1 = 10", r.res_1 == 10);
}
#endif

#ifdef TEST_LOOPCARRY_USED
// array_dv[double] carried through `for initial`: each iter doubles every
// element; n iters -> x2^n.
static void
test_loopcarry_used (void)
{
  printf ("\n=== Group: loopcarry_used (array carry doubled per iteration) ===\n");
  // The body is `A := for i in 1, n returns array_dv of old A[i] * 2.0`, so the
  // inner forall is sized by N, NOT by array_size(A).  The program is therefore
  // only well defined when n == array_size(Ain):
  //     n < size   silently SHRINKS the carry (n = 1 on a 3-element input
  //                returns a single element)
  //     n > size   reads past the end -- measured [16,32,48,0] for n = 4 on a
  //                3-element input, the 0 coming from off the end
  // n > size is excluded as a bad input rather than pinned.  Where n == size
  // the carry is a * 2^n, which is what is checked, and n = 0 is the zero trip
  // that returns the seed untouched.
  bool ok = true;
  for (int n = 1; n <= 5; n++)
    {
      std::vector<double> a;
      for (int k = 0; k < n; k++) a.push_back (1.0 + 0.5 * k);
      double scale = 1.0;
      for (int t = 0; t < n; t++) scale *= 2.0;
      sisal_array_t A = ewref::mkd (a);
      sisal_array_t r = func_MAIN (n, A);
      ok = ok && (r.rank == 1) && ((int)r.size == n);
      for (int k = 0; ok && k < n; k++) ok = near_d (ad (r, k), a[k] * scale);
      free (A.data);
      if (r.data && r.data != A.data) free (r.data);
    }
  check ("carry == a * 2^n for n = 1..5, with n == array_size(A)", ok);

  // zero trip: the seed is body_0, so `value of A` is Ain untouched
  {
    const std::vector<double> a = { 1.0, -2.0, 3.5 };
    sisal_array_t A = ewref::mkd (a);
    sisal_array_t r = func_MAIN (0, A);
    bool z = ((size_t)r.size == a.size ());
    for (size_t k = 0; z && k < a.size (); k++) z = near_d (ad (r, (int)k), a[k]);
    check ("n = 0 is the zero trip and returns the seed unchanged", z);
    free (A.data);
    if (r.data && r.data != A.data) free (r.data);
  }
}
#endif

#ifdef TEST_LOOPCARRY_IDENTITY
// Parallel multi-carry A,B := old A, old B; returns B unchanged.
static void
test_loopcarry_identity (void)
{
  printf ("\n=== Group: loopcarry_identity (parallel multi-carry -> B) ===\n");
  // the identity carry returns B unchanged; compared against B itself rather
  // than a copy of B's literal values
  const std::vector<double> a = { 1.0, 2.0, 3.0 }, b = { 10.0, -20.0, 30.5 };
  bool ok = true;
  for (int n : { 0, 1, 4 })
    {
      sisal_array_t A = ewref::mkd (a), B = ewref::mkd (b);
      sisal_array_t r = func_MAIN (n, A, B);
      ok = ok && (r.rank == 1) && ((size_t)r.size == b.size ());
      for (size_t k = 0; ok && k < b.size (); k++) ok = near_d (ad (r, (int)k), b[k]);
      // the result ALIASES B (no copy is made), so free B only via the alias
      free (A.data);
      if (r.data && r.data != B.data) { free (r.data); free (B.data); }
      else free (B.data);
    }
  check ("identity carry returns B unchanged, for n = 0, 1, 4", ok);
}
#endif

#ifdef TEST_SUB_MATMUL
static void
test_sub_matmul (void)
{
  printf ("\n=== Group: sub_matmul (matmul via 2-D subscripts; vs C) ===\n");
  // A[i,k] = i+k, B[k,j] = k*j, and the program returns C[1,1];
  // the reference contracts the same way rather than asserting the n = 2 value
  bool ok = true;
  for (int n = 1; n <= 6; n++)
    {
      int32_t want = 0;
      for (int k = 1; k <= n; k++) want += (1 + k) * (k * 1);
      ok = ok && (func_MAIN (n) == want);
    }
  check ("C[1,1] == sum_k (1+k)*k for n = 1..6", ok);
}
#endif

#ifdef TEST_PI
static void
test_pi (void)
{
  printf ("\n=== Group: pi (Leibniz for-initial) ===\n");
  check ("pi(100000) ~ 3.14159", fabs (func_MAIN (100000) - 3.14159f) < 1e-3f);
}
#endif

#ifdef TEST_TEST_MIX_ARRAY_DV
// for i in 1,N returns (array of i) AND (array_dv of i*10) — mixed plain+dv
// outputs.
static void
test_test_mix_array_dv (void)
{
  printf (
      "\n=== Group: test_mix_array_dv (mixed plain + array_dv outputs) ===\n");
  struct MIX_ARRAY_DV_results r = func_MAIN (3);
  bool ok0 = ((int)r.res_0.size == 3);
  for (int k = 0; ok0 && k < 3; k++)
    ok0 = ok0 && (((int32_t *)r.res_0.data)[k] == k + 1);
  bool ok1 = ((int)r.res_1.size == 3);
  for (int k = 0; ok1 && k < 3; k++)
    ok1 = ok1 && (((int32_t *)r.res_1.data)[k] == (k + 1) * 10);
  check ("mix res_0 = [1,2,3]", ok0);
  check ("mix res_1 = [10,20,30]", ok1);
}
#endif

#ifdef TEST_TST_LOOP1_DV
// Hydro fragment: for K in Y returns array_dv of K+K (scatter over a double
// array).
static void
test_tst_loop1_dv (void)
{
  printf ("\n=== Group: tst_loop1_dv (scatter for K in Y -> K+K) ===\n");
  const std::vector<double> y = { 1.0, -2.5, 3.0, 0.0, 7.25 };
  sisal_array_t Y = ewref::mkd (y), Z = ewref::mkd (y);
  sisal_array_t r = func_MAIN ((int)y.size (), 0.0, 0.0, 0.0, Y, Z);
  bool ok = (r.rank == 1) && ((size_t)r.size == y.size ());
  for (size_t k = 0; ok && k < y.size (); k++) ok = near_d (ad (r, (int)k), y[k] + y[k]);
  check ("result == K + K elementwise (negatives and zero included)", ok);
  free (Y.data); free (Z.data);
  if (r.data) free (r.data);
}
#endif

#ifdef TEST_LOOP2_INNER
// Standalone innermost `for initial` of loop2 (ICCG kernel): array carry Xt +
// int carries k,i. Verified against an INDEPENDENT C reference, element-wise.
// (The same loop nested inside loop2's outer for-initial mis-wires its MERGE
// seeds — see nested_init_merge_dv.sis — but standalone it is correct.)
static void
ref_loop2_inner (int IPNT, int IPNTP, const double *V, const double *X, int n,
                 double *out)
{
  for (int j = 0; j < n; j++)
    out[j] = X[j]; // Xt := X
  int k = IPNT + 2, i = IPNTP;
  while (k <= IPNTP)
    {
      int ok = k;
      k = ok + 2;
      i = i + 1; // k := old k + 2 ; i := old i + 1
      // Xt[i] := Xt[ok] - V[ok]*Xt[ok-1] + V[ok+1]*Xt[ok+1]  (1-based Sisal
      // indices)
      double nv = out[ok - 1] - V[ok - 1] * out[ok - 2] + V[ok] * out[ok];
      out[i - 1] = nv; // Xt := old Xt[i: nv]
    }
}
static void
test_loop2_inner (void)
{
  printf ("\n=== Group: loop2_inner (for-initial array carry, vs C reference) "
          "===\n");
  const int n = 20;
  double Vd[20], Xd[20];
  for (int j = 0; j < n; j++)
    {
      Vd[j] = 0.5 * (j + 1);
      Xd[j] = (double)(j + 1);
    }
  int IPNT = 2, IPNTP = 8; // -> loop runs (k=4,6,8 <= 8), updates Xt[9..11]
  double expd[20];
  ref_loop2_inner (IPNT, IPNTP, Vd, Xd, n, expd);
  sisal_array_t V = make_double_arr (Vd, n), X = make_double_arr (Xd, n);
  sisal_array_t r = func_MAIN (IPNT, IPNTP, V, X);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int j = 0; ok && j < n; j++)
    ok = ok && (fabs (((double *)r.data)[j] - expd[j]) < 1e-9);
  check ("loop2_inner matches C reference (n=20, IPNT=2, IPNTP=8)", ok);
  // also assert the loop actually changed something (Xt[9..11] != X)
  check ("loop2_inner did update Xt[9..11]",
         ((double *)r.data)[8] != Xd[8] && ((double *)r.data)[9] != Xd[9]
             && ((double *)r.data)[10] != Xd[10]);
  if (V.data)
    free (V.data);
  if (X.data)
    free (X.data);
  if (r.data)
    free (r.data);
}
#endif

// ---- Livermore loop kernels: independent C references + checks ----
#ifdef TEST_LOOP1_DV
// Hydro: X[k] = Q + Y[k]*(R*Z[k+10] + T*Z[k+11])  (Sisal 1-based; Z needs
// n+11)
static void
test_loop1_dv (void)
{
  printf ("\n=== Group: loop1_dv (hydro fragment, vs C reference) ===\n");
  const int n = 8;
  double Q = 1.0, R = 2.0, T = 3.0;
  double Y[8];
  for (int i = 0; i < n; i++)
    Y[i] = (double)(i + 1);
  double Z[19];
  for (int j = 0; j < n + 11; j++)
    Z[j] = 0.1 * (j + 1);
  double exp[8];
  for (int k = 0; k < n; k++)
    exp[k] = Q + Y[k] * (R * Z[k + 10] + T * Z[k + 11]);
  sisal_array_t Ya = make_double_arr (Y, n), Za = make_double_arr (Z, n + 11);
  sisal_array_t r = func_MAIN (1, n, Q, R, T, Ya, Za);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && (fabs (ad (r, k) - exp[k]) < 1e-9);
  check ("loop1_dv hydro matches C reference (n=8)", ok);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.data)
    free (r.data);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_LET_SEQ_BIND
  test_let_seq_bind ();
#endif
#ifdef TEST_XFA_B2_COND
  test_xfa_b2_cond ();
#endif
#ifdef TEST_AGGREGATE_ADD
  test_aggregate_add ();
#endif
#ifdef TEST_AREA
  test_area ();
#endif
#ifdef TEST_MULTIDECL
  test_multidecl ();
#endif
#ifdef TEST_LOOPCARRY_USED
  test_loopcarry_used ();
#endif
#ifdef TEST_LOOPCARRY_IDENTITY
  test_loopcarry_identity ();
#endif
#ifdef TEST_SUB_MATMUL
  test_sub_matmul ();
#endif
#ifdef TEST_PI
  test_pi ();
#endif
#ifdef TEST_TEST_MIX_ARRAY_DV
  test_test_mix_array_dv ();
#endif
#ifdef TEST_TST_LOOP1_DV
  test_tst_loop1_dv ();
#endif
#ifdef TEST_LOOP2_INNER
  test_loop2_inner ();
#endif
#ifdef TEST_LOOP1_DV
  test_loop1_dv ();
#endif
#if !defined(TEST_LET_SEQ_BIND) \
    && !defined(TEST_XFA_B2_COND) \
    && !defined(TEST_AGGREGATE_ADD) \
    && !defined(TEST_AREA) \
    && !defined(TEST_MULTIDECL) \
    && !defined(TEST_LOOPCARRY_USED) \
    && !defined(TEST_LOOPCARRY_IDENTITY) \
    && !defined(TEST_SUB_MATMUL) \
    && !defined(TEST_PI) \
    && !defined(TEST_TEST_MIX_ARRAY_DV) \
    && !defined(TEST_TST_LOOP1_DV) \
    && !defined(TEST_LOOP2_INNER) \
    && !defined(TEST_LOOP1_DV)
  g_no_macro = true;
#endif
}
