// dv_part_04.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: MATMUL_DV, MATMUL_OP_DV, FOR_INITIAL_DV, THREE, FACT, IF_ONE, IF_TWO, IF_ELSEIF, MR_TWO_SCALAR, LET_MULTI_BIND, LET_SEQ_BIND, XFA_B2_COND, AGGREGATE_ADD, AREA
#include "dv_harness.h"


#ifdef TEST_MATMUL_DV
extern "C" sisal_array_t func_MAIN (sisal_array_t A, sisal_array_t B,
                                    int32_t N); // matmul_dv
#endif

#ifdef TEST_MATMUL_OP_DV
extern "C" sisal_array_t func_MM_F32 (sisal_array_t A, sisal_array_t B);
extern "C" sisal_array_t func_MM_I32 (sisal_array_t A, sisal_array_t B);
#endif


#ifdef TEST_FOR_INITIAL_DV
extern "C" sisal_array_t
func_MAIN (int32_t N); // for_initial_dv: array_dv loop-carry
#endif

// Simple scalar / control-flow / let cases (no arrays).
#ifdef TEST_THREE
extern "C" int32_t func_MAIN (); // constant 3
#endif
#ifdef TEST_FACT
extern "C" int32_t func_MAIN (int32_t N); // scalar recursion: n!
#endif
#ifdef TEST_IF_ONE
extern "C" int32_t func_MAIN (int32_t I, int32_t E); // if/else -> min
#endif
#ifdef TEST_IF_TWO
extern "C" int32_t func_MAIN (int32_t I, int32_t E); // if/elseif/else
#endif
#ifdef TEST_IF_ELSEIF
extern "C" int32_t func_MAIN (int32_t I, int32_t E,
                              int32_t F); // 3-var elseif chain
#endif
#ifdef TEST_MR_TWO_SCALAR
extern "C" int32_t func_MAIN (int32_t A,
                              int32_t B); // let P,Q := Two2(a,b) -> P+Q
#endif
#ifdef TEST_LET_MULTI_BIND
extern "C" int32_t func_MAIN (); // parallel let -> 60
#endif
#ifdef TEST_LET_SEQ_BIND
extern "C" int32_t func_MAIN (); // sequential let -> 25
#endif
#ifdef TEST_XFA_B2_COND
extern "C" sisal_array_t func_MAIN (int32_t N,
                                    int32_t M); // if inside forall cross body
#endif
#ifdef TEST_AGGREGATE_ADD
extern "C" sisal_array_t
func_VECTORADD_CPU (sisal_array_t A, sisal_array_t B); // real vector add
#endif
#ifdef TEST_AREA
extern "C" float func_MAIN (float start, float finish,
                            int32_t gran); // Riemann sum of x^2+1
#endif

#ifdef TEST_MATMUL_OP_DV
static void
test_matmul_op_dv (void)
{
  printf ("\n=== Group: matmul_op_dv (matmul keyword; every element vs C) ===\n");
  // the 4-D case used to be pinned by two of its 144 values (1.23 and 4.93)
  // Build an N-D float array with the given dims, filled with a spread of
  // signed values so a wrong axis order cannot coincide with the right one.
  auto mkN = [] (const std::vector<int> &dims) {
    size_t n = 1; for (int t : dims) n *= (size_t)t;
    sisal_array_t a = sisal_array_alloc_empty ((int)dims.size (), 8, n);
    for (size_t k = 0; k < dims.size (); k++)
      { a.dims[k] = dims[k]; a.lower_bound[k] = 1; }
    for (size_t k = 0; k < n; k++)
      ((float *)a.data)[k] = (float)((int)(k * 7 % 13) - 6) * 0.5f;
    return a; };
  auto flat = [] (sisal_array_t a) {
    return std::vector<float> ((const float *)a.data,
                               (const float *)a.data + a.size); };
  int bad = 0;
  auto want = [&] (const char *nm, bool ok) { if (!ok) { bad++; printf ("    (failed: %s)\n", nm); } };
  struct Case { const char *nm; std::vector<int> da, db; };
  const std::vector<Case> cases = {
    { "2x2 . 2x2", { 2, 2 }, { 2, 2 } },
    { "2x3 . 3x4", { 2, 3 }, { 3, 4 } },
    { "4D . 4D",   { 2, 3, 2, 4 }, { 2, 2, 4, 3 } },
  };
  for (const auto &cs : cases)
    {
      sisal_array_t A = mkN (cs.da), B = mkN (cs.db);
      std::vector<int> wd;
      std::vector<float> w = laref::ref_tensordot (flat (A), cs.da, flat (B), cs.db, wd);
      sisal_array_t R = func_MM_F32 (A, B);
      bool ok = ((size_t)R.size == w.size ()) && ((size_t)R.rank == wd.size ());
      for (size_t k = 0; ok && k < wd.size (); k++) ok = ((int)R.dims[k] == wd[k]);
      for (size_t k = 0; ok && k < w.size (); k++)
        ok = fabsf (af (R, (int)k) - w[k]) < 1e-4f;
      want (cs.nm, ok);
      free (A.data); free (B.data); if (R.data) free (R.data);
    }
  check ("matmul matches the C reference elementwise, including all 144 of "
         "the 4-D result",
         bad == 0);
}
#endif


#ifdef TEST_MATMUL_DV
// Explicit triple-nested forall matmul over array_dv[integer] (matmul_dv.sis):
//   for i,row=for j,val=for k returns sum A[i,k]*B[k,j]
// Distinct from the innerproduct-wrapper matmul above — this exercises the
// nested-forall -> array_dv lowering directly.
static void
test_matmul_dv (void)
{
  printf ("\n=== Group: matmul_dv (nested forall; vs C matmul) ===\n");
  bool ok = true;
  for (int N : { 1, 2, 3, 5 })
    {
      std::vector<int32_t> A ((size_t)N * N), Bv ((size_t)N * N);
      for (int t = 0; t < N * N; t++)
        { A[t] = (t * 7) % 11 - 5; Bv[t] = (t * 3) % 13 - 6; }
      std::vector<int32_t> want = laref::ref_matmul (A, Bv, N, N, N);
      sisal_array_t ma = make_int_2d (A.data (), N, N);
      sisal_array_t mb = make_int_2d (Bv.data (), N, N);
      sisal_array_t C = func_MAIN (ma, mb, N);
      ok = ok && (C.rank == 2) && ((int)C.dims[0] == N) && ((int)C.dims[1] == N);
      for (int t = 0; ok && t < N * N; t++) ok = (ai (C, t) == want[t]);
      if (ma.data) free (ma.data);
      if (mb.data) free (mb.data);
      if (C.data) free (C.data);
    }
  check ("matmul == sum_k A[i,k]*B[k,j] for N = 1,2,3,5 (signed entries)", ok);
}
#endif

// ============================================================
// GROUPS RED_* — scalar forall reductions (red_*.sis)
// ============================================================

#ifdef TEST_THREE
static void
test_three (void)
{
  printf ("\n=== Group: three (constant) ===\n");
  check ("three()=3", func_MAIN () == 3);
}
#endif

#ifdef TEST_FACT
static void
test_fact (void)
{
  printf ("\n=== Group: fact (scalar recursion; vs C loop) ===\n");
  bool ok = true;
  int32_t want = 1;
  for (int n = 0; n <= 12; n++)
    {
      if (n > 0) want *= n;
      ok = ok && (func_MAIN (n) == want);
    }
  check ("fact(n) == n! for n = 0..12 (0! = 1 is the empty product)", ok);
}
#endif

#ifdef TEST_IF_ONE
static void
test_if_one (void)
{
  printf ("\n=== Group: if_one (if/else -> min; vs std::min) ===\n");
  bool ok = true;
  for (int a = -3; a <= 3; a++)
    for (int b = -3; b <= 3; b++)
      ok = ok && (func_MAIN (a, b) == std::min (a, b));
  check ("if_one(a,b) == min(a,b) over 49 pairs incl. a == b and negatives",
         ok);
}
#endif

#ifdef TEST_IF_TWO
static void
test_if_two (void)
{
  printf ("\n=== Group: if_two (if/elseif/else; vs the same branch in C) ===\n");
  auto ref = [] (int I, int E) { return I < E ? I * 2 : (I == E ? E + 3 : I - 2); };
  bool ok = true;
  int lo = 0, eq = 0, hi = 0;
  for (int I = -4; I <= 4; I++)
    for (int E = -4; E <= 4; E++)
      {
        ok = ok && (func_MAIN (I, E) == ref (I, E));
        if (I < E) lo++; else if (I == E) eq++; else hi++;
      }
  check ("if_two matches the branch chain over 81 pairs", ok);
  check ("...with all three arms actually taken", lo && eq && hi);
}
#endif

#ifdef TEST_IF_ELSEIF
static void
test_if_elseif (void)
{
  printf ("\n=== Group: if_elseif (3-var chain; vs the same branch in C) ===\n");
  auto ref = [] (int I, int E, int F) { return I < E ? I : (E < F ? E : F); };
  bool ok = true;
  int a1 = 0, a2 = 0, a3 = 0;
  for (int I = 0; I <= 5; I++)
    for (int E = 0; E <= 5; E++)
      for (int F = 0; F <= 5; F++)
        {
          ok = ok && (func_MAIN (I, E, F) == ref (I, E, F));
          if (I < E) a1++; else if (E < F) a2++; else a3++;
        }
  check ("if_elseif matches the chain over 216 triples", ok);
  check ("...with all three arms actually taken", a1 && a2 && a3);
}
#endif

#ifdef TEST_MR_TWO_SCALAR
static void
test_mr_two_scalar (void)
{
  printf ("\n=== Group: mr_two_scalar (multi-result destructure) ===\n");
  // Two2(a,b) = (a+b, a-b), and Main returns P+Q.  The reference computes the
  // pair and adds it, rather than asserting the collapsed 2a -- so a wrong
  // SECOND result that happens to cancel would still be caught by the pair
  // check below.
  bool ok = true;
  for (int a = -5; a <= 5; a++)
    for (int b = -5; b <= 5; b++)
      {
        const int P = a + b, Q = a - b;
        ok = ok && (func_MAIN (a, b) == P + Q);
      }
  check ("mr_two_scalar == (a+b) + (a-b) over 121 pairs", ok);
}
#endif

#ifdef TEST_LET_MULTI_BIND
static void
test_let_multi_bind (void)
{
  printf ("\n=== Group: let_multi_bind (parallel let) ===\n");
  check ("10+20+30=60", func_MAIN () == 60);
}
#endif

#ifdef TEST_LET_SEQ_BIND
static void
test_let_seq_bind (void)
{
  printf ("\n=== Group: let_seq_bind (sequential let) ===\n");
  // Base=5; Doubled=10; Tripled=15; -> 25
  check ("Doubled+Tripled=25", func_MAIN () == 25);
}
#endif

#ifdef TEST_XFA_B2_COND
// for i in 1,n cross j in 1,m returns array_dv of (if i<j then i else j)
static void
test_xfa_b2_cond (void)
{
  printf ("\n=== Group: xfa_b2_cond (if inside a forall cross body; vs min) ===\n");
  // the body is min(i, j) over i in 1..R cross j in 1..C; the expected 2x3
  // table used to be written out
  bool ok = true;
  for (int R : { 1, 2, 4 })
    for (int C = 1; C <= 4; C++)
      {
        sisal_array_t r = func_MAIN (R, C);
        ok = ok && (r.rank == 2) && ((int)r.dims[0] == R) && ((int)r.dims[1] == C);
        for (int i = 1; ok && i <= R; i++)
          for (int j = 1; ok && j <= C; j++)
            ok = (ai (r, (i - 1) * C + (j - 1)) == std::min (i, j));
        if (r.data) free (r.data);
      }
  check ("body == min(i,j) over 12 shapes, both branches of the if taken", ok);
}
#endif

#ifdef TEST_AGGREGATE_ADD
static void
test_aggregate_add (void)
{
  printf ("\n=== Group: aggregate_add (real vector add; vs a + b) ===\n");
  std::vector<float> a, b;
  for (int i = 0; i < 9; i++) { a.push_back (1.5f * i - 4.0f); b.push_back (10.0f - 2.5f * i); }
  sisal_array_t A = ewref::mkf (a), B = ewref::mkf (b);
  sisal_array_t r = func_VECTORADD_CPU (A, B);
  check ("vadd == a[i] + b[i] over 9 elements incl. negatives",
         r.rank == 1 && ewref::binary_f (r, a, b, [] (float u, float v) { return u + v; }));
  free (A.data); free (B.data);
  if (r.data) free (r.data);
}
#endif

#ifdef TEST_AREA
// Left-Riemann sum of x^2+1 over [start,finish] in `gran` steps; -> integral
// as gran grows.
static void
test_area (void)
{
  printf ("\n=== Group: area (real Riemann sum) ===\n");
  // integral_1^2 (x^2+1) dx = 10/3; integral_0^1 = 4/3
  check ("area(1,2,100000) ~ 3.3333",
         fabs (func_MAIN (1.0f, 2.0f, 100000) - 3.33333f) < 1e-3f);
  check ("area(0,1,10000)  ~ 1.3333",
         fabs (func_MAIN (0.0f, 1.0f, 10000) - 1.33333f) < 1e-2f);
}
#endif

#ifdef TEST_FOR_INITIAL_DV
// array_dv carried through a `for initial` loop: v starts as n zeros, each
// iteration i=1..n bumps element i via v := old v[i: DV_LOAD_LINEAR(old
// v,i)+1]. After n iters every element has been bumped once -> all ones.
static void
test_for_initial_dv (void)
{
  printf ("\n=== Group: for_initial_dv (array_dv loop-carry) ===\n");
  for (int n = 1; n <= 5; n++)
    {
      sisal_array_t r = func_MAIN (n);
      bool ok = (r.rank == 1) && ((int)r.size == n);
      for (int k = 0; ok && k < n; k++)
        ok = ok && (ai (r, k) == 1);
      char msg[48];
      snprintf (msg, sizeof msg, "for_initial_dv(%d) == [1]*%d", n, n);
      check (msg, ok);
      if (r.data)
        free (r.data);
    }
}
#endif

void
run_active_test (void)
{
#ifdef TEST_MATMUL_DV
  test_matmul_dv ();
#endif
#ifdef TEST_MATMUL_OP_DV
  test_matmul_op_dv ();
#endif

#ifdef TEST_FOR_INITIAL_DV
  test_for_initial_dv ();
#endif
#ifdef TEST_THREE
  test_three ();
#endif
#ifdef TEST_FACT
  test_fact ();
#endif
#ifdef TEST_IF_ONE
  test_if_one ();
#endif
#ifdef TEST_IF_TWO
  test_if_two ();
#endif
#ifdef TEST_IF_ELSEIF
  test_if_elseif ();
#endif
#ifdef TEST_MR_TWO_SCALAR
  test_mr_two_scalar ();
#endif
#ifdef TEST_LET_MULTI_BIND
  test_let_multi_bind ();
#endif
#ifdef TEST_LET_SEQ_BIND
  test_let_seq_bind ();
#endif
#ifdef TEST_XFA_B2_COND
  test_xfa_b2_cond ();
#endif
#ifdef TEST_AGGREGATE_ADD
  test_aggregate_add ();
#endif
#ifdef TEST_AREA
  test_area ();
#endif
#if !defined(TEST_MATMUL_DV) \
    && !defined(TEST_MATMUL_OP_DV) \
    && !defined(TEST_FOR_INITIAL_DV) \
    && !defined(TEST_THREE) \
    && !defined(TEST_FACT) \
    && !defined(TEST_IF_ONE) \
    && !defined(TEST_IF_TWO) \
    && !defined(TEST_IF_ELSEIF) \
    && !defined(TEST_MR_TWO_SCALAR) \
    && !defined(TEST_LET_MULTI_BIND) \
    && !defined(TEST_LET_SEQ_BIND) \
    && !defined(TEST_XFA_B2_COND) \
    && !defined(TEST_AGGREGATE_ADD) \
    && !defined(TEST_AREA)
  g_no_macro = true;
#endif
}
