// dv_part_04.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: LOOP2_INNER, LOOP1_DV, LOOP3_DV, LOOP7_DV, LOOP12_DV, LOOP24_DV, LOOP9_DV, LOOP10_DV, LOOP21_DV, LOOP2_DV, LOOP2S_DV, MR2_INIT, LOOP16_DV
#include "dv_harness.h"

#ifdef TEST_LOOP2_INNER
extern "C" sisal_array_t
func_MAIN (int32_t IPNT, int32_t IPNTP, sisal_array_t V,
           sisal_array_t X); // loop2 inner for-initial
#endif

// ---- Livermore loop kernels (array_dv), each vs an independent C reference
// ----
#ifdef TEST_LOOP1_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, double Q, double R,
                                    double T, sisal_array_t Y,
                                    sisal_array_t Z); // hydro fragment
#endif
#ifdef TEST_LOOP3_DV
extern "C" double func_MAIN (int32_t REP, int32_t N, sisal_array_t X,
                             sisal_array_t Z); // inner product
#endif
#ifdef TEST_LOOP7_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, double R, double T,
                                    sisal_array_t U, sisal_array_t Y,
                                    sisal_array_t Z); // equation of state
#endif
#ifdef TEST_LOOP12_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N,
                                    sisal_array_t YIN); // first difference
#endif
#ifdef TEST_LOOP24_DV
extern "C" int32_t func_MAIN (int32_t REP, int32_t N,
                              sisal_array_t X); // location of first minimum
#endif
#ifdef TEST_LOOP9_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, double CO, double DM22, double DM23,
           double DM24, double DM25, double DM26, double DM27, double DM28,
           sisal_array_t PXIN); // integrate predictors
#endif
#ifdef TEST_LOOP10_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t CX,
           sisal_array_t PXIN); // difference predictors
#endif
#ifdef TEST_LOOP21_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t CX,
                                    sisal_array_t PXIN,
                                    sisal_array_t VY); // matrix*matrix product
#endif
#ifdef TEST_LOOP2_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t V,
                                    sisal_array_t XIN); // ICCG excerpt
#endif
#ifdef TEST_LOOP2S_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t V,
           sisal_array_t XIN); // ICCG excerpt (s-form)
#endif
#ifdef TEST_MR2_INIT
struct MR2_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct MR2_results
func_MAIN (int32_t N); // for-initial returning TWO array_dv carries
#endif
#ifdef TEST_LOOP16_DV
struct LOOP16_results
{
  int32_t res_0;
  int32_t res_1;
};
extern "C" struct LOOP16_results
func_MAIN (int32_t REP, int32_t N, double R, double S, double T,
           sisal_array_t D, sisal_array_t PLAN,
           sisal_array_t ZONE); // Monte Carlo search (v1,v2)
#endif

#ifdef TEST_LOOP2_INNER
// Standalone innermost `for initial` of loop2 (ICCG kernel): array carry Xt +
// int carries k,i. Verified against an INDEPENDENT C reference, element-wise.
// (The same loop nested inside loop2's outer for-initial mis-wires its MERGE
// seeds — see nested_init_merge_dv.sis — but standalone it is correct.)
static void
ref_loop2_inner (int IPNT, int IPNTP, const double *V, const double *X, int n,
                 double *out)
{
  for (int j = 0; j < n; j++)
    out[j] = X[j]; // Xt := X
  int k = IPNT + 2, i = IPNTP;
  while (k <= IPNTP)
    {
      int ok = k;
      k = ok + 2;
      i = i + 1; // k := old k + 2 ; i := old i + 1
      // Xt[i] := Xt[ok] - V[ok]*Xt[ok-1] + V[ok+1]*Xt[ok+1]  (1-based Sisal
      // indices)
      double nv = out[ok - 1] - V[ok - 1] * out[ok - 2] + V[ok] * out[ok];
      out[i - 1] = nv; // Xt := old Xt[i: nv]
    }
}
static void
test_loop2_inner (void)
{
  printf ("\n=== Group: loop2_inner (for-initial array carry, vs C reference) "
          "===\n");
  const int n = 20;
  double Vd[20], Xd[20];
  for (int j = 0; j < n; j++)
    {
      Vd[j] = 0.5 * (j + 1);
      Xd[j] = (double)(j + 1);
    }
  int IPNT = 2, IPNTP = 8; // -> loop runs (k=4,6,8 <= 8), updates Xt[9..11]
  double expd[20];
  ref_loop2_inner (IPNT, IPNTP, Vd, Xd, n, expd);
  sisal_array_t V = make_double_arr (Vd, n), X = make_double_arr (Xd, n);
  sisal_array_t r = func_MAIN (IPNT, IPNTP, V, X);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int j = 0; ok && j < n; j++)
    ok = ok && (fabs (((double *)r.data)[j] - expd[j]) < 1e-9);
  check ("loop2_inner matches C reference (n=20, IPNT=2, IPNTP=8)", ok);
  // also assert the loop actually changed something (Xt[9..11] != X)
  check ("loop2_inner did update Xt[9..11]",
         ((double *)r.data)[8] != Xd[8] && ((double *)r.data)[9] != Xd[9]
             && ((double *)r.data)[10] != Xd[10]);
  if (V.data)
    free (V.data);
  if (X.data)
    free (X.data);
  if (r.data)
    free (r.data);
}
#endif

// ---- Livermore loop kernels: independent C references + checks ----
#ifdef TEST_LOOP1_DV
// Hydro: X[k] = Q + Y[k]*(R*Z[k+10] + T*Z[k+11])  (Sisal 1-based; Z needs
// n+11)
static void
test_loop1_dv (void)
{
  printf ("\n=== Group: loop1_dv (hydro fragment, vs C reference) ===\n");
  const int n = 8;
  double Q = 1.0, R = 2.0, T = 3.0;
  double Y[8];
  for (int i = 0; i < n; i++)
    Y[i] = (double)(i + 1);
  double Z[19];
  for (int j = 0; j < n + 11; j++)
    Z[j] = 0.1 * (j + 1);
  double exp[8];
  for (int k = 0; k < n; k++)
    exp[k] = Q + Y[k] * (R * Z[k + 10] + T * Z[k + 11]);
  sisal_array_t Ya = make_double_arr (Y, n), Za = make_double_arr (Z, n + 11);
  sisal_array_t r = func_MAIN (1, n, Q, R, T, Ya, Za);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && (fabs (ad (r, k) - exp[k]) < 1e-9);
  check ("loop1_dv hydro matches C reference (n=8)", ok);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP3_DV
// Inner product: sum_{i=1..n} X[i]*Z[i]
static void
test_loop3_dv (void)
{
  printf ("\n=== Group: loop3_dv (inner product, vs C reference) ===\n");
  const int n = 5;
  double X[5], Z[5];
  double exp = 0.0;
  for (int i = 0; i < n; i++)
    {
      X[i] = i + 1;
      Z[i] = i + 1;
      exp += X[i] * Z[i];
    }
  sisal_array_t Xa = make_double_arr (X, n), Za = make_double_arr (Z, n);
  double r = func_MAIN (1, n, Xa, Za);
  check ("loop3_dv inner product == 55", fabs (r - exp) < 1e-9);
  if (Xa.data)
    free (Xa.data);
  if (Za.data)
    free (Za.data);
}
#endif
#ifdef TEST_LOOP7_DV
// Equation of state: out[k] = U[k] + R*(Z[k]+R*Y[k])
//   + T*(U[k+3]+R*(U[k+2]+R*U[k+1]) + T*(U[k+6]+R*(U[k+5]+R*U[k+4])))  (U
//   needs n+6)
static void
test_loop7_dv (void)
{
  printf ("\n=== Group: loop7_dv (equation of state, vs C reference) ===\n");
  const int n = 6;
  double R = 0.5, T = 0.25;
  double U[12];
  for (int i = 0; i < n + 6; i++)
    U[i] = 0.1 * (i + 1);
  double Y[6], Z[6];
  for (int i = 0; i < n; i++)
    {
      Y[i] = i + 1;
      Z[i] = 2 * (i + 1);
    }
  double exp[6];
  for (int k = 0; k < n; k++)
    exp[k] = U[k] + R * (Z[k] + R * Y[k])
             + T
                   * (U[k + 3] + R * (U[k + 2] + R * U[k + 1])
                      + T * (U[k + 6] + R * (U[k + 5] + R * U[k + 4])));
  sisal_array_t Ua = make_double_arr (U, n + 6), Ya = make_double_arr (Y, n),
                Za = make_double_arr (Z, n);
  sisal_array_t r = func_MAIN (1, n, R, T, Ua, Ya, Za);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && (fabs (ad (r, k) - exp[k]) < 1e-9);
  check ("loop7_dv eos matches C reference (n=6)", ok);
  if (Ua.data)
    free (Ua.data);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP12_DV
// First difference: out[i] = Y[i+1] - Y[i]  (Y needs n+1)
static void
test_loop12_dv (void)
{
  printf ("\n=== Group: loop12_dv (first difference, vs C reference) ===\n");
  const int n = 6;
  double Y[7];
  for (int i = 0; i < n + 1; i++)
    Y[i] = (double)(i * i);
  double exp[6];
  for (int i = 0; i < n; i++)
    exp[i] = Y[i + 1] - Y[i];
  sisal_array_t Ya = make_double_arr (Y, n + 1);
  sisal_array_t r = func_MAIN (1, n, Ya);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int i = 0; ok && i < n; i++)
    ok = ok && (fabs (ad (r, i) - exp[i]) < 1e-9);
  check ("loop12_dv first-difference matches C reference (2i+1)", ok);
  if (Ya.data)
    free (Ya.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP24_DV
// Location (1-based) of first minimum: loc=1; for k=2..n if X[k]<X[loc] loc=k
static void
test_loop24_dv (void)
{
  printf (
      "\n=== Group: loop24_dv (first-minimum location, vs C reference) ===\n");
  const int n = 7;
  double X[7]
      = { 5.0, 3.0, 8.0, 1.0, 1.0, 9.0, 2.0 }; // first min (1.0) at 1-based 4
  int loc = 1;
  for (int k = 2; k <= n; k++)
    if (X[k - 1] < X[loc - 1])
      loc = k;
  sisal_array_t Xa = make_double_arr (X, n);
  int32_t r = func_MAIN (1, n, Xa);
  check ("loop24_dv first-min location == 4", r == loc && r == 4);
  if (Xa.data)
    free (Xa.data);
}
#endif

#ifdef TEST_LOOP9_DV
// Integrate predictors: out[i] = PX[3,i] + CO*(PX[5,i]+PX[6,i]) + DM22*PX[7,i]
//   + DM23*PX[8,i] + ... + DM28*PX[13,i].  PX is 13 rows x n cols (row-major).
static void
test_loop9_dv (void)
{
  printf (
      "\n=== Group: loop9_dv (integrate predictors, vs C reference) ===\n");
  const int n = 4, R = 13;
  double CO = 0.5, DM[7] = { 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7 }; // DM22..DM28
  double PX[13 * 4];
  for (int r = 1; r <= R; r++)
    for (int c = 1; c <= n; c++)
      PX[(r - 1) * n + (c - 1)] = (double)(r * 100 + c);
#define PXV(r, i) PX[((r) - 1) * n + ((i) - 1)]
  double exp[4];
  for (int i = 1; i <= n; i++)
    exp[i - 1] = PXV (3, i) + CO * (PXV (5, i) + PXV (6, i))
                 + DM[0] * PXV (7, i) + DM[1] * PXV (8, i) + DM[2] * PXV (9, i)
                 + DM[3] * PXV (10, i) + DM[4] * PXV (11, i)
                 + DM[5] * PXV (12, i) + DM[6] * PXV (13, i);
#undef PXV
  sisal_array_t PXa = make_double_2d (PX, R, n);
  sisal_array_t r = func_MAIN (1, n, CO, DM[0], DM[1], DM[2], DM[3], DM[4],
                               DM[5], DM[6], PXa);
  bool ok = (r.rank == 1) && ((int)r.size == n);
  for (int i = 0; ok && i < n; i++)
    ok = ok && (fabs (ad (r, i) - exp[i]) < 1e-6);
  check ("loop9_dv integrate-predictors matches C reference (n=4)", ok);
  if (PXa.data)
    free (PXa.data);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_LOOP10_DV
static void
test_loop10_dv (void)
{
  printf (
      "\n=== Group: loop10_dv (difference predictors, vs C reference) ===\n");
  const int R = 14, n = 2;
  double CX[28], PX[28];
  for (int r = 1; r <= R; r++)
    {
      for (int c = 1; c <= n; c++)
        {
          CX[(r - 1) * n + c - 1] = 100 + r;
          PX[(r - 1) * n + c - 1] = r;
        }
    }
  double ref[10 * n];
  for (int c = 0; c < n; c++)
    {
      double px = CX[(5 - 1) * n + c];
      ref[0 * n + c] = px;
      for (int k = 6; k <= 14; k++)
        {
          px = px - PX[((k - 1) - 1) * n + c];
          ref[(k - 5) * n + c] = px;
        }
    }
  sisal_array_t CXa = make_double_2d (CX, R, n);
  sisal_array_t PXa = make_double_2d (PX, R, n);
  sisal_array_t r = func_MAIN (1, n, CXa, PXa);
  bool ok = ((int)r.dims[0] == 10) && ((int)r.dims[1] == n);
  for (int k = 0; ok && k < 10 * n; k++)
    {
      ok = ok && (fabs (ad (r, k) - ref[k]) < 1e-9);
    }
  check ("loop10_dv difference-predictors matches C reference", ok);
  if (CXa.data)
    free (CXa.data);
  if (PXa.data)
    free (PXa.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP21_DV
// Matrix*matrix: out[i,j] = PX[i,j] + sum_{k=1..25} VY[i,k]*CX[j,k], i=1..25,
// j=1..n.
//   CX is n x 25, VY is 25 x 25, PX is 25 x n; output is 25 x n (row-major).
static void
test_loop21_dv (void)
{
  printf (
      "\n=== Group: loop21_dv (matrix*matrix product, vs C reference) ===\n");
  const int n = 3, M = 25;
  double CX[3 * 25], VY[25 * 25], PX[25 * 3];
  for (int j = 1; j <= n; j++)
    for (int k = 1; k <= M; k++)
      CX[(j - 1) * M + (k - 1)] = 0.01 * (j + k);
  for (int i = 1; i <= M; i++)
    for (int k = 1; k <= M; k++)
      VY[(i - 1) * M + (k - 1)] = 0.01 * ((i * k) % 7);
  for (int i = 1; i <= M; i++)
    for (int j = 1; j <= n; j++)
      PX[(i - 1) * n + (j - 1)] = 0.1 * (i + j);
  double exp[25 * 3];
  for (int i = 1; i <= M; i++)
    for (int j = 1; j <= n; j++)
      {
        double s = 0.0;
        for (int k = 1; k <= M; k++)
          s += VY[(i - 1) * M + (k - 1)] * CX[(j - 1) * M + (k - 1)];
        exp[(i - 1) * n + (j - 1)] = PX[(i - 1) * n + (j - 1)] + s;
      }
  sisal_array_t CXa = make_double_2d (CX, n, M),
                PXa = make_double_2d (PX, M, n),
                VYa = make_double_2d (VY, M, M);
  sisal_array_t r = func_MAIN (1, n, CXa, PXa, VYa);
  bool ok = (r.rank == 2) && ((int)r.dims[0] == M) && ((int)r.dims[1] == n);
  for (int t = 0; ok && t < M * n; t++)
    ok = ok && (fabs (ad (r, t) - exp[t]) < 1e-6);
  check ("loop21_dv matrix*matrix matches C reference (25x3)", ok);
  if (CXa.data)
    free (CXa.data);
  if (PXa.data)
    free (PXa.data);
  if (VYa.data)
    free (VYa.data);
  if (r.data)
    free (r.data);
}
#endif

#if defined(TEST_LOOP2_DV) || defined(TEST_LOOP2S_DV)
// ICCG excerpt (loop2 / loop2s -- identical kernels, only formatting differs):
// outer halving sweep (IL = n, n/2, ...) driving an inner tridiagonal-style
// update Xt[i] = Xt[k] - V[k]*Xt[k-1] + V[k+1]*Xt[k+1] (Sisal 1-based).
// In-place on X matches the Sisal `old Xt` semantics: each inner step writes
// one element and later steps read it back, which is exactly the running
// carry.  (This is the full kernel whose inner-only form is loop2_inner.)
static void
ref_loop2 (int n, const double *V, const double *Xin, int sz, double *X)
{
  for (int j = 0; j < sz; j++)
    X[j] = Xin[j];
  int IL = n, IPNTP = 0;
  while (IL > 1)
    {
      int IPNT = IPNTP;
      IPNTP = IPNTP + IL;
      IL = IL / 2;
      int k = IPNT + 2, i = IPNTP;
      while (k <= IPNTP)
        {
          int ok = k;
          k = ok + 2;
          i = i + 1;
          X[i - 1] = X[ok - 1] - V[ok - 1] * X[ok - 2] + V[ok] * X[ok];
        }
    }
}
#endif
#ifdef TEST_LOOP2_DV
static void
test_loop2_dv (void)
{
  printf ("\n=== Group: loop2_dv (ICCG excerpt, vs C reference) ===\n");
  const int n = 8, sz = 24;
  double V[24], Xin[24];
  for (int j = 0; j < sz; j++)
    {
      V[j] = 0.1 * (j + 1);
      Xin[j] = (double)(j + 1);
    }
  double exp[24];
  ref_loop2 (n, V, Xin, sz, exp);
  sisal_array_t Va = make_double_arr (V, sz), Xa = make_double_arr (Xin, sz);
  sisal_array_t r = func_MAIN (1, n, Va, Xa);
  bool ok = (r.rank == 1) && ((int)r.size == sz);
  for (int j = 0; ok && j < sz; j++)
    ok = ok && (fabs (ad (r, j) - exp[j]) < 1e-9);
  check ("loop2_dv ICCG matches C reference (n=8)", ok);
  check ("loop2_dv did update X (X[11] != Xin[11])",
         fabs (ad (r, 11) - Xin[11]) > 1e-12);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP2S_DV
// loop2s = loop2 with different source formatting only; same ref_loop2.
static void
test_loop2s_dv (void)
{
  printf ("\n=== Group: loop2s_dv (ICCG excerpt, vs C reference) ===\n");
  const int n = 8, sz = 24;
  double V[24], Xin[24];
  for (int j = 0; j < sz; j++)
    {
      V[j] = 0.1 * (j + 1);
      Xin[j] = (double)(j + 1);
    }
  double exp[24];
  ref_loop2 (n, V, Xin, sz, exp);
  sisal_array_t Va = make_double_arr (V, sz), Xa = make_double_arr (Xin, sz);
  sisal_array_t r = func_MAIN (1, n, Va, Xa);
  bool ok = (r.rank == 1) && ((int)r.size == sz);
  for (int j = 0; ok && j < sz; j++)
    ok = ok && (fabs (ad (r, j) - exp[j]) < 1e-9);
  check ("loop2s_dv ICCG matches C reference (n=8)", ok);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_MR2_INIT
// Minimal two-array for-initial return: H = all 10, P = all 20 (n x n). Guards
// the multi-return tuple wiring -- the per-clause (node,port) resolution fix.
// Without it both slots collapse to one carry.
static void
test_mr2_init (void)
{
  printf ("\n=== Group: mr2_init (for-initial returns two array_dv carries) "
          "===\n");
  // The 10s and 20s are constants in the .sis, so they ARE the specification;
  // what this group exists to check is that the two return slots stay distinct
  // and neither is cross-wired to the other.  Swept over n, since the carries
  // are rank-2 built by a cross forall and a size-dependent mis-wire would
  // otherwise hide at the single n = 3 it used to run.
  bool ok = true;
  for (int n : { 1, 2, 3, 5 })
    {
      struct MR2_results r = func_MAIN (n);
      const int sz = n * n;
      ok = ok && (r.res_0.rank == 2) && ((int)r.res_0.dims[0] == n)
           && ((int)r.res_0.dims[1] == n) && ((int)r.res_0.size == sz)
           && (r.res_1.rank == 2) && ((int)r.res_1.dims[0] == n)
           && ((int)r.res_1.dims[1] == n) && ((int)r.res_1.size == sz);
      for (int t = 0; ok && t < sz; t++)
        ok = (ai (r.res_0, t) == 10) && (ai (r.res_1, t) == 20);
      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data && r.res_1.data != r.res_0.data) free (r.res_1.data);
    }
  check ("both rank-2 carries return distinctly (H all 10, P all 20) for "
         "n = 1, 2, 3, 5",
         ok);
}
#endif
#ifdef TEST_LOOP16_DV
// Monte Carlo search (loop16): Y = least j4 of cells whose classifier C1==0;
// then (v1,v2) = Y==BIG ? (1,0) : ((Y-3)/(2n)+1, Y).  Sisal `exp(a,b)` is
// power -> pow.
static void
ref_loop16 (int n, double R, double S, double T, const double *D,
            const double *PLAN, const int *ZONE, int *v1, int *v2)
{
  int Z1 = ZONE[0];
  long BIG = 2L * n * Z1 + 2, Y = BIG;
  for (int j = 1; j <= n; j++)
    for (int i = 1; i <= Z1; i++)
      {
        int m = n * (i - 1) + j - 1;
        int j4 = 2 * m + 3;
        int j5 = ZONE[j4 - 1];
        int C1;
        if (j5 < n / 3)
          C1 = (PLAN[j5 - 1] < T)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == T) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 < 2 * n / 3)
          C1 = (PLAN[j5 - 1] < S)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == S) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 < n)
          C1 = (PLAN[j5 - 1] < R)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == R) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 == n)
          C1 = 0;
        else
          {
            double test
                = D[j5 - 1]
                  - (D[j5 - 2] * pow (T - D[j5 - 3], 2)
                     + pow (S - D[j5 - 4], 2) + pow (R - D[j5 - 5], 2));
            C1 = (test < 0.0) ? ZONE[j4 - 2] : -ZONE[j4 - 2];
          }
        long cand = (C1 == 0) ? j4 : BIG;
        if (cand < Y)
          Y = cand;
      }
  if (Y == BIG)
    {
      *v1 = 1;
      *v2 = 0;
    }
  else
    {
      *v1 = (int)((Y - 3) / (2 * n) + 1);
      *v2 = (int)Y;
    }
}
static void
test_loop16_dv (void)
{
  printf ("\n=== Group: loop16_dv (Monte Carlo search, vs C reference) ===\n");
  const int n = 3;
  double R = 0.3, S = 0.5, T = 0.7;
  double D[8] = { 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8 };
  double PLAN[3] = { 0.0, 0.0, 0.0 };
  int32_t ZONE[13] = { 2, 7, 5, 9, 3, 11, 3, 13, 3, 15, 3, 17, 3 };
  int ev1, ev2;
  ref_loop16 (n, R, S, T, D, PLAN, ZONE, &ev1, &ev2);
  sisal_array_t Da = make_double_arr (D, 8), Pa = make_double_arr (PLAN, 3),
                Za = make_int_arr (ZONE, 13);
  struct LOOP16_results r = func_MAIN (1, n, R, S, T, Da, Pa, Za);
  check ("loop16_dv v1 matches C reference", r.res_0 == ev1);
  check ("loop16_dv v2 matches C reference", r.res_1 == ev2);
  if (Da.data)
    free (Da.data);
  if (Pa.data)
    free (Pa.data);
  if (Za.data)
    free (Za.data);
}
#endif

// ============================================================
// main — dispatches to the single active test group
// ============================================================



void
run_active_test (void)
{
#ifdef TEST_LOOP2_INNER
  test_loop2_inner ();
#endif
#ifdef TEST_LOOP1_DV
  test_loop1_dv ();
#endif
#ifdef TEST_LOOP3_DV
  test_loop3_dv ();
#endif
#ifdef TEST_LOOP7_DV
  test_loop7_dv ();
#endif
#ifdef TEST_LOOP12_DV
  test_loop12_dv ();
#endif
#ifdef TEST_LOOP24_DV
  test_loop24_dv ();
#endif
#ifdef TEST_LOOP9_DV
  test_loop9_dv ();
#endif
#ifdef TEST_LOOP10_DV
  test_loop10_dv ();
#endif
#ifdef TEST_LOOP21_DV
  test_loop21_dv ();
#endif
#ifdef TEST_LOOP2_DV
  test_loop2_dv ();
#endif
#ifdef TEST_LOOP2S_DV
  test_loop2s_dv ();
#endif
#ifdef TEST_MR2_INIT
  test_mr2_init ();
#endif
#ifdef TEST_LOOP16_DV
  test_loop16_dv ();
#endif
#if !defined(TEST_LOOP2_INNER) \
    && !defined(TEST_LOOP1_DV) \
    && !defined(TEST_LOOP3_DV) \
    && !defined(TEST_LOOP7_DV) \
    && !defined(TEST_LOOP12_DV) \
    && !defined(TEST_LOOP24_DV) \
    && !defined(TEST_LOOP9_DV) \
    && !defined(TEST_LOOP10_DV) \
    && !defined(TEST_LOOP21_DV) \
    && !defined(TEST_LOOP2_DV) \
    && !defined(TEST_LOOP2S_DV) \
    && !defined(TEST_MR2_INIT) \
    && !defined(TEST_LOOP16_DV)
  g_no_macro = true;
#endif
}
