// dv_part_06.cpp -- generated by test/e2e/split_harness.py; do not hand-edit.
// Groups: LOOP10_DV, LOOP21_DV, LOOP2_DV, LOOP2S_DV, MR2_INIT, LOOP16_DV, LOOP13_DV, LOOP5_DV, LOOP11S_DV, LOOP17_DV, LOOP15_DV, LOOP22_DV, BUILDFILL_DV, LOOP20_DV
#include "dv_harness.h"

#ifdef TEST_LOOP10_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t CX,
           sisal_array_t PXIN); // difference predictors
#endif
#ifdef TEST_LOOP21_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t CX,
                                    sisal_array_t PXIN,
                                    sisal_array_t VY); // matrix*matrix product
#endif
#ifdef TEST_LOOP2_DV
extern "C" sisal_array_t func_MAIN (int32_t REP, int32_t N, sisal_array_t V,
                                    sisal_array_t XIN); // ICCG excerpt
#endif
#ifdef TEST_LOOP2S_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t V,
           sisal_array_t XIN); // ICCG excerpt (s-form)
#endif
#ifdef TEST_MR2_INIT
struct MR2_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct MR2_results
func_MAIN (int32_t N); // for-initial returning TWO array_dv carries
#endif
#ifdef TEST_LOOP16_DV
struct LOOP16_results
{
  int32_t res_0;
  int32_t res_1;
};
extern "C" struct LOOP16_results
func_MAIN (int32_t REP, int32_t N, double R, double S, double T,
           sisal_array_t D, sisal_array_t PLAN,
           sisal_array_t ZONE); // Monte Carlo search (v1,v2)
#endif
#ifdef TEST_LOOP13_DV
struct LOOP13_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct LOOP13_results
func_MAIN (int32_t REP, int32_t N, sisal_array_t E, sisal_array_t F,
           sisal_array_t B, sisal_array_t C, sisal_array_t HIN,
           sisal_array_t PIN, sisal_array_t Y,
           sisal_array_t Z); // 2-D PIC -> (H,P)
#endif
#ifdef TEST_LOOP5_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N, sisal_array_t XIN, sisal_array_t Y,
           sisal_array_t Z); // tridiagonal: for-initial `array of X` gather
#endif
#ifdef TEST_LOOP11S_DV
extern "C" sisal_array_t
func_MAIN (int32_t REP, int32_t N,
           sisal_array_t YIN); // first-sum (prefix sum): for-initial gather
#endif
#ifdef TEST_LOOP17_DV
struct LOOP17_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
  sisal_array_t res_2;
};
extern "C" struct LOOP17_results
func_MAIN (int32_t REP, int32_t N, sisal_array_t VLIN, sisal_array_t VLR,
           sisal_array_t VSP, sisal_array_t VSTP,
           sisal_array_t VXNEIN); // descending for-initial, 3 gathers
#endif
#ifdef TEST_LOOP15_DV
struct LOOP15_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct LOOP15_results
func_MAIN (int32_t REP, int32_t N, sisal_array_t VF, sisal_array_t VG,
           sisal_array_t VH); // nested forall + addh/fill -> (VS,VYc)
#endif
#ifdef TEST_LOOP22_DV
struct LOOP22_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct LOOP22_results
func_MAIN (int32_t REP, int32_t N, sisal_array_t U, sisal_array_t V,
           sisal_array_t X); // Planckian -> (W,Y)
#endif
#ifdef TEST_BUILDFILL_DV
extern "C" sisal_array_t
func_MAIN (int32_t N); // empty array_dv build + array_fill keep-last
#endif
#ifdef TEST_LOOP20_DV
struct LOOP20_results
{
  sisal_array_t res_0;
  sisal_array_t res_1;
};
extern "C" struct LOOP20_results func_MAIN (
    int32_t REP, int32_t N, double DK, double S, double T, sisal_array_t XXIN,
    sisal_array_t G, sisal_array_t U, sisal_array_t V, sisal_array_t VX,
    sisal_array_t W, sisal_array_t Y,
    sisal_array_t Z); // for-initial recurrence + gather -> (Xgather, XX)
#endif

#ifdef TEST_LOOP10_DV
static void
test_loop10_dv (void)
{
  printf (
      "\n=== Group: loop10_dv (difference predictors, vs C reference) ===\n");
  const int R = 14, n = 2;
  double CX[28], PX[28];
  for (int r = 1; r <= R; r++)
    {
      for (int c = 1; c <= n; c++)
        {
          CX[(r - 1) * n + c - 1] = 100 + r;
          PX[(r - 1) * n + c - 1] = r;
        }
    }
  double ref[10 * n];
  for (int c = 0; c < n; c++)
    {
      double px = CX[(5 - 1) * n + c];
      ref[0 * n + c] = px;
      for (int k = 6; k <= 14; k++)
        {
          px = px - PX[((k - 1) - 1) * n + c];
          ref[(k - 5) * n + c] = px;
        }
    }
  sisal_array_t CXa = make_double_2d (CX, R, n);
  sisal_array_t PXa = make_double_2d (PX, R, n);
  sisal_array_t r = func_MAIN (1, n, CXa, PXa);
  bool ok = ((int)r.dims[0] == 10) && ((int)r.dims[1] == n);
  for (int k = 0; ok && k < 10 * n; k++)
    {
      ok = ok && (fabs (ad (r, k) - ref[k]) < 1e-9);
    }
  check ("loop10_dv difference-predictors matches C reference", ok);
  if (CXa.data)
    free (CXa.data);
  if (PXa.data)
    free (PXa.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP21_DV
// Matrix*matrix: out[i,j] = PX[i,j] + sum_{k=1..25} VY[i,k]*CX[j,k], i=1..25,
// j=1..n.
//   CX is n x 25, VY is 25 x 25, PX is 25 x n; output is 25 x n (row-major).
static void
test_loop21_dv (void)
{
  printf (
      "\n=== Group: loop21_dv (matrix*matrix product, vs C reference) ===\n");
  const int n = 3, M = 25;
  double CX[3 * 25], VY[25 * 25], PX[25 * 3];
  for (int j = 1; j <= n; j++)
    for (int k = 1; k <= M; k++)
      CX[(j - 1) * M + (k - 1)] = 0.01 * (j + k);
  for (int i = 1; i <= M; i++)
    for (int k = 1; k <= M; k++)
      VY[(i - 1) * M + (k - 1)] = 0.01 * ((i * k) % 7);
  for (int i = 1; i <= M; i++)
    for (int j = 1; j <= n; j++)
      PX[(i - 1) * n + (j - 1)] = 0.1 * (i + j);
  double exp[25 * 3];
  for (int i = 1; i <= M; i++)
    for (int j = 1; j <= n; j++)
      {
        double s = 0.0;
        for (int k = 1; k <= M; k++)
          s += VY[(i - 1) * M + (k - 1)] * CX[(j - 1) * M + (k - 1)];
        exp[(i - 1) * n + (j - 1)] = PX[(i - 1) * n + (j - 1)] + s;
      }
  sisal_array_t CXa = make_double_2d (CX, n, M),
                PXa = make_double_2d (PX, M, n),
                VYa = make_double_2d (VY, M, M);
  sisal_array_t r = func_MAIN (1, n, CXa, PXa, VYa);
  bool ok = (r.rank == 2) && ((int)r.dims[0] == M) && ((int)r.dims[1] == n);
  for (int t = 0; ok && t < M * n; t++)
    ok = ok && (fabs (ad (r, t) - exp[t]) < 1e-6);
  check ("loop21_dv matrix*matrix matches C reference (25x3)", ok);
  if (CXa.data)
    free (CXa.data);
  if (PXa.data)
    free (PXa.data);
  if (VYa.data)
    free (VYa.data);
  if (r.data)
    free (r.data);
}
#endif

#if defined(TEST_LOOP2_DV) || defined(TEST_LOOP2S_DV)
// ICCG excerpt (loop2 / loop2s -- identical kernels, only formatting differs):
// outer halving sweep (IL = n, n/2, ...) driving an inner tridiagonal-style
// update Xt[i] = Xt[k] - V[k]*Xt[k-1] + V[k+1]*Xt[k+1] (Sisal 1-based).
// In-place on X matches the Sisal `old Xt` semantics: each inner step writes
// one element and later steps read it back, which is exactly the running
// carry.  (This is the full kernel whose inner-only form is loop2_inner.)
static void
ref_loop2 (int n, const double *V, const double *Xin, int sz, double *X)
{
  for (int j = 0; j < sz; j++)
    X[j] = Xin[j];
  int IL = n, IPNTP = 0;
  while (IL > 1)
    {
      int IPNT = IPNTP;
      IPNTP = IPNTP + IL;
      IL = IL / 2;
      int k = IPNT + 2, i = IPNTP;
      while (k <= IPNTP)
        {
          int ok = k;
          k = ok + 2;
          i = i + 1;
          X[i - 1] = X[ok - 1] - V[ok - 1] * X[ok - 2] + V[ok] * X[ok];
        }
    }
}
#endif
#ifdef TEST_LOOP2_DV
static void
test_loop2_dv (void)
{
  printf ("\n=== Group: loop2_dv (ICCG excerpt, vs C reference) ===\n");
  const int n = 8, sz = 24;
  double V[24], Xin[24];
  for (int j = 0; j < sz; j++)
    {
      V[j] = 0.1 * (j + 1);
      Xin[j] = (double)(j + 1);
    }
  double exp[24];
  ref_loop2 (n, V, Xin, sz, exp);
  sisal_array_t Va = make_double_arr (V, sz), Xa = make_double_arr (Xin, sz);
  sisal_array_t r = func_MAIN (1, n, Va, Xa);
  bool ok = (r.rank == 1) && ((int)r.size == sz);
  for (int j = 0; ok && j < sz; j++)
    ok = ok && (fabs (ad (r, j) - exp[j]) < 1e-9);
  check ("loop2_dv ICCG matches C reference (n=8)", ok);
  check ("loop2_dv did update X (X[11] != Xin[11])",
         fabs (ad (r, 11) - Xin[11]) > 1e-12);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP2S_DV
// loop2s = loop2 with different source formatting only; same ref_loop2.
static void
test_loop2s_dv (void)
{
  printf ("\n=== Group: loop2s_dv (ICCG excerpt, vs C reference) ===\n");
  const int n = 8, sz = 24;
  double V[24], Xin[24];
  for (int j = 0; j < sz; j++)
    {
      V[j] = 0.1 * (j + 1);
      Xin[j] = (double)(j + 1);
    }
  double exp[24];
  ref_loop2 (n, V, Xin, sz, exp);
  sisal_array_t Va = make_double_arr (V, sz), Xa = make_double_arr (Xin, sz);
  sisal_array_t r = func_MAIN (1, n, Va, Xa);
  bool ok = (r.rank == 1) && ((int)r.size == sz);
  for (int j = 0; ok && j < sz; j++)
    ok = ok && (fabs (ad (r, j) - exp[j]) < 1e-9);
  check ("loop2s_dv ICCG matches C reference (n=8)", ok);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.data)
    free (r.data);
}
#endif

#ifdef TEST_MR2_INIT
// Minimal two-array for-initial return: H = all 10, P = all 20 (n x n). Guards
// the multi-return tuple wiring -- the per-clause (node,port) resolution fix.
// Without it both slots collapse to one carry.
static void
test_mr2_init (void)
{
  printf ("\n=== Group: mr2_init (for-initial returns two array_dv carries) "
          "===\n");
  // The 10s and 20s are constants in the .sis, so they ARE the specification;
  // what this group exists to check is that the two return slots stay distinct
  // and neither is cross-wired to the other.  Swept over n, since the carries
  // are rank-2 built by a cross forall and a size-dependent mis-wire would
  // otherwise hide at the single n = 3 it used to run.
  bool ok = true;
  for (int n : { 1, 2, 3, 5 })
    {
      struct MR2_results r = func_MAIN (n);
      const int sz = n * n;
      ok = ok && (r.res_0.rank == 2) && ((int)r.res_0.dims[0] == n)
           && ((int)r.res_0.dims[1] == n) && ((int)r.res_0.size == sz)
           && (r.res_1.rank == 2) && ((int)r.res_1.dims[0] == n)
           && ((int)r.res_1.dims[1] == n) && ((int)r.res_1.size == sz);
      for (int t = 0; ok && t < sz; t++)
        ok = (ai (r.res_0, t) == 10) && (ai (r.res_1, t) == 20);
      if (r.res_0.data) free (r.res_0.data);
      if (r.res_1.data && r.res_1.data != r.res_0.data) free (r.res_1.data);
    }
  check ("both rank-2 carries return distinctly (H all 10, P all 20) for "
         "n = 1, 2, 3, 5",
         ok);
}
#endif
#ifdef TEST_LOOP16_DV
// Monte Carlo search (loop16): Y = least j4 of cells whose classifier C1==0;
// then (v1,v2) = Y==BIG ? (1,0) : ((Y-3)/(2n)+1, Y).  Sisal `exp(a,b)` is
// power -> pow.
static void
ref_loop16 (int n, double R, double S, double T, const double *D,
            const double *PLAN, const int *ZONE, int *v1, int *v2)
{
  int Z1 = ZONE[0];
  long BIG = 2L * n * Z1 + 2, Y = BIG;
  for (int j = 1; j <= n; j++)
    for (int i = 1; i <= Z1; i++)
      {
        int m = n * (i - 1) + j - 1;
        int j4 = 2 * m + 3;
        int j5 = ZONE[j4 - 1];
        int C1;
        if (j5 < n / 3)
          C1 = (PLAN[j5 - 1] < T)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == T) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 < 2 * n / 3)
          C1 = (PLAN[j5 - 1] < S)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == S) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 < n)
          C1 = (PLAN[j5 - 1] < R)    ? ZONE[j4 - 2]
               : (PLAN[j5 - 1] == R) ? 0
                                     : -ZONE[j4 - 2];
        else if (j5 == n)
          C1 = 0;
        else
          {
            double test
                = D[j5 - 1]
                  - (D[j5 - 2] * pow (T - D[j5 - 3], 2)
                     + pow (S - D[j5 - 4], 2) + pow (R - D[j5 - 5], 2));
            C1 = (test < 0.0) ? ZONE[j4 - 2] : -ZONE[j4 - 2];
          }
        long cand = (C1 == 0) ? j4 : BIG;
        if (cand < Y)
          Y = cand;
      }
  if (Y == BIG)
    {
      *v1 = 1;
      *v2 = 0;
    }
  else
    {
      *v1 = (int)((Y - 3) / (2 * n) + 1);
      *v2 = (int)Y;
    }
}
static void
test_loop16_dv (void)
{
  printf ("\n=== Group: loop16_dv (Monte Carlo search, vs C reference) ===\n");
  const int n = 3;
  double R = 0.3, S = 0.5, T = 0.7;
  double D[8] = { 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8 };
  double PLAN[3] = { 0.0, 0.0, 0.0 };
  int32_t ZONE[13] = { 2, 7, 5, 9, 3, 11, 3, 13, 3, 15, 3, 17, 3 };
  int ev1, ev2;
  ref_loop16 (n, R, S, T, D, PLAN, ZONE, &ev1, &ev2);
  sisal_array_t Da = make_double_arr (D, 8), Pa = make_double_arr (PLAN, 3),
                Za = make_int_arr (ZONE, 13);
  struct LOOP16_results r = func_MAIN (1, n, R, S, T, Da, Pa, Za);
  check ("loop16_dv v1 matches C reference", r.res_0 == ev1);
  check ("loop16_dv v2 matches C reference", r.res_1 == ev2);
  if (Da.data)
    free (Da.data);
  if (Pa.data)
    free (Pa.data);
  if (Za.data)
    free (Za.data);
}
#endif
#ifdef TEST_LOOP13_DV
// 2-D PIC (loop13): per particle i, compute grid cell from P, push P, bump H
// histogram. MOD2N(i,j): i<0 ? i-(i/j)*j+j/2+|j/2| : i-(i/j)*j+j/2-|j/2|.  All
// indices Sisal 1-based. P is 4 x n; H/B/C are G x G; E/F/Y/Z 1-based length
// >= 96.  In-place on P and H matches the Sisal `old P`/`old H` carries (each
// particle writes its own P column; H accumulates). (This kernel is the
// regression guard for the 2-D element-update X[r,c: v] fix.)
static int
l13_mod2n (int i, int j)
{
  int r = i - (i / j) * j + j / 2;
  return (i < 0) ? r + abs (j / 2) : r - abs (j / 2);
}
static void
ref_loop13 (int n, const int32_t *E, const int32_t *F, const double *B,
            const double *C, int G, double *H, double *P, const double *Y,
            const double *Z)
{
  for (int i = 1; i <= n; i++)
    {
#define PV(r, c) P[((r) - 1) * n + ((c) - 1)]
      int i1 = 1 + l13_mod2n ((int)trunc (PV (1, i)), 64);
      int j1 = 1 + l13_mod2n ((int)trunc (PV (2, i)), 64);
      double Bij = B[(i1 - 1) * G + (j1 - 1)],
             Cij = C[(i1 - 1) * G + (j1 - 1)];
      double o1 = PV (1, i), o2 = PV (2, i), o3 = PV (3, i), o4 = PV (4, i);
      PV (4, i) = o4 + Cij;
      PV (3, i) = o3 + Bij;
      PV (2, i) = o2 + o4 + Cij;
      PV (1, i) = o1 + o3 + Bij;
      int i2 = l13_mod2n ((int)trunc (PV (1, i)), 64);
      int j2 = l13_mod2n ((int)trunc (PV (2, i)), 64);
      int i3 = i2 + E[(i2 + 32) - 1];
      int j3 = j2 + F[(j2 + 32) - 1];
      PV (1, i) = PV (1, i) + Y[(i2 + 32) - 1];
      PV (2, i) = PV (2, i) + Z[(j2 + 32) - 1];
      H[(i3 - 1) * G + (j3 - 1)] += 1.0;
#undef PV
    }
}
static void
test_loop13_dv (void)
{
  printf ("\n=== Group: loop13_dv (2-D PIC, vs C reference) ===\n");
  const int n = 2, G = 64;
  static int32_t E[96], F[96];
  static double B[64 * 64], C[64 * 64], Hin[64 * 64], Y[96], Z[96];
  for (int k = 0; k < 96; k++)
    {
      E[k] = 1;
      F[k] = 1;
      Y[k] = 0.5;
      Z[k] = 0.25;
    }
  for (int k = 0; k < G * G; k++)
    {
      B[k] = 0.0;
      C[k] = 0.0;
      Hin[k] = 0.0;
    }
  double Pin[4 * 2] = { 5, 3, 7, 9, 0, 0, 0, 0 };
  static double Hexp[64 * 64];
  for (int k = 0; k < G * G; k++)
    Hexp[k] = Hin[k];
  double Pexp[4 * 2];
  for (int k = 0; k < 8; k++)
    Pexp[k] = Pin[k];
  ref_loop13 (n, E, F, B, C, G, Hexp, Pexp, Y, Z);
  sisal_array_t Ea = make_int_arr (E, 96), Fa = make_int_arr (F, 96);
  sisal_array_t Ba = make_double_2d (B, G, G), Ca = make_double_2d (C, G, G);
  sisal_array_t Ha = make_double_2d (Hin, G, G),
                Pa = make_double_2d (Pin, 4, n);
  sisal_array_t Ya = make_double_arr (Y, 96), Za = make_double_arr (Z, 96);
  struct LOOP13_results r = func_MAIN (1, n, Ea, Fa, Ba, Ca, Ha, Pa, Ya, Za);
  bool hok = (r.res_0.rank == 2) && ((int)r.res_0.dims[0] == G)
             && ((int)r.res_0.dims[1] == G);
  for (int k = 0; hok && k < G * G; k++)
    hok = hok && (fabs (ad (r.res_0, k) - Hexp[k]) < 1e-9);
  bool pok = (r.res_1.rank == 2) && ((int)r.res_1.dims[0] == 4)
             && ((int)r.res_1.dims[1] == n);
  for (int k = 0; pok && k < 4 * n; k++)
    pok = pok && (fabs (ad (r.res_1, k) - Pexp[k]) < 1e-9);
  check ("loop13_dv H histogram matches C reference", hok);
  check ("loop13_dv P particles match C reference", pok);
  check ("loop13_dv H got the two particle hits (6,8)&(4,10)",
         ad (r.res_0, (6 - 1) * G + (8 - 1)) == 1.0
             && ad (r.res_0, (4 - 1) * G + (10 - 1)) == 1.0);
  if (Ea.data)
    free (Ea.data);
  if (Fa.data)
    free (Fa.data);
  if (Ba.data)
    free (Ba.data);
  if (Ca.data)
    free (Ca.data);
  if (Ha.data)
    free (Ha.data);
  if (Pa.data)
    free (Pa.data);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
}
#endif
#ifdef TEST_LOOP5_DV
// Livermore loop 5: tridiagonal elimination (sequential recurrence) lowered as
// a `for initial ... returns array_dv(n) of X`.  X[1]=Xin[1];
// X[i]=Z[i]*(Y[i]-X[i-1]) for i=2..n.  The declared extent is a SIZE
// DESCRIPTOR: slot 0 is the seed (body_0, here X[1]) and the loop fills the
// rest, so the gather is the whole X[1..n] -- n elements, not the n-1 body
// values.  That is what makes this form agree with `value of`, the bare
// `array_dv of`, `stream of`, every reduction, and OSC 13.0.3.
static void
test_loop5_dv (void)
{
  printf ("\n=== Group: loop5_dv (tridiagonal for-initial gather, vs C "
          "reference) ===\n");
  const int n = 6;
  double Xin[6] = { 2, 0, 0, 0, 0, 0 };         // only Xin[1] used
  double Y[6] = { 0, 5, 10, 15, 20, 25 };       // 1-based Y[2..6]
  double Z[6] = { 0, 0.5, 0.5, 0.5, 0.5, 0.5 }; // 1-based Z[2..6]
  double X[7];
  X[1] = Xin[0];
  for (int i = 2; i <= n; i++)
    X[i] = Z[i - 1] * (Y[i - 1] - X[i - 1]); // ref recurrence
  sisal_array_t Xa = make_double_arr (Xin, 6), Ya = make_double_arr (Y, 6),
                Za = make_double_arr (Z, 6);
  sisal_array_t r = func_MAIN (1, n, Xa, Ya, Za);
  bool ok = (r.rank == 1) && ((int)r.size == n) && ((int)r.dims[0] == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && near_d (ad (r, k), X[k + 1]);
  check ("loop5_dv gather [X1..Xn] incl. the seed matches C reference", ok);
  if (Xa.data)
    free (Xa.data);
  if (Ya.data)
    free (Ya.data);
  if (Za.data)
    free (Za.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP11S_DV
// Livermore loop 11: first sum (prefix sum), a `for initial ... returns array
// of X` gather.  X[1]=Yin[1]; X[i]=X[i-1]+Yin[i]; gather body values X[2..n]
// (n-1 elems).
static void
test_loop11s_dv (void)
{
  printf ("\n=== Group: loop11s_dv (first-sum for-initial gather, vs C "
          "reference) ===\n");
  const int n = 6;
  double Yin[6] = { 1, 2, 3, 4, 5, 6 };
  double X[7];
  X[1] = Yin[0];
  for (int i = 2; i <= n; i++)
    X[i] = X[i - 1] + Yin[i - 1]; // ref prefix sum
  sisal_array_t Ya = make_double_arr (Yin, 6);
  sisal_array_t r = func_MAIN (1, n, Ya);
  // declared extent is a SIZE DESCRIPTOR: slot 0 is the seed (body_0 = X[1]),
  // so the gather is the whole prefix-sum X[1..n], not just the body values.
  bool ok = (r.rank == 1) && ((int)r.size == n) && ((int)r.dims[0] == n);
  for (int k = 0; ok && k < n; k++)
    ok = ok && near_d (ad (r, k), X[k + 1]);
  check ("loop11s_dv prefix-sum gather [X1..Xn] incl. seed matches C reference",
         ok);
  if (Ya.data)
    free (Ya.data);
  if (r.data)
    free (r.data);
}
#endif
#ifdef TEST_LOOP17_DV
// Livermore loop 17: implicit conditional computation, a DESCENDING
// for-initial (i:=n; while i>2; i:=old i-1) with THREE gathers (array of
// VXNE/VE3/VXND). Exercises multi-gather + the `>` comparison.  Body i =
// n-1..2 -> n-2 elements.
#define LV(arr, i) arr[(i) - 1]
static void
test_loop17_dv (void)
{
  printf ("\n=== Group: loop17_dv (descending for-initial, 3 gathers, vs C "
          "reference) ===\n");
  const int n = 4;
  double VLIN[4] = { 0.1, 0.2, 0.3, 0.4 }, VLR[4] = { 1.0, 1.1, 1.2, 1.3 },
         VSP[4] = { 2.0, 2.1, 2.2, 2.3 }, VSTP[4] = { 0.5, 0.6, 0.7, 0.8 },
         VXNEin[4] = { 3.0, 3.1, 3.2, 3.3 };
  double XNMt = 1.0 / 3.0, E6t = 1.03 / 3.07;
  double E3 = XNMt * LV (VLR, n) + LV (VLIN, n), XNC = 5.0 / 3.0 * E3,
         XNEI = LV (VXNEin, n), E6, XNM;
  if (XNMt > XNC || XNEI > XNC)
    {
      E6 = XNMt * LV (VSP, n) + LV (VSTP, n);
      XNM = E6;
    }
  else
    {
      E6 = E3 + E3 - XNMt;
      XNM = E3 + E3 - XNMt;
    }
  double oldXNM = XNM, oldE6 = E6;
  // body_0: VXNE, VE3 and VXND all have seed values from the initial clause
  // (VXND := E6t; VE3/VXNE from the same if that set E6/XNM), and the declared
  // extent is a size descriptor, so each gather starts with its seed.
  double seedVE3, seedVXNE;
  if (XNMt > XNC || XNEI > XNC) { seedVE3 = E6; seedVXNE = E6; }
  else { seedVE3 = E3; seedVXNE = E3 + E3 - XNEI; }
  int cnt = n - 1;
  double gV[8], gE[8], gD[8];
  int idx = 0;
  gV[idx] = seedVXNE; gE[idx] = seedVE3; gD[idx] = E6t; idx++;
  for (int i = n - 1; i >= 2; i--)
    {
      double e3 = oldXNM * LV (VLR, i) + LV (VLIN, i), xnc = 5.0 / 3.0 * e3,
             xnei = LV (VXNEin, i), vxnd = oldE6;
      double ve3, e6, vxne, xnm;
      if (oldXNM > xnc || xnei > xnc)
        {
          e6 = oldXNM * LV (VSP, i) + LV (VSTP, i);
          ve3 = e6;
          vxne = e6;
          xnm = e6;
        }
      else
        {
          ve3 = e3;
          e6 = e3 + e3 - oldXNM;
          vxne = e3 + e3 - xnei;
          xnm = e3 + e3 - oldXNM;
        }
      gV[idx] = vxne;
      gE[idx] = ve3;
      gD[idx] = vxnd;
      idx++;
      oldXNM = xnm;
      oldE6 = e6;
    }
  sisal_array_t a = make_double_arr (VLIN, 4), b = make_double_arr (VLR, 4),
                c = make_double_arr (VSP, 4), d = make_double_arr (VSTP, 4),
                e = make_double_arr (VXNEin, 4);
  struct LOOP17_results r = func_MAIN (1, n, a, b, c, d, e);
  bool ok = ((int)r.res_0.size == cnt) && ((int)r.res_1.size == cnt)
            && ((int)r.res_2.size == cnt);
  for (int k = 0; ok && k < cnt; k++)
    ok = ok && near_d (ad (r.res_0, k), gV[k])
         && near_d (ad (r.res_1, k), gE[k]) && near_d (ad (r.res_2, k), gD[k]);
  check ("loop17_dv 3 gathers (VXNE,VE3,VXND) incl. seeds match C reference", ok);
  if (a.data)
    free (a.data);
  if (b.data)
    free (b.data);
  if (c.data)
    free (c.data);
  if (d.data)
    free (d.data);
  if (e.data)
    free (e.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
  if (r.res_2.data)
    free (r.res_2.data);
}
#undef LV
#endif
#ifdef TEST_LOOP15_DV
// Livermore loop 15: nested foralls (j=2..6 outer, i=2..n-1 inner) with
// conditional branches, per-row array_addh(VSrc,0)/array_addh(VYrc,LastY), and
// a final array_addh(VYc, array_fill(2,n,0)) appending a zero ROW to a 2-D
// matrix (the rank-poly DV_ARRAY_ADDH splice).  Returns VS [5 x n-1], VYc [6 x
// n-1].
static void
test_loop15_dv (void)
{
  printf ("\n=== Group: loop15_dv (nested forall + addh/fill, vs C reference) "
          "===\n");
  const int n = 4, NC = 4;
  double VF[28], VG[28], VH[28];
  for (int r = 1; r <= 7; r++)
    for (int c = 1; c <= 4; c++)
      {
        VF[(r - 1) * 4 + c - 1] = r + 0.1 * c;
        VG[(r - 1) * 4 + c - 1] = 0.5 * r + c;
        VH[(r - 1) * 4 + c - 1] = 0.3 * r + 0.2 * c;
      }
#define LV(a, r, c) a[((r) - 1) * NC + ((c) - 1)]
  const int W = n - 1;
  double VS[15], VYc[15];
  for (int j = 2; j <= 6; j++)
    {
      int jd = j - 2;
      for (int i = 2; i <= n - 1; i++)
        {
          int id = i - 2;
          double Si;
          if (LV (VF, j, i) >= LV (VF, j - 1, i))
            {
              double R = std::max (LV (VG, j, i), LV (VG, j, i + 1)),
                     s = LV (VF, j, i), t = 0.053;
              Si = sqrt (LV (VH, j, i) * LV (VH, j, i) + R * R) * t / s;
            }
          else
            {
              double R = std::max (LV (VG, j - 1, i), LV (VG, j - 1, i + 1)),
                     s = LV (VF, j - 1, i), t = 0.073;
              Si = sqrt (LV (VH, j, i) * LV (VH, j, i) + R * R) * t / s;
            }
          double Ti = (LV (VH, j + 1, i) > LV (VH, j, i)) ? 0.053 : 0.073, Yi;
          if (LV (VF, j, i) >= LV (VF, j, i - 1))
            {
              double R = std::max (LV (VH, j, i), LV (VH, j + 1, i)),
                     s = LV (VF, j, i);
              Yi = sqrt (LV (VG, j, i) * LV (VG, j, i) + R * R) * Ti / s;
            }
          else
            {
              double R = std::max (LV (VH, j, i - 1), LV (VH, j + 1, i - 1)),
                     s = LV (VF, j, i - 1);
              Yi = sqrt (LV (VG, j, i) * LV (VG, j, i) + R * R) * Ti / s;
            }
          VS[jd * W + id] = Si;
          VYc[jd * W + id] = Yi;
        }
      double Tj = (LV (VH, j + 1, n) > LV (VH, j, n)) ? 0.053 : 0.073, LastY;
      if (LV (VF, j, n) >= LV (VF, j, n - 1))
        {
          double R = std::max (LV (VH, j, n), LV (VH, j + 1, n)),
                 s = LV (VF, j, n);
          LastY = sqrt (LV (VG, j, n) * LV (VG, j, n) + R * R) * Tj / s;
        }
      else
        {
          double R = std::max (LV (VH, j, n - 1), LV (VH, j + 1, n - 1)),
                 s = LV (VF, j, n - 1);
          LastY = sqrt (LV (VG, j, n) * LV (VG, j, n) + R * R) * Tj / s;
        }
      VS[jd * W + (W - 1)] = 0.0;
      VYc[jd * W + (W - 1)] = LastY;
    }
  double VYcf[18];
  for (int k = 0; k < 5 * W; k++)
    VYcf[k] = VYc[k];
  for (int k = 0; k < W; k++)
    VYcf[5 * W + k] = 0.0;
#undef LV
  sisal_array_t a = make_double_2d (VF, 7, 4), b = make_double_2d (VG, 7, 4),
                c = make_double_2d (VH, 7, 4);
  struct LOOP15_results r = func_MAIN (1, n, a, b, c);
  bool sok = (r.res_0.rank == 2) && ((int)r.res_0.dims[0] == 5)
             && ((int)r.res_0.dims[1] == W);
  for (int k = 0; sok && k < 5 * W; k++)
    sok = sok && (fabs (ad (r.res_0, k) - VS[k]) < 1e-4);
  bool yok = (r.res_1.rank == 2) && ((int)r.res_1.dims[0] == 6)
             && ((int)r.res_1.dims[1] == W);
  for (int k = 0; yok && k < 6 * W; k++)
    yok = yok && (fabs (ad (r.res_1, k) - VYcf[k]) < 1e-4);
  check ("loop15_dv VS [5 x n-1] matches C reference", sok);
  check ("loop15_dv VYc [6 x n-1] (row-append via DV_ARRAY_ADDH) matches C "
         "reference",
         yok);
  if (a.data)
    free (a.data);
  if (b.data)
    free (b.data);
  if (c.data)
    free (c.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
}
#endif
#ifdef TEST_LOOP22_DV
// Livermore loop 22: Planckian distribution.  forall k:
// Y=U[k]<20V[k]?U[k]/V[k]:20; W=X[k]/(exp(Y)-1).  Returns (W,Y), each length
// n.
static void
test_loop22_dv (void)
{
  printf ("\n=== Group: loop22_dv (Planckian, vs C reference) ===\n");
  const int n = 5;
  double U[5] = { 1, 2, 3, 100, 5 }, V[5] = { 1, 1, 1, 1, 1 },
         X[5] = { 10, 20, 30, 40, 50 };
  double W[5], Y[5];
  for (int k = 0; k < n; k++)
    {
      Y[k] = (U[k] < 20.0 * V[k]) ? U[k] / V[k] : 20.0;
      W[k] = X[k] / (exp (Y[k]) - 1.0);
    }
  sisal_array_t Ua = make_double_arr (U, 5), Va = make_double_arr (V, 5),
                Xa = make_double_arr (X, 5);
  struct LOOP22_results r = func_MAIN (1, n, Ua, Va, Xa);
  bool wok = ((int)r.res_0.size == n), yok = ((int)r.res_1.size == n);
  for (int k = 0; wok && k < n; k++)
    wok = wok && near_d (ad (r.res_0, k), W[k]);
  for (int k = 0; yok && k < n; k++)
    yok = yok && near_d (ad (r.res_1, k), Y[k]);
  check ("loop22_dv W (Planckian) matches C reference", wok);
  check ("loop22_dv Y (clamped ratio) matches C reference", yok);
  if (Ua.data)
    free (Ua.data);
  if (Va.data)
    free (Va.data);
  if (Xa.data)
    free (Xa.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
}
#endif
#ifdef TEST_BUILDFILL_DV
// Empty array_dv build seed (array OneD []) + array_fill in a for-initial,
// keep-last on an array carry.  X := array_fill(1,i,2.0) each iteration; value
// of X = last fill.
static void
test_buildfill_dv (void)
{
  printf ("\n=== Group: buildfill_dv (fill(1,n,2.0)) ===\n");
  bool ok = true;
  for (int n : { 1, 3, 7 })
    {
      sisal_array_t r = func_MAIN (n);
      ok = ok && ((int)r.size == n);
      for (int k = 0; ok && k < n; k++) ok = near_d (ad (r, k), 2.0);
      if (r.data) free (r.data);
    }
  check ("fill(1,n,2.0) is n twos, for n = 1, 3, 7", ok);
}
#endif
#ifdef TEST_LOOP20_DV
// Livermore loop 20: for-initial recurrence.  DI=Y[i]-G[i]/(XX[i]+DK);
// DN=DI==0?0.2:max(S,min(Z[i]/DI,T));
// X=(XX[i]*(W[i]+DN*V[i])+U[i])/(VX[i]+DN*V[i]); XX[i+1]=XX[i]+DN*(X-XX[i]).
// returns gather X (i=2..n, n-1 elems) + keep-last XX.
static void
test_loop20_dv (void)
{
  printf ("\n=== Group: loop20_dv (for-initial recurrence + gather, vs C "
          "reference) ===\n");
  const int n = 4;
  double XXin[5] = { 3, 3, 3, 3, 3 }, G[5] = { 0, 0, 0, 0, 0 },
         Y[5] = { 1, 1, 1, 1, 1 }, Z[5] = { 2, 2, 2, 2, 2 },
         U[5] = { 1, 1, 1, 1, 1 }, V[5] = { 1, 1, 1, 1, 1 },
         W[5] = { 1, 1, 1, 1, 1 }, VX[5] = { 2, 2, 2, 2, 2 };
  double DK = 1, S = 0, T = 100;
#define A(arr, i) arr[(i) - 1]
  double XX[6];
  for (int k = 1; k <= 5; k++)
    XX[k] = A (XXin, k);
  double Xg[8];
  int gc = 0;
  {
    double DI = A (Y, 1) - A (G, 1) / (A (XXin, 1) + DK);
    double DN = (DI == 0.0) ? 0.20 : std::max (S, std::min (A (Z, 1) / DI, T));
    double X = (A (XXin, 1) * (A (W, 1) + DN * A (V, 1)) + A (U, 1))
               / (A (VX, 1) + DN * A (V, 1));
    Xg[gc++] = X;   // body_0: the seed X is slot 0 of the declared gather
    XX[2] = A (XXin, 1) + DN * (X - A (XXin, 1));
  }
  for (int i = 2; i <= n; i++)
    {
      double DI = A (Y, i) - A (G, i) / (XX[i] + DK);
      double DN
          = (DI == 0.0) ? 0.20 : std::max (S, std::min (A (Z, i) / DI, T));
      double X = (XX[i] * (A (W, i) + DN * A (V, i)) + A (U, i))
                 / (A (VX, i) + DN * A (V, i));
      Xg[gc++] = X;
      XX[i + 1] = XX[i] + DN * (X - XX[i]);
    }
#undef A
  sisal_array_t xx = make_double_arr (XXin, 5), g = make_double_arr (G, 5),
                u = make_double_arr (U, 5), v = make_double_arr (V, 5),
                vx = make_double_arr (VX, 5), w = make_double_arr (W, 5),
                y = make_double_arr (Y, 5), z = make_double_arr (Z, 5);
  struct LOOP20_results r
      = func_MAIN (1, n, DK, S, T, xx, g, u, v, vx, w, y, z);
  bool xok = ((int)r.res_0.size == gc);
  for (int k = 0; xok && k < gc; k++)
    xok = xok && near_d (ad (r.res_0, k), Xg[k]);
  bool xxok = ((int)r.res_1.size == 5);
  for (int k = 0; xxok && k < 5; k++)
    xxok = xxok && near_d (ad (r.res_1, k), XX[k + 1]);
  check ("loop20_dv X gather (seed + i=2..n) matches C reference", xok);
  check ("loop20_dv XX (keep-last recurrence) matches C reference", xxok);
  if (xx.data)
    free (xx.data);
  if (g.data)
    free (g.data);
  if (u.data)
    free (u.data);
  if (v.data)
    free (v.data);
  if (vx.data)
    free (vx.data);
  if (w.data)
    free (w.data);
  if (y.data)
    free (y.data);
  if (z.data)
    free (z.data);
  if (r.res_0.data)
    free (r.res_0.data);
  if (r.res_1.data)
    free (r.res_1.data);
}
#endif

void
run_active_test (void)
{
#ifdef TEST_LOOP10_DV
  test_loop10_dv ();
#endif
#ifdef TEST_LOOP21_DV
  test_loop21_dv ();
#endif
#ifdef TEST_LOOP2_DV
  test_loop2_dv ();
#endif
#ifdef TEST_LOOP2S_DV
  test_loop2s_dv ();
#endif
#ifdef TEST_MR2_INIT
  test_mr2_init ();
#endif
#ifdef TEST_LOOP16_DV
  test_loop16_dv ();
#endif
#ifdef TEST_LOOP13_DV
  test_loop13_dv ();
#endif
#ifdef TEST_LOOP5_DV
  test_loop5_dv ();
#endif
#ifdef TEST_LOOP11S_DV
  test_loop11s_dv ();
#endif
#ifdef TEST_LOOP17_DV
  test_loop17_dv ();
#endif
#ifdef TEST_LOOP15_DV
  test_loop15_dv ();
#endif
#ifdef TEST_LOOP22_DV
  test_loop22_dv ();
#endif
#ifdef TEST_BUILDFILL_DV
  test_buildfill_dv ();
#endif
#ifdef TEST_LOOP20_DV
  test_loop20_dv ();
#endif
#if !defined(TEST_LOOP10_DV) \
    && !defined(TEST_LOOP21_DV) \
    && !defined(TEST_LOOP2_DV) \
    && !defined(TEST_LOOP2S_DV) \
    && !defined(TEST_MR2_INIT) \
    && !defined(TEST_LOOP16_DV) \
    && !defined(TEST_LOOP13_DV) \
    && !defined(TEST_LOOP5_DV) \
    && !defined(TEST_LOOP11S_DV) \
    && !defined(TEST_LOOP17_DV) \
    && !defined(TEST_LOOP15_DV) \
    && !defined(TEST_LOOP22_DV) \
    && !defined(TEST_BUILDFILL_DV) \
    && !defined(TEST_LOOP20_DV)
  g_no_macro = true;
#endif
}
