#!/usr/bin/env python3
"""Partition dv_run_all.cpp into N part files.  See docs/e2e_harness_split_plan.md.

Every group's code lives in `#ifdef TEST_<MACRO>` blocks and the runner compiles
with exactly one -D, so a block is inert unless its macro is the active one.
That is what makes partitioning safe: a part file carries a subset of the blocks.

Two details that are easy to get wrong:

  * A few blocks are `#if defined(A) || defined(B)` -- shared reference code, e.g.
    the bmr:: namespace used by both bmk11a_rel_dv and bmk11a_dv.  Such a block is
    REPLICATED into every part owning any of its macros.  Duplication across parts
    is harmless because only one macro is ever defined.
  * The no-macro guard must list only the part's OWN macros, or a part would
    report "no TEST_XXX defined" whenever the active group lives in another part.

Usage:  python3 test/e2e/split_harness.py <N>
"""
import os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(REPO, "test/e2e/dv_run_all.cpp")
OUT = os.path.join(REPO, "test/e2e/parts")


def blocks(lines):
    """Split a region into (macros, text) units; macros == () means unconditional.

    Macros come from the opening `#if` line and its backslash continuations, which
    is where a block declares what it belongs to.  Preceding comments and blanks
    are attached to the block that follows them."""
    out, pending, i = [], [], 0
    while i < len(lines):
        if re.match(r"^#\s*if", lines[i]):
            head = [lines[i]]
            while head[-1].rstrip().endswith("\\") and i + len(head) < len(lines):
                head.append(lines[i + len(head)])
            macs = tuple(re.findall(r"TEST_[A-Z0-9_]+", "\n".join(head)))
            depth, j = 0, i
            while j < len(lines):
                if re.match(r"^#\s*if", lines[j]):
                    depth += 1
                elif re.match(r"^#\s*endif", lines[j]):
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            out.append((macs, "\n".join(pending + lines[i : j + 1])))
            pending = []
            i = j + 1
        else:
            pending.append(lines[i])
            i += 1
    if any(x.strip() for x in pending):
        out.append(((), "\n".join(pending)))
    return out


def main():
    n_parts = int(sys.argv[1])
    L = open(SRC).read().split("\n")

    inc = next(i for i, l in enumerate(L) if l.startswith('#include "dv_harness.h"'))
    rat = next(i for i, l in enumerate(L) if l.startswith("run_active_test (void)"))
    body_open = next(i for i in range(rat, len(L)) if L[i].strip() == "{")
    body_close = len(L) - 1
    while L[body_close].strip() != "}":
        body_close -= 1

    code = blocks(L[inc + 1 : rat - 1])
    disp_all = blocks(L[body_open + 1 : body_close])

    is_guard = lambda t: t.lstrip().startswith("#if !defined")
    disp = [(m, t) for m, t in disp_all if not is_guard(t)]

    # dispatch order == the order groups run, so partition along it
    ordered = []
    for macs, _ in disp:
        for m in macs:
            if m not in ordered:
                ordered.append(m)

    per = (len(ordered) + n_parts - 1) // n_parts
    parts = [ordered[p * per : (p + 1) * per] for p in range(n_parts)]
    parts = [c for c in parts if c]

    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith((".cpp", ".index")):
            os.remove(os.path.join(OUT, f))

    index = []
    for idx, chunk in enumerate(parts):
        mine = set(chunk)
        keep = lambda units: [t for macs, t in units if not macs or (mine & set(macs))]
        guard = ("#if " + " \\\n    && ".join(f"!defined({m})" for m in chunk)
                 + "\n  g_no_macro = true;\n#endif")
        name = f"dv_part_{idx + 1:02d}.cpp"
        open(os.path.join(OUT, name), "w").write(
            f"// {name} -- generated by test/e2e/split_harness.py; do not hand-edit.\n"
            f"// Groups: {', '.join(m[5:] for m in chunk)}\n"
            f'#include "dv_harness.h"\n\n'
            + "\n".join(keep(code))
            + "\n\nvoid\nrun_active_test (void)\n{\n"
            + "\n".join(keep(disp))
            + "\n" + guard + "\n}\n")
        index += [f"{m[5:]} {name}" for m in chunk]

    open(os.path.join(OUT, "parts.index"), "w").write("\n".join(sorted(index)) + "\n")
    print(f"{len(ordered)} groups -> {len(parts)} parts (~{per} each)")


if __name__ == "__main__":
    main()
